<html><head><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><title>CAASddCreateSDDUnit.CATScript</title><link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css"></head><body><pre>
<font color="#0000FF">Option Explicit</font>
<font color="#008000">'---------------------------------------------------------------------------</font>
<font color="#008000">'COPYRIGHT DASSAULT SYSTEMES 2011</font>

<font color="#008000">' ****************************************************************************</font>
<font color="#008000">'</font>
<font color="#008000">' Purpose:       To create an SDD Design unit and features in it.</font>
<font color="#008000">'</font>
<font color="#008000">' Assumptions:   No document need to be active</font>
<font color="#008000">'</font>
<font color="#008000">' Author:</font>
<font color="#008000">' Languages:     VBScript</font>
<font color="#008000">' Version:       V5R21</font>
<font color="#008000">' Locales:       English</font>
<font color="#008000">' CATIA Level:   V5R21</font>
<font color="#008000">'</font>
<font color="#008000">' ****************************************************************************</font>
<font color="#0000FF">Sub </font>CATMain()

  <font color="#008000">'Create a Product Document</font>
<font color="#0000FF">  Dim </font>NewProdDoc<font color="#0000FF"> As </font>ProductDocument
<font color="#0000FF">  Set </font>NewProdDoc = CATIA.Documents.Add("Product")

  <font color="#008000">'Get the Product from Product Document</font>
<font color="#0000FF">  Dim </font>RootPrd<font color="#0000FF"> As </font>Product
<font color="#0000FF">  Set </font>RootPrd = NewProdDoc.Product

  <font color="#008000">'Select the Product Document and Add Product to this selection</font>
<font color="#0000FF">  Dim </font>SelectionObj<font color="#0000FF"> As </font>Selection
<font color="#0000FF">  Set </font>SelectionObj = NewProdDoc.Selection
  SelectionObj.Add RootPrd

  <font color="#008000">'Create a SDD product by Finding it it selection</font>
<font color="#0000FF">  Dim </font>SddProductObj<font color="#0000FF"> As </font>SddProduct
<font color="#0000FF">  Set </font>SddProductObj = SelectionObj.FindObject("CATIASddProduct")

<font color="#0000FF">  Dim </font>sddpart<font color="#0000FF"> As </font>Part
<font color="#0000FF">  Set </font>sddpart = SddProductObj.CreateDesignUnit

<font color="#0000FF">  Dim </font>FactoryObj<font color="#0000FF"> As </font>SfmFactory
<font color="#0000FF">  Set </font>FactoryObj = sddpart.GetCustomerFactory("SfmFactory")


  <font color="#008000">'Retrieve the Manager from the Factory</font>
<font color="#0000FF">  Dim </font>ManagerObj<font color="#0000FF"> As </font>SfmManager
<font color="#0000FF">  Set </font>ManagerObj = FactoryObj.GetManager
  
  <font color="#008000">'Add Hull Using Manager</font>
  ManagerObj.AddHull

  <font color="#008000">'Define Shell Plate Support</font>
<font color="#0000FF">  Dim </font>ShellSupport<font color="#0000FF"> As </font>AnyObject
<font color="#0000FF">  Set </font>ShellSupport = sddpart.FindObjectByName("Hull1234")
<font color="#0000FF">  Dim </font>ShellSupportRef<font color="#0000FF"> As </font>Reference
<font color="#0000FF">  Set </font>ShellSupportRef = sddpart.CreateReferenceFromObject(ShellSupport)
  
<font color="#0000FF">  Dim </font>ShellSuperplate1<font color="#0000FF"> As </font>SfmSuperPlate
<font color="#0000FF">  Set </font>ShellSuperplate1 = FactoryObj.AddSuperPlate("ShellPanel", ShellSupportRef, Nothing)
  <font color="#008000">'Define Limit</font>
<font color="#0000FF">  Dim </font>ShellPlateLimit<font color="#0000FF"> As </font>AnyObject
<font color="#0000FF">  Set </font>ShellPlateLimit = sddpart.FindObjectByName("LONG.0")
<font color="#0000FF">  Dim </font>ShellPlateLimitRef<font color="#0000FF"> As </font>Reference
<font color="#0000FF">  Set </font>ShellPlateLimitRef = sddpart.CreateReferenceFromObject(ShellPlateLimit)
  
  <font color="#008000">'Define Orientation of Third Limit</font>
<font color="#0000FF">  Dim </font>ShellPlateOrnt<font color="#0000FF"> As </font>Long
  ShellPlateOrnt = 5
  ShellSuperplate1.AddLimit ShellPlateLimitRef, ShellPlateOrnt

  ShellSuperplate1.Thickness = "3.0"
  
  ShellSuperplate1.Run
  sddpart.Update
<font color="#0000FF">End Sub</font>
</pre></body></html>
