<html>

<head>
<meta http-equiv="Content-Language" content="en-us">
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<meta name="GENERATOR" content="Microsoft FrontPage 12.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>Creating an SDD Design Unit</title>
<link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css">
<script type="text/javascript" src="../CAAScrJavaScript/submit.js"></script>
</head>

<body>

<table border="0" width="100%">
	<tr>
		<td>
		<h2>Structure Functional Design</h2>
		</td>
		<td align="right" valign="top">
		<h2><a name="Top"></a>Creating an SDD Design Unit</h2>
		</td>
	</tr>
</table>
<hr>
<!----------------------------------comment------------------------------------->
<table border="0" width="100%">
	<tr>
		<td width="7%" valign="top">
		<img alt="" src="../CAAScrBase/images/atarget.gif" width="32" height="32"></td>
		<td width="93%">
		<p><a name="Learn"></a>This macro shows you how to create a SDD Design unit from scratch.
		This Design unit then can be used to design SDD features.</p>
		</td>
	</tr>
	<tr>
		<td width="7%" valign="top">
		<img alt="" src="../CAAScrBase/images/ainfo.gif" width="32" height="32"></td>
		<td width="93%">
		<p><a name="How"></a>CAASddCreateSDDUnit is launched in CATIA [<a href="#References">1</a>].
		There is no need to open any Part or Product documents to run this 
		macro.</p>
		<p><a href="CAASddCreateSDDUnitSource.htm" target="Source">CAASddCreateSDDUnit.CATScript</a>
		 is located in the CAAScdSddUseCases.
		<a href="macros/CAASddCreateSDDUnit.CATScript">Execute macro</a> (Windows 
		only).</p>
		</td>
	</tr>
	<tr>
		<td width="7%" valign="top">
		<img alt="" src="../CAAScrBase/images/ascenari.gif" width="32" height="32"></td>
		<td width="93%">
		<p><a name="Step"></a>CAASddCreateSDDUnit includes ten steps:</p>
		<ol>
			<li><a href="#Step1">Creating a Product Document</a></li>
			<li><a href="#Step2">Retrieving the Product Root Object from the Product Document</a></li>
			<li><a href="#Step3">Selecting the Product Document</a></li>
			<li><a href="#Step4">Adding the Product to the Selection</a></li>
			<li><a href="#Step5">Getting the SDD Product from the Created Product</a></li>
			<li><a href="#Step6">Creating the SDD Design Unit Part</a></li>
			<li><a href="#Step7">Retrieving the Factory from the SDD Part</a></li>
			<li><a href="#Step8">Retrieving the Manager from the Factory</a></li>
			<li><a href="#Step9">Adding the Hull Surface</a></li>
			<li><a href="#Step10">Creating a Shell Plate using the Hull Surface</a></li>
			<li><a href="#Step11">Updating the Part Document</a></li>
		</ol>
		<!-- -------------------------------comment---------------------------------- -->
		<h4><a name="Step1">Creating a Product Document</a></h4>
		<table class="code">
			<tr>
				<td width="100%">
				<pre>Sub CATMain()
  'Create a Product Document
  Dim NewProdDoc As ProductDocument
  Set NewProdDoc = CATIA.Documents.Add("Product")
  ...</pre>
				</td>
			</tr>
		</table>
		<!-- -------------------------------comment---------------------------------- -->
		<h4><a name="Step2">Retrieving the Product Root Object from the Product Document</a></h4>
		<table class="code">
			<tr>
				<td width="100%">
				<pre>  ...
  'Get the Product from Product Document
  Dim RootPrd As Product
  Set RootPrd = NewProdDoc.Product
  ...</pre>
				</td>
			</tr>
		</table>
		<!-- -------------------------------comment---------------------------------- -->
		<h4><a name="Step3">Selecting the Product Document</a></h4>
		<table class="code">
			<tr>
				<td width="100%">
				<pre>  ...
  'Select the Product Document
  Dim SelectionObj As Selection
  Set SelectionObj = NewProdDoc.Selection
  ...</pre>
				</td>
			</tr>
		</table>
		<!-- -------------------------------comment---------------------------------- -->
		<h4><a name="Step4">Adding the Product to the Selection</a></h4>
		<table class="code">
			<tr>
				<td width="100%">
				<pre>  ...
  SelectionObj.Add RootPrd
  ...</pre>
				</td>
			</tr>
		</table>
		<!-- -------------------------------comment---------------------------------- -->
		<h4><a name="Step5">Getting the SDD Product from the Created Product</a></h4>
		<table class="code">
			<tr>
				<td width="100%">
				<pre>  ...
  'Create a SDD product by finding its selection
  Dim SddProductObj As SddProduct
  Set SddProductObj = SelectionObj.FindObject("CATIASddProduct")
  ...</pre>
				</td>
			</tr>
		</table>
		<!-- -------------------------------comment---------------------------------- -->
		<h4><a name="Step6">Creating the SDD Design Unit Part</a></h4>
		<table class="code">
			<tr>
				<td width="100%">
				<pre>  ...
  'Create a SDD Design Unit
  Dim sddpart As Part
  Set sddpart = SddProductObj.CreateDesignUnit
  ...
</pre>
				</td>
			</tr>
		</table>
		<!-- -------------------------------comment---------------------------------- -->
		<h4><a name="Step7">Retrieving the Factory from the SDD Part</a></h4>
		<table class="code">
			<tr>
				<td width="100%">
				<pre>  ...
  'Retrieve the Factory from the SDD System part
  Dim FactoryObj As SfmFactory
  Set FactoryObj = sddpart.GetCustomerFactory("SfmFactory")
  ...</pre>
				</td>
			</tr>
		</table>
		<!-- -------------------------------comment---------------------------------- -->
		<h4><a name="Step8">Retrieving the Manager from the Factory</a></h4>
		<table class="code">
			<tr>
				<td width="100%">
				<pre>  ...
  'Retrieve the Manager from the Factory
  Dim ManagerObj As SfmManager
  Set ManagerObj = FactoryObj.GetManager
  ...</pre>
				</td>
			</tr>
		</table>

		<!-- -------------------------------comment---------------------------------- -->
		<h4><a name="Step9">Adding the Hull Surface</a></h4>
		<table class="code">
			<tr>
				<td width="100%">
				<pre>  ...
  'Add Hull Using Manager
  ManagerObj.AddHull
  ...</pre>
				</td>
			</tr>
		</table>
		<!-- -------------------------------comment---------------------------------- -->
		<h4><a name="Step10">Creating a Shell Plate using the Hull Surface</a></h4>
<p>The following script is common to Structure Functional Design and Structure Detail Design.</p>
		<table class="code">
			<tr>
				<td width="100%">
				<pre>  ...
  'Define Shell Plate Support
  Dim ShellSupport As AnyObject
  Set ShellSupport = sddpart.FindObjectByName("Hull1234")
  Dim ShellSupportRef As Reference
  Set ShellSupportRef = sddpart.CreateReferenceFromObject(ShellSupport)
  
  Dim ShellSuperplate1 As SfmSuperPlate
  Set ShellSuperplate1 = FactoryObj.AddSuperPlate("ShellPanel", ShellSupportRef, Nothing)

  'Define Limit
  Dim ShellPlateLimit As AnyObject
  Set ShellPlateLimit = sddpart.FindObjectByName("LONG.0")
  Dim ShellPlateLimitRef As Reference
  Set ShellPlateLimitRef = sddpart.CreateReferenceFromObject(ShellPlateLimit)
  
  'Define Orientation of Third Limit
  Dim ShellPlateOrnt As Long
  ShellPlateOrnt = 5
  ShellSuperplate1.AddLimit ShellPlateLimitRef, ShellPlateOrnt
  ShellSuperplate1.Thickness = "1.0"
  ShellSuperplate1.Run
  sddpart.Update
  ...</pre>
				</td>
			</tr>
		</table>
		<!-- -------------------------------comment---------------------------------- -->
		<h4><a name="Step11">Updating the Part Document</a></h4>
		<table class="code">
			<tr>
				<td width="100%">
				<pre> ...
  'To Updating CATIA Part Document
  sfdpart.Update
End Sub
</pre>
				</td>
			</tr>
		</table>
		</td>
	</tr>
	<tr>
		<td width="7%" valign="top"></td>
		<td width="93%">
		<p align="center">
		<img alt="" src="../CAAScrBase/images/aendtask.gif" width="64" height="32"></p>
		</td>
	</tr>
	<!-- -------------------------------comment---------------------------------- -->
</table>
<p align="right">[<a href="#Top">Top</a>]</p>
<hr>
<!-- -------------------------------comment---------------------------------- -->
<h4><a name="InShort"></a>In Short</h4>
<p>This use case has shown how to create SDD Design unit and features inside it.</p>
<hr>
<!-- -------------------------------comment---------------------------------- -->
<h4><a name="References"></a>References</h4>
<table border="0" width="100%">
	<tr>
		<td valign="top">[1]</td>
		<td><a href="../CAAScdInfUseCases/CAAInfLauchMacro.htm">Replaying a Macro</a></td>
	</tr>
	<tr>
		<td colspan="2" align="right">[<a href="#Top">Top</a>]</td>
	</tr>
</table>
<hr>
<!-- -------------------------------comment---------------------------------- -->
<p><i>Copyright © 1999-2011, Dassault Systèmes. All rights reserved.</i></p>

</body>

</html>
