<html><head><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><title>CAASddEditStiffener.CATScript</title><link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css"></head><body><pre>
<font color="#0000FF">Option Explicit</font>
<font color="#008000">'---------------------------------------------------------------------------</font>
<font color="#008000">'COPYRIGHT DASSAULT SYSTEMES 2011</font>

<font color="#008000">' ****************************************************************************</font>
<font color="#008000">'</font>
<font color="#008000">' Purpose:       To create members.</font>
<font color="#008000">'</font>
<font color="#008000">' Assumptions:   The Part document CAASddEditStiffener.CATPart should be active</font>
<font color="#008000">'</font>
<font color="#008000">' Author:</font>
<font color="#008000">' Languages:     VBScript</font>
<font color="#008000">' Version:       V5R21</font>
<font color="#008000">' Locales:       English</font>
<font color="#008000">' CATIA Level:   V5R21</font>
<font color="#008000">'</font>
<font color="#008000">' ****************************************************************************</font>
<font color="#0000FF">Sub </font>CATMain()

<font color="#0000FF">  Dim </font>ObjPart<font color="#0000FF"> As </font>Part
<font color="#0000FF">  Set </font>ObjPart = CATIA.ActiveDocument.Part
      
<font color="#0000FF">  Dim </font>FactoryObj<font color="#0000FF"> As </font>SfmFactory
<font color="#0000FF">  Set </font>FactoryObj = ObjPart.GetCustomerFactory("SfmFactory")
  
<font color="#0000FF">  Dim </font>ManagerObj<font color="#0000FF"> As </font>SfmManager
<font color="#0000FF">  Set </font>ManagerObj = FactoryObj.GetManager
  
<font color="#008000">'RETRIEVING THE SUPERSTIFFENERS</font>
<font color="#0000FF">  Dim </font>SuperStiffeners<font color="#0000FF"> As </font>References
<font color="#0000FF">  Set </font>SuperStiffeners = ManagerObj.GetSuperStiffeners

<font color="#0000FF">  Dim </font>SuperStiffener1, SuperStiffener2, SuperStiffener3<font color="#0000FF"> As </font>SfmStiffener
<font color="#0000FF">  Set </font>SuperStiffener1 = SuperStiffeners.Item(1)
<font color="#0000FF">  Set </font>SuperStiffener2 = SuperStiffeners.Item(3)
<font color="#0000FF">  Set </font>SuperStiffener3 = SuperStiffeners.Item(4)
  
  <font color="#008000">'Retrieving The Seamed Stiffeners on Deck</font>
<font color="#0000FF">  Dim </font>SplitStiffeners<font color="#0000FF"> As </font>References
<font color="#0000FF">  Set </font>SplitStiffeners = SuperStiffener2.SplitProfiles
  
<font color="#0000FF">  Dim </font>SplitStiffener1, SplitStiffener2<font color="#0000FF"> As </font>Reference
<font color="#0000FF">  Set </font>SplitStiffener1 = SplitStiffeners.Item(1)
<font color="#0000FF">  Set </font>SplitStiffener2 = SplitStiffeners.Item(2)
  
<font color="#0000FF">  Set </font>SelctionObj = CATIA.ActiveDocument.Selection
  
  <font color="#008000">'DECK STIFFENER</font>
  SelctionObj.Add SplitStiffener1
<font color="#0000FF">  Dim </font>DeckStiffener1<font color="#0000FF"> As </font>SfmStiffener
<font color="#0000FF">  Set </font>DeckStiffener1 = SelctionObj.FindObject("CATIASfmStiffener")
  
  <font color="#008000">'Checking Name and the Support</font>
<font color="#0000FF">  Dim </font>stiffname<font color="#0000FF"> As </font>String
  stiffname = DeckStiffener1.Name

<font color="#0000FF">  Dim </font>DeckStiffSupport<font color="#0000FF"> As </font>Reference
<font color="#0000FF">  Set </font>DeckStiffSupport = DeckStiffener1.Support
  <font color="#008000">'Applying Material and Grade</font>
  DeckStiffener1.Material = "Aluminium"
  DeckStiffener1.Grade = "A47"
    
  <font color="#008000">'Retrieving and Modifying the side and section Orientation</font>
<font color="#0000FF">  Dim </font>SideOrient, SectionOrient<font color="#0000FF"> As </font>Long
  SideOrient = DeckStiffener1.SideOrientation
  SectionOrient = DeckStiffener1.SectionOrientation
  
<font color="#0000FF">  Dim </font>DeckStiff1SideOrnt, DeckStiff1SectionOrnt<font color="#0000FF"> As </font>Long
  DeckStiff1SectionOrnt = -1
  DeckStiff1SideOrnt = 6
  DeckStiffener1.SideOrientation = DeckStiff1SideOrnt
  DeckStiffener1.SectionOrientation = DeckStiff1SectionOrnt
  
  <font color="#008000">'Modifying the Section</font>
<font color="#0000FF">  Dim </font>DeckStiffSectionName<font color="#0000FF"> As </font>String
  DeckStiffSectionName = DeckStiffener1.SectionName
  DeckStiffener1.SectionName = "WT15x54"
  
  <font color="#008000">'SHELL STIFFENER</font>
<font color="#0000FF">  Dim </font>SelctionObj<font color="#0000FF"> As </font>Selection
  SelctionObj.Add SuperStiffener1
<font color="#0000FF">  Dim </font>ShellStiffener1<font color="#0000FF"> As </font>SfmStiffener
<font color="#0000FF">  Set </font>ShellStiffener1 = SelctionObj.FindObject("CATIASfmStiffener")

  <font color="#008000">'Retrieving and Modifying Websupport of ShellStiffener</font>
<font color="#0000FF">  Dim </font>ShellStiffWebSupport<font color="#0000FF"> As </font>Reference
<font color="#0000FF">  Set </font>ShellStiffWebSupport = ShellStiffener1.WebSupport
  
<font color="#0000FF">  Dim </font>webSupport1<font color="#0000FF"> As </font>AnyObject
<font color="#0000FF">  Set </font>webSupport1 = ObjPart.FindObjectByName("LONG.0")
<font color="#0000FF">  Dim </font>webSupportRef1<font color="#0000FF"> As </font>Reference
<font color="#0000FF">  Set </font>webSupportRef1 = ObjPart.CreateReferenceFromObject(webSupport1)
  ShellStiffener1.WebSupport = webSupportRef1

  <font color="#008000">'Getting MoldedSurface Of ShellStiffener</font>
<font color="#0000FF">  Dim </font>ShellStiffMoldedSurface<font color="#0000FF"> As </font>Reference
<font color="#0000FF">  Set </font>ShellStiffMoldedSurface = ShellStiffener1.GetMoldedSurface
  
  <font color="#008000">'Modifying Anchor Point</font>
<font color="#0000FF">  Dim </font>ShellStiffAnchorPt<font color="#0000FF"> As </font>String
  ShellStiffAnchorPt = ShellStiffener1.AnchorPoint
  ShellStiffener1.AnchorPoint = "catStrWebCenter"
  
  <font color="#008000">'Getting And Setting Profile Limit</font>
<font color="#0000FF">  Dim </font>StiffNewLimit<font color="#0000FF"> As </font>AnyObject
<font color="#0000FF">  Set </font>StiffNewLimit = ObjPart.FindObjectByName("CROSS.90")
<font color="#0000FF">  Dim </font>StiffNewLimitRef<font color="#0000FF"> As </font>Reference
<font color="#0000FF">  Set </font>StiffNewLimitRef = ObjPart.CreateReferenceFromObject(StiffNewLimit)
  ShellStiffener1.SetProfileLimit 1, StiffNewLimitRef
  
<font color="#0000FF">  Dim </font>ShellStiffLimitRef<font color="#0000FF"> As </font>Reference
<font color="#0000FF">  Set </font>ShellStiffLimitRef = ShellStiffener1.GetProfileLimit(1)
  
  <font color="#008000">'Returning and Setting the AngleMode</font>
<font color="#0000FF">  Dim </font>StiffAngleMode<font color="#0000FF"> As </font>Integer
  StiffAngleMode = ShellStiffener1.AngleMode
<font color="#0000FF">  Dim </font>StiffAngleMode2<font color="#0000FF"> As </font>Long
  StiffAngleMode2 = 2
<font color="#0000FF">  Dim </font>AngleModeValidity<font color="#0000FF"> As </font>Boolean
  AngleModeValidity = ShellStiffener1.IsAngleModeValid(StiffAngleMode2)
  ShellStiffener1.AngleMode = StiffAngleMode2
  
  <font color="#008000">'Getting WebSupportOffset of ShellStiffener</font>
  ShellStiffener1.webSupportOffset = "30"
<font color="#0000FF">  Dim </font>ShellStiffwebSupportOffset<font color="#0000FF"> As </font>Double
  ShellStiffwebSupportOffset = ShellStiffener1.webSupportOffset

  <font color="#008000">'Updating The Part with All Modifications</font>
  ObjPart.Update
<font color="#0000FF">End Sub</font>
</pre></body></html>
