<html><head><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><title>CAASddCreateOpening.CATScript</title><link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css"></head><body><pre>
<font color="#0000FF">Option Explicit</font>
<font color="#008000">'---------------------------------------------------------------------------</font>
<font color="#008000">'COPYRIGHT DASSAULT SYSTEMES 2011</font>

<font color="#008000">' ****************************************************************************</font>
<font color="#008000">'</font>
<font color="#008000">' Purpose:       To create members.</font>
<font color="#008000">'</font>
<font color="#008000">' Assumptions:   The Product document Product1.CATProduct located in</font>
<font color="#008000">'                CAASddUseCases/samples/OpeningCreationData should be active</font>
<font color="#008000">'</font>
<font color="#008000">' Author:</font>
<font color="#008000">' Languages:     VBScript</font>
<font color="#008000">' Version:       V5R20</font>
<font color="#008000">' Locales:       English</font>
<font color="#008000">' CATIA Level:   V5R20</font>
<font color="#008000">'</font>
<font color="#008000">' ****************************************************************************</font>
<font color="#0000FF">Sub </font>CATMain()

<font color="#0000FF">  Dim </font>documents1<font color="#0000FF"> As </font>Documents
<font color="#0000FF">  Set </font>documents1 = CATIA.Documents
<font color="#0000FF">  Dim </font>partDocument1<font color="#0000FF"> As </font>PartDocument
<font color="#0000FF">  Set </font>partDocument1 = documents1.Item("Design_Unit_004.CATPart")
<font color="#0000FF">  Dim </font>part1<font color="#0000FF"> As </font>Part
<font color="#0000FF">  Set </font>part1 = partDocument1.Part
<font color="#0000FF">  Dim </font>plate<font color="#0000FF"> As </font>SfmSuperPlate
<font color="#0000FF">  Set </font>plate = part1.FindObjectByName("Deck_005")
<font color="#0000FF">  Dim </font>plateref<font color="#0000FF"> As </font>Reference
<font color="#0000FF">  Set </font>plateref = part1.CreateReferenceFromObject(plate)

  <font color="#008000">'Create Opening Using Sketch Mode</font>

<font color="#0000FF">  Dim </font>sketch<font color="#0000FF"> As </font>Sketch
<font color="#0000FF">  Set </font>sketch= part1.FindObjectByName("Sketch.19")
<font color="#0000FF">  Dim </font>sketchref<font color="#0000FF"> As </font>Reference
<font color="#0000FF">  Set </font> sketchref=part1.CreateReferenceFromObject(sketch)
<font color="#0000FF">  Dim </font>Factory<font color="#0000FF"> As </font>SfmFunctionFactory
<font color="#0000FF">  Set </font>Factory =  part1.GetCustomerFactory("SfmFunctionFactory")
<font color="#0000FF">  Dim </font>OpeningUsingSketch<font color="#0000FF"> As </font>SfmOpening
<font color="#0000FF">  Set </font>OpeningUsingSketch = Factory.CreateOpening("FunctionalOpening",1,sketchref, plateref)
  part1.Update

  <font color="#008000">'Create Opening Using 3D Object Mode</font>
<font color="#0000FF">  Dim </font>Object<font color="#0000FF"> As </font>AnyObject
<font color="#0000FF">  Set </font>Object =  part1.FindObjectByName("Volume Extrude.1")
<font color="#0000FF">  Dim </font>ObjectRef<font color="#0000FF"> As </font>Reference
<font color="#0000FF">  Set </font>ObjectRef = part1.CreateReferenceFromObject(Object)
<font color="#0000FF">  Dim </font>OpeningUsing3DObj<font color="#0000FF"> As </font>SfmOpening
<font color="#0000FF">  Set </font>OpeningUsing3DObj = Factory.CreateOpening("FunctionalOpening",0,ObjectRef, plateref)
  part1.Update

<font color="#0000FF">End Sub</font>
</pre></body></html>
