<!doctype html public "-//w3c//dtd html 4.0 transitional//en">
<html>
<head>
 <meta http-equiv="Content-Language" content="en-us"> 
 <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"> 
 <meta name="Generator" content="mihGene v1.1">
 <meta http-equiv="Expires" content="Tue, 04 Dec 1993 21:29:02 GMT">
 <title>CATStrFunctionalInterfaces SfmProfile (Object)</title>
<link rel="Stylesheet" type="text/css" href="../../../caav5.css">
<link href="../_index/cdg.css" rel="stylesheet" type="text/css"> 
<script type="text/javascript">var PubDirExist = false; var ProDirExist = false; var PrivDirExist = false;</script> 
<script type="text/javascript" src="../_index/cdg.js"></script> 
<script language="Javascript" id="jsLinkjs" type="text/javascript" src="../_index/jslink.js"></script> 
<script language="Javascript" id="jsFwLinkjs" type="text/javascript" src="jsFwLink.js"></script> 
<script language="Javascript" id="jsTreejs" type="text/javascript" src="../_index/jsTree.js"></script>  
</head>
<body>
<div class="menu1" id="menuViewPPP" > 
 	<a href="javascript:writeIndex('IPublic')" name="viewPPP" id="PublicView"  class="ongletPub" > Public View</a> 
 	<a href="javascript:writeIndex('IProtected')" name="viewPPP" id="ProtectedView" class="ongletPro"  > Protected View</a>  
 	<a href="javascript:writeIndex('IPrivate')" name="viewPPP" id="PrivateView" class="ongletPriv" > Private View</a> 
 </div> 
 <div id="indexView" class="menu1">	 
 <a name="multiview" class="onglet" rel="../_index/main.htm" href="../_index/main.htm">All Frameworks</a>   
 <a name="multiview" class="onglet"  rel="../_index/tree.htm" href="../_index/tree.htm">Class Hierarchy</a>   
 <a name="multiview" class="onglet"  rel="../CATStrFunctionalInterfaces.htm" href="../CATStrFunctionalInterfaces.htm">This Framework</a>
<a name="multiview" class="onglet"  rel="../_index/HomeIdx.htm" href="../_index/HomeIdx.htm">Indexes</a>  
 <a id="multiviewP" class="onglet" href="javascript:openLinkNP(getCurrentObjectName(),getCurrentType(),'0')"  >Previous</a>  
 	<a id="multiviewN" class="onglet" href="javascript:openLinkNP(getCurrentObjectName(),getCurrentType(),'1')"  >Next</a> 
 </div> 
<script type="text/javascript" > 
 	function getCurrentLevel() { 
 return "";	} 
	function getCurrentFw() { 
	return "CATStrFunctionalInterfaces";	}
		function getCurrentObjectName() { 
 	return "SfmProfile"; } 
	function getCurrentType() { 
 	return "interface"; }  
 function callInit() { 
 		if (PubDirExist == true || ProDirExist == true || PrivDirExist == true) {  
 			var parent = document.getElementById("indexView"); 
 			if (parent && (ProDirExist == true || PrivDirExist == true) ) { 
 			var elem = document.getElementById("multiviewP"); 
 			if(elem) parent.removeChild(elem); 
 			elem = document.getElementById("multiviewN"); 
 			if(elem) parent.removeChild(elem); }
 			initData(); 
 		} else { 
 			var elem; 
 			var parent = document.getElementById("menuViewPPP"); 
 			if (parent) { 
 				elem = document.getElementById("PublicView"); 
 				parent.removeChild(elem); 
 				elem = document.getElementById("ProtectedView"); 
 				parent.removeChild(elem); 
 				elem = document.getElementById("PrivateView"); 
 				parent.removeChild(elem); 
 			} 
 if (locateObject(getCurrentObjectName(), getCurrentType(), '0')==0) { 
 				elem = document.getElementById("multiviewP"); 
 				if (elem) { elem.removeAttribute("href"); elem.removeAttribute("onclick"); } 
 			} 
 			if (locateObject(getCurrentObjectName(), getCurrentType(), '1')==0) { 
 				elem = document.getElementById("multiviewN"); 
 				if (elem) { elem.removeAttribute("href"); elem.removeAttribute("onclick"); } 
 			} 
 }	 
 	} 
 	window.onload = callInit; 
  </script> 
 
<h1>SfmProfile<font size=-1> (Object)</font></h1>
<script type="text/javascript" > 
 generatedFatherClass('interface_SfmProfile_42143','SfmProfile','0');</script>
<b><i> Interface to manage the structure frame modeling member object
 <b>Role</b>:  Allows accessing and setting of member's data.</i></b><br>

 <dl>
  <dt> <b>See also:</b> 
  <dd> <script type="text/javascript"> activateLinkAnchor('SfmFactory','','SfmFactory') </script>
</dl>
<hr>
<dl>
 <h2><a name="PropertyIndex"></a>Property Index</h2>
 <dt>
    <a href="#AnchorPoint"><b>AnchorPoint</b></a>
<dd>  Returns or sets the member's anchor point.
 <dt>
    <a href="#SectionName"><b>SectionName</b></a>
<dd>  Returns or sets the member's section name.
 <dt>
    <a href="#SplitProfiles"><b>SplitProfiles</b></a>
<dd>  Returns the SplitProfiles.
 <dt>
    <a href="#Support"><b>Support</b></a>
<dd>  Returns the member's support.
</dl>
<dl>
 <h2><a name="MethodIndex"></a>Method Index</h2>
 <dt>
    <a href="#AddEndcut"><b>AddEndcut</b></a>
<dd>  Creates Endcut on a SuperProfile.
 <dt>
    <a href="#GetEndCoord"><b>GetEndCoord</b></a>
<dd>  Retrieves the coordinates of the member's end extremity.
 <dt>
    <a href="#GetEndcut"><b>GetEndcut</b></a>
<dd>  Retrieves Existing Endcut on Profile.
 <dt>
    <a href="#GetProfileLimit"><b>GetProfileLimit</b></a>
<dd>  Returns the limit at an Extremity of a Profile.
 <dt>
    <a href="#GetSectionAxis"><b>GetSectionAxis</b></a>
<dd>  Retrieves the axis system of the section at a given location on the member's support.
 <dt>
    <a href="#GetSlotsOnProfile"><b>GetSlotsOnProfile</b></a>
<dd>  Retrieves Slots on Profile.
 <dt>
    <a href="#GetStartCoord"><b>GetStartCoord</b></a>
<dd>  Retrieves the coordinates of the member's start extremity.
 <dt>
    <a href="#RemoveEndcut"><b>RemoveEndcut</b></a>
<dd>  Removes Existing Endcut on Profile.
 <dt>
    <a href="#Run"><b>Run</b></a>
<dd>  Compute the member's result.
 <dt>
    <a href="#SetProfileLimit"><b>SetProfileLimit</b></a>
<dd>  Sets the limit at an Extremity of a Profile.
</dl>
 <h2><a name="Properties"></a>Properties</h2> <br>
<a name="AnchorPoint"><dt>

<table><tr><td>o Property <b>AnchorPoint</b>(<td>) As <script type="text/javascript"> activateLink('CATBSTR','CATBSTR')</script> </table></dt>
<dl>
  <dd>
 Returns or sets the member's anchor point.
<dl>
<dt>Example</dt>:
<dd>
 This example retrieves in <code>AnchorPointName</code> the anchor point name of the <code>SfmProfile</code> feature.
 <pre>
 Dim AnchorPointName As String
 Set AnchorPointName = SfmProfile.<font color="red">AnchorPoint</font>
 </pre>
 </dl>
</dl>
<a name="SectionName"><dt>

<table><tr><td>o Property <b>SectionName</b>(<td>) As <script type="text/javascript"> activateLink('CATBSTR','CATBSTR')</script> </table></dt>
<dl>
  <dd>
 Returns or sets the member's section name.
<dl>
<dt>Example</dt>:
<dd>
 This example retrieves in <code>Name</code> the name of section user by the <code>SfmProfile</code> feature.
 <pre>
 Dim Name As String
 Set Name = SfmProfile.<font color="red">SectionName</font>
 </pre>
 </dl>
</dl>
<a name="SplitProfiles"><dt>

<table><tr><td>o Property <b>SplitProfiles</b>(<td>) As <script type="text/javascript"> activateLink('References','References')</script>  (Read Only)</table></dt>
<dl>
  <dd>
 Returns the SplitProfiles.
<dl>
<dt>Example</dt>:
<dd>
 This example retrieves SplitProfiles list of the Stiffener.
 <pre>
 Dim SplitStiffeners As References
 Set SplitStiffeners = SuperStiffener.<font color="red">SplitProfiles</font>
 Dim SplitStiffener1 As Reference
 Set SplitStiffener1 = SplitStiffeners.Item(1)
 Set SelctionObj = CATIA.ActiveDocument.Selection
 SelctionObj.Add SplitStiffener1
 Dim SplitStiff1 As SfmStiffener
 Set SplitStiff1 = SelctionObj.FindObject("CATIASfmStiffener")
 </pre>
 </dl>
</dl>
<a name="Support"><dt>

<table><tr><td>o Property <b>Support</b>(<td>) As <script type="text/javascript"> activateLink('Reference','Reference')</script>  (Read Only)</table></dt>
<dl>
  <dd>
 Returns the member's support.
<dl>
<dt>Example</dt>:
<dd>
 This example retrieves in <code>Support</code> the support of the <code>SfmProfile</code> feature.
 <pre>
 Dim Support As Reference
 Set Support = SfmProfile.<font color="red">Support</font>
 </pre>
 </dl>
</dl>
 <h2><a name="Methods"></a>Methods</h2> <br>
<a name="AddEndcut"><dt>

<table><tr><td>o Func <b>AddEndcut</b>(<td><script type="text/javascript"> activateLink('long','long')</script> <td><tt>iExtremityIndex</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('CATBSTR','CATBSTR')</script> <td><tt>iEndcutType</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('CATBSTR','CATBSTR')</script> <td><tt>iEndcutName</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('SfmReferences','SfmReferences')</script> <td><tt>iListContext</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('SfmConnectionParameters','SfmConnectionParameters')</script> <td><tt>iListParameters</tt>) As <script type="text/javascript"> activateLink('SfmEndcut','SfmEndcut')</script> </table></dt>
<dl>
  <dd>
 Creates Endcut on a SuperProfile.Use the method to create as well as edit the endcut.
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iExtremityIndex</tt>
   <dd> [in]     The extremity on which endcut is to be applied(1-Start,2-End).
 </dd>
    <dt><tt> iEndcutType</tt>
   <dd> [in]   The type of Endcut(Snipe,Trim,Weld).
 </dd>
    <dt><tt> iEndcutName</tt>
   <dd> [in]   Name of the Endcut.
 </dd>
    <dt><tt> iListContext</tt>
   <dd> [in]   Context inputs for contextual endcuts or cutbacks.Not required for Custom.
 </dd>
    <dt><tt> iListParameters</tt>
   <dd> [in]   The list of Parameters.
 </dd>
    <dt><tt> oSfmProfileEndCut</tt>
   <dd> [out]   The created Endcut.
 </dd>
</dl>
  <dt> <b>Returns:</b> 
  <dd>  <code>S_OK</code> if everything ran ok
 <dl>
 <dt><b>Example:<b>
 <dd>
 This Example creates a new contextual endcut on Stiifener Start extremity.
 <pre>
 ' First read the specifications required for endcut
 Dim FactoryObj As SfmOperationFactory
 Set FactoryObj = PartObj.GetCustomerFactory("SfmOperationFactory")
 Dim EndCutManagerObj As SfmEndcutManager
 Set EndCutManagerObj = FactoryObj.GetEndcutManager
 Dim ListOfContextNames, ListOfUDFParamNames As Variant
 Dim ListOfUDFParameters As SfmConnectionParameters
 EndCutManagerObj.GetEndcutSpecifications "Tee", "Snipe", "T-CTX-PLATE", ListOfContextNames, ListOfUDFParameters, ListOfUDFParamNames
 ' Read the Name of Context
 Dim SizeOfContextNames As Long
 SizeOfContext = UBound(ListOfContextNames)
 Dim ContextName As String
 For i = 0 To SizeOfContext  
  ContextName = ListOfContextNames(i)
 Next
 ' Read and Set the Parameter Values
 Dim SizeOfUDFParams As Long
 SizeOfUDFParams = ListOfUDFParameters.Count
 Dim UDFParam As Parameter
 For i = 1 To SizeOfUDFParams  
  Set UDFParam = ListOfUDFParameters.Item(i)
  Dim UDFParamName,UDFParamValue As String
  UDFParamName = ListOfUDFParamNames(j - 1)
  UDFParamValue = UDFParam.ValueAsString
 'Redefine Param Value
  If (UDFParamName = "Snipe Radius") Then
    UDFParam.ValuateFromString ("52mm")
  End If
 Next
 ' Define the Context
 Dim FactoryRef As SfmFunctionFactory
 Set FactoryRef = PartObj.GetCustomerFactory("SfmFunctionFactory")
 Dim ListOfContexts As SfmReferences
 Set ListOfContexts = FactoryRef.SfmReferences
 Dim Limit As Reference
 Set Limit = PartObj.CreateReferenceFromObject(SfmSuperPlateObj)
 ListOfContexts.Add Limit
 ' Create the Endcut
 Dim EndCutObj As SfmEndcut
 Set EndCutObj = SfmStiffenerObj.<font color="red">AddEndcut(1, "Snipe", "T-CTX-PLATE", ListOfContexts, ListOfUDFParameters)</font>
 ' For Non Conetxtual Endcuts pass Nothing for iListContext
 Set EndCutObj = SfmStiffenerObj.<font color="red">AddEndcut(1, "Snipe", "Web_Snipe_Radius", Nothing, ListOfUDFParameters)</font>
 </pre>
 </dl>
</dl>
</dl>
<a name="GetEndCoord"><dt>

<table><tr><td>o Sub <b>GetEndCoord</b>(<td><script type="text/javascript"> activateLink('CATSafeArrayVariant','CATSafeArrayVariant')</script> <td><tt>oCoord</tt>)</table></dt>
<dl>
  <dd>
 Retrieves the coordinates of the member's end extremity.
<dl>
<dt>Example</dt>:
<dd>
 This example retrieves in <code>EndExtr</code> the end extremity coordinates of the <code>SfmProfile</code> feature.
 <pre>
 SfmProfile.<font color="red">GetEndCoord</font> EndExtr
 </pre>
 </dl>
</dl>
<a name="GetEndcut"><dt>

<table><tr><td>o Func <b>GetEndcut</b>(<td><script type="text/javascript"> activateLink('long','long')</script> <td><tt>iExtremityIndex</tt>) As <script type="text/javascript"> activateLink('SfmEndcut','SfmEndcut')</script> </table></dt>
<dl>
  <dd>
 Retrieves Existing Endcut on Profile.
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iExtremityIndex</tt>
   <dd> [in]      Extremity of Profile(1-Start,2-End).
 </dd>
    <dt><tt> oSfmEndcut</tt>
   <dd> [out]      Retrieved Endcut.
 </dd>
</dl>
  <dt> <b>Returns:</b> 
  <dd>  <code>S_OK</code> if everything ran ok
<dl>
<dt>Example</dt>:
<dd>
 This example gets the Existing Endcut.
 <pre>
 Dim EndCutObj As SfmEndcut
 Set EndCutObj = ProfileObj.<font color="red">GetEndcut(1)</font>
 </pre>
 </dl>
</dl>
</dl>
<a name="GetProfileLimit"><dt>

<table><tr><td>o Func <b>GetProfileLimit</b>(<td><script type="text/javascript"> activateLink('long','long')</script> <td><tt>iExtremityIndex</tt>) As <script type="text/javascript"> activateLink('Reference','Reference')</script> </table></dt>
<dl>
  <dd>
 Returns the limit at an Extremity of a Profile.
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iExtremityIndex</tt>
   <dd> [in]   Extremity of Profile(1-Start,2-End).
 </dd>
    <dt><tt> oLimit</tt>
   <dd> [out]      Existing Limit.
 </dd>
</dl>
  <dt> <b>Returns:</b> 
  <dd>  <code>S_OK</code> if everything ran ok.
<dl>
<dt>Example</dt>:
<dd>
 This example retrieves the Start Limit of a Stiffener.
 <pre>
 Dim ProfileLimit As Reference
 Set ProfileLimit = SuperStiffenerObj.<font color="red">GetProfileLimit(1)</font>
 </pre>
 </dl>
</dl>
</dl>
<a name="GetSectionAxis"><dt>

<table><tr><td>o Sub <b>GetSectionAxis</b>(<td><script type="text/javascript"> activateLink('double','double')</script> <td><tt>iAbside</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('CATSafeArrayVariant','CATSafeArrayVariant')</script> <td><tt>iOrigin</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('CATSafeArrayVariant','CATSafeArrayVariant')</script> <td><tt>ioVector1</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('CATSafeArrayVariant','CATSafeArrayVariant')</script> <td><tt>ioVector2</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('CATSafeArrayVariant','CATSafeArrayVariant')</script> <td><tt>ioVector3</tt>)</table></dt>
<dl>
  <dd>
 Retrieves the axis system of the section at a given location on the member's support.
<dl>
<dt>Example</dt>:
<dd>
 This example retrieves in <code>Origin</code>, <code>Vector1</code>, <code>Vector2</code>, <code>Vector3</code> the section axis at the start extremity of the <code>SfmProfile</code> feature.
 <pre>
 Dim Origin, Vector1, Vector2, Vector3 As 
 SfmProfile.<font color="red">GetSectionAxis</font> 0., Origin, Vector1, Vector2, Vector3
 </pre>
 </dl>
</dl>
<a name="GetSlotsOnProfile"><dt>

<table><tr><td>o Func <b>GetSlotsOnProfile</b>(<td>) As <script type="text/javascript"> activateLink('SfmSlots','SfmSlots')</script> </table></dt>
<dl>
  <dd>
 Retrieves Slots on Profile.
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> oSfmSlots</tt>
   <dd> [out]      Slots.
 </dd>
</dl>
  <dt> <b>Returns:</b> 
  <dd>  <code>S_OK</code> if everything ran ok
<dl>
<dt>Example</dt>:
<dd>
 This example gets the Slots.
 <pre>
 Dim SlotsonProfile As SfmSlots
 Set SlotsonProfile = ProfileObj.<font color="red">GetSlotsOnProfile</font>
 </pre>
 </dl>
</dl>
</dl>
<a name="GetStartCoord"><dt>

<table><tr><td>o Sub <b>GetStartCoord</b>(<td><script type="text/javascript"> activateLink('CATSafeArrayVariant','CATSafeArrayVariant')</script> <td><tt>oCoord</tt>)</table></dt>
<dl>
  <dd>
 Retrieves the coordinates of the member's start extremity.
<dl>
<dt>Example</dt>:
<dd>
 This example retrieves in <code>StartExtr</code> the start extremity coordinates of the <code>SfmProfile</code> feature.
 <pre>
 SfmProfile.<font color="red">GetStartCoord</font> StartExtr
 </pre>
 </dl>
</dl>
<a name="RemoveEndcut"><dt>

<table><tr><td>o Sub <b>RemoveEndcut</b>(<td><script type="text/javascript"> activateLink('long','long')</script> <td><tt>iExtremityIndex</tt>)</table></dt>
<dl>
  <dd>
 Removes Existing Endcut on Profile.
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iExtremityIndex</tt>
   <dd> [in]      Extremity of Profile(1-Start,2-End).
 </dd>
</dl>
  <dt> <b>Returns:</b> 
  <dd>  <code>S_OK</code> if everything ran ok
 <dl>
 <dt>Example</dt>:
 <dd>
 This example removes the Existing Endcut.
 <pre>
 Dim EndCutObj As SfmEndcut
 Set EndCutObj = ProfileObj.<font color="red">RemoveEndcut(1)</font>
 </pre>
 </dl>
</dl>
</dl>
<a name="Run"><dt>

<table><tr><td>o Sub <b>Run</b>(<td>)</table></dt>
<dl>
  <dd>
 Compute the member's result.
<dl>
<dt>Example</dt>:
<dd>
 This example builds the result of the <code>SfmProfile</code> feature.
 <pre>
 SfmProfile.<font color="red">Run</font>
 </pre>
 </dl>
</dl>
<a name="SetProfileLimit"><dt>

<table><tr><td>o Sub <b>SetProfileLimit</b>(<td><script type="text/javascript"> activateLink('long','long')</script> <td><tt>iExtremityIndex</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('Reference','Reference')</script> <td><tt>iLimit</tt>)</table></dt>
<dl>
  <dd>
 Sets the limit at an Extremity of a Profile.
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iExtremityIndex</tt>
   <dd> [in]   Extremity of Profile(1-Start,2-End).
 </dd>
    <dt><tt> iLimit</tt>
   <dd> [in]      New Limit to add.
 </dd>
</dl>
  <dt> <b>Returns:</b> 
  <dd>  <code>S_OK</code> if everything ran ok
<dl>
<dt>Example</dt>:
<dd>
 This example sets the limit at the Extremity.
 <pre>
 Set StiffenerLimit = ObjPart.FindObjectByName("CROSS.115")
 Dim LimitRef As Reference
 Set LimitRef = ObjPart.CreateReferenceFromObject(StiffenerLimit)
 SuperStiffener.<font color="red">SetProfileLimit</font> 2, LimitRef
 </pre>
 </dl>
</dl>
</dl>
<hr/><p><i>
Copyright &#169; 1999-2011, Dassault Syst&#232;mes. All rights reserved.</i></p>
</body>

</html>

