<!doctype html public "-//w3c//dtd html 4.0 transitional//en">
<html>
<head>
 <meta http-equiv="Content-Language" content="en-us"> 
 <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"> 
 <meta name="Generator" content="mihGene v1.1">
 <meta http-equiv="Expires" content="Tue, 04 Dec 1993 21:29:02 GMT">
 <title>StructureInterfaces StrFeatureFactory (Object)</title>
<link rel="Stylesheet" type="text/css" href="../../../caav5.css">
<link href="../_index/cdg.css" rel="stylesheet" type="text/css"> 
<script type="text/javascript">var PubDirExist = false; var ProDirExist = false; var PrivDirExist = false;</script> 
<script type="text/javascript" src="../_index/cdg.js"></script> 
<script language="Javascript" id="jsLinkjs" type="text/javascript" src="../_index/jslink.js"></script> 
<script language="Javascript" id="jsFwLinkjs" type="text/javascript" src="jsFwLink.js"></script> 
<script language="Javascript" id="jsTreejs" type="text/javascript" src="../_index/jsTree.js"></script>  
</head>
<body>
<div class="menu1" id="menuViewPPP" > 
 	<a href="javascript:writeIndex('IPublic')" name="viewPPP" id="PublicView"  class="ongletPub" > Public View</a> 
 	<a href="javascript:writeIndex('IProtected')" name="viewPPP" id="ProtectedView" class="ongletPro"  > Protected View</a>  
 	<a href="javascript:writeIndex('IPrivate')" name="viewPPP" id="PrivateView" class="ongletPriv" > Private View</a> 
 </div> 
 <div id="indexView" class="menu1">	 
 <a name="multiview" class="onglet" rel="../_index/main.htm" href="../_index/main.htm">All Frameworks</a>   
 <a name="multiview" class="onglet"  rel="../_index/tree.htm" href="../_index/tree.htm">Class Hierarchy</a>   
 <a name="multiview" class="onglet"  rel="../StructureInterfaces.htm" href="../StructureInterfaces.htm">This Framework</a>
<a name="multiview" class="onglet"  rel="../_index/HomeIdx.htm" href="../_index/HomeIdx.htm">Indexes</a>  
 <a id="multiviewP" class="onglet" href="javascript:openLinkNP(getCurrentObjectName(),getCurrentType(),'0')"  >Previous</a>  
 	<a id="multiviewN" class="onglet" href="javascript:openLinkNP(getCurrentObjectName(),getCurrentType(),'1')"  >Next</a> 
 </div> 
<script type="text/javascript" > 
 	function getCurrentLevel() { 
 return "";	} 
	function getCurrentFw() { 
	return "StructureInterfaces";	}
		function getCurrentObjectName() { 
 	return "StrFeatureFactory"; } 
	function getCurrentType() { 
 	return "interface"; }  
 function callInit() { 
 		if (PubDirExist == true || ProDirExist == true || PrivDirExist == true) {  
 			var parent = document.getElementById("indexView"); 
 			if (parent && (ProDirExist == true || PrivDirExist == true) ) { 
 			var elem = document.getElementById("multiviewP"); 
 			if(elem) parent.removeChild(elem); 
 			elem = document.getElementById("multiviewN"); 
 			if(elem) parent.removeChild(elem); }
 			initData(); 
 		} else { 
 			var elem; 
 			var parent = document.getElementById("menuViewPPP"); 
 			if (parent) { 
 				elem = document.getElementById("PublicView"); 
 				parent.removeChild(elem); 
 				elem = document.getElementById("ProtectedView"); 
 				parent.removeChild(elem); 
 				elem = document.getElementById("PrivateView"); 
 				parent.removeChild(elem); 
 			} 
 if (locateObject(getCurrentObjectName(), getCurrentType(), '0')==0) { 
 				elem = document.getElementById("multiviewP"); 
 				if (elem) { elem.removeAttribute("href"); elem.removeAttribute("onclick"); } 
 			} 
 			if (locateObject(getCurrentObjectName(), getCurrentType(), '1')==0) { 
 				elem = document.getElementById("multiviewN"); 
 				if (elem) { elem.removeAttribute("href"); elem.removeAttribute("onclick"); } 
 			} 
 }	 
 	} 
 	window.onload = callInit; 
  </script> 
 
<h1>StrFeatureFactory<font size=-1> (Object)</font></h1>
<script type="text/javascript" > 
 generatedFatherClass('interface_StrFeatureFactory_36096','StrFeatureFactory','0');</script>
<b><i>  Represents the Factory Object for Structure Features.</i></b><br>

 The factory is retrieved using the StrPlate or StrMember
 <! @sample>
 <dl>
 <dt><b>Example:</b>
 <dd>
 The following example retrieves the Feature factory object from the Selection on ActiveDocument.
 <pre>
 Dim Plate As StrPlate
 Set Plate = strPlates.Item("Plate_007")
 Dim Sel As Selection
 Set Sel = CATIA.ActiveDocument.Selection
 ' Use the Add method to add Plate to selection
 Sel.Add Plate
 Dim Factory As StrFeatureFactory
 Set Factory = Sel.FindObject("CATIAStrFeatureFactory")
 </pre><hr>
<dl>
</dl>
<dl>
 <h2><a name="MethodIndex"></a>Method Index</h2>
 <dt>
    <a href="#AddCutoutWithAfterFormingMode"><b>AddCutoutWithAfterFormingMode</b></a>
<dd>  Adds a Cutout Feature on Plate/Member using AfterForming Mode.
 <dt>
    <a href="#AddCutoutWithBeforeFormingMode"><b>AddCutoutWithBeforeFormingMode</b></a>
<dd>  Adds a Cutout Feature on Plate/Member using BeforeForming Mode.
 <dt>
    <a href="#AddNibbling"><b>AddNibbling</b></a>
<dd>  Adds a Coping on Plate or Member.
</dl>
 <h2><a name="Methods"></a>Methods</h2> <br>
<a name="AddCutoutWithAfterFormingMode"><dt>

<table><tr><td>o Func <b>AddCutoutWithAfterFormingMode</b>(<td><script type="text/javascript"> activateLink('Reference','Reference')</script> <td><tt>iContour</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('Reference','Reference')</script> <td><tt>iDirection</tt>) As <script type="text/javascript"> activateLink('StrCutoutFeature','StrCutoutFeature')</script> </table></dt>
<dl>
  <dd>
 Adds a Cutout Feature on Plate/Member using AfterForming Mode.  
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iContour</tt>
   <dd> [in]   The Sketch used to create the cutout. This must exist in the document.
 </dd>
    <dt><tt> iDirection</tt>
   <dd> [in]   The direction in which the cutout should be created. Valid inputs are line created in sketch,3D Line.
 </dd>
    <dt><tt> oCutout[out]</tt>
   <dd>	  The CutOut Feature 
 </dd>
    <dt><tt> @return</tt>
   <dd>   <code>S_OK</code> if everything ran ok.
 <dl>
 <dt>Example</dt>:
 <dd>
 This example creates Cutout on Plate. 
 <pre>
 ' Define the Plate on which cutout is to be created
 Dim strPlates As strPlates
 Set strPlates = rootProduct.GetTechnologicalObject("StructurePlates")
 Dim PlateToCut As StrPlate
 Set PlateToCut = strPlates.Item("Plate_012")
' Add the Plate to Selection
 Dim Sel As Selection
 Set Sel = CATIA.ActiveDocument.Selection
 Sel.Add PlateToCut
 'Get The factory from selection
 Dim Factory As StrFeatureFactory
 Set Factory = Sel.FindObject("CATIAStrFeatureFactory")
 ' Select the Sketch profile exisitng in the document
 Dim sketch As Reference
 Set sketch = rootProduct.CreateReferenceFromName("Product1/Grid/!Sketch.1")
 ' Select the direction in which the cutout should be created
 Dim dir1 As Reference
 Set dir1 = rootProduct.CreateReferenceFromName("Product1/Grid/!Sketch.2")
 ' Create cutout
 Dim Cutout1 As StrCutoutFeature
 Set Cutout1 = Factory.<font color="red">AddCutoutWithAfterFormingMode(sketch, dir1)</font>
 </pre></dd>
</dl>
</dl>
</dl>
<a name="AddCutoutWithBeforeFormingMode"><dt>

<table><tr><td>o Func <b>AddCutoutWithBeforeFormingMode</b>(<td><script type="text/javascript"> activateLink('Reference','Reference')</script> <td><tt>iContour</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('Reference','Reference')</script> <td><tt>iSurface</tt>) As <script type="text/javascript"> activateLink('StrCutoutFeature','StrCutoutFeature')</script> </table></dt>
<dl>
  <dd>
 Adds a Cutout Feature on Plate/Member using BeforeForming Mode.  
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iContour</tt>
   <dd> [in]   The Sketch used to create the cutout. This must exist in the document
 </dd>
    <dt><tt> iSurface</tt>
   <dd> [in]   A Surface on which Plate/Member is created.
 </dd>
    <dt><tt> oCutout[out]</tt>
   <dd>	  The CutOut Feature 
 </dd>
    <dt><tt> @return</tt>
   <dd>   <code>S_OK</code> if everything ran ok.
 <dl>
 <dt>Example</dt>:
 <dd>
 This example creates Cutout on Member. 
 <pre>
 'Define the Plate on which cutout is to be created
 Dim strPlates As strPlates
 Set strPlates = rootProduct.GetTechnologicalObject("StructurePlates")
 Dim PlateToCut As StrPlate
 Set PlateToCut = strPlates.Item("Plate_012")
 ' Add the Plate to Selection
 Dim Sel As Selection
 Set Sel = CATIA.ActiveDocument.Selection
 Sel.Add PlateToCut
 ' Get The factory from selection
 Dim Factory As StrFeatureFactory
 Set Factory = Sel.FindObject("CATIAStrFeatureFactory")
 ' Select the Sketch profile exisitng in the document
 Dim sketch As Reference
 Set sketch = rootProduct.CreateReferenceFromName("Product1/Grid/!Sketch.1")
 ' Select the surface 
 Dim Surface1 As Reference
 Set Surface1 = rootProduct.CreateReferenceFromName("Product1/Grid/!Extrude.1")
 ' Create cutout
 Dim Cutout1 As StrCutoutFeature
 Set Cutout1 = Factory.AddCutoutWithBeforeFormingMode(sketch, Surface1)
 </pre></dd>
</dl>
</dl>
</dl>
<a name="AddNibbling"><dt>

<table><tr><td>o Func <b>AddNibbling</b>(<td><script type="text/javascript"> activateLink('CATSafeArrayVariant','CATSafeArrayVariant')</script> <td><tt>iListOfLimitingElements</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('CATBSTR','CATBSTR')</script> <td><tt>iNibblingType</tt>) As <script type="text/javascript"> activateLink('StrNibblingFeature','StrNibblingFeature')</script> </table></dt>
<dl>
  <dd>
 Adds a Coping on Plate or Member.  
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iListOfLimitingElements</tt>
   <dd> [in]   List of Limiting elements used for limiting the Plate/Member. Pass only one limit at a time.
 </dd>
    <dt><tt> iNibblingType</tt>
   <dd> [in]   Possible Values for Plate:"Remove".
   Possible Values for Member:"Remove","ShortPoint","LongPoint","WeldCut". 
	For Defining further attributes refer CATIAStrNibblingFeature.
 </dd>
    <dt><tt> oNibblingFeature[out]</tt>
   <dd>	  The Nibbled Plate/Member.
 </dd>
    <dt><tt> @return</tt>
   <dd>   <code>S_OK</code> if everything ran ok.
 <dl>
 <dt>Example</dt>:
 <dd>
 This example creates Coping on Plate.  
 <pre>
 Dim Limitplate1 As StrPlate
 Set Limitplate1 = strPlates.Item("Plate_008")
 Dim Listoflimits As Variant
 Set Listoflimits(0) =Limitplate1
 Dim NibblingFeature As StrNibblingFeature
 Set NibblingFeature = Factory.<font color="red">AddNibbling(Listoflimits, "Remove")</font>
 </pre></dd>
</dl>
</dl>
</dl>
<hr/><p><i>
Copyright &#169; 1999-2011, Dassault Syst&#232;mes. All rights reserved.</i></p>
</body>

</html>

