<!DOCTYPE html 
     PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
     "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
<meta http-equiv="Content-Language" content="en-us" />
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<meta name="devlang" content="idl" />
<link rel="stylesheet" type="text/css" href="../CAADocStyleSheets/caav5.css"/>
<script type="text/javascript" src="../CAADocJavaScript/DSDocTocToc.js">/* */</script>
<script type="text/javascript" src="../CAADocJavaScript/DSDocHighlight.js">/* */</script>
<script type="text/javascript" src="../CAADocJavaScript/submit.js">/* */</script>
<title>CAAScdSddUcTestCollarSource.CATScript</title>
</head>

<body onload="highlightSearchTerms();">

<pre>
<span class="comment">'-------------- Sample MACRO written in Basic Script ------------------------------------------ </span>
<span class="comment">'This sample tests sdd collar.</span>
<span class="comment">'This script requires sdd model. Slot with section containing collar already present on one of the two intersecting plates.</span>
<span class="comment">'</span>
<span class="comment">'Steps:</span>
<span class="comment">'   1- Searches and opens model which is named as &quot;SddProduct&quot;.</span>
<span class="comment">'   2- Retrieves Part object. </span>
<span class="comment">'   3- Retrieves SddProductPlate object.</span>
<span class="comment">'   4- Retrieves sdd slot object.</span>
<span class="comment">'   5- Retrieves sdd collar object.</span>
<span class="comment">'   6- Setting up collar parameters.</span>
<span class="comment">'   7- Adding Collar on Slot.</span>
<span class="comment">'   8- Removing Collar on Slot.</span>
<span class="comment">'   9- Update the plate</span>
<span class="comment">'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
Language = &quot;VBSCRIPT&quot; 
<span class="keyword">Dim </span>Manager<span class="keyword"> As </span>RfgService
<span class="keyword">Dim </span>ObjPart<span class="keyword"> As </span>Part
<span class="keyword">Dim </span>SDDProdSel<span class="keyword"> As </span>Selection


<span class="keyword">Sub </span>CATMain()
    
<span class="comment">'   1- Searches and opens model which is named as &quot;SddProduct&quot;</span>
<span class="keyword">    Dim </span>SDDPrdEditor<span class="keyword"> As </span>Editor
<span class="keyword">    Dim </span>prdName<span class="keyword"> As </span>String
    prdName = &quot;SddProduct&quot;
    OpenProduct prdName , SDDPrdEditor
    
<span class="keyword">    Set </span>SDDProdSel = SDDPrdEditor.Selection

<span class="comment">'   2- Retrieves Part object </span>
<span class="keyword">    Dim </span>product1Service  <span class="keyword"> As </span>PLMProductService
<span class="keyword">    Set </span>product1Service = SDDPrdEditor.GetService(&quot;PLMProductService&quot;)
<span class="keyword">    Dim </span>ObjVPMRootOccurrence  <span class="keyword"> As </span>VPMRootOccurrence
<span class="keyword">    Set </span>ObjVPMRootOccurrence = product1Service.RootOccurrence
<span class="keyword">    Dim </span>ObjVPMReference<span class="keyword"> As </span>VPMReference
<span class="keyword">    Set </span>ObjVPMReference = ObjVPMRootOccurrence.ReferenceRootOccurrenceOf
<span class="keyword">    Dim </span>ObjVPMRepInstances<span class="keyword"> As </span>VPMRepInstances
<span class="keyword">    Set </span>ObjVPMRepInstances = ObjVPMReference.RepInstances
<span class="keyword">    Set </span>ObjVPMRepReference = ObjVPMRepInstances.Item(1).ReferenceInstanceOf
<span class="keyword">    Set </span>ObjPart = ObjVPMRepReference.GetItem(&quot;Part&quot;)

<span class="comment">'   3- Retrieves SddProductPlate object</span>
<span class="keyword">    Set </span>ListOfInstances = ObjVPMReference.Instances
<span class="keyword">    Set </span>PlateRef = ListOfInstances.Item(1).ReferenceInstanceOf
<span class="keyword">    Set </span>PlateRepInstances = PlateRef.RepInstances
<span class="keyword">    Set </span>PlateRepInstReference = PlateRepInstances.Item(1).ReferenceInstanceOf
<span class="keyword">    Set </span>PlatePart = PlateRepInstReference.GetItem(&quot;Part&quot;)
  
<span class="keyword">    Dim</span> ObjSddProductPlate As SddProductPlate
    SFDProdSel.Add PlateRef
<span class="keyword">    Set </span>ObjSddProductPlate = SFDProdSel.FindObject(&quot;CATIASddProductPlate&quot;)
<span class="keyword">    Dim</span> ObjSddPlate As SddPlate
<span class="keyword">    Set </span>ObjSddPlate = ObjSddProductPlate.SddPlate

<span class="comment">'   4- Retrieves sdd slot object </span>
<span class="keyword">    Dim</span> ObjStrSlot <span class="keyword">As</span> StrSlot
    <strong>GetSlot</strong> ObjSddPlate, ObjStrSlot
	
<span class="comment">'   5- Retrieves sdd collar object </span>
<span class="keyword">    Dim</span> ObjStrCollar <span class="keyword">As</span> StrCollar
    <strong>GetCollar</strong> ObjStrSlot, ObjStrCollar 
    
<span class="comment">'   6- Setting up Collar Parameters</span>
    <strong>SetCollarParameters</strong> ObjStrCollar
    
<span class="comment">'   7- Adding Collar on Slot</span>
    <span class="keyword">Dim</span> ObjStrCollar_2 <span class="keyword">As</span> StrCollar
    <strong>AddCollar</strong> ObjStrSlot, ObjStrCollar_2 

<span class="comment">'   8- Removing Collar on Slot</span>
    <strong>RemoveCollar</strong> ObjStrSlot

<span class="comment">'   9- Update the plate</span>
    ObjSddProductPlate.Update
    
<span class="keyword">End Sub</span>

<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="comment">'Get Slot</span>
<span class="comment">'</span>
<span class="comment">''Steps</span>
<span class="comment">'   4.1- Retrieves StrSlots object. </span>
<span class="comment">'   4.2- Get StrSlot.</span>
<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="keyword">Sub</span> <strong>GetSlot</strong>(iObjSfdPanel <span class="keyword">As</span> SddPlate, oObjStrSlot <span class="keyword">As</span> StrSlot)
    
<span class="comment">    '4.1- Retrieves StrSlots object   </span>
    <span class="keyword">Dim</span> ObjStrSlots <span class="keyword">As</span> StrSlots
    <span class="keyword">Set</span> ObjStrSlots = iObjSddPlate.StrSlots
    
    <span class="comment">'4.2- Get StrSlot</span>
    Set oObjStrSlot = ObjStrSlots.Item(1)
	
<span class="keyword">End Sub</span>

<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="comment">'Get Collar</span>
<span class="comment">'</span>
<span class="comment">''Steps</span>
<span class="comment">'   5.1- Retrieves StrCollars object. </span>
<span class="comment">'   5.2- Get StrCollar.</span>
<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="keyword">Sub</span> <strong>GetCollar</strong>(iObjStrSlot <span class="keyword">As</span> StrSlot, oObjStrCollar <span class="keyword">As</span> StrCollar)
    
<span class="comment">    '5.1- Retrieves StrCollars object   </span>
    <span class="keyword">Dim</span> ObjStrCollars <span class="keyword">As</span> StrCollars
    <span class="keyword">Set</span> ObjStrCollars = iObjStrSlot.Collars
    
    <span class="comment">'5.2- Get StrCollar</span>
    Set oObjStrCollar = ObjStrCollars.<strong>Item</strong>(1)
	
<span class="keyword">End Sub</span>

<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="comment">'Set Collar Parameters.</span>
<span class="comment">'</span>
<span class="comment">''Steps</span>
<span class="comment">'   6.1- Set Collar Material. </span>
<span class="comment">'   6.2- Set Collar Material Throw Orientation.</span>
<span class="comment">'   6.3- Get Collar Thickness. Valuate it as required.</span>
<span class="comment">'   6.4- Get Collar Material Throw Orientation.</span>
<span class="comment">'   6.5- Get Collar Material. </span>
<span class="comment">'   6.6- Get Collar public parameters. Valuate it as required.</span>
<span class="comment">'   6.7- Updates the modified Collar object.</span>
<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="keyword">Sub</span> <strong>SetCollarParameters</strong>(iObjStrCollar <span class="keyword">As</span> StrCollar)
    
    <span class="comment">'6.1- Set Collar Material. </span>
    iObjStrCollar.<strong>Material</strong> = &quot;Steel A42&quot;
	
    <span class="comment">'6.2- Set Collar Material Throw Orientation.</span>
    iObjStrCollar.<strong>MaterialThrowOrientation</strong> = 1
	
    <span class="comment">'6.3- Get Collar Thickness. Valuate it as required.</span>
    <span class="keyword">Dim</span> oThickness <span class="keyword">As</span> Parameter
    <span class="keyword">Set</span> oThickness = iObjStrCollar.<strong>Thickness</strong>
    oThickness.ValuateFromString(&quot;20mm&quot;)
	
    <span class="comment">'6.4- Get Collar Material Throw Orientation.</span>
    <span class="keyword">Dim</span> oMaterialThrowOrientation <span class="keyword">As</span> CATStrCollarThrowOrientation
    oMaterialThrowOrientation = iObjStrCollar.<strong>MaterialThrowOrientation</strong>
	
    <span class="comment">'6.5- Get Collar Material. </span>
    <span class="keyword">Dim</span> oMaterial <span class="keyword">As</span> String
    oMaterial = iObjStrCollar.<strong>Material</strong>

    <span class="comment">'6.6- Get Collar public parameters. Valuate it as required.</span>
    <span class="keyword">Dim</span> ObjCollarParameters <span class="keyword">As</span> StrParameters
    <span class="keyword">Set</span> ObjCollarParameters = iObjStrCollar.<strong>CollarParameters</strong>
    <span class="keyword">Dim</span> Width <span class="keyword">As</span> Parameter
    <span class="keyword">Set</span> Width = ObjCollarParameters.Item(1)
    Width.ValuateFromString(&quot;205mm&quot;)
    <span class="keyword">Dim</span> Angle <span class="keyword">As</span> Parameter
    <span class="keyword">Set</span> Angle = ObjCollarParameters.Item(2)
    Angle.ValuateFromString(&quot;35deg&quot;)
    
    <span class="comment">'6.7- Updates the modified Collar object.</span>
    iObjStrCollar.<strong>Update</strong>

		
<span class="keyword">End Sub</span>

<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="comment">'Add Collar</span>
<span class="comment">'</span>
<span class="comment">''Steps</span>
<span class="comment">'   7.1- Retrieves StrCollars object. </span>
<span class="comment">'   7.2- Add StrCollar.</span>
<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="keyword">Sub</span> <strong>AddCollar</strong>(iObjStrSlot <span class="keyword">As</span> StrSlot, oObjStrCollar_2 <span class="keyword">As</span> StrCollar)
    
<span class="comment">    '7.1- Retrieves StrCollars object   </span>
    <span class="keyword">Dim</span> ObjStrCollars <span class="keyword">As</span> StrCollars
    <span class="keyword">Set</span> ObjStrCollars = iObjStrSlot.Collars
    
    <span class="comment">'7.2- Add StrCollar</span>
    <span class="keyword">Set</span> oObjStrCollar_2 = ObjStrCollars.<strong>Add</strong>
	
<span class="keyword">End Sub</span>

<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="comment">'Remove Collar</span>
<span class="comment">'</span>
<span class="comment">''Steps</span>
<span class="comment">'   8.1- Retrieves StrCollars object. </span>
<span class="comment">'   8.2- Remove the newly added collar.</span>
<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="keyword">Sub</span> <strong>RemoveCollar</strong>(iObjStrSlot <span class="keyword">As</span> StrSlot)
    
<span class="comment">    '8.1- Retrieves StrCollars object   </span>
    <span class="keyword">Dim</span> ListOfCollars <span class="keyword">As</span> StrCollars
    <span class="keyword">Set</span> ListOfCollars = iObjStrSlot.Collars
    
    <span class="comment">'8.2- 'Remove the newly added collar</span>
    <span class="keyword">Dim</span> ObjStrCollar <span class="keyword">As</span> StrCollar
    <span class="keyword">Set</span> ObjStrCollar = ListOfCollars.Item(2)
    ListOfCollars.<strong>Remove</strong> (ObjStrCollar)
	
<span class="keyword">End Sub</span>

<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="comment">'Searches a product and open it.</span>
<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="keyword">Sub </span><strong>OpenProduct</strong>(byVal prdName as String, SDDPrdEditor<span class="keyword"> As </span>Editor)

    <span class="comment">'Get the Search Service.</span>
    <span class="keyword">Set </span>oSearchService = CATIA.GetSessionService(&quot;Search&quot;)
    <span class="keyword">Dim</span> oDBSearch <span class="keyword">As</span> DatabaseSearch 
    <span class="keyword">Set</span> oDBSearch = oSearchService.DatabaseSearch
    oDBSearch.BaseType = &quot;VPMReference&quot;
    <span class="comment">' To retrieve the product by its Title, use V_Name attribute</span>
    <span class="comment">' To retrieve the product by its Name, use PLM_ExternalID attribute</span>
    oDBSearch.AddEasyCriteria &quot;V_Name&quot;, prdName
    oSearchService.Search
    <span class="comment">'Retrieve the first entity.</span>
    <span class="keyword">Dim</span> oEntity <span class="keyword">As</span> PLMEntity 
    <span class="keyword">Set</span> oEntity = oDBSearch.Results.Item(1)
    <span class="comment">'Get the PLMOpen service &amp; Open the first retrieved entity.</span>
    <span class="keyword">Dim</span> oPLMOpenService <span class="keyword">As</span> PLMOpenService
    <span class="keyword">Set </span>oPLMOpenService = CATIA.GetSessionService(&quot;PLMOpenService&quot;)
    <span class="comment">'Get the editor.</span>
    oPLMOpenService.PLMOpen oEntity , SDDPrdEditor
    
<span class="keyword">End Sub</span>
</pre>
<script type="text/javascript">insertCopyright();</script>

</body>

</html>
