<!DOCTYPE html 
     PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
     "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
<meta http-equiv="Content-Language" content="en-us" />
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<meta name="devlang" content="idl" />
<link rel="stylesheet" type="text/css" href="../CAADocStyleSheets/caav5.css"/>
<script type="text/javascript" src="../CAADocJavaScript/DSDocTocToc.js">/* */</script>
<script type="text/javascript" src="../CAADocJavaScript/DSDocHighlight.js">/* */</script>
<script type="text/javascript" src="../CAADocJavaScript/submit.js">/* */</script>
<title>CAAScdSddUcGetProfileSubElementsSource.CATScript</title>
</head>

<body onload="highlightSearchTerms();">

<pre>
<span class="comment">'-------------- Sample MACRO written in Basic Script ------------------------------------------ </span>
<span class="comment">'This sample gets profile sub elements.</span>
<span class="comment">'This script requires sdd model.</span>
<span class="comment">'</span>
<span class="comment">'Steps:</span>
<span class="comment">'   1- Searches and opens model which is named as &quot;SddProduct&quot;.</span>
<span class="comment">'   2- Retrieves Part object. </span>
<span class="comment">'   3- Retrieves Service manager. (RfgService)</span>
<span class="comment">'   4- Retrieves SddProductStiffener object.</span>
<span class="comment">'   5- Get Profile Sub-Elements </span>
<span class="comment">'       5.1- Retrieves the SddProfileSubElementMngt object from the stiffener object.</span>
<span class="comment">'       5.2- Get Faces.</span>
<span class="comment">'       5.2- Get Edges.</span>
<span class="comment">'   6- Update the Stiffener</span>
<span class="comment">'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
Language = &quot;VBSCRIPT&quot; 
<span class="keyword">Dim </span>Manager<span class="keyword"> As </span>RfgService
<span class="keyword">Dim </span>ObjPart<span class="keyword"> As </span>Part
<span class="keyword">Dim </span>SDDProdSel<span class="keyword"> As </span>Selection


<span class="keyword">Sub </span>CATMain()
    
<span class="comment">'   1- Searches and opens model which is named as &quot;SddProduct&quot;</span>
<span class="keyword">    Dim </span>SDDPrdEditor<span class="keyword"> As </span>Editor
<span class="keyword">    Dim </span>prdName<span class="keyword"> As </span>String
    prdName = &quot;SddProduct&quot;
    OpenProduct prdName , SDDPrdEditor
    
<span class="keyword">    Set </span>SDDProdSel = SDDPrdEditor.Selection

<span class="comment">'   2- Retrieves Part object </span>
<span class="keyword">    Dim </span>product1Service  <span class="keyword"> As </span>PLMProductService
<span class="keyword">    Set </span>product1Service = SDDPrdEditor.GetService(&quot;PLMProductService&quot;)
<span class="keyword">    Dim </span>ObjVPMRootOccurrence  <span class="keyword"> As </span>VPMRootOccurrence
<span class="keyword">    Set </span>ObjVPMRootOccurrence = product1Service.RootOccurrence
<span class="keyword">    Dim </span>ObjVPMReference<span class="keyword"> As </span>VPMReference
<span class="keyword">    Set </span>ObjVPMReference = ObjVPMRootOccurrence.ReferenceRootOccurrenceOf
<span class="keyword">    Dim </span>ObjVPMRepInstances<span class="keyword"> As </span>VPMRepInstances
<span class="keyword">    Set </span>ObjVPMRepInstances = ObjVPMReference.RepInstances
<span class="keyword">    Set </span>ObjVPMRepReference = ObjVPMRepInstances.Item(1).ReferenceInstanceOf
<span class="keyword">    Set </span>ObjPart = ObjVPMRepReference.GetItem(&quot;Part&quot;)

<span class="comment">'   3- Retrieves Service manager (RfgService)</span>
<span class="keyword">    Set </span>Manager = CATIA.ActiveEditor.GetService(&quot;RfgService&quot;)
    
<span class="comment">'   4- Retrieves SddProductStiffener object</span>
<span class="keyword">    Set </span>ListOfInstances = ObjVPMReference.Instances
<span class="keyword">    Set </span>StiffenerRef = ListOfInstances.Item(2).ReferenceInstanceOf
<span class="keyword">    Set </span>StiffenerRepInstances = StiffenerRef.RepInstances
<span class="keyword">    Set </span>StiffenerRepInstReference = StiffenerRepInstances.Item(1).ReferenceInstanceOf
<span class="keyword">    Set </span>StiffenerPart = StiffenerRepInstReference.GetItem(&quot;Part&quot;)
  
<span class="keyword">    Dim</span> ObjSddProductStiffener As SddProductStiffener
    SFDProdSel.Add StiffenerRef
<span class="keyword">    Set </span>ObjSddProductStiffener = SFDProdSel.FindObject(&quot;CATIASddProductStiffener&quot;)
<span class="keyword">    Dim</span> ObjSddStiffener As SddStiffener
<span class="keyword">    Set </span>ObjSddStiffener = ObjSddProductStiffener.SddStiffener

<span class="comment">'   5- Get Profile Sub-Elements</span>
<span class="keyword">    Dim</span> ObjSddProfileeSubElementMngt <span class="keyword">As</span> SddProfileSubElementMngt
    GetProfileSubElements ObjSddStiffener, ObjSddProfileSubElementMngt
    
<span class="comment">'   6- Update the stiffener</span>
    ObjSddProductStiffener.Update
    
<span class="keyword">End Sub</span>

<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="comment">'Calling GetProfileSubElements</span>
<span class="comment">'</span>
<span class="comment">'Steps:</span>
<span class="comment">'     5.1- Retrieves the SddProfileSubElementMngt object from the stiffener object.</span>
<span class="comment">'     5.2- Get Faces.</span>
<span class="comment">'     5.3- Get Edges.</span>
<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>

<span class="keyword">Sub</span> GetProfileSubElements(iObjSddStiffener <span class="keyword">As</span> SddStiffener, oObjSddProfileSubElementMngt <span class="keyword">As</span> SddProfileSubElementMngt)

<span class="comment">' 5.1- Retrieves the SddProfileSubElementMngt object from the stiffener object.</span>    
    <span class="keyword">Set</span> oObjSddProfileSubElementMngt = iObjSddStiffener.ProfileSubElements
    
<span class="comment">' 5.2- Get Faces.</span>
    <span class="keyword">Dim</span> oListOfFaces <span class="keyword">As</span> References
    <span class="keyword">Set</span> oListOfFaces = oObjSddProfileSubElementMngt.<strong>GetFaces</strong>(&quot;WebInner+&quot;)

<span class="comment">' 5.3- Get Edges.</span>
    <span class="keyword">Dim</span> oListOfEdges <span class="keyword">As</span> References
    <span class="keyword">Set</span> oListOfEdges = oObjSddProfileSubElementMngt.<strong>GetEdges</strong>(&quot;Start&quot;, &quot;WebInner-&quot;)    
    
<span class="keyword">End Sub</span>

<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="comment">'Searches a product and open it.</span>
<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="keyword">Sub </span><strong>OpenProduct</strong>(byVal prdName as String, SDDPrdEditor<span class="keyword"> As </span>Editor)

    <span class="comment">'Get the Search Service.</span>
    <span class="keyword">Set </span>oSearchService = CATIA.GetSessionService(&quot;Search&quot;)
    <span class="keyword">Dim</span> oDBSearch <span class="keyword">As</span> DatabaseSearch 
    <span class="keyword">Set</span> oDBSearch = oSearchService.DatabaseSearch
    oDBSearch.BaseType = &quot;VPMReference&quot;
    <span class="comment">' To retrieve the product by its Title, use V_Name attribute</span>
    <span class="comment">' To retrieve the product by its Name, use PLM_ExternalID attribute</span>
    oDBSearch.AddEasyCriteria &quot;V_Name&quot;, prdName
    oSearchService.Search
    <span class="comment">'Retrieve the first entity.</span>
    <span class="keyword">Dim</span> oEntity <span class="keyword">As</span> PLMEntity 
    <span class="keyword">Set</span> oEntity = oDBSearch.Results.Item(1)
    <span class="comment">'Get the PLMOpen service &amp; Open the first retrieved entity.</span>
    <span class="keyword">Dim</span> oPLMOpenService <span class="keyword">As</span> PLMOpenService
    <span class="keyword">Set </span>oPLMOpenService = CATIA.GetSessionService(&quot;PLMOpenService&quot;)
    <span class="comment">'Get the editor.</span>
    oPLMOpenService.PLMOpen oEntity , SDDPrdEditor
    
<span class="keyword">End Sub</span>
</pre>
<script type="text/javascript">insertCopyright();</script>

</body>

</html>
