<!DOCTYPE html 
     PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
     "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
<meta http-equiv="Content-Language" content="en-us" />
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<meta name="devlang" content="idl" />
<link rel="stylesheet" type="text/css" href="../CAADocStyleSheets/caav5.css"/>
<script type="text/javascript" src="../CAADocJavaScript/DSDocTocToc.js">/* */</script>
<script type="text/javascript" src="../CAADocJavaScript/DSDocHighlight.js">/* */</script>
<script type="text/javascript" src="../CAADocJavaScript/submit.js">/* */</script>
<title>CAAScdSddUcCreateEndcut.CATScript</title>
</head>

<body onload="highlightSearchTerms();">

<pre>
<span class="comment">'-------------- Sample MACRO written in Basic Script ------------------------------------------</span>
<span class="comment">'This sample creates an Endcut and edit it.</span>
<span class="comment">'This script requires sdd model which contains a panel and stiffener on it</span>
<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="comment">'</span>
<span class="comment">''Steps</span>
<span class="comment">'   1- Searches and opens model which is named as &quot;SddProduct&quot;</span>
<span class="comment">'   2- Retrieves Selection object </span>
<span class="comment">'   3- Retrieves Part object </span>
<span class="comment">'   4- Retrieves a SddStiffener object</span>
<span class="comment">'   5- Creates Endcut.</span>
<span class="comment">'   6- Updates the Part object.</span>
<span class="comment">'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
Language=&quot;VBSCRIPT&quot; 
<span class="keyword">Dim </span>ObjPart<span class="keyword"> As </span>Part
<span class="keyword">Dim </span>SDDProdSel<span class="keyword"> As </span>Selection
<span class="keyword">Dim </span>StiffenerPart<span class="keyword"> As </span>Part

<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="keyword">Sub </span>CATMain()
    
<span class="comment">'   1- Searches and opens model which is named as &quot;SddProduct&quot;</span>
<span class="keyword">    Dim </span>SDDPrdEditor<span class="keyword"> As </span>Editor
<span class="keyword">    Dim </span>prdName<span class="keyword"> As </span>String
    prdName = &quot;SddProduct&quot;
    OpenProduct prdName , SDDPrdEditor
    
<span class="comment">'   2- Retrieves Selection object </span>
<span class="keyword">    Set </span>SDDProdSel = SDDPrdEditor.Selection

<span class="comment">'   3- Retrieves Part object </span>
<span class="keyword">    Dim </span>product1Service  <span class="keyword"> As </span>PLMProductService
<span class="keyword">    Set </span>product1Service = SDDPrdEditor.GetService(&quot;PLMProductService&quot;)
<span class="keyword">    Dim </span>ObjVPMRootOccurrence<span class="keyword"> As </span>VPMRootOccurrence
<span class="keyword">    Set </span>ObjVPMRootOccurrence = product1Service.RootOccurrence
<span class="keyword">    Dim </span>ObjVPMReference<span class="keyword"> As </span>VPMReference
<span class="keyword">    Set </span>ObjVPMReference = ObjVPMRootOccurrence.ReferenceRootOccurrenceOf
<span class="keyword">    Dim </span>ObjVPMRepInstances<span class="keyword"> As </span>VPMRepInstances
<span class="keyword">    Set </span>ObjVPMRepInstances = ObjVPMReference.RepInstances
<span class="keyword">    Set </span>ObjVPMRepReference = ObjVPMRepInstances.Item(1).ReferenceInstanceOf
<span class="keyword">    Set </span>ObjPart = ObjVPMRepReference.GetItem(&quot;Part&quot;)

<span class="comment">'   4- Retrieves a SddStiffener object.</span>
<span class="keyword">    Set </span>ListOfInstances = ObjVPMReference.Instances
<span class="keyword">    Set </span>StiffenerRef = ListOfInstances.Item(2).ReferenceInstanceOf
<span class="keyword">    Set </span>StiffenerRepInstances = StiffenerRef.RepInstances
<span class="keyword">    Set </span>StiffenerRepInstReference = StiffenerRepInstances.Item(1).ReferenceInstanceOf
<span class="keyword">    Set </span>StiffenerPart = StiffenerRepInstReference.GetItem(&quot;Part&quot;)
<span class="keyword">    Dim </span>ObjSddProductStiffener<span class="keyword"> As </span>SddProductStiffener
    SDDProdSel.Add StiffenerRef
<span class="keyword">    Set </span>ObjSddProductStiffener = SDDProdSel.FindObject(&quot;CATIASddProductStiffener&quot;)
    

<span class="comment">'   5- Creates Endcut.</span>
<span class="keyword">    Dim </span>ObjStrEndcut<span class="keyword"> As </span>StrEndcut
    CreateEndCut ObjSddProductStiffener, ObjStrEndcut
    
<span class="comment">'   6- Updates the Part object.</span>
    ObjPart.Update

<span class="keyword">End Sub</span>


<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="comment">'Create EndCut</span>
<span class="comment">'</span>
<span class="comment">''Steps</span>
<span class="comment">'   5.1- Retrieves StrEndcutMngt object and create an Endcut with no data        </span>
<span class="comment">'   5.2- Sets Endcut parameters</span>
<span class="comment">'   5.3- Updates StrEndCut object</span>
<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="keyword">Sub </span>CreateEndCut(iObjSddProductStiffener<span class="keyword"> As </span>SddProductStiffener, oObjStrEndcut<span class="keyword"> As </span>StrEndcut)

<span class="comment">'   5.1- Retrieves StrEndcutMngt object and create an Endcut with no data        </span>
    <span class="comment">'Get StrEndcutMngt object</span>
<span class="keyword">    Dim </span>ObjSddStiffener<span class="keyword"> As </span>SddStiffener
<span class="keyword">    Set </span>ObjSddStiffener = iObjSddProductStiffener.SddStiffener
<span class="keyword">    Dim </span>ObjStrEndcutMngt<span class="keyword"> As </span>StrEndcutMngt
<span class="keyword">    Set </span>ObjStrEndcutMngt = ObjSddStiffener.StrEndcutMngt
    
<span class="keyword">    Set </span>oObjStrEndcut = ObjStrEndcutMngt.AddEndCut(2)
    
<span class="comment">'   5.2- Sets Endcut parameters</span>
    SetSNIPE_WT_radiusEndCutParameters oObjStrEndcut

<span class="comment">'   5.3- Updates StrEndCut object</span>
   iObjSddProductStiffener.Update

<span class="keyword">End Sub</span>

<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="comment">'set End Cut parameters</span>
<span class="comment">'</span>
<span class="comment">''Steps</span>
<span class="comment">'   5.2.1- Retrieves StrDetailFeature object </span>
<span class="comment">'   5.2.2- Sets Endcut name</span>
<span class="comment">'   5.2.3- Retrieves list of parameters of impacted object </span>
<span class="comment">'   5.2.4- Sets SNIPE_WT_radiusEndCutParameters</span>
<span class="comment">'   5.2.5- Updates the ObjStrDetailFeature object</span>
<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="keyword">Sub </span>SetSNIPE_WT_radiusEndCutParameters(iObjStrEndcut<span class="keyword"> As </span>StrEndcut)

<span class="comment">'   5.2.1- Retrieves StrDetailFeature object </span>
<span class="keyword">    Dim </span>ObjStrDetailFeature<span class="keyword"> As </span>StrDetailFeature
<span class="keyword">    Set </span>ObjStrDetailFeature = iObjStrEndcut.StrDetailFeature

<span class="comment">'   5.2.2- Sets Endcut name</span>
    ObjStrDetailFeature.InitByName &quot;WT_snipe_radius&quot;
    
<span class="comment">'   5.2.3- Retrieves list of parameters of impacted object </span>
<span class="keyword">    Dim </span>EndcutParameters<span class="keyword"> As </span>StrParameters
<span class="keyword">    Set </span>EndcutParameters = ObjStrDetailFeature.GetParameters
    
<span class="comment">'   5.2.4- Sets SNIPE_WT_radiusEndCutParameters</span>
<span class="keyword">    Dim </span>Radius<span class="keyword"> As </span>Parameter
<span class="keyword">    Set </span>Radius = EndcutParameters.Item(1)
    Radius.ValuateFromString (&quot;70mm&quot;)
    
<span class="comment">'   5.2.5- Updates the ObjStrDetailFeature object</span>
    ObjStrDetailFeature.Update

<span class="keyword">End Sub</span>


<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="comment">'Searches a product and open it.</span>
<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="keyword">Sub </span><strong>OpenProduct</strong>(byVal prdName as String, SDDPrdEditor<span class="keyword"> As </span>Editor)

    <span class="comment">'Get the Search Service.</span>
    <span class="keyword">Set </span>oSearchService = CATIA.GetSessionService(&quot;Search&quot;)
    <span class="keyword">Dim</span> oDBSearch <span class="keyword">As</span> DatabaseSearch 
    <span class="keyword">Set</span> oDBSearch = oSearchService.DatabaseSearch
    oDBSearch.BaseType = &quot;VPMReference&quot;
    <span class="comment">' To retrieve the product by its Title, use V_Name attribute</span>
    <span class="comment">' To retrieve the product by its Name, use PLM_ExternalID attribute</span>
    oDBSearch.AddEasyCriteria &quot;V_Name&quot;, prdName
    oSearchService.Search
    <span class="comment">'Retrieve the first entity.</span>
    <span class="keyword">Dim</span> oEntity <span class="keyword">As</span> PLMEntity 
    <span class="keyword">Set</span> oEntity = oDBSearch.Results.Item(1)
    <span class="comment">'Get the PLMOpen service &amp; Open the first retrieved entity.</span>
    <span class="keyword">Dim</span> oPLMOpenService <span class="keyword">As</span> PLMOpenService
    <span class="keyword">Set </span>oPLMOpenService = CATIA.GetSessionService(&quot;PLMOpenService&quot;)
    <span class="comment">'Get the editor.</span>
    oPLMOpenService.PLMOpen oEntity , SDDPrdEditor
    
<span class="keyword">End Sub</span>
</pre>
<script type="text/javascript">insertCopyright();</script>
  </body>
</html>
