<!doctype html public "-//w3c//dtd html 4.0 transitional//en">
<html>
<head>
 <meta http-equiv="Content-Language" content="en-us"> 
 <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"> 
 <meta name="Generator" content="mihGene v1.1">
 <meta http-equiv="Expires" content="Tue, 04 Dec 1993 21:29:02 GMT">
 <title>CATGSMIDLItf HybridShapePointTangent (Object)</title>
<link rel="Stylesheet" type="text/css" href="../../../caav5.css">
<link href="../_index/cdg.css" rel="stylesheet" type="text/css"> 
<script type="text/javascript">var PubDirExist = false; var ProDirExist = false; var PrivDirExist = false;</script> 
<script type="text/javascript" src="../_index/cdg.js"></script> 
<script language="Javascript" id="jsLinkjs" type="text/javascript" src="../_index/jslink.js"></script> 
<script language="Javascript" id="jsFwLinkjs" type="text/javascript" src="jsFwLink.js"></script> 
<script language="Javascript" id="jsTreejs" type="text/javascript" src="../_index/jsTree.js"></script>  
</head>
<body>
<div class="menu1" id="menuViewPPP" > 
 	<a href="javascript:writeIndex('IPublic')" name="viewPPP" id="PublicView"  class="ongletPub" > Public View</a> 
 	<a href="javascript:writeIndex('IProtected')" name="viewPPP" id="ProtectedView" class="ongletPro"  > Protected View</a>  
 	<a href="javascript:writeIndex('IPrivate')" name="viewPPP" id="PrivateView" class="ongletPriv" > Private View</a> 
 </div> 
 <div id="indexView" class="menu1">	 
 <a name="multiview" class="onglet" rel="../_index/main.htm" href="../_index/main.htm">All Frameworks</a>   
 <a name="multiview" class="onglet"  rel="../_index/tree.htm" href="../_index/tree.htm">Class Hierarchy</a>   
 <a name="multiview" class="onglet"  rel="../CATGSMIDLItf.htm" href="../CATGSMIDLItf.htm">This Framework</a>
<a name="multiview" class="onglet"  rel="../_index/HomeIdx.htm" href="../_index/HomeIdx.htm">Indexes</a>  
 <a id="multiviewP" class="onglet" href="javascript:openLinkNP(getCurrentObjectName(),getCurrentType(),'0')"  >Previous</a>  
 	<a id="multiviewN" class="onglet" href="javascript:openLinkNP(getCurrentObjectName(),getCurrentType(),'1')"  >Next</a> 
 </div> 
<script type="text/javascript" > 
 	function getCurrentLevel() { 
 return "";	} 
	function getCurrentFw() { 
	return "CATGSMIDLItf";	}
		function getCurrentObjectName() { 
 	return "HybridShapePointTangent"; } 
	function getCurrentType() { 
 	return "interface"; }  
 function callInit() { 
 		if (PubDirExist == true || ProDirExist == true || PrivDirExist == true) {  
 			var parent = document.getElementById("indexView"); 
 			if (parent && (ProDirExist == true || PrivDirExist == true) ) { 
 			var elem = document.getElementById("multiviewP"); 
 			if(elem) parent.removeChild(elem); 
 			elem = document.getElementById("multiviewN"); 
 			if(elem) parent.removeChild(elem); }
 			initData(); 
 		} else { 
 			var elem; 
 			var parent = document.getElementById("menuViewPPP"); 
 			if (parent) { 
 				elem = document.getElementById("PublicView"); 
 				parent.removeChild(elem); 
 				elem = document.getElementById("ProtectedView"); 
 				parent.removeChild(elem); 
 				elem = document.getElementById("PrivateView"); 
 				parent.removeChild(elem); 
 			} 
 if (locateObject(getCurrentObjectName(), getCurrentType(), '0')==0) { 
 				elem = document.getElementById("multiviewP"); 
 				if (elem) { elem.removeAttribute("href"); elem.removeAttribute("onclick"); } 
 			} 
 			if (locateObject(getCurrentObjectName(), getCurrentType(), '1')==0) { 
 				elem = document.getElementById("multiviewN"); 
 				if (elem) { elem.removeAttribute("href"); elem.removeAttribute("onclick"); } 
 			} 
 }	 
 	} 
 	window.onload = callInit; 
  </script> 
 
<h1>HybridShapePointTangent<font size=-1> (Object)</font></h1>
<script type="text/javascript" > 
 generatedFatherClass('interface_HybridShapePointTangent_35586','HybridShapePointTangent','0');</script>
<b><i> Point Tangent.</i></b><br>
 
 <b>Role</b>: Allows to access data of the point feature created as follow :
 <br>The tangent to the curve at this point is colinear to a given direction.
 <br>Note: The resulting feature can contain several points.
 <dl>
  <dt> <b>See also:</b> 
  <dd> <script type="text/javascript"> activateLinkAnchor('CATIALength','','CATIALength') </script>
  <dt> <b>See also:</b> 
  <dd> <script type="text/javascript"> activateLinkAnchor('CATIAReference','','CATIAReference') </script>
  <dt> <b>See also:</b> 
  <dd> <script type="text/javascript"> activateLinkAnchor('CATIAHybridShapeDirection','','CATIAHybridShapeDirection') </script>
  <dt> <b>See also:</b> 
  <dd> <script type="text/javascript"> activateLinkAnchor('CATIAHybridShapeFactory','','CATIAHybridShapeFactory') </script>
</dl>
<hr>
<dl>
 <h2><a name="PropertyIndex"></a>Property Index</h2>
 <dt>
    <a href="#Curve"><b>Curve</b></a>
<dd>  Returns or Gets the supporting curve.
 <dt>
    <a href="#Direction"><b>Direction</b></a>
<dd>  Returns or Sets the direction.
</dl>
<dl>
</dl>
 <h2><a name="Properties"></a>Properties</h2> <br>
<a name="Curve"><dt>

<table><tr><td>o Property <b>Curve</b>(<td>) As <script type="text/javascript"> activateLink('CATIAReference','CATIAReference')</script> </table></dt>
<dl>
  <dd>
 Returns or Gets the supporting curve.
 <br>Sub-element(s) supported (see 
<script type="text/javascript"> activateLinkAnchor('CATIABoundary','','CATIABoundary') </script> object):  
<script type="text/javascript"> activateLinkAnchor('CATIAEdge','','CATIAEdge') </script>. <dl>
 <dt>Example</dt>:
 <dd>
 This example retrieves in <code>oCurve</code> the supporting Curve for the <code>PointTangent</code> feature.
 <pre>
 Dim oCurve As CATIAReference   
 Set oCurve  = PointTangent.<font color="red">Curve</font>
 </pre>
 </dl>
</dl>
<a name="Direction"><dt>

<table><tr><td>o Property <b>Direction</b>(<td>) As <script type="text/javascript"> activateLink('HybridShapeDirection','HybridShapeDirection')</script> </table></dt>
<dl>
  <dd>
 Returns or Sets the direction.
 <dl>
 <dt>Example</dt>:
 <dd>
 This example retrieves in <code>oDirection</code> the tangent direction use to compute
 on supporting curve the <code>PointTangent</code> feature.
 <pre>
 Dim oDirection As CATIAHybridShapeDirection
 Set oDirection  = PointTangent.<font color="red">Direction</font>
 </pre>
 </dl>
</dl>
<hr/><p><i>
Copyright &#169; 1999-2014, Dassault Syst&#232;mes. All rights reserved.
</i></p>
</body>

</html>

