<!doctype html public "-//w3c//dtd html 4.0 transitional//en">
<html>
<head>
 <meta http-equiv="Content-Language" content="en-us"> 
 <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"> 
 <meta name="Generator" content="mihGene v1.1">
 <meta http-equiv="Expires" content="Tue, 04 Dec 1993 21:29:02 GMT">
 <title>CATGSMIDLItf HybridShapePointBetween (Object)</title>
<link rel="Stylesheet" type="text/css" href="../../../caav5.css">
<link href="../_index/cdg.css" rel="stylesheet" type="text/css"> 
<script type="text/javascript">var PubDirExist = false; var ProDirExist = false; var PrivDirExist = false;</script> 
<script type="text/javascript" src="../_index/cdg.js"></script> 
<script language="Javascript" id="jsLinkjs" type="text/javascript" src="../_index/jslink.js"></script> 
<script language="Javascript" id="jsFwLinkjs" type="text/javascript" src="jsFwLink.js"></script> 
<script language="Javascript" id="jsTreejs" type="text/javascript" src="../_index/jsTree.js"></script>  
</head>
<body>
<div class="menu1" id="menuViewPPP" > 
 	<a href="javascript:writeIndex('IPublic')" name="viewPPP" id="PublicView"  class="ongletPub" > Public View</a> 
 	<a href="javascript:writeIndex('IProtected')" name="viewPPP" id="ProtectedView" class="ongletPro"  > Protected View</a>  
 	<a href="javascript:writeIndex('IPrivate')" name="viewPPP" id="PrivateView" class="ongletPriv" > Private View</a> 
 </div> 
 <div id="indexView" class="menu1">	 
 <a name="multiview" class="onglet" rel="../_index/main.htm" href="../_index/main.htm">All Frameworks</a>   
 <a name="multiview" class="onglet"  rel="../_index/tree.htm" href="../_index/tree.htm">Class Hierarchy</a>   
 <a name="multiview" class="onglet"  rel="../CATGSMIDLItf.htm" href="../CATGSMIDLItf.htm">This Framework</a>
<a name="multiview" class="onglet"  rel="../_index/HomeIdx.htm" href="../_index/HomeIdx.htm">Indexes</a>  
 <a id="multiviewP" class="onglet" href="javascript:openLinkNP(getCurrentObjectName(),getCurrentType(),'0')"  >Previous</a>  
 	<a id="multiviewN" class="onglet" href="javascript:openLinkNP(getCurrentObjectName(),getCurrentType(),'1')"  >Next</a> 
 </div> 
<script type="text/javascript" > 
 	function getCurrentLevel() { 
 return "";	} 
	function getCurrentFw() { 
	return "CATGSMIDLItf";	}
		function getCurrentObjectName() { 
 	return "HybridShapePointBetween"; } 
	function getCurrentType() { 
 	return "interface"; }  
 function callInit() { 
 		if (PubDirExist == true || ProDirExist == true || PrivDirExist == true) {  
 			var parent = document.getElementById("indexView"); 
 			if (parent && (ProDirExist == true || PrivDirExist == true) ) { 
 			var elem = document.getElementById("multiviewP"); 
 			if(elem) parent.removeChild(elem); 
 			elem = document.getElementById("multiviewN"); 
 			if(elem) parent.removeChild(elem); }
 			initData(); 
 		} else { 
 			var elem; 
 			var parent = document.getElementById("menuViewPPP"); 
 			if (parent) { 
 				elem = document.getElementById("PublicView"); 
 				parent.removeChild(elem); 
 				elem = document.getElementById("ProtectedView"); 
 				parent.removeChild(elem); 
 				elem = document.getElementById("PrivateView"); 
 				parent.removeChild(elem); 
 			} 
 if (locateObject(getCurrentObjectName(), getCurrentType(), '0')==0) { 
 				elem = document.getElementById("multiviewP"); 
 				if (elem) { elem.removeAttribute("href"); elem.removeAttribute("onclick"); } 
 			} 
 			if (locateObject(getCurrentObjectName(), getCurrentType(), '1')==0) { 
 				elem = document.getElementById("multiviewN"); 
 				if (elem) { elem.removeAttribute("href"); elem.removeAttribute("onclick"); } 
 			} 
 }	 
 	} 
 	window.onload = callInit; 
  </script> 
 
<h1>HybridShapePointBetween<font size=-1> (Object)</font></h1>
<script type="text/javascript" > 
 generatedFatherClass('interface_HybridShapePointBetween_35457','HybridShapePointBetween','0');</script>
<b><i> Represents the hybrid shape PointBetween feature object.</i></b><br>

 <b>Role</b>: To access the data of the hybrid shape PointBetween feature object.<BR>
 This data includes:
<ul>
<li>The first reference point
<li>The second reference point
</ul>
 <dl>
  <dt> <b>See also:</b> 
  <dd> <script type="text/javascript"> activateLinkAnchor('CATIAHybridShapeFactory','','CATIAHybridShapeFactory') </script>
</dl>
<hr>
<dl>
 <h2><a name="PropertyIndex"></a>Property Index</h2>
 <dt>
    <a href="#FirstPoint"><b>FirstPoint</b></a>
<dd>  Returns or sets the first reference point.
 <dt>
    <a href="#Orientation"><b>Orientation</b></a>
<dd>  Returns or sets the orientation.
 <dt>
    <a href="#Ratio"><b>Ratio</b></a>
<dd>   Get the ratio.
 <dt>
    <a href="#SecondPoint"><b>SecondPoint</b></a>
<dd>  Returns or sets the second reference point.
 <dt>
    <a href="#Support"><b>Support</b></a>
<dd>  Returns or Sets the support.
</dl>
<dl>
</dl>
 <h2><a name="Properties"></a>Properties</h2> <br>
<a name="FirstPoint"><dt>

<table><tr><td>o Property <b>FirstPoint</b>(<td>) As <script type="text/javascript"> activateLink('CATIAReference','CATIAReference')</script> </table></dt>
<dl>
  <dd>
 Returns or sets the first reference point.
 <br>Sub-element(s) supported (see 
<script type="text/javascript"> activateLinkAnchor('CATIABoundary','','CATIABoundary') </script> object):  
<script type="text/javascript"> activateLinkAnchor('CATIAVertex','','CATIAVertex') </script>.<dl>
<dt><b>Example</b>:
<dd>
 This example retrieves in <code>RefPoint1</code> the first reference point for the
<code>PointBetween</code> hybrid shape feature.
<pre>
 Dim RefPoint1 As Reference
 Set RefPoint1 = PointBetween.<font color="red">FirstPoint</font>
</pre>
</dl>
</dl>
<a name="Orientation"><dt>

<table><tr><td>o Property <b>Orientation</b>(<td>) As <script type="text/javascript"> activateLink('long','long')</script> </table></dt>
<dl>
  <dd>
 Returns or sets the orientation.
 <b>Role</b>:<br>
  Orientation = 1 means that distance is measured from the second point
 <dl>
 <dt><b>Example</b>:
 <dd>
 This example retrieves in <code>Orient</code> the orientation for the <code>PointBetween</code> hybrid shape feature.
<pre>
 Dim Orient As long
 Set Orient = PointBetween.<font color="red">Orientation</font>
 </pre>
 </dl>
</dl>
<a name="Ratio"><dt>

<table><tr><td>o Property <b>Ratio</b>(<td>) As <script type="text/javascript"> activateLink('CATIARealParam','CATIARealParam')</script>  (Read Only)</table></dt>
<dl>
  <dd>
  Get the ratio.
 <b>Role</b>: <br>
   if  d1 is the distance between the first point and the created point,
   and d2 is the distance between the first point and the second point,
   then ratio = d1/d2.
 <dl>
 <dt><b>Example</b>:
 <dd>
 This example retrieves in <code>ratio</code> the orientation for the <code>PointBetween</code> hybrid shape feature.
<pre>
 Dim ratio  As CATIARealParam
 Get ratio = PointBetween.<font color="red">Ratio</font>
 </pre>
 </dl>
</dl>
<a name="SecondPoint"><dt>

<table><tr><td>o Property <b>SecondPoint</b>(<td>) As <script type="text/javascript"> activateLink('CATIAReference','CATIAReference')</script> </table></dt>
<dl>
  <dd>
 Returns or sets the second reference point.
 <br>Sub-element(s) supported (see 
<script type="text/javascript"> activateLinkAnchor('CATIABoundary','','CATIABoundary') </script> object):  
<script type="text/javascript"> activateLinkAnchor('CATIAVertex','','CATIAVertex') </script>.<dl>
<dt><b>Example</b>:
<dd>
 This example retrieves in <code>RefPoint2</code> the second reference point for the
<code>PointBetween</code> hybrid shape feature.
<pre>
 Dim RefPoint2 As Reference
 Set RefPoint2 = PointBetween.<font color="red">SecondPoint</font>
</pre>
</dl>
</dl>
<a name="Support"><dt>

<table><tr><td>o Property <b>Support</b>(<td>) As <script type="text/javascript"> activateLink('CATIAReference','CATIAReference')</script> </table></dt>
<dl>
  <dd>
 Returns or Sets the support.
 <br> Note: the support can be surface or curve. It is not mandatory<br>
 <br>Sub-element(s) supported (see 
<script type="text/javascript"> activateLinkAnchor('CATIABoundary','','CATIABoundary') </script> object):  
<script type="text/javascript"> activateLinkAnchor('CATIAFace','','CATIAFace') </script> and 
<script type="text/javascript"> activateLinkAnchor('CATIATriDimFeatEdge','','CATIATriDimFeatEdge') </script> and 
<script type="text/javascript"> activateLinkAnchor('CATIABiDimFeatEdge','','CATIABiDimFeatEdge') </script>. <dl>
 <dt><b>Example</b>:
 <dd>
 This example retrieves in <code>oSupport</code> the support(if it exist)  
 for the <code>PointBetween</code> hybrid shape feature.
 <pre>
 Dim oSupport As Reference 
 Set oSupport = PointBetween.<font color="red">Support</font>
 </pre>
 </dl>
</dl>
<hr/><p><i>
Copyright &#169; 1999-2014, Dassault Syst&#232;mes. All rights reserved.
</i></p>
</body>

</html>

