<html>
<head>
 <meta name="Generator" content="mihGene v1.1">
 <meta http-equiv="Expires" content="Tue, 04 Dec 1993 21:29:02 GMT">
 <title>MecModInterfaces Boundary (Object)</title>
<link rel="Stylesheet" type="text/css" href="../../../caav5.css">
</head>
<body>
<pre><a href="../main.htm">All Frameworks</a>  <a href="../tree.htm">Object Hierarchy</a>  <a href="../MecModInterfaces.htm">This Framework</a>  <a href=".htm">Previous</a>  <a href="interface_Constraint_22634.htm">Next</a>  <a href="../CAAHomeIdx.htm">Indexes</a>  </pre>
<hr>
<h1>Boundary<font size=-1> (Object)</font></h1>
<pre>
<a href="../System/interface_IUnknown_14460.htm">IUnknown</a>
  |
  +---<a href="../System/interface_IDispatch_17333.htm">IDispatch</a>
    |
    +---<a href="../System/interface_CATBaseUnknown_40786.htm">CATBaseUnknown</a>
      |
      +---<a href="../System/interface_CATBaseDispatch_45333.htm">CATBaseDispatch</a>
        |
        +---<a href="../System/interface_AnyObject_17321.htm">AnyObject</a>
          |
          +---<a href="../InfInterfaces/interface_Reference_17481.htm">Reference</a>
            |
            +---Boundary
 </pre>
<hr><br>
<b><i> Topological cell, such as a face, an edge or a vertex.</i></b><br>

 <b>Role</b>: 
 The Boundary objects are basic topological objects, such as the edge of a Pad. Some of them posess 
 a geometrical feature (<i>planar</i> face, <i>rectilinear</i> edge).</br>
 You will create a Boundary object (such as the <a href="../MecModInterfaces/interface_TriDimFeatEdge_39030.htm">TriDimFeatEdge</a> object, which is derived, indirectly,  from the Boundary object) using the 
<a href="../MecModInterfaces/interface_Shapes_8122.htm#GetBoundary">Shapes.GetBoundary</a> , 
<a href="../MecModInterfaces/interface_HybridShapes_30836.htm#GetBoundary">HybridShapes.GetBoundary</a> ,  
<a href="../MecModInterfaces/interface_Sketches_14228.htm#GetBoundary">Sketches.GetBoundary</a> or 
<a href="../InfInterfaces/interface_Selection_18040.htm#SelectElement2">Selection.SelectElement2</a> method. Then, you pass it to the operator (such as 
<a href="../PartInterfaces/interface_ShapeFactory_31272.htm#AddNewEdgeFilletWithConstantRadius">ShapeFactory.AddNewEdgeFilletWithConstantRadius</a> ). Note that, regarding V4 sub-elements, once the data of a CATIA Version 4 Model has been copied to a .CATPart, the sub-elements of the resulting .CATPart are
 supported by the 
<a href="../MecModInterfaces/interface_Boundary_14542.htm">Boundary</a> object.</br>  The lifetime of a Boundary object is limited. In particular, after having call 
<a href="../MecModInterfaces/interface_Part_3788.htm#Update">Part.Update</a> , the Boundary objects are usually no more valid.</br> 
 <b>See also:</b>
 <ul>
 <li>
<a href="../MecModInterfaces/interface_Face_3398.htm">Face</a> , 
<a href="../MecModInterfaces/interface_PlanarFace_20456.htm">PlanarFace</a> , 
<a href="../MecModInterfaces/interface_CylindricalFace_46299.htm">CylindricalFace</a> </li> <li>
<a href="../MecModInterfaces/interface_Edge_3456.htm">Edge</a> , 
<a href="../MecModInterfaces/interface_TriDimFeatEdge_39030.htm">TriDimFeatEdge</a> , 
<a href="../MecModInterfaces/interface_RectilinearTriDimFeatEdge_125698.htm">RectilinearTriDimFeatEdge</a> , 
<a href="../MecModInterfaces/interface_BiDimFeatEdge_33192.htm">BiDimFeatEdge</a> , 
<a href="../MecModInterfaces/interface_RectilinearBiDimFeatEdge_114366.htm">RectilinearBiDimFeatEdge</a> , 
<a href="../MecModInterfaces/interface_MonoDimFeatEdge_44932.htm">MonoDimFeatEdge</a> , 
<a href="../MecModInterfaces/interface_RectilinearMonoDimFeatEdge_136236.htm">RectilinearMonoDimFeatEdge</a> </li> <li>
<a href="../MecModInterfaces/interface_Vertex_8466.htm">Vertex</a> , 
<a href="../MecModInterfaces/interface_TriDimFeatVertexOrBiDimFeatVertex_221087.htm">TriDimFeatVertexOrBiDimFeatVertex</a> , 
<a href="../MecModInterfaces/interface_NotWireBoundaryMonoDimFeatVertex_212840.htm">NotWireBoundaryMonoDimFeatVertex</a>, 
<a href="../MecModInterfaces/interface_ZeroDimFeatVertexOrWireBoundaryMonoDimFeatVertex_474398.htm">ZeroDimFeatVertexOrWireBoundaryMonoDimFeatVertex</a> </li> </ul>
 <b>Note:</b>
<a href="../MecModInterfaces/interface_Boundary_14542.htm">Boundary</a> objects cannot be selected into the specification tree.</p> <b>Note:</b>For a 
<a href="../MecModInterfaces/interface_Boundary_14542.htm">Boundary</a> object, the object returned by the 
<a href="../System/interface_AnyObject_17321.htm#Parent">AnyObject.Parent</a> property is the master shape. For example, if we have:<pre>
                         Pad.2
                          !
                          !
 +                        V
 !                      +---+ 
 !                    /   / !
 +-- Pad.1          /   /   !
 !                /   / one +------+
 !               +---+    /       /! <--- Pad.1
 !               !   !  /       /  +
 +-- Pad.2       !   !/       /   /
                 !   +------+   /
                 !          ! /
                 +----------+
 </pre>then, for the 
<a href="../MecModInterfaces/interface_PlanarFace_20456.htm">PlanarFace</a> number "one", the 
<a href="../System/interface_AnyObject_17321.htm#Parent">AnyObject.Parent</a> property returns the Pad.2 automation object (see 
<a href="../PartInterfaces/interface_Pad_1979.htm">Pad</a> ). <! @sample>
 <dl>
 <dt><b>Example:</b>
 <dd>
 This example asks the end user to select an edge (using the 
<a href="../MecModInterfaces/interface_TriDimFeatEdge_39030.htm">TriDimFeatEdge</a> object), and creates an edge fillet on this edge: <pre>
 Dim InputObjectType(0)
 Set Document = CATIA.ActiveDocument
 Set Selection = Document.Selection
 'We propose to the user that he select an edge
 InputObjectType(0)="TriDimFeatEdge"
 Status=Selection.SelectElement2(InputObjectType,"Select an edge",true)
 if (Status = "cancel") then Exit Sub
 Set EdgeFillet = ShapeFactory.AddNewEdgeFilletWithConstantRadius(Selection.Item(1).Value,1,5.0)
 EdgeFillet.EdgePropagation = 1
 Document.Part.Update 
 </pre>
 </dl>
<hr>
<dl>
</dl>
<dl>
</dl>

</body>
<hr><p><i>
Copyright &#169; 2003, Dassault Syst&#232;mes. All rights reserved.</i></p>
</html>
