<html>
<head>
 <meta name="Generator" content="mihGene v1.1">
 <meta http-equiv="Expires" content="Tue, 04 Dec 1993 21:29:02 GMT">
 <title>MecModInterfaces CylindricalFace (Object)</title>
<link rel="Stylesheet" type="text/css" href="../../../caav5.css">
</head>
<body>
<pre><a href="../main.htm">All Frameworks</a>  <a href="../tree.htm">Object Hierarchy</a>  <a href="../MecModInterfaces.htm">This Framework</a>  <a href=".htm">Previous</a>  <a href="interface_Edge_3456.htm">Next</a>  <a href="../CAAHomeIdx.htm">Indexes</a>  </pre>
<hr>
<h1>CylindricalFace<font size=-1> (Object)</font></h1>
<pre>
<a href="../System/interface_IUnknown_14460.htm">IUnknown</a>
  |
  +---<a href="../System/interface_IDispatch_17333.htm">IDispatch</a>
    |
    +---<a href="../System/interface_CATBaseUnknown_40786.htm">CATBaseUnknown</a>
      |
      +---<a href="../System/interface_CATBaseDispatch_45333.htm">CATBaseDispatch</a>
        |
        +---<a href="../System/interface_AnyObject_17321.htm">AnyObject</a>
          |
          +---<a href="../InfInterfaces/interface_Reference_17481.htm">Reference</a>
            |
            +---<a href="../MecModInterfaces/interface_Boundary_14542.htm">Boundary</a>
              |
              +---<a href="../MecModInterfaces/interface_Face_3398.htm">Face</a>
                |
                +---CylindricalFace
 </pre>
<hr><br>
<b><i> 2-D boundary with a cylindrical geometry.</i></b><br>

 <b>Role</b>: 
 This <a href="../MecModInterfaces/interface_Boundary_14542.htm">Boundary</a> object may be, for example, the lateral face of a cylinder.</br> You will create a CylindricalFace object using the 
<a href="../MecModInterfaces/interface_Shapes_8122.htm#GetBoundary">Shapes.GetBoundary</a> , 
<a href="../MecModInterfaces/interface_HybridShapes_30836.htm#GetBoundary">HybridShapes.GetBoundary</a> ,  
<a href="../MecModInterfaces/interface_Sketches_14228.htm#GetBoundary">Sketches.GetBoundary</a> or 
<a href="../InfInterfaces/interface_Selection_18040.htm#SelectElement2">Selection.SelectElement2</a> method. Then, you pass it to the operator (such as 
<a href="../PartInterfaces/interface_ShapeFactory_31272.htm#AddNewCircPattern">ShapeFactory.AddNewCircPattern</a> ).</br>  The lifetime of a CylindricalFace object is limited, see 
<a href="../MecModInterfaces/interface_Boundary_14542.htm">Boundary</a>.</br>  <! @sample>
 <dl>
 <dt><b>Example:</b>
 <dd>
 This example asks the end user to select a shape to pattern and a cylindrical face, and creates a circular
 pattern of the shape. The cylindrical face specifies the rotation axis.
 <pre>
 Dim InputObjectType(0)
 Set Document = CATIA.ActiveDocument
 Set Selection = Document.Selection
 'We propose to the user that he select the shape to pattern
 InputObjectType(0)="SketchBasedShape"
 Status=Selection.SelectElement2(InputObjectType,"Select the shape to pattern",true)
 if (Status = "cancel") then Exit Sub
 Set Shape = Selection.Item(1).Value
 Selection.Clear
 'We propose to the user that he select the cylindrical face
 InputObjectType(0)="CylindricalFace"
 Status=Selection.SelectElement2(InputObjectType,"Select the cylindrical face",true)
 if (Status = "cancel") then Exit Sub
 Set CylindricalFace = Selection.Item(1).Value
 Set RotationCenter = Document.Part.CreateReferenceFromName("")
 Set CircPattern = ShapeFactory.AddNewCircPattern(Shape,1,4,20.0,45.0,1,4,RotationCenter,CylindricalFace,True,0.0,True)
 Document.Part.Update  
 </pre>
 </dl>
<hr>
<dl>
</dl>
<dl>
 <h2><a name="MethodIndex"></a>Method Index</h2>
 <dt>
    <a href="#GetDirection"><b>GetDirection</b></a>
<dd>   Returns the direction of the cylindrical face axis
   
 <dt>
    <a href="#GetOrigin"><b>GetOrigin</b></a>
<dd>  Returns the origin of the cylindrical face axis.
</dl>
 <h2><a name="Methods"></a>Methods</h2> <br>
<a name="GetDirection"><dt>

<table><tr><td>o Sub <b>GetDirection</b>(<td><a href="../System/typedef_CATSafeArrayVariant_73843.htm">CATSafeArrayVariant</a> <td><tt>oDirection</tt>)</table></dt>
<dl>
  <dd>
  Returns the direction of the cylindrical face axis
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> oDirection[0]</tt>
   <dd>   The X Coordinate of the axis direction 
   </dd>
    <dt><tt> oDirection[1]</tt>
   <dd>   The Y Coordinate of the axis direction
   </dd>
    <dt><tt> oDirection[2]</tt>
   <dd>   The Z Coordinate of the axis direction</dd>
</dl>
</dl>
</dl>
<a name="GetOrigin"><dt>

<table><tr><td>o Sub <b>GetOrigin</b>(<td><a href="../System/typedef_CATSafeArrayVariant_73843.htm">CATSafeArrayVariant</a> <td><tt>oOrigin</tt>)</table></dt>
<dl>
  <dd>
 Returns the origin of the cylindrical face axis. 	
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> oOrigin[0]</tt>
   <dd>   The X Coordinate of the axis origin
   </dd>
    <dt><tt> oOrigin[1]</tt>
   <dd>   The Y Coordinate of the axis origin
   </dd>
    <dt><tt> oOrigin[2]</tt>
   <dd>   The Z Coordinate of the axis origin</dd>
</dl>
</dl>
</dl>

</body>
<hr><p><i>
Copyright &#169; 2003, Dassault Syst&#232;mes. All rights reserved.</i></p>
</html>
