<html>
<head>
 <meta name="Generator" content="mihGene v1.1">
 <meta http-equiv="Expires" content="Tue, 04 Dec 1993 21:29:02 GMT">
 <title>MecModInterfaces Edge (Object)</title>
<link rel="Stylesheet" type="text/css" href="../../../caav5.css">
</head>
<body>
<pre><a href="../main.htm">All Frameworks</a>  <a href="../tree.htm">Object Hierarchy</a>  <a href="../MecModInterfaces.htm">This Framework</a>  <a href=".htm">Previous</a>  <a href="interface_Face_3398.htm">Next</a>  <a href="../CAAHomeIdx.htm">Indexes</a>  </pre>
<hr>
<h1>Edge<font size=-1> (Object)</font></h1>
<pre>
<a href="../System/interface_IUnknown_14460.htm">IUnknown</a>
  |
  +---<a href="../System/interface_IDispatch_17333.htm">IDispatch</a>
    |
    +---<a href="../System/interface_CATBaseUnknown_40786.htm">CATBaseUnknown</a>
      |
      +---<a href="../System/interface_CATBaseDispatch_45333.htm">CATBaseDispatch</a>
        |
        +---<a href="../System/interface_AnyObject_17321.htm">AnyObject</a>
          |
          +---<a href="../InfInterfaces/interface_Reference_17481.htm">Reference</a>
            |
            +---<a href="../MecModInterfaces/interface_Boundary_14542.htm">Boundary</a>
              |
              +---Edge
 </pre>
<hr><br>
<b><i> 1-D boundary.</i></b><br>

 <b>Role</b>: 
 This <a href="../MecModInterfaces/interface_Boundary_14542.htm">Boundary</a> object may be, for example, the edge of a cylinder.</br> You will create an Edge object using the 
<a href="../MecModInterfaces/interface_Shapes_8122.htm#GetBoundary">Shapes.GetBoundary</a> , 
<a href="../MecModInterfaces/interface_HybridShapes_30836.htm#GetBoundary">HybridShapes.GetBoundary</a> ,  
<a href="../MecModInterfaces/interface_Sketches_14228.htm#GetBoundary">Sketches.GetBoundary</a> or 
<a href="../InfInterfaces/interface_Selection_18040.htm#SelectElement2">Selection.SelectElement2</a> method. Then, you pass it to the operator (such as 
<a href="../GSMInterfaces/interface_HybridShapeFactory_68680.htm#AddNewPointTangent">HybridShapeFactory.AddNewPointTangent</a> ).</br>  The lifetime of an Edge object is limited, see 
<a href="../MecModInterfaces/interface_Boundary_14542.htm">Boundary</a>.</br>  <b>See also:</b><br>
 
<a href="../MecModInterfaces/interface_TriDimFeatEdge_39030.htm">TriDimFeatEdge</a> , 
<a href="../MecModInterfaces/interface_RectilinearTriDimFeatEdge_125698.htm">RectilinearTriDimFeatEdge</a> , 
<a href="../MecModInterfaces/interface_BiDimFeatEdge_33192.htm">BiDimFeatEdge</a> , 
<a href="../MecModInterfaces/interface_RectilinearBiDimFeatEdge_114366.htm">RectilinearBiDimFeatEdge</a> , 
<a href="../MecModInterfaces/interface_MonoDimFeatEdge_44932.htm">MonoDimFeatEdge</a> , 
<a href="../MecModInterfaces/interface_RectilinearMonoDimFeatEdge_136236.htm">RectilinearMonoDimFeatEdge</a> . <! @sample>
 <dl>
 <dt><b>Example:</b>
 <dd>
 This example asks the end user to select a planar curve, whose plane is parallel to the XY plane. 
 Then, it creates a point on the tangent to the curve in the X direction:
 <pre>
 Dim InputObjectType(0)
 Set Document = CATIA.ActiveDocument
 Set Selection = Document.Selection
 Set HybridBodies = Document.Part.HybridBodies
 Set HybridBody = HybridBodies.Item("Geometrical Set.1")
 'We propose to the user that he select a planar curve whose plane is parallel to the XY plane
 InputObjectType(0)="Edge"
 Status=Selection.SelectElement2(InputObjectType,"Select a planar curve whose plane is parallel to the XY plane",true)
 if (Status = "cancel") then Exit Sub
 Set PlanarCurve = Selection.Item(1).Value
 Set HybridShapeDirection = HybridShapeFactory.AddNewDirectionByCoord(1.0,0.0,0.0)
 Set HybridShapePointTangent = HybridShapeFactory.AddNewPointTangent(PlanarCurve,HybridShapeDirection)
 HybridBody.AppendHybridShape HybridShapePointTangent
 Document.Part.InWorkObject = HybridShapePointTangent
 Document.Part.Update  
 </pre>
 </dl>
<hr>
<dl>
</dl>
<dl>
</dl>

</body>
<hr><p><i>
Copyright &#169; 2003, Dassault Syst&#232;mes. All rights reserved.</i></p>
</html>
