<html>
<head>
 <meta name="Generator" content="mihGene v1.1">
 <meta http-equiv="Expires" content="Tue, 04 Dec 1993 21:29:02 GMT">
 <title>MecModInterfaces PlanarFace (Object)</title>
<link rel="Stylesheet" type="text/css" href="../../../caav5.css">
</head>
<body>
<pre><a href="../main.htm">All Frameworks</a>  <a href="../tree.htm">Object Hierarchy</a>  <a href="../MecModInterfaces.htm">This Framework</a>  <a href=".htm">Previous</a>  <a href="interface_RectilinearBiDimFeatEdge_114366.htm">Next</a>  <a href="../CAAHomeIdx.htm">Indexes</a>  </pre>
<hr>
<h1>PlanarFace<font size=-1> (Object)</font></h1>
<pre>
<a href="../System/interface_IUnknown_14460.htm">IUnknown</a>
  |
  +---<a href="../System/interface_IDispatch_17333.htm">IDispatch</a>
    |
    +---<a href="../System/interface_CATBaseUnknown_40786.htm">CATBaseUnknown</a>
      |
      +---<a href="../System/interface_CATBaseDispatch_45333.htm">CATBaseDispatch</a>
        |
        +---<a href="../System/interface_AnyObject_17321.htm">AnyObject</a>
          |
          +---<a href="../InfInterfaces/interface_Reference_17481.htm">Reference</a>
            |
            +---<a href="../MecModInterfaces/interface_Boundary_14542.htm">Boundary</a>
              |
              +---<a href="../MecModInterfaces/interface_Face_3398.htm">Face</a>
                |
                +---PlanarFace
 </pre>
<hr><br>
<b><i> 2-D boundary with a planar geometry.</i></b><br>

 <b>Role</b>: 
 This <a href="../MecModInterfaces/interface_Boundary_14542.htm">Boundary</a> object may be, for example, the face of a cube.</br> You will create a PlanarFace object using the 
<a href="../MecModInterfaces/interface_Shapes_8122.htm#GetBoundary">Shapes.GetBoundary</a> , 
<a href="../MecModInterfaces/interface_HybridShapes_30836.htm#GetBoundary">HybridShapes.GetBoundary</a> ,  
<a href="../MecModInterfaces/interface_Sketches_14228.htm#GetBoundary">Sketches.GetBoundary</a> or 
<a href="../InfInterfaces/interface_Selection_18040.htm#SelectElement2">Selection.SelectElement2</a> method. Then, you pass it to the operator (such as 
<a href="../PartInterfaces/interface_ShapeFactory_31272.htm#AddNewDraft">ShapeFactory.AddNewDraft</a> ).</br>  The lifetime of a PlanarFace object is limited, see 
<a href="../MecModInterfaces/interface_Boundary_14542.htm">Boundary</a>.</br>  <! @sample>
 <dl>
 <dt><b>Example:</b>
 <dd>
 This example asks the end user to select a face and two planar faces, and creates a draft on these faces:
 <pre>
 Dim InputObjectType(0)
 Set Document = CATIA.ActiveDocument
 Set Selection = Document.Selection
 'We propose to the user that he select the face to draft
 InputObjectType(0)="Face"
 Status=Selection.SelectElement2(InputObjectType,"Select the face to draft",true)
 if (Status = "cancel") then Exit Sub
 Set FaceToDraft = Selection.Item(1).Value
 Selection.Clear
 'We propose to the user that he select the neutral face
 InputObjectType(0)="PlanarFace"
 Status=Selection.SelectElement2(InputObjectType,"Select the neutral face",true)
 if (Status = "cancel") then Exit Sub
 Set NeutralFace = Selection.Item(1).Value
 Selection.Clear
 'We propose to the user that he select the parting element
 InputObjectType(0)="PlanarFace"
 Status=Selection.SelectElement2(InputObjectType,"Select the parting element",true)
 if (Status = "cancel") then Exit Sub
 Set PartingElement = Selection.Item(1).Value
 Set Draft = ShapeFactory.AddNewDraft(FaceToDraft,NeutralFace,0,PartingElement,0.0,0.0,1.0,0,5.0,0)
 Set DraftDomains = Draft.DraftDomains
 Set DraftDomain = DraftDomains.Item(1)
 DraftDomain.SetPullingDirection 0.0, 0.0,1.0
 Document.Part.Update  
 </pre>
 </dl>
<hr>
<dl>
</dl>
<dl>
 <h2><a name="MethodIndex"></a>Method Index</h2>
 <dt>
    <a href="#GetFirstAxis"><b>GetFirstAxis</b></a>
<dd>   Returns the planar face first axis
   
 <dt>
    <a href="#GetOrigin"><b>GetOrigin</b></a>
<dd>  Returns the origin of the planar face.
 <dt>
    <a href="#GetSecondAxis"><b>GetSecondAxis</b></a>
<dd>   Returns the planar face second axis.
</dl>
 <h2><a name="Methods"></a>Methods</h2> <br>
<a name="GetFirstAxis"><dt>

<table><tr><td>o Sub <b>GetFirstAxis</b>(<td><a href="../System/typedef_CATSafeArrayVariant_73843.htm">CATSafeArrayVariant</a> <td><tt>oFirstAxis</tt>)</table></dt>
<dl>
  <dd>
  Returns the planar face first axis
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> oFirstAxis[0]</tt>
   <dd>   The X Coordinate of the planar face first axis
   </dd>
    <dt><tt> oFirstAxis[1]</tt>
   <dd>   The Y Coordinate of the planar face first axis
   </dd>
    <dt><tt> oFirstAxis[2]</tt>
   <dd>   The Z Coordinate of the planar face first axis</dd>
</dl>
</dl>
</dl>
<a name="GetOrigin"><dt>

<table><tr><td>o Sub <b>GetOrigin</b>(<td><a href="../System/typedef_CATSafeArrayVariant_73843.htm">CATSafeArrayVariant</a> <td><tt>oOrigin</tt>)</table></dt>
<dl>
  <dd>
 Returns the origin of the planar face. 	
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> oOrigin[0]</tt>
   <dd>   The X Coordinate of the planar face origin
   </dd>
    <dt><tt> oOrigin[1]</tt>
   <dd>   The Y Coordinate of the planar face origin
   </dd>
    <dt><tt> oOrigin[2]</tt>
   <dd>   The Z Coordinate of the planar face origin</dd>
</dl>
</dl>
</dl>
<a name="GetSecondAxis"><dt>

<table><tr><td>o Sub <b>GetSecondAxis</b>(<td><a href="../System/typedef_CATSafeArrayVariant_73843.htm">CATSafeArrayVariant</a> <td><tt>oSecondAxis</tt>)</table></dt>
<dl>
  <dd>
  Returns the planar face second axis.
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> oSecondAxis[0]</tt>
   <dd>    The X Coordinate of the planar face second axis
   </dd>
    <dt><tt> oSecondAxis[1]</tt>
   <dd>   The Y Coordinate of the planar face second axis
   </dd>
    <dt><tt> oSecondAxis[2]</tt>
   <dd>   The Z Coordinate of the planar face second axis</dd>
</dl>
</dl>
</dl>

</body>
<hr><p><i>
Copyright &#169; 2003, Dassault Syst&#232;mes. All rights reserved.</i></p>
</html>
