<html>
<head>
 <meta name="Generator" content="mihGene v1.1">
 <meta http-equiv="Expires" content="Tue, 04 Dec 1993 21:29:02 GMT">
 <title>MecModInterfaces Face (Object)</title>
<link rel="Stylesheet" type="text/css" href="../../../caav5.css">
</head>
<body>
<pre><a href="../main.htm">All Frameworks</a>  <a href="../tree.htm">Object Hierarchy</a>  <a href="../MecModInterfaces.htm">This Framework</a>  <a href=".htm">Previous</a>  <a href="interface_Factory_11318.htm">Next</a>  <a href="../CAAHomeIdx.htm">Indexes</a>  </pre>
<hr>
<h1>Face<font size=-1> (Object)</font></h1>
<pre>
<a href="../System/interface_IUnknown_14460.htm">IUnknown</a>
  |
  +---<a href="../System/interface_IDispatch_17333.htm">IDispatch</a>
    |
    +---<a href="../System/interface_CATBaseUnknown_40786.htm">CATBaseUnknown</a>
      |
      +---<a href="../System/interface_CATBaseDispatch_45333.htm">CATBaseDispatch</a>
        |
        +---<a href="../System/interface_AnyObject_17321.htm">AnyObject</a>
          |
          +---<a href="../InfInterfaces/interface_Reference_17481.htm">Reference</a>
            |
            +---<a href="../MecModInterfaces/interface_Boundary_14542.htm">Boundary</a>
              |
              +---Face
 </pre>
<hr><br>
<b><i> 2-D boundary.</i></b><br>

 <b>Role</b>: 
 This <a href="../MecModInterfaces/interface_Boundary_14542.htm">Boundary</a> object may be, for example, the lateral face of cylinder.</br> You will create a Face object using the 
<a href="../MecModInterfaces/interface_Shapes_8122.htm#GetBoundary">Shapes.GetBoundary</a> , 
<a href="../MecModInterfaces/interface_HybridShapes_30836.htm#GetBoundary">HybridShapes.GetBoundary</a> ,  
<a href="../MecModInterfaces/interface_Sketches_14228.htm#GetBoundary">Sketches.GetBoundary</a> or 
<a href="../InfInterfaces/interface_Selection_18040.htm#SelectElement2">Selection.SelectElement2</a> method. Then, you pass it to the operator (such as 
<a href="../PartInterfaces/interface_ShapeFactory_31272.htm#AddNewFaceFillet">ShapeFactory.AddNewFaceFillet</a> ).</br>  The lifetime of a Face object is limited, see 
<a href="../MecModInterfaces/interface_Boundary_14542.htm">Boundary</a>.</br>  <b>See also:</b><br>
 
<a href="../MecModInterfaces/interface_PlanarFace_20456.htm">PlanarFace</a> , 
<a href="../MecModInterfaces/interface_CylindricalFace_46299.htm">CylindricalFace</a> . <! @sample>
 <dl>
 <dt><b>Example:</b>
 <dd>
 This example asks the end user to select two faces, and creates a face-face fillet on these faces:
 <pre>
 Dim InputObjectType(0)
 Set Document = CATIA.ActiveDocument
 Set Selection = Document.Selection
 'We propose to the user that he select the first face
 InputObjectType(0)="Face"
 Status=Selection.SelectElement2(InputObjectType,"Select the first face",true)
 if (Status = "cancel") then Exit Sub
 Set FirstFace = Selection.Item(1).Value
 Selection.Clear
 'We propose to the user that he select the second face
 InputObjectType(0)="Face"
 Status=Selection.SelectElement2(InputObjectType,"Select the second face",true)
 if (Status = "cancel") then Exit Sub
 Set SecondFace = Selection.Item(1).Value
 Set FaceFillet = ShapeFactory.AddNewFaceFillet(FirstFace,SecondFace,5.0)
 Document.Part.Update  
 </pre>
 </dl>
<hr>
<dl>
</dl>
<dl>
</dl>

</body>
<hr><p><i>
Copyright &#169; 2003, Dassault Syst&#232;mes. All rights reserved.</i></p>
</html>
