<html>
<head>
 <meta name="Generator" content="mihGene v1.1">
 <meta http-equiv="Expires" content="Tue, 04 Dec 1993 21:29:02 GMT">
 <title>MecModInterfaces RectilinearTriDimFeatEdge (Object)</title>
<link rel="Stylesheet" type="text/css" href="../../../caav5.css">
</head>
<body>
<pre><a href="../main.htm">All Frameworks</a>  <a href="../tree.htm">Object Hierarchy</a>  <a href="../MecModInterfaces.htm">This Framework</a>  <a href=".htm">Previous</a>  <a href="interface_Shape_5555.htm">Next</a>  <a href="../CAAHomeIdx.htm">Indexes</a>  </pre>
<hr>
<h1>RectilinearTriDimFeatEdge<font size=-1> (Object)</font></h1>
<pre>
<a href="../System/interface_IUnknown_14460.htm">IUnknown</a>
  |
  +---<a href="../System/interface_IDispatch_17333.htm">IDispatch</a>
    |
    +---<a href="../System/interface_CATBaseUnknown_40786.htm">CATBaseUnknown</a>
      |
      +---<a href="../System/interface_CATBaseDispatch_45333.htm">CATBaseDispatch</a>
        |
        +---<a href="../System/interface_AnyObject_17321.htm">AnyObject</a>
          |
          +---<a href="../InfInterfaces/interface_Reference_17481.htm">Reference</a>
            |
            +---<a href="../MecModInterfaces/interface_Boundary_14542.htm">Boundary</a>
              |
              +---<a href="../MecModInterfaces/interface_Edge_3456.htm">Edge</a>
                |
                +---<a href="../MecModInterfaces/interface_TriDimFeatEdge_39030.htm">TriDimFeatEdge</a>
                  |
                  +---RectilinearTriDimFeatEdge
 </pre>
<hr><br>
<b><i> 1-D boundary belonging to a feature whose topological result is three dimensional, the boundary having a rectilinear geometry.</i></b><br>

 <b>Role</b>: 
 This <a href="../MecModInterfaces/interface_Boundary_14542.htm">Boundary</a> object may be, for example, the edge of a Pad resulting from the extrusion of a square.</br>  You will create a RectilinearTriDimFeatEdge object using the 
<a href="../MecModInterfaces/interface_Shapes_8122.htm#GetBoundary">Shapes.GetBoundary</a> , 
<a href="../MecModInterfaces/interface_HybridShapes_30836.htm#GetBoundary">HybridShapes.GetBoundary</a> ,  
<a href="../MecModInterfaces/interface_Sketches_14228.htm#GetBoundary">Sketches.GetBoundary</a> or 
<a href="../InfInterfaces/interface_Selection_18040.htm#SelectElement2">Selection.SelectElement2</a> method. Then, you pass it to the operator (such as 
<a href="../PartInterfaces/interface_Hole_3612.htm#SetDirection">Hole.SetDirection</a> ).</br>  The lifetime of a RectilinearTriDimFeatEdge object is limited, see 
<a href="../MecModInterfaces/interface_Boundary_14542.htm">Boundary</a>.</br>  <! @sample>
 <dl>
 <dt><b>Example:</b>
 <dd>
 This example asks the end user to select a face, a rectilinear edge, and creates a hole.
 The rectilinear edge specifies the hole direction. It may be a RectilinearTriDimFeatEdge, a RectilinearBiDimFeatEdge
 or a RectilinearMonoDimFeatEdge.
 <pre>
 Dim EnabledObjectSelection1(0)
 Dim EnabledObjectSelection2(2)
 Set Document = CATIA.ActiveDocument
 Set Selection = Document.Selection
 'We propose to the user that he select a face
 EnabledObjectSelection1(0)="Face"
 Status=Selection.SelectElement2(EnabledObjectSelection1,"Select a face",true)
 if (Status = "cancel") then Exit Sub
 Set Face = Selection.Item(1).Value
 Selection.Clear
 'We propose to the user that he select the hole direction
 EnabledObjectSelection2(0)="RectilinearTriDimFeatEdge"
 EnabledObjectSelection2(1)="RectilinearBiDimFeatEdge"
 EnabledObjectSelection2(2)="RectilinearMonoDimFeatEdge"
 Status=Selection.SelectElement2(EnabledObjectSelection2,"Select the hole direction",true)
 if (Status = "cancel") then Exit Sub
 Set Hole = ShapeFactory.AddNewHoleFromPoint(20.0,-5.5, 1.07,Face,10.0)
 Hole.ThreadingMode = 1
 Hole.ThreadSide = 0
 Hole.SetDirection Selection.Item(1).Value
 Document.Part.Update 
 </pre>
 </dl>
<hr>
<dl>
</dl>
<dl>
 <h2><a name="MethodIndex"></a>Method Index</h2>
 <dt>
    <a href="#GetDirection"><b>GetDirection</b></a>
<dd>   Returns the direction of the rectilinear edge
   
 <dt>
    <a href="#GetOrigin"><b>GetOrigin</b></a>
<dd>  Returns the origin of the the rectilinear edge.
</dl>
 <h2><a name="Methods"></a>Methods</h2> <br>
<a name="GetDirection"><dt>

<table><tr><td>o Sub <b>GetDirection</b>(<td><a href="../System/typedef_CATSafeArrayVariant_73843.htm">CATSafeArrayVariant</a> <td><tt>oDirection</tt>)</table></dt>
<dl>
  <dd>
  Returns the direction of the rectilinear edge
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> oDirection[0]</tt>
   <dd>   The X Coordinate of the direction
   </dd>
    <dt><tt> oDirection[1]</tt>
   <dd>   The Y Coordinate of the direction
   </dd>
    <dt><tt> oDirection[2]</tt>
   <dd>   The Z Coordinate of the direction</dd>
</dl>
</dl>
</dl>
<a name="GetOrigin"><dt>

<table><tr><td>o Sub <b>GetOrigin</b>(<td><a href="../System/typedef_CATSafeArrayVariant_73843.htm">CATSafeArrayVariant</a> <td><tt>oOrigin</tt>)</table></dt>
<dl>
  <dd>
 Returns the origin of the the rectilinear edge. 	
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> oOrigin[0]</tt>
   <dd>   The X Coordinate of the rectilinear edge origin
   </dd>
    <dt><tt> oOrigin[1]</tt>
   <dd>   The Y Coordinate of the rectilinear edge origin
   </dd>
    <dt><tt> oOrigin[2]</tt>
   <dd>   The Z Coordinate of the rectilinear edge origin</dd>
</dl>
</dl>
</dl>

</body>
<hr><p><i>
Copyright &#169; 2003, Dassault Syst&#232;mes. All rights reserved.</i></p>
</html>
