<html>
<head>
 <meta name="Generator" content="mihGene v1.1">
 <meta http-equiv="Expires" content="Tue, 04 Dec 1993 21:29:02 GMT">
 <title>KnowledgeInterfaces Rule (Object)</title>
<link rel="Stylesheet" type="text/css" href="../../../caav5.css">
</head>
<body>
<pre><a href="../main.htm">All Frameworks</a>  <a href="../tree.htm">Object Hierarchy</a>  <a href="../KnowledgeInterfaces.htm">This Framework</a>  <a href=".htm">Previous</a>  <a href="interface_SetOfEquation_36247.htm">Next</a>  <a href="../CAAHomeIdx.htm">Indexes</a>  </pre>
<hr>
<h1>Rule<font size=-1> (Object)</font></h1>
<pre>
<a href="../System/interface_IUnknown_14460.htm">IUnknown</a>
  |
  +---<a href="../System/interface_IDispatch_17333.htm">IDispatch</a>
    |
    +---<a href="../System/interface_CATBaseUnknown_40786.htm">CATBaseUnknown</a>
      |
      +---<a href="../System/interface_CATBaseDispatch_45333.htm">CATBaseDispatch</a>
        |
        +---<a href="../System/interface_AnyObject_17321.htm">AnyObject</a>
          |
          +---<a href="../KnowledgeInterfaces/interface_KnowledgeObject_47429.htm">KnowledgeObject</a>
            |
            +---<a href="../KnowledgeInterfaces/interface_KnowledgeActivateObject_110372.htm">KnowledgeActivateObject</a>
              |
              +---<a href="../KnowledgeInterfaces/interface_Relation_14366.htm">Relation</a>
                |
                +---Rule
 </pre>
<hr><br>
<b><i> Represents the program relation.</i></b><br>

 The following example shows how to create a program that selects a 
 depth with respect to a mass value. The depth and mass parameters
 should exist before the creation of the program (also called Rule) object.
 <pre>
	Dim CATDocs As Documents
 Set CATDocs = CATIA.Documents
 Dim part1 As Document
 Set part1   = CATDocs.Add("CATPart")
 Dim mass As RealParam
 Set mass         = part1.Part.Parameters.<font color="red">CreateReal</font>("mass", 5.)
 Dim depth As RealParam
 Set depth        = part1.Part.Parameters.<font color="red">CreateReal</font>("depth", 0.)
 Dim selectdepth As Relation
 Set selectdepth = part1.Part.Relations.<font color="red">CreateProgram</font>
                    ("select_depth",
                     "Select depth with respect to mass", 
                     "if (mass>2kg) { depth=2mm } else { depth=1mm }")
 </pre><hr>
<dl>
</dl>
<dl>
</dl>

</body>
<hr><p><i>
Copyright &#169; 2003, Dassault Syst&#232;mes. All rights reserved.</i></p>
</html>
