<html>
<head>
 <meta name="Generator" content="mihGene v1.1">
 <meta http-equiv="Expires" content="Tue, 04 Dec 1993 21:29:02 GMT">
 <title>KnowledgeInterfaces Formula (Object)</title>
<link rel="Stylesheet" type="text/css" href="../../../caav5.css">
</head>
<body>
<pre><a href="../main.htm">All Frameworks</a>  <a href="../tree.htm">Object Hierarchy</a>  <a href="../KnowledgeInterfaces.htm">This Framework</a>  <a href=".htm">Previous</a>  <a href="interface_FreeParameter_36139.htm">Next</a>  <a href="../CAAHomeIdx.htm">Indexes</a>  </pre>
<hr>
<h1>Formula<font size=-1> (Object)</font></h1>
<pre>
<a href="../System/interface_IUnknown_14460.htm">IUnknown</a>
  |
  +---<a href="../System/interface_IDispatch_17333.htm">IDispatch</a>
    |
    +---<a href="../System/interface_CATBaseUnknown_40786.htm">CATBaseUnknown</a>
      |
      +---<a href="../System/interface_CATBaseDispatch_45333.htm">CATBaseDispatch</a>
        |
        +---<a href="../System/interface_AnyObject_17321.htm">AnyObject</a>
          |
          +---<a href="../KnowledgeInterfaces/interface_KnowledgeObject_47429.htm">KnowledgeObject</a>
            |
            +---<a href="../KnowledgeInterfaces/interface_KnowledgeActivateObject_110372.htm">KnowledgeActivateObject</a>
              |
              +---<a href="../KnowledgeInterfaces/interface_Relation_14366.htm">Relation</a>
                |
                +---Formula
 </pre>
<hr><br>
<b><i> Represents the formula relation.</i></b><br>

 The following example shows how to create a formula that computes the mass
 of a cuboid, given its geometric dimensions and the density of the material
 it is made of: 
 <pre>
	Dim CATDocs As Documents
 Set CATDocs = CATIA.Documents
 Dim part1 As Document
 Set part1   = CATDocs.Add("CATPart")
 Dim width As RealParam
 Set width        = part1.Part.Parameters.<font color="red">CreateReal</font>("width", 1.)  
 Dim height As RealParam
 Set height       = part1.Part.Parameters.<font color="red">CreateReal</font>("height", 2.)  
 Dim depth As RealParam
 Set depth        = part1.Part.Parameters.<font color="red">CreateReal</font>("depth", 3.)  
 Dim density As RealParam
 Set density      = part1.Part.Parameters.<font color="red">CreateReal</font>("density", 1.5)  
 Dim mass As RealParam
 Set mass         = part1.Part.Parameters.<font color="red">CreateReal</font>("mass", 0.)  
 Dim computemass As RealParam
 Set computemass = part1.Part.Relations.<font color="red">CreateFormula</font>
                    ("computemass",
                     "Computes the cuboid mass",  mass,
                     "(width*height*depth)*density")
  </pre><hr>
<dl>
</dl>
<dl>
</dl>

</body>
<hr><p><i>
Copyright &#169; 2003, Dassault Syst&#232;mes. All rights reserved.</i></p>
</html>
