<!DOCTYPE html 
     PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
     "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
<meta http-equiv="Content-Language" content="en-us" />
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<meta name="devlang" content="idl" />
<link rel="stylesheet" type="text/css" href="../CAADocStyleSheets/caav5.css"/>
<script type="text/javascript" src="../CAADocJavaScript/DSDocTocToc.js">/* */</script>
<script type="text/javascript" src="../CAADocJavaScript/DSDocHighlight.js">/* */</script>
<script type="text/javascript" src="../CAADocJavaScript/submit.js">/* */</script>
<title>CAAScdSfdUcCreateMember.CATScript</title></head>

<body onload="highlightSearchTerms();">

<pre>
<span class="comment">'-------------- Sample MACRO written in Basic Script ------------------------------------------ </span>
<span class="comment">'This sample creates members(beams) of 6 types.</span>
<span class="comment">'This script requires sfd model</span>
<span class="comment">'</span>
<span class="comment">''Steps</span>
<span class="comment">'   1- Searches and opens model which is named as &quot;SFD_VB_TEST&quot;</span>
<span class="comment">'   2- Retrieves Part object </span>
<span class="comment">'   3- Retrieves Service manager (RfgService)</span>
<span class="comment">'   4- Creates a Geometrical Set in Part for creating Members in it</span>
<span class="comment">'   5- Creates a member using two surfaces</span>
<span class="comment">'   6- Creates a member using a point and a limit</span>
<span class="comment">'   7- Creates a member using a pt and length</span>
<span class="comment">'   8- Creates a member using using a curve</span>
<span class="comment">'   9- Creates a member using two surfaces and two members(crvs)</span>
<span class="comment">'  10- Creates a member using two points</span>
<span class="comment">'  11- Updates the Part object</span>
<span class="comment">'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
Language=&quot;VBSCRIPT&quot; 
<span class="keyword">Dim </span>Manager<span class="keyword"> As </span>RfgService
<span class="keyword">Dim </span>ObjPart<span class="keyword"> As </span>Part

<span class="keyword">Sub </span>CATMain()
    
<span class="comment">'   1- Searches and opens model which is named as &quot;SFD_VB_TEST&quot;</span>
<span class="keyword">    Dim </span>SFDPrdEditor<span class="keyword"> As </span>Editor
<span class="keyword">    Dim </span>prdName<span class="keyword"> As </span>String
    prdName = &quot;SFD_VB_TEST&quot;
    OpenProduct prdName , SFDPrdEditor
    
<span class="comment">'   2- Retrieves Part object </span>
<span class="keyword">    Set </span>ObjPart = SFDPrdEditor.ActiveObject

<span class="comment">'   3- Retrieves Service manager (RfgService)</span>
<span class="keyword">    Set </span>Manager = CATIA.ActiveEditor.GetService(&quot;RfgService&quot;)

<span class="comment">'   4- Creates a Geometrical Set in Part for creating Members in it</span>
<span class="keyword">    Set </span>oHybridBodies = ObjPart.HybridBodies
<span class="keyword">    Set </span>oGeometricalSet = oHybridBodies.Add()
<span class="keyword">    Set </span>RefGeometricalSet = ObjPart.CreateReferenceFromObject(oGeometricalSet)
    
<span class="comment">'   5- Creates a member using two surfaces</span>
<span class="keyword">    Dim </span>ObjMemberSurfSurf<span class="keyword"> As </span>SfdMember
    CreateMemberSurfSurf RefGeometricalSet, ObjMemberSurfSurf
    
<span class="comment">'   6- Creates a member using a point and a limit</span>
<span class="keyword">    Dim </span>ObjMemberPtLimit<span class="keyword"> As </span>SfdMember
    CreateMemberPtLimit RefGeometricalSet, ObjMemberPtLimit
    
<span class="comment">'   7- Creates a member using a point and length</span>
<span class="keyword">    Dim </span>ObjMemberPtLength<span class="keyword"> As </span>SfdMember
    CreateMemberPtLength RefGeometricalSet, ObjMemberPtLength
    
<span class="comment">'   8- Creates a member using using a curve</span>
<span class="keyword">    Dim </span>ObjMemberCrv<span class="keyword"> As </span>SfdMember
    CreateMemberCrv RefGeometricalSet, ObjMemberCrv
    
<span class="comment">'   9- Creates a member using a surface and two members(curves)</span>
<span class="keyword">    Dim </span>ObjMemberSurf2Crv<span class="keyword"> As </span>SfdMember
    CreateMemberSurf2Crvs RefGeometricalSet, ObjMemberPtLimit, ObjMemberPtLength, ObjMemberSurf2Crv
    
<span class="comment">'   10- Creates a member using two points</span>
<span class="keyword">    Dim </span>ObjMemberPtPt<span class="keyword"> As </span>SfdMember
    CreateMemberPtPt RefGeometricalSet, ObjMemberPtPt
    
<span class="comment">'   11- Updates the Part object</span>
    ObjPart.Update
    
<span class="keyword">End Sub</span>

<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="comment">'Create member using two surfaces</span>
<span class="comment">'</span>
<span class="comment">''Steps</span>
<span class="comment">'   5.1- Creates a empty member and sets category, material, profile type and section parameters</span>
<span class="comment">'   5.2- Retrieves StrProfileLimitMngt and sets profile limits</span>
<span class="comment">'   5.3- Retrieves StrProfileSurfSurf and sets surfaces for member creation</span>
<span class="comment">'   5.4- Updates created member object</span>
<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="keyword">Sub </span>CreateMemberSurfSurf(iRefGeometricalSet<span class="keyword"> As </span>Reference, oObjMember<span class="keyword"> As </span>SfdMember)
    
<span class="comment">'   5.1- Creates a empty member and sets category, material, profile type and section parameters</span>
    CreateMemberAndSetData iRefGeometricalSet, &quot;SldMember&quot;, catStrProfileModeSurfSurf, &quot;Steel A42&quot;, &quot;WT18x179.5&quot;, &quot;catStrTopCenter&quot;, oObjMember

<span class="comment">'   5.2- Retrieves StrProfileLimitMngt and sets profile limits</span>
<span class="keyword">    Dim </span>ObjStrProfileLimitMngt<span class="keyword"> As </span>StrProfileLimitMngt
<span class="keyword">    Set </span>ObjStrProfileLimitMngt = oObjMember.StrProfileLimitMngt
    <span class="comment">'set the limits</span>
<span class="keyword">    Set </span>ObjStartLimit = Manager.GetReferencePlane(ObjPart, 1, &quot;DECK.8&quot;)
<span class="keyword">    Set </span>StartLimit = ObjPart.CreateReferenceFromObject(ObjStartLimit)
    ObjStrProfileLimitMngt.SetLimitingObject 1, StartLimit
<span class="keyword">    Set </span>ObjEndLimit = Manager.GetReferencePlane(ObjPart, 1, &quot;DECK.3&quot;)
<span class="keyword">    Set </span>EndLimit = ObjPart.CreateReferenceFromObject(ObjEndLimit)
    ObjStrProfileLimitMngt.SetLimitingObject 2, EndLimit

<span class="comment">'   5.3- Retrieves StrProfileSurfSurf and sets surfaces for member creation</span>
    <span class="comment">'Get StrProfileSurfSurf object</span>
<span class="keyword">    Dim </span>ObjStrProfileSurfSurf<span class="keyword"> As </span>StrProfileSurfSurf
<span class="keyword">    Set </span>ObjStrProfileSurfSurf = oObjMember.StrProfileSurfSurf
    <span class="comment">'Set FirstSurface </span>
<span class="keyword">    Set </span>ObjRefFirstSurf = Manager.GetReferencePlane(ObjPart, 2, &quot;CROSS.8&quot;)
<span class="keyword">    Set </span>RefFirstSurf = ObjPart.CreateReferenceFromObject(ObjRefFirstSurf)
    ObjStrProfileSurfSurf.FirstSurface = RefFirstSurf
    <span class="comment">'Set SecondSurface</span>
<span class="keyword">    Set </span>ObjRefSecondSurf = Manager.GetReferencePlane(ObjPart, 3, &quot;LONG.-4&quot;)
<span class="keyword">    Set </span>RefSecondSurf = ObjPart.CreateReferenceFromObject(ObjRefSecondSurf)
    ObjStrProfileSurfSurf.SecondSurface = RefSecondSurf
   
<span class="comment">'   5.4- Updates created member object</span>
    ObjPart.UpdateObject oObjMember
    
<span class="keyword">End Sub</span>

<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="comment">'Create member using a pt and a limit</span>
<span class="comment">'</span>
<span class="comment">''Steps</span>
<span class="comment">'   6.1- Creates a empty member and sets category, material, profile type and section parameters</span>
<span class="comment">'   6.2- Creates a point. Later this point will be used for member creation</span>
<span class="comment">'   6.3- Retrieves StrProfilePtLimit and sets point and limit and direction</span>
<span class="comment">'   6.4- Updates created member object</span>
<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="keyword">Sub </span>CreateMemberPtLimit(iRefGeometricalSet<span class="keyword"> As </span>Reference, oObjMember<span class="keyword"> As </span>SfdMember)
    
<span class="comment">'   6.1- Creates a empty member and sets category, material, profile type and section parameters</span>
    CreateMemberAndSetData iRefGeometricalSet, &quot;SldMember&quot;, catStrProfileModePtLimit, &quot;Steel A42&quot;, &quot;WT18x179.5&quot;, &quot;catStrTopCenter&quot;, oObjMember

<span class="comment">'   6.2- Creates a point. Later this point will be used for member creation</span>
<span class="keyword">    Set </span>ObjHybridShapeFactory = ObjPart.HybridShapeFactory
<span class="keyword">    Set </span>ObjHybridShapePointCoord = ObjHybridShapeFactory.AddNewPointCoord(5000, 5000, 0)
<span class="keyword">    Set </span>RefPoint = ObjPart.CreateReferenceFromObject(ObjHybridShapePointCoord)
    
<span class="comment">'   6.3- Retrieves StrProfilePtLimit and sets point and limit and direction</span>
    <span class="comment">'Get StrProfilePtLimit object</span>
<span class="keyword">    Dim </span>ObjStrProfilePtLimit<span class="keyword"> As </span>StrProfilePtLimit
<span class="keyword">    Set </span>ObjStrProfilePtLimit = oObjMember.StrProfilePtLimit
    <span class="comment">'set point</span>
    ObjStrProfilePtLimit.StartPoint = RefPoint
    <span class="comment">'set limit</span>
<span class="keyword">    Set </span>ObjMemberLimitRef = Manager.GetReferencePlane(ObjPart, 1, &quot;DECK.4&quot;)
<span class="keyword">    Set </span>MemberLimitRef = ObjPart.CreateReferenceFromObject(ObjMemberLimitRef)
    ObjStrProfilePtLimit.UpToLimit = MemberLimitRef
    <span class="comment">'set direction</span>
    ObjStrProfilePtLimit.Direction = MemberLimitRef
    
<span class="comment">'   6.4- Updates created member object</span>
    ObjPart.UpdateObject oObjMember
    
<span class="keyword">End Sub</span>

<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="comment">'Create member using a pt and length</span>
<span class="comment">'</span>
<span class="comment">''Steps</span>
<span class="comment">'   7.1- Creates a empty member and sets category, material, profile type and section parameters</span>
<span class="comment">'   7.2- Creates a point. Later this point will be used for member creation</span>
<span class="comment">'   7.3- Retrieves StrProfilePtLength and sets point and direction and length</span>
<span class="comment">'   7.4- Updates created member object</span>
<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="keyword">Sub </span>CreateMemberPtLength(iRefGeometricalSet<span class="keyword"> As </span>Reference, oObjMember<span class="keyword"> As </span>SfdMember)

<span class="comment">'   7.1- Creates a empty member and sets category, material, profile type and section parameters</span>
    CreateMemberAndSetData iRefGeometricalSet, &quot;SldMember&quot;, catStrProfileModePtLength, &quot;Steel A42&quot;, &quot;WT18x179.5&quot;, &quot;catStrTopCenter&quot;, oObjMember

<span class="comment">'   7.2- Creates a point. Later this point will be used for member creation</span>
<span class="keyword">    Set </span>ObjHybridShapeFactory = ObjPart.HybridShapeFactory
<span class="keyword">    Set </span>ObjHybridShapePointCoord = ObjHybridShapeFactory.AddNewPointCoord(20000, 20000, 0)
<span class="keyword">    Set </span>RefPoint = ObjPart.CreateReferenceFromObject(ObjHybridShapePointCoord)
    
<span class="comment">'   7.3- Retrieves StrProfilePtLength and sets point and direction and length</span>
    <span class="comment">'Get StrProfilePtLength object</span>
<span class="keyword">    Dim </span>ObjStrProfilePtLength<span class="keyword"> As </span>StrProfilePtLength
<span class="keyword">    Set </span>ObjStrProfilePtLength = oObjMember.StrProfilePtLength
    <span class="comment">'set point</span>
    ObjStrProfilePtLength.StartPoint = RefPoint
    <span class="comment">'set direction</span>
<span class="keyword">    Set </span>ObjRefMemberDirection = Manager.GetReferencePlane(ObjPart, 1, &quot;DECK.7&quot;)
<span class="keyword">    Set </span>RefMemberDirection = ObjPart.CreateReferenceFromObject(ObjRefMemberDirection)
    ObjStrProfilePtLength.Direction = RefMemberDirection
    <span class="comment">'set length</span>
<span class="keyword">    Set </span>LengthParm = ObjStrProfilePtLength.GetLength
    LengthParm.ValuateFromString (&quot;20000mm&quot;)
    
<span class="comment">'   7.4- Updates created member object</span>
    ObjPart.UpdateObject oObjMember
    
<span class="keyword">End Sub</span>

<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="comment">'Create member using a curve</span>
<span class="comment">'</span>
<span class="comment">''Steps</span>
<span class="comment">'   8.1- Creates a empty member and sets category, material, profile type and section parameters</span>
<span class="comment">'   8.2- Creates two points and a line between them. Later this line will be used for member creation</span>
<span class="comment">'   8.3- Retrieves StrProfileCrv and sets Curve</span>
<span class="comment">'   8.4- Updates created member object</span>
<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="keyword">Sub </span>CreateMemberCrv(iRefGeometricalSet<span class="keyword"> As </span>Reference, oObjMember<span class="keyword"> As </span>SfdMember)

<span class="comment">'   8.1- Creates a empty member and sets category, material, profile type and section parameters</span>
    CreateMemberAndSetData iRefGeometricalSet, &quot;SldMember&quot;, catStrProfileModeCrv, &quot;Steel A42&quot;, &quot;WT18x179.5&quot;, &quot;catStrTopCenter&quot;, oObjMember

<span class="comment">'   8.2- Creates two points and a line between them. Later this line will be used for member creation</span>
    <span class="comment">'Get HybridShapeFactory</span>
<span class="keyword">    Set </span>ObjHybridShapeFactory = ObjPart.HybridShapeFactory
    <span class="comment">'Create a point </span>
<span class="keyword">    Set </span>ObjHybridShapePointCoord = ObjHybridShapeFactory.AddNewPointCoord(5000, 5000, 0)
<span class="keyword">    Set </span>RefPoint1 = ObjPart.CreateReferenceFromObject(ObjHybridShapePointCoord)
    <span class="comment">'Create one more point</span>
<span class="keyword">    Set </span>ObjHybridShapePointCoord = ObjHybridShapeFactory.AddNewPointCoord(20000, 20000, 0)
<span class="keyword">    Set </span>RefPoint2 = ObjPart.CreateReferenceFromObject(ObjHybridShapePointCoord)
    <span class="comment">'create line between two points</span>
<span class="keyword">    Set </span>ObjHybridShapeLinePtPt = ObjHybridShapeFactory.AddNewLinePtPt(RefPoint2, RefPoint1)
<span class="keyword">    Set </span>RefLine = ObjPart.CreateReferenceFromObject(ObjHybridShapeLinePtPt)
    
<span class="comment">'   8.3- Retrieves StrProfileCrv and sets Curve</span>
    <span class="comment">'Get StrProfileCrv object</span>
<span class="keyword">    Dim </span>ObjStrProfileCrv<span class="keyword"> As </span>StrProfileCrv
<span class="keyword">    Set </span>ObjStrProfileCrv = oObjMember.StrProfileCrv
    <span class="comment">'set the curve</span>
    ObjStrProfileCrv.Curve = RefLine
    
<span class="comment">'   8.4- Updates created member object</span>
    ObjPart.UpdateObject oObjMember
    
<span class="keyword">End Sub</span>

<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="comment">'Creates member using a surface and two members(crvs)</span>
<span class="comment">'</span>
<span class="comment">''Steps</span>
<span class="comment">'   9.1- Creates a empty member and sets category, material, profile type and section parameters</span>
<span class="comment">'   9.2- Retrieves StrProfileSurf2Crvs and sets a surface and two curves for member creation</span>
<span class="comment">'   9.3- Updates created member object</span>
<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="keyword">Sub </span>CreateMemberSurf2Crvs(iRefGeometricalSet<span class="keyword"> As </span>Reference, iFirstMember<span class="keyword"> As </span>SfdMember, iSecondMember<span class="keyword"> As </span>SfdMember, oObjMember<span class="keyword"> As </span>SfdMember)

<span class="comment">'   9.1- Creates a empty member and sets category, material, profile type and section parameters</span>
    CreateMemberAndSetData iRefGeometricalSet, &quot;SldMember&quot;, catStrProfileModeSurf2Crvs, &quot;Steel A42&quot;, &quot;WT18x179.5&quot;, &quot;catStrTopCenter&quot;, oObjMember

<span class="comment">'   9.2- Retrieves StrProfileSurf2Crvs and sets a surface and two curves for member creation</span>
    <span class="comment">'Get StrProfileSurf2Crvs object</span>
<span class="keyword">    Dim </span>ObjStrProfileSurf2Crvs<span class="keyword"> As </span>StrProfileSurf2Crvs
<span class="keyword">    Set </span>ObjStrProfileSurf2Crvs = oObjMember.StrProfileSurf2Crvs
    <span class="comment">'Set Surface</span>
<span class="keyword">    Set </span>ObjRefSurface = Manager.GetReferencePlane(ObjPart, 1, &quot;DECK.3&quot;)
<span class="keyword">    Set </span>RefSurface = ObjPart.CreateReferenceFromObject(ObjRefSurface)
    ObjStrProfileSurf2Crvs.Surface = RefSurface
    <span class="comment">'Set FirstCurve</span>
<span class="keyword">    Set </span>RefFirstCrv = iFirstMember.GetDelimitedSupport
    ObjStrProfileSurf2Crvs.FirstCurve = RefFirstCrv
    <span class="comment">'Set SecondCurve</span>
<span class="keyword">    Set </span>RefSecondCrv = iSecondMember.GetDelimitedSupport
    ObjStrProfileSurf2Crvs.SecondCurve = RefSecondCrv
   
<span class="comment">'   9.3- Updates created member object</span>
    ObjPart.UpdateObject oObjMember
    
<span class="keyword">End Sub</span>

<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="comment">'Create member using two points</span>
<span class="comment">'</span>
<span class="comment">''Steps</span>
<span class="comment">'   10.1- Creates a empty member and sets category, material, profile type and section parameters</span>
<span class="comment">'   10.2- Creates two points and references to these points. Later these points are used for member creation</span>
<span class="comment">'   10.3- Retrieves StrProfilePtPt object and sets StartPoint and EndPoint</span>
<span class="comment">'   10.4- Updates created member object</span>
<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="keyword">Sub </span>CreateMemberPtPt(iRefGeometricalSet<span class="keyword"> As </span>Reference, oObjMember<span class="keyword"> As </span>SfdMember)
    
<span class="comment">'   10.1- Creates a empty member and sets category, material, profile type and section parameters</span>
    CreateMemberAndSetData iRefGeometricalSet, &quot;SldMember&quot;, catStrProfileModePts, &quot;Steel A42&quot;, &quot;WT18x179.5&quot;, &quot;catStrTopCenter&quot;, oObjMember

<span class="comment">'   10.2- Creates two points and references to these points. Later these points are used for member creation</span>
    <span class="comment">'Create Start point</span>
<span class="keyword">    Set </span>ObjHybridShapeFactory = ObjPart.HybridShapeFactory
<span class="keyword">    Set </span>StartPoint = ObjHybridShapeFactory.AddNewPointCoord(25000, 25000, 0)
<span class="keyword">    Set </span>RefStartPoint = ObjPart.CreateReferenceFromObject(StartPoint)
    <span class="comment">'Create End point</span>
<span class="keyword">    Set </span>ObjHybridShapeFactory = ObjPart.HybridShapeFactory
<span class="keyword">    Set </span>EndPoint = ObjHybridShapeFactory.AddNewPointCoord(25000, 25000, 20000)
<span class="keyword">    Set </span>RefEndPoint = ObjPart.CreateReferenceFromObject(EndPoint)

<span class="comment">'   10.3- Retrieves StrProfilePtPt object and sets StartPoint and EndPoint</span>
    <span class="comment">'Get StrProfilePtPt object</span>
<span class="keyword">    Dim </span>ObjStrProfilePtPt<span class="keyword"> As </span>StrProfilePtPt
<span class="keyword">    Set </span>ObjStrProfilePtPt = oObjMember.StrProfilePtPt
    <span class="comment">'Set StartPoint</span>
    ObjStrProfilePtPt.StartPoint = RefStartPoint
    <span class="comment">'Set EndPoint</span>
    ObjStrProfilePtPt.EndPoint = RefEndPoint
   
<span class="comment">'   10.4- Updates created member object</span>
    ObjPart.UpdateObject oObjMember

<span class="keyword">End Sub</span>

<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="comment">'Creates a empty member and sets category, material, profile type and section parameters</span>
<span class="comment">'</span>
<span class="comment">''Steps</span>
<span class="comment">'   1- Retrieves SfdFactory object and creates a empty member</span>
<span class="comment">'   2- Retrieves StrCategoryMngt object and sets category</span>
<span class="comment">'   3- Sets profile type</span>
<span class="comment">'   4- Retrieves StrMaterialMngt object and sets material</span>
<span class="comment">'   5- Retrieves StrSectionMngt object and sets section parameters</span>
<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="keyword">Sub </span>CreateMemberAndSetData(iRefGeometricalSet<span class="keyword"> As </span>Reference, iCategory<span class="keyword"> As </span>String, iProfileType<span class="keyword"> As </span>CATStrProfileMode, iMaterial<span class="keyword"> As </span>String, iSectionName<span class="keyword"> As </span>String, iAnchorPoint<span class="keyword"> As </span>String, oObjMember<span class="keyword"> As </span>SfdMember)
<span class="comment">'   1- Retrieves SfdFactory object and creates a empty member</span>
<span class="keyword">    Dim </span>ObjSfdFactory<span class="keyword"> As </span>SfdFactory
<span class="keyword">    Set </span>ObjSfdFactory = ObjPart.GetCustomerFactory(&quot;SfdFactory&quot;)
<span class="keyword">    Set </span>oObjMember = ObjSfdFactory.AddMember(iRefGeometricalSet)

<span class="comment">'   2- Retrieves StrCategoryMngt object and sets category</span>
<span class="keyword">    Dim </span>ObjStrCategoryMngt<span class="keyword"> As </span>StrCategoryMngt
<span class="keyword">    Set </span>ObjStrCategoryMngt = oObjMember.StrCategoryMngt
    ObjStrCategoryMngt.SetCategory iCategory

<span class="comment">'   3- Sets profile type</span>
    oObjMember.ProfileType = iProfileType

<span class="comment">'   4- Retrieves StrMaterialMngt object and sets material</span>
<span class="keyword">    Dim </span>ObjMaterialMngt<span class="keyword"> As </span>StrMaterialMngt
<span class="keyword">    Set </span>ObjMaterialMngt = oObjMember.StrMaterialMngt
    ObjMaterialMngt.SetMaterial iMaterial

<span class="comment">'   5- Retrieves StrSectionMngt object and sets section parameters</span>
<span class="keyword">    Dim </span>ObjStrSectionMngt<span class="keyword"> As </span>StrSectionMngt
<span class="keyword">    Set </span>ObjStrSectionMngt = oObjMember.StrSectionMngt
    ObjStrSectionMngt.SetSectionName iSectionName
    ObjStrSectionMngt.AnchorPoint = iAnchorPoint
<span class="keyword">End Sub</span>

<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="comment">'Searches a product and open it.</span>
<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="keyword">Sub </span><strong>OpenProduct</strong>(byVal prdName as String, SFDPrdEditor<span class="keyword"> As </span>Editor)

    <span class="comment">'Get the Search Service.</span>
    <span class="keyword">Set </span>oSearchService = CATIA.GetSessionService(&quot;Search&quot;)
    <span class="keyword">Dim</span> oDBSearch <span class="keyword">As</span> DatabaseSearch 
    <span class="keyword">Set</span> oDBSearch = oSearchService.DatabaseSearch
    oDBSearch.BaseType = &quot;VPMReference&quot;
    <span class="comment">' To retrieve the product by its Title, use V_Name attribute</span>
    <span class="comment">' To retrieve the product by its Name, use PLM_ExternalID attribute</span>
    oDBSearch.AddEasyCriteria &quot;V_Name&quot;, prdName
    oSearchService.Search
    <span class="comment">'Retrieve the first entity.</span>
    <span class="keyword">Dim</span> oEntity <span class="keyword">As</span> PLMEntity 
    <span class="keyword">Set</span> oEntity = oDBSearch.Results.Item(1)
    <span class="comment">'Get the PLMOpen service &amp; Open the first retrieved entity.</span>
    <span class="keyword">Dim</span> oPLMOpenService <span class="keyword">As</span> PLMOpenService
    <span class="keyword">Set </span>oPLMOpenService = CATIA.GetSessionService(&quot;PLMOpenService&quot;)
    <span class="comment">'Get the editor.</span>
    oPLMOpenService.PLMOpen oEntity , SFDPrdEditor
    
<span class="keyword">End Sub</span>
</pre>
<script type="text/javascript">insertCopyright();</script>

</body>

</html>
