<!DOCTYPE html 
     PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
     "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">

<head>
<meta http-equiv="Content-Language" content="en-us" />
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<meta name="devlang" content="idl" />
<link rel="stylesheet" type="text/css" href="../CAADocStyleSheets/caav5.css"/>
<script type="text/javascript" src="../CAADocJavaScript/DSDocTocToc.js">/* */</script>
<script type="text/javascript" src="../CAADocJavaScript/DSDocHighlight.js">/* */</script>
<script type="text/javascript" src="../CAADocJavaScript/submit.js">/* */</script>
<title>CAAScdSfdUcCreateOpeningOnProfile3DObject.CATScript</title></head>

<body onload="highlightSearchTerms();">

<pre><span class="comment">'-------------- Sample MACRO written in Basic Script ------------------------------------------ </span>
<span class="comment">'This sample creates a opening using 3d object and removes it.</span>
<span class="comment">'This script requires sfd model which contains a stiffener on panel with an extruded sketch intersecting it</span>
<span class="comment">'</span>
<span class="comment">''Steps</span>
<span class="comment">'   1- Searches and opens model which is named as &quot;SFD_CreateOpeningOnProfile&quot;</span>
<span class="comment">'   2- Retrieves Selection object </span>
<span class="comment">'   3- Retrieves Part object </span>
<span class="comment">'   4- Retrieves a SFD stiffener object</span>
<span class="comment">'   5- Get 3D object for creating opening on profile</span>
<span class="comment">'   6- Creates opening on profile</span>
<span class="comment">'   7- Removes opening on profile</span>
<span class="comment">'   8- Updates the Part object</span>
<span class="comment">'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
Language=&quot;VBSCRIPT&quot; 
<span class="keyword">Dim </span>ObjPart<span class="keyword"> As </span>Part

<span class="keyword">Sub </span>CATMain()
    
<span class="comment">'   1- Searches and opens model which is named as &quot;SFD_CreateOpeningOnProfile&quot;</span>
<span class="keyword">    Dim </span>SFDPrdEditor<span class="keyword"> As </span>Editor
<span class="keyword">    Dim </span>prdName<span class="keyword"> As </span>String
    prdName = &quot;SFD_CreateOpeningOnProfile&quot;
    OpenProduct prdName , SFDPrdEditor

<span class="comment">'   2- Retrieves Selection object </span>
<span class="keyword">    Set </span>SFDProdSel = SFDPrdEditor.Selection
    
<span class="comment">'   3- Retrieves Part object </span>
<span class="keyword">    Set </span>ObjPart = SFDPrdEditor.ActiveObject

<span class="comment">'   4- Retrieves a SFD stiffener object</span>
<span class="keyword">    Set </span>RefObjSfdStiffener = ObjPart.FindObjectByName(&quot;Stiffener.1&quot;)
<span class="keyword">    Dim </span>ObjSfdStiffener<span class="keyword"> As </span>StrSfdStiffener
    SFDProdSel.Add RefObjSfdStiffener
<span class="keyword">    Set </span>ObjSfdStiffener = SFDProdSel.FindObject(&quot;CATIASfdStiffener&quot;)

<span class="comment">'   5- Get 3D object for creating opening on profile</span>
<span class="keyword">    Set</span> Obj3DOpeningOnProfileDimensions = ObjPart.FindObjectByName(&quot;Extrude.1&quot;)
<span class="keyword">    Dim</span> Ref3DObjectOpeningOnProfileDimensions <span class="keyword">As</span> Reference
<span class="keyword">    Set</span> Ref3DObjectOpeningOnProfileDimensions = ObjPart.CreateReferenceFromObject(Obj3DOpeningOnProfileDimensions)

<span class="comment">'   6- Creates opening on profile</span>
<span class="keyword">    Dim </span>ObjStrOpeningOnProfile<span class="keyword"> As </span>StrOpeningOnProfile
    CreateOpening3DObject ObjSfdStiffener, Ref3DObjectOpeningOnProfileDimensions, ObjStrOpeningOnProfile
    
<span class="comment">'   7- Removes opening on profile</span>
<span class="keyword">    Dim </span>ObjStrOpeningsOnProfile<span class="keyword"> As </span>StrOpeningsOnProfile
<span class="keyword">    Set </span>ObjStrOpeningsOnProfile = ObjSfdStiffener.GetOpeningsOnProfile(0)
    ObjStrOpeningsOnProfile.Remove ObjStrOpeningOnProfile
    
<span class="comment">'   8- Updates the Part object</span>
    ObjPart.Update
    
<span class="keyword">End Sub</span>

<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="comment">'Create Opening On Profile</span>
<span class="comment">'</span>
<span class="comment">''Steps</span>
<span class="comment">'   6.1- Add Opening On Profile</span>
<span class="comment">'   6.2- Get StrOpening from StrOpeningOnProfile</span>
<span class="comment">'   6.3- Set Opening Type for 3D Object</span>
<span class="comment">'   6.4- Set Category</span>
<span class="comment">'   6.5- sets intersecting element for opening creation</span>
<span class="comment">'   6.6- Sets forming mode and extrusion mode</span>
<span class="comment">'   6.7- Updates created opening on profile object.</span>
<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="keyword">Sub</span> CreateOpening3DObject(iObjSfdStiffener <span class="keyword">As</span> StrSfdStiffener, Ref3DObject <span class="keyword">As</span> Reference, oObjStrOpeningOnProfile <span class="keyword">As</span> StrOpeningOnProfile)
    
 <span class="comment">   'Add Opening On Profile</span>
    AddOpening iObjSfdStiffener, oObjStrOpeningOnProfile
	
<span class="comment">    'Get StrOpening from StrOpeningOnProfile</span>
<span class="keyword">    Dim</span> ObjStrOpening <span class="keyword">As</span> StrOpening
<span class="keyword">    Set</span> ObjStrOpening = oObjStrOpeningOnProfile.StrOpening
    
<span class="comment">    'Set opening type catStrOpeningMode3DObject for 3dobject opening</span>
    ObjStrOpening.OpeningType = catStrOpeningMode3DObject
    
<span class="comment">    'Set category</span>
<span class="keyword">    Dim</span> ObjStrCategoryMngt <span class="keyword">As</span> StrCategoryMngt
<span class="keyword">    Set</span> ObjStrCategoryMngt = ObjStrOpening.StrCategoryMngt
    ObjStrCategoryMngt.SetCategory &quot;SldOpening&quot;

 <span class="comment">   'Set intersecting element for opening creation</span>
 <span class="keyword">   Dim</span> ObjStrOpening3DObject <span class="keyword">As</span> StrOpening3DObject
 <span class="keyword">   Set</span> ObjStrOpening3DObject = ObjStrOpening.StrOpening3DObject
    ObjStrOpening3DObject.IntersectingElement = Ref3DObject
    
<span class="comment">    'Set forming mode</span>
<span class="keyword">    Set</span> ObjStrOpeningExtrusionMngt = ObjStrOpening.StrOpeningExtrusionMngt
    ObjStrOpeningExtrusionMngt.ExtrusionMode = 0
    'ObjStrOpening.FormingMode = 0
    
<span class="comment">    'Update the created opening</span>
    ObjPart.UpdateObject oObjStrOpeningOnProfile
    ObjPart.UpdateObject iObjSfdStiffener
    
<span class="style2">End Sub</span>
<span class="style1">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
'Adds a new opening
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="style2">Sub</span> <strong>AddOpening</strong>(iObjSfdStiffener As StrSfdStiffener, oObjSfdOpeningOnProfile As StrOpeningOnProfile)
    <span class="style2"> Dim</span> ObjStrOpeningsOnProfile As StrOpeningsOnProfile
    <span class="style2"> Set</span> ObjStrOpeningsOnProfile = iObjSfdStiffener.GetOpeningsOnProfile(0)
    <span class="style1"> 'Add opening</span>
     <span class="style2">Set</span> oObjSfdOpeningOnProfile = ObjStrOpeningsOnProfile.Add
<span class="style2">End Sub</span>
<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="comment">'Searches a product and open it.</span>
<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="keyword">Sub </span><strong>OpenProduct</strong>(byVal prdName as String, SFDPrdEditor<span class="keyword"> As </span>Editor)

    <span class="comment">'Get the Search Service.</span>
    <span class="keyword">Set </span>oSearchService = CATIA.GetSessionService(&quot;Search&quot;)
    <span class="keyword">Dim</span> oDBSearch <span class="keyword">As</span> DatabaseSearch 
    <span class="keyword">Set</span> oDBSearch = oSearchService.DatabaseSearch
    oDBSearch.BaseType = &quot;VPMReference&quot;
    <span class="comment">' To retrieve the product by its Title, use V_Name attribute</span>
    <span class="comment">' To retrieve the product by its Name, use PLM_ExternalID attribute</span>
    oDBSearch.AddEasyCriteria &quot;V_Name&quot;, prdName
    oSearchService.Search
    <span class="comment">'Retrieve the first entity.</span>
    <span class="keyword">Dim</span> oEntity <span class="keyword">As</span> PLMEntity 
    <span class="keyword">Set</span> oEntity = oDBSearch.Results.Item(1)
    <span class="comment">'Get the PLMOpen service &amp; Open the first retrieved entity.</span>
    <span class="keyword">Dim</span> oPLMOpenService <span class="keyword">As</span> PLMOpenService
    <span class="keyword">Set </span>oPLMOpenService = CATIA.GetSessionService(&quot;PLMOpenService&quot;)
    <span class="comment">'Get the editor.</span>
    oPLMOpenService.PLMOpen oEntity , SFDPrdEditor
    
<span class="keyword">End Sub</span>
</pre>

</body>

</html>
