<!DOCTYPE html 
     PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
     "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
<meta http-equiv="Content-Language" content="en-us" />
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<meta name="devlang" content="idl" />
<link rel="stylesheet" type="text/css" href="../CAADocStyleSheets/caav5.css"/>
<script type="text/javascript" src="../CAADocJavaScript/DSDocTocToc.js">/* */</script>
<script type="text/javascript" src="../CAADocJavaScript/DSDocHighlight.js">/* */</script>
<script type="text/javascript" src="../CAADocJavaScript/submit.js">/* */</script>
<title>CAAScdSfdUcCreateEndcut.CATScript</title></head>

<body onload="highlightSearchTerms();">

<pre>
<span class="comment">'-------------- Sample MACRO written in Basic Script ------------------------------------------ </span>
<span class="comment">'This sample creates an Endcut and edit it.</span>
<span class="comment">'This script requires sfd model which contains a panel and stiffener on it</span>
<span class="comment">'</span>
<span class="comment">''Steps</span>
<span class="comment">'   1- Searches and opens model which is named as &quot;SFD_VB_TEST&quot;</span>
<span class="comment">'   2- Retrieves Selection object </span>
<span class="comment">'   3- Retrieves Part object </span>
<span class="comment">'   4- Retrieves a SFD stiffener object</span>
<span class="comment">'   5- Creates Endcut.</span>
<span class="comment">'   6- Edits Endcut.</span>
<span class="comment">'   7- Retrieves StrEndcutMngt object and remove the Endcut created at the start of the profile</span>
<span class="comment">'   8- Updates the Part object.</span>
<span class="comment">'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
Language=&quot;VBSCRIPT&quot; 
<span class="keyword">Dim </span>ObjPart<span class="keyword"> As </span>Part
<span class="keyword">Dim </span>SFDProdSel<span class="keyword"> As </span>Selection

<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="keyword">Sub </span>CATMain()
<span class="comment">'   1- Searches and opens model which is named as &quot;SFD_VB_TEST&quot;</span>
<span class="keyword">    Dim </span>SFDPrdEditor<span class="keyword"> As </span>Editor
<span class="keyword">    Dim </span>prdName<span class="keyword"> As </span>String
    prdName = &quot;SFD_VB_TEST&quot;
    OpenProduct prdName , SFDPrdEditor

<span class="comment">'   2- Retrieves Selection object </span>
<span class="keyword">    Set </span>SFDProdSel = SFDPrdEditor.Selection

<span class="comment">'   3- Retrieves Part object </span>
<span class="keyword">    Set </span>ObjPart = SFDPrdEditor.ActiveObject

<span class="comment">'   4- Retrieves a SFD Stiffener object.</span>
<span class="keyword">    Set </span>RefObjSfdStiffener = ObjPart.FindObjectByName(&quot;Stiffener.1&quot;)
<span class="keyword">    Dim </span>ObjSfdStiffener<span class="keyword"> As </span>StrSfdStiffener
    SFDProdSel.Add (RefObjSfdStiffener)
<span class="keyword">    Set </span>ObjSfdStiffener = SFDProdSel.FindObject(&quot;CATIASfdStiffener&quot;)

<span class="comment">'   5- Creates Endcut.</span>
<span class="keyword">    Dim </span>ObjStrEndCut<span class="keyword"> As </span>StrEndCut
    CreateEndCut ObjSfdStiffener, ObjStrEndCut

<span class="comment">'   6- Edits Endcut.</span>
    EditEndcut ObjStrEndCut

<span class="comment">'   7- Retrieves StrEndcutMngt object and remove the Endcut created at the start of the profile</span>
    <span class="comment">'Get StrEndcutMngt object</span>
<span class="keyword">    Set </span>ObjStrEndcutMngt = ObjSfdStiffener.StrEndcutMngt
    <span class="comment">'Remove the Endcut</span>
    ObjStrEndcutMngt.RemoveEndcut (1)
    
<span class="comment">'   8- Updates the Part object.</span>
    ObjPart.Update
    
<span class="keyword">End Sub</span>


<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="comment">'Create Endcut</span>
<span class="comment">'</span>
<span class="comment">''Steps</span>
<span class="comment">'   5.1- Retrieves StrEndcutMngt object and create an Endcut with no data        </span>
<span class="comment">'   5.2- Sets Endcut parameters</span>
<span class="comment">'   5.3- Retrieves SfdConnectionSet object from SfdPart object and updates the ConnectionSet</span>
<span class="comment">'   5.4- Updates StrEndCut object</span>
<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="keyword">Sub </span>CreateEndCut(iObjSfdStiffener<span class="keyword"> As </span>StrSfdStiffener, oObjStrEndCut<span class="keyword"> As </span>StrEndCut)
    
<span class="comment">'   5.1- Retrieves StrEndcutMngt object and create an Endcut with no data        </span>
    <span class="comment">'Get StrEndcutMngt object</span>
<span class="keyword">    Dim </span>ObjStrEndcutMngt<span class="keyword"> As </span>StrEndcutMngt
<span class="keyword">    Set </span>ObjStrEndcutMngt = iObjSfdStiffener.StrEndcutMngt
    <span class="comment">'Create Endcut</span>
<span class="keyword">    Set </span>oObjStrEndCut = ObjStrEndcutMngt.AddEndCut(1)
    
<span class="comment">'   5.2- Sets Endcut parameters</span>
    SetEndCutParameters oObjStrEndCut, iObjSfdStiffener
    
<span class="comment">'   5.3- Retrieves SfdConnectionSet object from SfdPart object and updates the ConnectionSet</span>
    <span class="comment">'Get SfdPart object</span>
<span class="keyword">    Dim </span>ObjSfdPart<span class="keyword"> As </span>SfdPart
    SFDProdSel.Add (ObjPart)
<span class="keyword">    Set </span>ObjSfdPart = SFDProdSel.FindObject(&quot;CATIASfdPart&quot;)
    <span class="comment">'Get SfdConnectionSet</span>
<span class="keyword">    Dim </span>ObjSfdConnectionSet<span class="keyword"> As </span>SfdConnectionSet
<span class="keyword">    Set </span>ObjSfdConnectionSet = ObjSfdPart.GetConnectionsSet
    <span class="comment">'update connectionset</span>
    ObjSfdConnectionSet.UpdateConnectionsSet 0, 0, 0
   
<span class="comment">'   5.4- Updates StrEndCut object</span>
    ObjPart.UpdateObject oObjStrEndCut
    
<span class="keyword">End Sub</span>

<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="comment">'Set Endcut parameters</span>
<span class="comment">'</span>
<span class="comment">''Steps</span>
<span class="comment">'   5.2.1- Retrieves StrDetailFeature object </span>
<span class="comment">'   5.2.2- Sets Endcut type    </span>
<span class="comment">'   5.2.3- Sets Endcut name</span>
<span class="comment">'   5.2.4- Retrieves list of parameters of impacted object </span>
<span class="comment">'   5.2.5- Creates parameters and stores role of each parameter in an array</span>
<span class="comment">'   5.2.6- Sets parameters</span>
<span class="comment">'   5.2.7- Updates the ObjStrDetailFeature object</span>
<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="keyword">Sub </span>SetEndCutParameters(iObjStrEndCut<span class="keyword"> As </span>StrEndCut, iObjSfdStiffener<span class="keyword"> As </span>StrSfdStiffener)
<span class="comment">'   5.2.1- Retrieves StrDetailFeature object </span>
<span class="keyword">    Dim </span>ObjStrDetailFeature<span class="keyword"> As </span>StrDetailFeature
<span class="keyword">    Set </span>ObjStrDetailFeature = iObjStrEndCut.StrDetailFeature
    
<span class="comment">'   5.2.2- Sets Endcut type    </span>
    ObjStrDetailFeature.Type = &quot;SNIPE&quot;

<span class="comment">'   5.2.3- Sets Endcut name</span>
    ObjStrDetailFeature.FeatureName = &quot;WT_snipe_radius&quot;
    
<span class="comment">'   5.2.4- Retrieves list of parameters of impacted object </span>
<span class="keyword">    Set </span>ObjPartParameters = ObjPart.Parameters
    <span class="comment">'parameters will be aggregated under impacted </span>
    <span class="comment">'object(here impacted object is iObjSfdStiffener)</span>
<span class="keyword">    Set </span>HBParameters = ObjPartParameters.SubList(iObjSfdStiffener, True)
    
<span class="comment">'   5.2.5- Creates parameters and stores role of each parameter in an array</span>
<span class="keyword">    Set </span>R1 = HBParameters.CreateDimension(&quot;R1&quot;, &quot;LENGTH&quot;, &quot;50&quot;)
    <span class="comment">'Define parameter roles in an array</span>
<span class="keyword">    Dim </span>ParamRoles(0)<span class="keyword"> As </span>Variant
    ParamRoles(0) = &quot;R1&quot;
    
<span class="comment">'   5.2.6- Sets parameters</span>
    ObjStrDetailFeature.SetParameters HBParameters, ParamRoles
    
<span class="comment">'   5.2.7- Updates the ObjStrDetailFeature object</span>
    ObjStrDetailFeature.Update

<span class="keyword">End Sub</span>

<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="comment">'Edit Endcut </span>
<span class="comment">'</span>
<span class="comment">''Steps</span>
<span class="comment">'   7.1- Retrieves StrDetailFeature object using created Endcut</span>
<span class="comment">'   7.2- Changes the Endcut Type and Name</span>
<span class="comment">'   7.3- Updates the connection coordinate and visualiztion for Endcut</span>
<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="keyword">Sub </span>EditEndcut(iObjStrEndCut<span class="keyword"> As </span>StrEndCut)
<span class="comment">'   7.1- Retrieves StrDetailFeature object using created Endcut</span>
<span class="keyword">    Dim </span>ObjStrDetailFeature<span class="keyword"> As </span>StrDetailFeature
<span class="keyword">    Set </span>ObjStrDetailFeature = iObjStrEndCut.StrDetailFeature
    
<span class="comment">'   7.2- Changes the Endcut Type and Name</span>
    ObjStrDetailFeature.Type = &quot;Weld&quot;
    ObjStrDetailFeature.FeatureName = &quot;Metal To Metal&quot;
   
<span class="comment">'   7.3- Updates the connection coordinate and visualiztion for Endcut</span>
    ObjStrDetailFeature.Update

<span class="keyword">End Sub</span>


<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="comment">'Searches a product and open it.</span>
<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="keyword">Sub </span><strong>OpenProduct</strong>(byVal prdName as String, SFDPrdEditor<span class="keyword"> As </span>Editor)

    <span class="comment">'Get the Search Service.</span>
    <span class="keyword">Set </span>oSearchService = CATIA.GetSessionService(&quot;Search&quot;)
    <span class="keyword">Dim</span> oDBSearch <span class="keyword">As</span> DatabaseSearch 
    <span class="keyword">Set</span> oDBSearch = oSearchService.DatabaseSearch
    oDBSearch.BaseType = &quot;VPMReference&quot;
    <span class="comment">' To retrieve the product by its Title, use V_Name attribute</span>
    <span class="comment">' To retrieve the product by its Name, use PLM_ExternalID attribute</span>
    oDBSearch.AddEasyCriteria &quot;V_Name&quot;, prdName
    oSearchService.Search
    <span class="comment">'Retrieve the first entity.</span>
    <span class="keyword">Dim</span> oEntity <span class="keyword">As</span> PLMEntity 
    <span class="keyword">Set</span> oEntity = oDBSearch.Results.Item(1)
    <span class="comment">'Get the PLMOpen service &amp; Open the first retrieved entity.</span>
    <span class="keyword">Dim</span> oPLMOpenService <span class="keyword">As</span> PLMOpenService
    <span class="keyword">Set </span>oPLMOpenService = CATIA.GetSessionService(&quot;PLMOpenService&quot;)
    <span class="comment">'Get the editor.</span>
    oPLMOpenService.PLMOpen oEntity , SFDPrdEditor
    
<span class="keyword">End Sub</span>
</pre>
<script type="text/javascript">insertCopyright();</script>

</body>

</html>
