<!DOCTYPE html 
     PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
     "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
<meta http-equiv="Content-Language" content="en-us" />
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<meta name="devlang" content="idl" />
<link rel="stylesheet" type="text/css" href="../CAADocStyleSheets/caav5.css"/>
<script type="text/javascript" src="../CAADocJavaScript/DSDocTocToc.js">/* */</script>
<script type="text/javascript" src="../CAADocJavaScript/DSDocHighlight.js">/* */</script>
<script type="text/javascript" src="../CAADocJavaScript/submit.js">/* */</script>
<title>CAAScdSfdUcCreateSlot.CATScript</title></head>

<body onload="highlightSearchTerms();">

<pre>
<span class="comment">'-------------- Sample MACRO written in Basic Script ------------------------------------------</span>
<span class="comment">'This sample shows usage of StrNavigate API.</span>
<span class="comment">'This script requires sfd model which contains a Deck panel which is limited by Transversal</span>
<span class="comment">'Bulkhead</span>
<span class="comment">'</span>
<span class="comment">''Steps</span>
<span class="comment">'   1- Searches and opens model which is named as &quot;SfdProduct&quot;.</span>
<span class="comment">'   2- Retrieves Selection object.</span>
<span class="comment">'   3- Retrieves Part object.</span>
<span class="comment">'   4- Retrieves Transversal Bulkhead which is already created.</span>
<span class="comment">'   5- Retrieving children of the panel</span>
<span class="comment">'   6- Retrieving Parents of the panel</span>
<span class="comment">'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="keyword">Dim</span> ObjPart <span class="keyword">As</span> Part
<span class="keyword">Dim</span> SFDProdSel <span class="keyword">As</span> Selection


<span class="keyword">Sub</span> CATMain()
<span class="comment">'   1- Searches and opens model which is named as &quot;SfdProduct&quot;</span>
    <span class="keyword">Dim</span> SFDPrdEditor <span class="keyword">As</span> Editor
<span class="keyword">    Dim </span>prdName<span class="keyword"> As </span>String
    prdName = &quot;SfdProduct&quot;
    OpenProduct prdName , SFDPrdEditor
    
<span class="comment">'   2- Retrieves Selection object</span>
    <span class="keyword">Set</span> SFDProdSel = SFDPrdEditor.Selection

<span class="comment">'   3- Retrieves Part object</span>
    <span class="keyword">Set</span> ObjPart = SFDPrdEditor.ActiveObject
    
<span class="comment">'   4- Retrieves Transversal Bulkhead which is already created.</span>
    <span class="keyword">Set</span> RefSfdPanel = ObjPart.FindObjectByName(&quot;Transverse Bulkhead_1&quot;)
    SFDProdSel.Add RefSfdPanel
    <span class="keyword">Dim</span> ObjStrNavigate <span class="keyword">As</span> StrNavigate
    <span class="keyword">Set</span> ObjStrNavigate = SFDProdSel.FindObject(&quot;CATIAStrNavigate&quot;)
    
<span class="comment">'   5- Retrieving children of the panel</span>
    <span class="keyword">Dim</span> ListOfPanelChildren <span class="keyword">As</span> References
    <span class="keyword">Set</span> ListOfPanelChildren = ObjStrNavigate.GetChildren
    
<span class="comment">'   6- Retrieving Parents of the panel</span>
    <span class="keyword">Dim</span> ListOfPanelParents <span class="keyword">As</span> References
    <span class="keyword">Set</span> ListOfPanelParents = ObjStrNavigate.GetParents
<span class="keyword">End Sub</span>


<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="comment">'Searches a product and open it.</span>
<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="keyword">Sub </span><strong>OpenProduct</strong>(byVal prdName as String, SFDPrdEditor<span class="keyword"> As </span>Editor)

    <span class="comment">'Get the Search Service.</span>
    <span class="keyword">Set </span>oSearchService = CATIA.GetSessionService(&quot;Search&quot;)
    <span class="keyword">Dim</span> oDBSearch <span class="keyword">As</span> DatabaseSearch 
    <span class="keyword">Set</span> oDBSearch = oSearchService.DatabaseSearch
    oDBSearch.BaseType = &quot;VPMReference&quot;
    <span class="comment">' To retrieve the product by its Title, use V_Name attribute</span>
    <span class="comment">' To retrieve the product by its Name, use PLM_ExternalID attribute</span>
    oDBSearch.AddEasyCriteria &quot;V_Name&quot;, prdName
    oSearchService.Search
    <span class="comment">'Retrieve the first entity.</span>
    <span class="keyword">Dim</span> oEntity <span class="keyword">As</span> PLMEntity 
    <span class="keyword">Set</span> oEntity = oDBSearch.Results.Item(1)
    <span class="comment">'Get the PLMOpen service &amp; Open the first retrieved entity.</span>
    <span class="keyword">Dim</span> oPLMOpenService <span class="keyword">As</span> PLMOpenService
    <span class="keyword">Set </span>oPLMOpenService = CATIA.GetSessionService(&quot;PLMOpenService&quot;)
    <span class="comment">'Get the editor.</span>
    oPLMOpenService.PLMOpen oEntity , SFDPrdEditor
    
<span class="keyword">End Sub</span>
</pre>
<script type="text/javascript">insertCopyright();</script>

</body>

</html>
