<!doctype html public "-//w3c//dtd html 4.0 transitional//en">
<html>
<head>
 <meta http-equiv="Content-Language" content="en-us"> 
 <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"> 
 <meta name="Generator" content="mihGene v1.1">
 <meta http-equiv="Expires" content="Tue, 04 Dec 1993 21:29:02 GMT">
 <title>Drafting2DLIDLItf Layout2DViews (Object)</title>
<link rel="Stylesheet" type="text/css" href="../../../caav5.css">
<link href="../_index/cdg.css" rel="stylesheet" type="text/css"> 
<script type="text/javascript">var PubDirExist = false; var ProDirExist = false; var PrivDirExist = false;</script> 
<script type="text/javascript" src="../_index/cdg.js"></script> 
<script language="Javascript" id="jsLinkjs" type="text/javascript" src="../_index/jslink.js"></script> 
<script language="Javascript" id="jsFwLinkjs" type="text/javascript" src="jsFwLink.js"></script> 
<script language="Javascript" id="jsTreejs" type="text/javascript" src="../_index/jsTree.js"></script>  
</head>
<body>
<div class="menu1" id="menuViewPPP" > 
 	<a href="javascript:writeIndex('IPublic')" name="viewPPP" id="PublicView"  class="ongletPub" > Public View</a> 
 	<a href="javascript:writeIndex('IProtected')" name="viewPPP" id="ProtectedView" class="ongletPro"  > Protected View</a>  
 	<a href="javascript:writeIndex('IPrivate')" name="viewPPP" id="PrivateView" class="ongletPriv" > Private View</a> 
 </div> 
 <div id="indexView" class="menu1">	 
 <a name="multiview" class="onglet" rel="../_index/main.htm" href="../_index/main.htm">All Frameworks</a>   
 <a name="multiview" class="onglet"  rel="../_index/tree.htm" href="../_index/tree.htm">Class Hierarchy</a>   
 <a name="multiview" class="onglet"  rel="../Drafting2DLIDLItf.htm" href="../Drafting2DLIDLItf.htm">This Framework</a>
<a name="multiview" class="onglet"  rel="../_index/HomeIdx.htm" href="../_index/HomeIdx.htm">Indexes</a>  
 <a id="multiviewP" class="onglet" href="javascript:openLinkNP(getCurrentObjectName(),getCurrentType(),'0')"  >Previous</a>  
 	<a id="multiviewN" class="onglet" href="javascript:openLinkNP(getCurrentObjectName(),getCurrentType(),'1')"  >Next</a> 
 </div> 
<script type="text/javascript" > 
 	function getCurrentLevel() { 
 return "";	} 
	function getCurrentFw() { 
	return "Drafting2DLIDLItf";	}
		function getCurrentObjectName() { 
 	return "Layout2DViews"; } 
	function getCurrentType() { 
 	return "interface"; }  
 function callInit() { 
 		if (PubDirExist == true || ProDirExist == true || PrivDirExist == true) {  
 			var parent = document.getElementById("indexView"); 
 			if (parent && (ProDirExist == true || PrivDirExist == true) ) { 
 			var elem = document.getElementById("multiviewP"); 
 			if(elem) parent.removeChild(elem); 
 			elem = document.getElementById("multiviewN"); 
 			if(elem) parent.removeChild(elem); }
 			initData(); 
 		} else { 
 			var elem; 
 			var parent = document.getElementById("menuViewPPP"); 
 			if (parent) { 
 				elem = document.getElementById("PublicView"); 
 				parent.removeChild(elem); 
 				elem = document.getElementById("ProtectedView"); 
 				parent.removeChild(elem); 
 				elem = document.getElementById("PrivateView"); 
 				parent.removeChild(elem); 
 			} 
 if (locateObject(getCurrentObjectName(), getCurrentType(), '0')==0) { 
 				elem = document.getElementById("multiviewP"); 
 				if (elem) { elem.removeAttribute("href"); elem.removeAttribute("onclick"); } 
 			} 
 			if (locateObject(getCurrentObjectName(), getCurrentType(), '1')==0) { 
 				elem = document.getElementById("multiviewN"); 
 				if (elem) { elem.removeAttribute("href"); elem.removeAttribute("onclick"); } 
 			} 
 }	 
 	} 
 	window.onload = callInit; 
  </script> 
 
<h1>Layout2DViews<font size=-1> (Object)</font></h1>
<script type="text/javascript" > 
 generatedFatherClass('interface_Layout2DViews_23279','Layout2DViews','0');</script>
<b><i> </i></b><br>
<hr>
<dl>
 <h2><a name="PropertyIndex"></a>Property Index</h2>
 <dt>
    <a href="#ActiveView"><b>ActiveView</b></a>
<dd>  Returns the active Layout2D view of the active Layout2D sheet.
</dl>
<dl>
 <h2><a name="MethodIndex"></a>Method Index</h2>
 <dt>
    <a href="#AddAuxiliary"><b>AddAuxiliary</b></a>
<dd>  Creates a section or section-cut or auxiliary View2DL from a given Layout View2DL.
 <dt>
    <a href="#AddDetail"><b>AddDetail</b></a>
<dd>  Creates a detail view and adds it to the layout view collection.
 <dt>
    <a href="#AddFrom3DPlane"><b>AddFrom3DPlane</b></a>
<dd>  Creates a viewFrom3D View2DL with the given 3Dplane as its
 view plane at the given position in the given Sheet2DL.
 <dt>
    <a href="#AddPrimary"><b>AddPrimary</b></a>
<dd>  Creates a Layout view and adds it to the Layout view collection.
 <dt>
    <a href="#AddRelated"><b>AddRelated</b></a>
<dd>  Creates a projection or isometric Layout View2DL from a given View2DL.
 <dt>
    <a href="#Item"><b>Item</b></a>
<dd>  Returns a Layout2D view using its index or its name from the Layout2DViews collection.
 <dt>
    <a href="#Remove"><b>Remove</b></a>
<dd>  Removes a layout2D view from the Layout2DViews collection.
</dl>
 <h2><a name="Properties"></a>Properties</h2> <br>
<a name="ActiveView"><dt>

<table><tr><td>o Property <b>ActiveView</b>(<td>) As <script type="text/javascript"> activateLink('Layout2DView','Layout2DView')</script>  (Read Only)</table></dt>
<dl>
  <dd>
 Returns the active Layout2D view of the active Layout2D sheet.
 <!-- @sample -->
 <dl>
 <dt><b>Example:</b>
 <dd>
 The following example retrieves in <tt>ViewToWorkIn</tt>
 the active Layout2D view in the Layout2DSheets collection of the layoutRoot
 <pre>
 Dim myPart as CATIAPart
 Set myPart = CATIA.ActiveEditor.ActievObject
 Dim MyRoot As Layout2DRoot
 Set MyRoot = myPart.GetItem("CATLayoutRoot")
 Dim ViewToWorkIn As Layout2DView
 Set ViewToWorkIn = MyRoot.Sheets.ActiveSheet.Layout2DViews.<font color="red">ActiveView</font>
 </pre>
 </dl>
</dl>
 <h2><a name="Methods"></a>Methods</h2> <br>
<a name="AddAuxiliary"><dt>

<table><tr><td>o Func <b>AddAuxiliary</b>(<td><script type="text/javascript"> activateLink('Layout2DView','Layout2DView')</script> <td><tt>iReferenceView</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('CATSafeArrayVariant','CATSafeArrayVariant')</script> <td><tt>iBCSegment</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('double','double')</script> <td><tt>iXorient</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('double','double')</script> <td><tt>iYorient</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('CatViewType','CatViewType')</script> <td><tt>iSectionType</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('double','double')</script> <td><tt>iX</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('double','double')</script> <td><tt>iY</tt>) As <script type="text/javascript"> activateLink('Layout2DView','Layout2DView')</script> </table></dt>
<dl>
  <dd>
 Creates a section or section-cut or auxiliary View2DL from a given Layout View2DL.
 The View2DL must be in this collection. 
 Caracteristics of new view (view plane etc) are computed based on the given
 basic callout and reference view 2DL viewplane.
  <br><b> Precondition</b> : 1/ The reference View2DL must be in this collection 
  <br><b> Precondition</b> : 2/ The reference View2DL must be a projection view.
  <br><b> Precondition</b> : 3/ The callout segment's length must not be 0.
  <br><b> Precondition</b> : 4/ iViewType must be either auxiliary or section or section cut.

 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iReferenceView</tt>
   <dd> [in] The reference view. Must be a projection View.
 </dd>
    <dt><tt> iBCSegment</tt>
   <dd> [in]  The callout's segment gives the trace of the auxiliary View2DL's projection
 plane in the reference View2DL.
 It has the following contents:
   <dl>
     <dt><tt>iBCSegment[0] = X1</tt>     <dd>x coordinate of the first point
     <dt><tt>iBCSegment[1] = Y1</tt>     <dd>y coordinate of the first point
     <dt><tt>iBCSegment[2] = X2</tt>     <dd>x coordinate of the second point
     <dt><tt>iBCSegment[3] = Y2</tt>     <dd>y coordinate of the second point
   </dl>
 </dd>
    <dt><tt> iBCOrient</tt>
   <dd> [in]  The callout's orientation gives the direction taken into account when Layout2D
 the auxilliary View2DL.
 </dd>
    <dt><tt> iXorient</tt>
   <dd> [in]  </dd>
    <dt><tt> iYorient</tt>
   <dd> [in]  This point determine the type taken into account when Layout2D the auxilliary View2DL.
 </dd>
    <dt><tt> iSectionType</tt>
   <dd>  </dd>
    <dt><tt> iX</tt>
   <dd> [in]  </dd>
    <dt><tt> iY</tt>
   <dd> [in]  The coordinate in the Sheet2DL for the new View2DL.
 
 </dd>
</dl>
  <dt> <b>Returns:</b> 
  <dd>  The created Layout2D view <!-- @sample -->
 </dl>
 <dt><b>Example:</b>
 <dd>
 The following example creates a Layout2D view named from the active view
 and retrieved in <tt>MyView</tt>
 in the Layout2D view collection of the <tt>MySheet</tt> Layout2D sheet.
 This sheet belongs to the Layout2D sheet collection of the layoutRoot
 <pre>
 Dim x As double
 Set x = 10.
 Dim y As double
 Set y = 10.
 Dim MySegment 
 ReDim MySegment(3)
     MySegment(0) = 10.
     MySegment(1) = 200.
     MySegment(2) = 100.
     MySegment(3) = 200.
 Dim myPart as CATIAPart
 Set myPart = CATIA.ActiveEditor.ActievObject
 Dim MyRoot As Layout2DRoot
 Set MyRoot = myPart.GetItem("CATLayoutRoot")
 Dim MyFirstView As Layout2DView
 Set MyFirstView = MyRoot.Sheets.ActiveSheet.Views.ActiveView
 Dim MyView As Layout2DView
 Set MyView = MyRoot.Sheets.ActiveSheet.Views.
 </pre>
 </dl>
</dl>
</dl>
<a name="AddDetail"><dt>

<table><tr><td>o Func <b>AddDetail</b>(<td><script type="text/javascript"> activateLink('CATBSTR','CATBSTR')</script> <td><tt>iDetailName</tt>) As <script type="text/javascript"> activateLink('Layout2DView','Layout2DView')</script> </table></dt>
<dl>
  <dd>
 Creates a detail view and adds it to the layout view collection.
 This layout view becomes the active one.
  <br><b> Precondition</b> : The collection view must be a Detail Sheet
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iDetailName</tt>
   <dd>   The name to assign to the created layout view
 </dd>
</dl>
  <dt> <b>Returns:</b> 
  <dd>  The created layout view
 
  <dt> Example: </dt> 
  <dd> <pre class="code">  The following example creates a detail view named <tt>Ditto</tt>
 and retrieved in <tt>MyView</tt> in the layout view collection 
 of the <tt>MyDetailSheet</tt> layout sheet. Where <tt>MyDetailSheet</tt>
 is the active sheet of the layout sheet collection of the layout root
 <pre>
 Dim myPart as CATIAPart
 Set myPart = CATIA.ActiveEditor.ActievObject
 Dim MyLayoutRoot As Layout2DRoot
 Set MyLayoutRoot = myPart.GetItem("CATLayoutRoot")
 Dim MyDetailSheet As Layout2DSheet
 Set MyDetailSheet = .Sheets.ActiveSheet
 Dim MyView As Layout2DView
 Set MyView = MyDetailSheet.Views.<font color="red">AddDetail</font>("Ditto")
 </pre>
 </dl></pre></dd>
</dl>
</dl>
<a name="AddFrom3DPlane"><dt>

<table><tr><td>o Func <b>AddFrom3DPlane</b>(<td><script type="text/javascript"> activateLink('CATSafeArrayVariant','CATSafeArrayVariant')</script> <td><tt>iPlane</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('CatViewType','CatViewType')</script> <td><tt>iViewType</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('double','double')</script> <td><tt>iX</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('double','double')</script> <td><tt>iY</tt>) As <script type="text/javascript"> activateLink('Layout2DView','Layout2DView')</script> </table></dt>
<dl>
  <dd>
 Creates a viewFrom3D View2DL with the given 3Dplane as its
 view plane at the given position in the given Sheet2DL.
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iPlane</tt>
   <dd> [in] Define the plane on wich the view as to be created
 It has the following contents:
   <dl>
     <dt><tt>iPlane[0] = X </tt>     <dd>x coordinate of plane origin in 3D space
     <dt><tt>iPlane[1] = Y </tt>     <dd>y coordinate of plane origin in 3D space
     <dt><tt>iPlane[2] = Z </tt>     <dd>z coordinate of plane origin in 3D space
     <dt><tt>iPlane[3] = H1</tt>     <dd>Define the direction which the view's viewplane H 
     <dt><tt>iPlane[4] = H2</tt>     <dd>axis has to be colinear with
     <dt><tt>iPlane[5] = H3</tt>     <dd>  
     <dt><tt>iPlane[6] = V1</tt>     <dd>Define the direction which the view's viewplane V
     <dt><tt>iPlane[7] = V2</tt>     <dd>axis has to be colinear with
     <dt><tt>iPlane[8] = V3</tt>     <dd>
   </dl>
 <br><b> Precondition</b> : 1/iViewType must be either auxiliary or section or section cut.
 <br><b> Precondition</b> : 2/ iFirstDirection and iSecondDirection must be orthogonal.
 </dd>
    <dt><tt> iViewType</tt>
   <dd>   The view type: <tt>catAuxiliary</tt> or <tt>catSectionCut</tt> or <tt>catSectionView</tt>
 </dd>
    <dt><tt> iX</tt>
   <dd> [in] </dd>
    <dt><tt> iY</tt>
   <dd> [in] The coordinate of the new View2DL in the Sheet2DL

 </dd>
</dl>
  <dt> <b>Returns:</b> 
  <dd>  The created Layout2D view
</dl>
</dl>
<a name="AddPrimary"><dt>

<table><tr><td>o Func <b>AddPrimary</b>(<td><script type="text/javascript"> activateLink('double','double')</script> <td><tt>iX</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('double','double')</script> <td><tt>iY</tt>) As <script type="text/javascript"> activateLink('Layout2DView','Layout2DView')</script> </table></dt>
<dl>
  <dd>
 Creates a Layout view and adds it to the Layout view collection.
 This Layout view becomes the active one.
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iX</tt>
   <dd> [in]  </dd>
    <dt><tt> iY</tt>
   <dd> [in]  The coordinate in the Sheet2DL for the new View2DL.

 </dd>
</dl>
  <dt> <b>Returns:</b> 
  <dd>  The created Layout2D view <!-- @sample -->
 </dl>
 <dt><b>Example:</b>
 <dd>
 The following example creates a Layout2D view and retrieved in <tt>MyView</tt>
 in the Layout2D view collection of the Layout2D sheet.
 This sheet belongs to the Layout2D sheet collection.
 <pre>
 Dim x as double
 Set x = 10.
 Dim y as double
 Set y = 10.
 Dim MyView As Layout2DView
 Dim myPart as CATIAPart
 Set myPart = CATIA.ActiveEditor.ActievObject
 Set MyView = myPart.GetItem("CATLayoutRoot").Sheets.ActiveSheet.
              Views.<font color="red">AddPrimary</font>(x, y).
 </pre>
 </dl>
</dl>
</dl>
<a name="AddRelated"><dt>

<table><tr><td>o Func <b>AddRelated</b>(<td><script type="text/javascript"> activateLink('Layout2DView','Layout2DView')</script> <td><tt>iReferenceView</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('CatViewSide','CatViewSide')</script> <td><tt>iSide</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('double','double')</script> <td><tt>iX</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('double','double')</script> <td><tt>iY</tt>) As <script type="text/javascript"> activateLink('Layout2DView','Layout2DView')</script> </table></dt>
<dl>
  <dd>
 Creates a projection or isometric Layout View2DL from a given View2DL.
 The view will be created in the same collection as the given 
 View2DL, at the given position. 
 The caracteristics (ex: view plane etc) of this new View2DL are computed 
 based on the caracteristics stored in the ViewBox its <tt>iReferenceView</tt>
 is associated with.
  
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iReferenceView</tt>
   <dd> [in]   The reference View2DL from which the new View2DL is created.
 </dd>
    <dt><tt> iSide</tt>
   <dd> [in]   Used with the ViewBox and iReferenceView to give the related view to create (type etc).
 </dd>
    <dt><tt> iX</tt>
   <dd> [in]  </dd>
    <dt><tt> iY</tt>
   <dd> [in]  The coordinate in the Sheet2DL for the new View2DL.

 </dd>
</dl>
  <dt> <b>Returns:</b> 
  <dd>  The created Layout2D view <br><b> Precondition</b> : The reference View2DL must be in this collection 
 <!-- @sample -->
 </dl>
 <dt><b>Example:</b>
 <dd>
 The following example creates a Layout2D view named from the active view
 and retrieved in <tt>MyView</tt>
 in the Layout2D view collection of the <tt>MySheet</tt> Layout2D sheet.
 This sheet belongs to the Layout2D sheet collection of the layoutRoot.
 <pre>
 Dim x as double
 Set x = 10.
 Dim y as double
 Set y = 10.
 Dim MyFirstView As Layout2DView
 Set MyFirstView = CATIA.ActiveDocument.Part.GetItem("CATLayoutRoot").Sheets.ActiveSheet.Views.ActiveView
 Dim MyView As Layout2DView
 Dim myPart as CATIAPart
 Set myPart = CATIA.ActiveEditor.ActievObject
 Set MyView = myPart.GetItem("CATLayoutRoot").Sheets.ActiveSheet.Views.
              <font color="red">AddRelated</font>(MyFirstView,catLeftSide, x, y)
 </pre>
 </dl>
</dl>
</dl>
<a name="Item"><dt>

<table><tr><td>o Func <b>Item</b>(<td><script type="text/javascript"> activateLink('CATVariant','CATVariant')</script> <td><tt>iIndex</tt>) As <script type="text/javascript"> activateLink('Layout2DView','Layout2DView')</script> </table></dt>
<dl>
  <dd>
 Returns a Layout2D view using its index or its name from the Layout2DViews collection.
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iIndex</tt>
   <dd>   The index or the name of the Layout2D view to retrieve from
   the collection of Layout2D views.
   As a numerics, this index is the rank of the Layout2D view
   in the collection.
   The index of the first Layout2D view in the collection is 1, and
   the index of the last Layout2D view is Count.
   As a string, it is the name you assigned to the Layout2D view using
   the </dd>
</dl>
<script type="text/javascript"> activateLinkAnchor('CATIABase','Name','CATIABase.Name') </script> property or when creating it using   the 
<script type="text/javascript"> activateLinkAnchor('','Add','Add') </script> method. 
  <dt> <b>Returns:</b> 
  <dd>  The retrieved Layout2D view 
  <dt> Example: </dt> 
  <dd> <pre class="code">  This example retrieves in <tt>ThisLayout2DView</tt> the second Layout2D view,
 and in <tt>ThatLayout2DView</tt> the Layout2D view named
 <tt>MyView</tt> in the Layout2D view collection of the active sheet of a layoutRoot
 of a part of the active document, supposed to be a part document.
 <pre>
 Dim myPart as CATIAPart
 Set myPart = CATIA.ActiveEditor.ActievObject
 Dim MySheet As Layout2DSheet
 Set MySheet = myPart.GetItem("CATLayoutRoot").Sheets.ActiveSheet
 Dim ThisLayout2DView As Layout2DView
 Set ThisLayout2DView = MySheet.Views.ActiveView.<font color="red">Item</font>(2)
 Dim ThatLayout2DView As Layout2DView
 Set ThatLayout2DView = MySheet.Views.ActiveView.<font color="red">Item</font>("MyView")
 </pre></pre></dd>
</dl>
</dl>
<a name="Remove"><dt>

<table><tr><td>o Sub <b>Remove</b>(<td><script type="text/javascript"> activateLink('CATVariant','CATVariant')</script> <td><tt>iIndex</tt>)</table></dt>
<dl>
  <dd>
 Removes a layout2D view from the Layout2DViews collection.
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iIndex</tt>
   <dd>   The index or the name of the Layout2D view to remove from
   the collection of Layout2D views.
   As a numerics, this index is the rank of the Layout2D view
   in the collection.
   The index of the first Layout2D view in the collection is 1, and
   the index of the last Layout2D view is Count.
   As a string, it is the name you assigned to the Layout2D view using
   the </dd>
</dl>
<script type="text/javascript"> activateLinkAnchor('CATIABase','Name','CATIABase.Name') </script> property or when creating it using   the 
<script type="text/javascript"> activateLinkAnchor('','Add','Add') </script> method. <!-- @sample -->
 </dl>
 <dt><b>Example:</b>
 <dd>
 The following example removes the third Layout2D view and the Layout2D view
 named <tt>TopView</tt> in the Layout2D view collection of the active sheet of a layoutRoot
 of a part of the active document, supposed to be a part document.
 <pre>
 Dim myPart as CATIAPart
 Set myPart = CATIA.ActiveEditor.ActievObject
 Dim MySheet As Layout2DSheet
 Set MySheet = myPart.GetItem("CATLayoutRoot").Sheets.ActiveSheet
 MySheet.ActiveViews.<font color="red">Remove</font>(3)
 MySheet.ActiveViews.<font color="red">Remove</font>("TopView")
 </pre>
 </dl>
</dl>
</dl>
<hr/><p><i>
Copyright &#169; 1999-2014, Dassault Syst&#232;mes. All rights reserved.
</i></p>
</body>

</html>

