<html xmlns:m="http://schemas.microsoft.com/office/2004/12/omml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">

<head>
<meta http-equiv="Content-Language" content="en-us">
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<meta name="GENERATOR" content="Microsoft FrontPage 12.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>Creating Standard Openings</title>
<link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css">
<script type="text/javascript" src="../CAAScrJavaScript/submit.js"></script>
</head>

<body>

<table border="0" width="100%">
	<tr>
		<td>
		<h2>Structure Functional Design</h2>
		</td>
		<td align="right" valign="top">
		<h2><a name="Top"></a>Creating Standard Openings</h2>
		</td>
	</tr>
</table>
<hr>
<!----------------------------------comment------------------------------------->
<table border="0" width="100%">
	<tr>
		<td width="7%" valign="top">
		<img alt="" src="../CAAScrBase/images/atarget.gif" width="32" height="32"></td>
		<td width="93%">
		<p><a name="Learn"></a>This macro shows you how to create a standard opening 
		on an SDD plate. Here we will use &quot;Rect&quot; profile and the MidDist-MidDist 
		strategy.</p>
		<p><strong>Note</strong>: Scripts for creation of Standard Openings using 
		other positioning strategies are also provided in the CAAScdSfdUseCases/macros 
		directory:</p>
		<ul>
			<li>CAASfdHalfHeight_MidDist.CATScript</li>
			<li>CAASfdHalfHeight_Offset.CATScript</li>
			<li>CAASfdMidDist_Offset.CATScript</li>
			<li>CAASfdOffset_Offset.CATScript</li>
		</ul>
		</td>
	</tr>
	<tr>
		<td width="7%" valign="top">
		<img alt="" src="../CAAScrBase/images/ainfo.gif" width="32" height="32"></td>
		<td width="93%">
		<p><a name="How" href="macros/CAASfdCreateStdOpening.CATScript">CAASfdCreateStdOpening</a> 
		is launched in CATIA [<a href="#References">1</a>]. First open 
		CAASfdCreateStdOpening.CATPart located in the samples directory.</p>
		<p><a href="CAASfdCreateStdOpeningSource.htm" target="Source">CAASfdCreateStdOpening.CATScript</a> 
		is located in the CAAScdSfdUseCases directory.
		<a href="macros/CAASfdCreateStdOpening.CATScript">Execute macro</a> (Windows 
		only).</p>
		</td>
	</tr>
	<tr>
		<td width="7%" valign="top">
		<img alt="" src="../CAAScrBase/images/ascenari.gif" width="32" height="32"></td>
		<td width="93%">
		<p><a name="Step"></a>CAASfdMidDist-MidDist includes five steps:</p>
		<ol>
			<li><a href="#Step1">Prolog</a></li>
			<li><a href="#Step2">Retrieving the Factory and Two Managers (Contour 
			Manager and Position Strategy Manager)</a></li>
			<li><a href="#Step3">Selecting the Contour and Set Contour Parameters</a></li>
			<li><a href="#Step4">Defining the Position Strategy and Preparing Lists 
			for U References and V References</a></li>
			<li><a href="#Step5">Creating a Standard Opening by Setting PositionStrategyParms</a></li>
		</ol>
		<p><img alt="" src="images/CAASfdCreateStdOpening.png"></p>
		<!-- -------------------------------comment---------------------------------- -->
		<h4><a name="Step1">Prolog</a></h4>
		<p>Opens in CATIA the CAASfdCreateStdOpening.CATPart located in the samples 
		directory.</p>
		<table class="code">
			<tr>
				<td width="100%">
				<pre>
Sub CATMain()

  Dim Part1 As Part
  Set Part1 = CATIA.ActiveDocument.Part
  Dim plate As SfmSuperPlate
  Set plate = Part1.FindObjectByName(&quot;Deck_002&quot;)
  Dim plateref As Reference
  Set plateref = Part1.CreateReferenceFromObject(plate)
  ...</pre>
				</td>
			</tr>
		</table>
		<!-- -------------------------------comment---------------------------------- -->
		<h4><a name="Step2">Retrieving the Factory and Two Managers (Contour Manager 
		and Position Strategy Manager)</a></h4>
		<p>First retrieve the factory from the part. Then retrieve the SfmOpeningContoursMgr 
		and SfmPositioningStrategyManager objects.</p>
		<table class="code">
			<tr>
				<td width="100%">
				<pre>  ...
  Dim Factory As SfmFunctionFactory
  Set Factory = Part1.GetCustomerFactory(&quot;SfmFunctionFactory&quot;)

  Dim ObjSfmContourMgr As SfmOpeningContoursMgr
  Set ObjSfmContourMgr = Factory.GetOpeningMgr(Part1, &quot;SfmOpeningContoursMgr&quot;)
 
  Dim ObjSfmPosStrategyMgr As SfmPositioningStrategyManager
  Set ObjSfmPosStrategyMgr = Factory.GetOpeningMgr(Part1, &quot;SfmPositioningStrategyManager&quot;)
  ...</pre>
				</td>
			</tr>
		</table>
		<!-- -------------------------------comment---------------------------------- -->
		<h4><a name="Step3">Selecting the Contour and Set Contour Parameters</a></h4>
		<p>Use ObjSfmContourMgr to get the list of the entire contour Names available. 
		Out of the list &quot;Sfm_Rect&quot; is selected. To set its parameters, use the GetStdOpeningContourParams 
		method.</p>
		<table class="code">
			<tr>
				<td width="100%">
				<pre>  ...
  &#39;Define the Contour

  Dim oListContourNames() As Variant
  ObjSfmContourMgr.GetAvailableStdOpeningContours oListContourNames

  Dim NbOfContour As Long
  NbOfContour = UBound(oListContourNames)

  &#39;Display List of contours
  Dim i As Integer
  For i = 0 To NbOfContour
    MsgBox oListContourNames(i)
  Next

  &#39;Set the Required Contour and Set its Contour Parameters
  Dim oListCkeParms As SfmStandardContourParameters
  Set oListCkeParms = ObjSfmContourMgr.GetStdOpeningContourParams(&quot;Sfm_Rect&quot;)

  Dim NbOfParam As Long
  NbOfParam = oListCkeParms.Count

  Dim ContourParam As Parameter
  Dim ContourParamName As String

  For i = 1 To NbOfParam
    Set ContourParam = oListCkeParms.Item(i)
    ContourParamName = oListCkeParms.Item(i).Name
    &#39;MsgBox ContourParamName

    If ContourParamName = &quot;Sfm_Width&quot; Then
      ContourParam.ValuateFromString (&quot;1000mm&quot;)
    End If
    If ContourParamName = &quot;Sfm_Height&quot; Then
      ContourParam.ValuateFromString (&quot;2000mm&quot;)
    End If
    If ContourParamName = &quot;Sfm_CornerRadius&quot; Then
      ContourParam.ValuateFromString (&quot;10mm&quot;)
     End If
  Next
  ...</pre>
				</td>
			</tr>
		</table>
		<!-- -------------------------------comment---------------------------------- -->
		<h4><a name="Step4">Defining the Position Strategy and Preparing Lists for 
		U References and V References</a></h4>
		<p>Use ObjSfmPosStrategyMgr to GetPositioningStrategyParams.</p>
		<p>Since MidDist-MidDist strategy is selected, you need to prepare List 
		of U References and V References. Both these lists will contain even number 
		of reference Planes.</p>
		<table class="code">
			<tr>
				<td width="100%">
				<pre>  ...
  &#39;Define the Position Strategy
  Dim PositionStrategyParms As SfmStandardPosStrategyParameters
  Set PositionStrategyParms = ObjSfmPosStrategyMgr.GetPositioningStrategyParams(&quot;CATSfmPosMidDistMidDist&quot;)

  &#39;Prepare a List of U &amp; V Reference
  Dim UrefList As SfmReferences
  Dim Uref1, Uref2, Uref3, Uref4 As Reference
  Set Uref1 = Part1.FindObjectByName(&quot;CROSS.95&quot;)
  Set Uref2 = Part1.FindObjectByName(&quot;CROSS.50&quot;)
  Set Uref3 = Part1.FindObjectByName(&quot;CROSS.25&quot;)
  Set Uref4 = Part1.FindObjectByName(&quot;CROSS.40&quot;)
  Set UrefList = Factory.SfmReferences
  UrefList.Add Uref1
  UrefList.Add Uref2
  UrefList.Add Uref3
  UrefList.Add Uref4
 
  Dim VrefList As SfmReferences
  Dim Vref1, Vref2 As Reference
  Set Vref1 = Part1.FindObjectByName(&quot;LONG.0&quot;)
  Set Vref2 = Part1.FindObjectByName(&quot;LONG.10&quot;)
  Set VrefList = Factory.SfmReferences
  VrefList.Add Vref1
  VrefList.Add Vref2
 
  Dim NbofURef As Long
  NbofURef = UrefList.Count
 
  Dim NbofVRef As Long
  NbofVRef = VrefList.Count
  ...</pre>
				</td>
			</tr>
		</table>
		<!-- -------------------------------comment---------------------------------- -->
		<h4><a name="Step5">Creating a Standard Opening by Setting PositionStrategyParms</a></h4>
		<ol>
			<li>An intermediate list for U references is created (URefListint).</li>
			<li>Inside the For loop, this intermediate list will hold first two 
			U references. The For loop moves in step of 2.</li>
			<li>SetPosParamData Method is called on PositonStrategyParams to set 
			the data</li>
			<li>Create Standard Opening by defining required parameters. It is called 
			on Factory.</li>
			<li>Clear the current intermediate list. It will be populated again 
			with next two elements in next loop.</li>
		</ol>
		<table class="code">
			<tr>
				<td width="100%">
				<pre>  ...
  Dim StdOpening As SfmStandardOpening
  Dim URefListint As SfmReferences
  Set URefListint = Factory.SfmReferences

  Dim nUrefCnt As Integer
  For nUrefCnt = 1 To NbofURef Step 2
    If (nUrefCnt + 1) &lt;= NbofURef Then
      URefListint.Add UrefList.Item (nUrefCnt)
      URefListint.Add UrefList.Item (nUrefCnt + 1)
      PositionStrategyParms.SetPosParamData &quot;CATSfmPosMidDistMidDist&quot;, 20, URefListint, 1, VrefList, 2
      Set StdOpening = Factory.CreateStandardOpening (&quot;FunctionalOpening&quot;, &quot;Sfm_Rect&quot;, oListCkeParms, &quot;CATSfmPosMidDistMidDist&quot;, PositionStrategyParms, plateref)
      URefListint.ClearList
    End If
  Next

  Part1.Update
  ...</pre>
				</td>
			</tr>
		</table>
		<!-- -------------------------------comment---------------------------------- -->
		</td>
	</tr>
	<tr>
		<td width="7%" valign="top"></td>
		<td width="93%">
		<p align="center">
		<img alt="" src="../CAAScrBase/images/aendtask.gif" width="64" height="32"></p>
		</td>
	</tr>
	<!-- -------------------------------comment---------------------------------- -->
</table>
<p align="right">[<a href="#Top">Top</a>]</p>
<hr>
<!-- -------------------------------comment---------------------------------- -->
<h4><a name="InShort"></a>In Short</h4>
<p>This use case has shown how to create a standard opening using the MidDist-MidDist 
strategy.</p>
<hr>
<!-- -------------------------------comment---------------------------------- -->
<h4><a name="References"></a>References</h4>
<table border="0" width="100%">
	<tr>
		<td valign="top">[1]</td>
		<td><a href="../CAAScdInfUseCases/CAAInfLauchMacro.htm">Replaying 
		a Macro</a></td>
	</tr>
	<tr>
		<td valign="top">[2]</td>
		<td><a href="../CAAScdInfUseCases/CAAInfOpenDocument.htm">Opening 
		an Existing CATIA Document</a></td>
	</tr>
	<tr>
		<td colspan="2" align="right">[<a href="#Top">Top</a>]</td>
	</tr>
</table>
<hr>
<!-- -------------------------------comment---------------------------------- -->
<p><i>Copyright © 1999-2011, Dassault Systèmes. All rights reserved.</i></p>

</body>

</html>
