<html>

<head>
<meta http-equiv="Content-Language" content="en-us">
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<meta name="GENERATOR" content="Microsoft FrontPage 12.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>Creating Plates</title>
<link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css">
<script type="text/javascript" src="../CAAScrJavaScript/submit.js"></script>
</head>

<body>

<table border="0" width="100%">
	<tr>
		<td>
		<h2>Structure Functional Design</h2>
		</td>
		<td align="right" valign="top">
		<h2><a name="Top"></a>Creating Plates</h2>
		</td>
	</tr>
</table>
<hr>
<!----------------------------------comment------------------------------------->
<table border="0" width="100%">
	<tr>
		<td width="7%" valign="top">
		<img alt="" src="../CAAScrBase/images/atarget.gif" width="32" height="32"></td>
		<td width="93%">
		<p><a name="Learn"></a>This macro shows you how to create plates and advanced 
		plates of different categories in the SFD workbench.</p>
		</td>
	</tr>
	<tr>
		<td width="7%" valign="top">
		<img alt="" src="../CAAScrBase/images/ainfo.gif" width="32" height="32"></td>
		<td width="93%">
		<p><a name="How"></a>CAASfdCreatePlate is launched in CATIA [<a href="#References">1</a>].
		First open CAASfdCreatePlate.CATPart in the samples directory.</p>
		<p><a href="CAASfdCreatePlateSource.htm" target="Source">CAASfdCreatePlate.CATScript</a>
		 is located in the CAAScdSfdUseCases.
		<a href="macros/CAASfdCreatePlate.CATScript">Execute macro</a> (Windows 
		only).</p>
		</td>
	</tr>
	<tr>
		<td width="7%" valign="top">
		<img alt="" src="../CAAScrBase/images/ascenari.gif" width="32" height="32"></td>
		<td width="93%">
		<p><a name="Step"></a>CAASfdCreatePlate includes ten steps:</p>
		<ol>
			<li><a href="#Step1">Prolog</a></li>
			<li><a href="#Step2">Retrieving the Factory from the Part Document</a></li>
			<li><a href="#Step3">Getting the Manager from the Factory</a></li>
			<li><a href="#Step4">Adding a Hull</a></li>
			<li><a href="#Step5">Creating a Shell Plate by Defining the Support</a></li>
			<li><a href="#Step6">Adding Limits to the Shell Plate</a></li>
			<li><a href="#Step7">Generating Geometry for the Shell Plate</a></li>
			<li><a href="#Step8">Creating a Shell Plate on PortSide</a></li>
			<li><a href="#Step9">Creating a Deck Plate</a></li>
			<li><a href="#Step10">Creating an Advanced Transverse Bulkhead</a></li>
			<li><a href="#Step11">Updating the Part Document</a></li>
		</ol>
		<!-- -------------------------------comment---------------------------------- -->
		<h4><a name="Step1">Prolog</a></h4>
		<p>Opens the CAASfdCreatePlate.CATPart in CATIA.</p>
		<table class="code">
			<tr>
				<td width="100%">
				<pre>Sub CATMain()
  Dim ObjPart As Part
  Set ObjPart = CATIA.ActiveDocument.Part
  ...</pre>
				</td>
			</tr>
		</table>
		<!-- -------------------------------comment---------------------------------- -->
		<h4><a name="Step2">Retrieving the Factory from the Part Document</a></h4>
		<p>This Step describes how to get Structure Functional Modeler factory. The 
		SfmFactory object will be used for creating Structure Functional Modeler objects.</p>
		<table class="code">
			<tr>
				<td width="100%">
				<pre>  ...
  &#39;Get the Factory Object
  Dim FactoryObj As SfmFactory
  Set FactoryObj = ObjPart.GetCustomerFactory(&quot;SfmFactory&quot;)
  ...</pre>
				</td>
			</tr>
		</table>
		<!-- -------------------------------comment---------------------------------- -->
		<h4><a name="Step3">Getting the Manager from the Factory</a></h4>
		<p>The Manager object is obtained by the GetManager method.</p>
		<table class="code">
			<tr>
				<td width="100%">
				<pre>  ...
  &#39;Get the Manager Object
  Dim ManagerObj As SfmManager
  Set ManagerObj = FactoryObj.GetManager
  ...</pre>
				</td>
			</tr>
		</table>
		<!-- -------------------------------comment---------------------------------- -->
		<h4><a name="Step4">Adding a Hull</a></h4>
		<p>A hull is added to current part.</p>
		<table class="code">
			<tr>
				<td width="100%">
				<pre>  ...
  &#39;Adding Hull
  ManagerObj.AddHull
  ...</pre>
				</td>
			</tr>
		</table>
		<!-- -------------------------------comment---------------------------------- -->
		<h4><a name="Step5">Creating a Shell Plate by Defining the Support</a></h4>
		<table class="code">
			<tr>
				<td width="100%">
				<pre>  ...
  Dim ShellSupport As AnyObject
  Set ShellSupport = ObjPart.FindObjectByName(&quot;Hull1234&quot;)
  Dim ShellSupportRef As Reference
  Set ShellSupportRef = ObjPart.CreateReferenceFromObject(ShellSupport)
  Dim ShellSuperplate1 As SfmSuperPlate
  Set ShellSuperplate1 = FactoryObj.AddSuperPlate(&quot;ShellPanel&quot;, ShellSupportRef, Nothing)
  ...</pre>
				</td>
			</tr>
		</table>
		<!-- -------------------------------comment---------------------------------- -->
		<h4><a name="Step6">Adding Limits to the Shell Plate</a></h4>
		<p>Add limits to the shell plate by selecting a reference. Also, define orientation 
		of the limit, so as to keep desired side.</p>
		<table class="code">
			<tr>
				<td width="100%">
				<pre>  ...
  &#39;Defining First Limit
  Dim ShellPlateLimit1 As AnyObject
  Set ShellPlateLimit1 = ObjPart.FindObjectByName(&quot;CROSS.40&quot;)
  Dim ShellPlateLimitRef1 As Reference
  Set ShellPlateLimitRef1 = ObjPart.CreateReferenceFromObject(ShellPlateLimit1)

  &#39;Defining Orientation of First Limit
  Dim ShellPlateOrnt1 As Long
  ShellPlateOrnt1 = 8
  ShellSuperplate1.AddLimit ShellPlateLimitRef1, ShellPlateOrnt1

  &#39;Defining Second Limit
  Dim ShellPlateLimit2 As AnyObject
  Set ShellPlateLimit2 = ObjPart.FindObjectByName(&quot;CROSS.140&quot;)
  Dim ShellPlateLimitRef2 As Reference
  Set ShellPlateLimitRef2 = ObjPart.CreateReferenceFromObject(ShellPlateLimit2)

  &#39;Defining Orientation of Second Limit
  Dim ShellPlateOrnt2 As Long
  ShellPlateOrnt2 = 9
  ShellSuperplate1.AddLimit ShellPlateLimitRef2, ShellPlateOrnt2

  &#39;Defining Third Limit
  Dim ShellPlateLimit3 As AnyObject
  Set ShellPlateLimit3 = ObjPart.FindObjectByName(&quot;LONG.0&quot;)
  Dim ShellPlateLimitRef3 As Reference
  Set ShellPlateLimitRef3 = ObjPart.CreateReferenceFromObject(ShellPlateLimit3)

  &#39;Defining Orientation of Third Limit
  Dim ShellPlateOrnt3 As Long
  ShellPlateOrnt3 = 5
  ShellSuperplate1.AddLimit ShellPlateLimitRef3, ShellPlateOrnt3
  ...
</pre>
				</td>
			</tr>
		</table>
		<!-- -------------------------------comment---------------------------------- -->
		<h4><a name="Step7">Generating Geometry for the Shell Plate</a></h4>
		<p>To generate geometry, build is done for Shell Plate by Run.</p>
		<table class="code">
			<tr>
				<td width="100%">
				<pre>  ...
  ShellSuperplate1.Run
  ...</pre>
				</td>
			</tr>
		</table>
		<!-- -------------------------------comment---------------------------------- -->
		<h4><a name="Step8">Creating a Shell Plate on PortSide</a></h4>
		<table class="code">
			<tr>
				<td width="100%">
				<pre>  ...
  Dim ShellSuperplate2 As SfmSuperPlate
  Set ShellSuperplate2 = FactoryObj.AddSuperPlate(&quot;ShellPanel&quot;, ShellSupportRef, Nothing)
  Dim ShellPlate2Limit1 As AnyObject
  Set ShellPlate2Limit1 = ObjPart.FindObjectByName(&quot;CROSS.40&quot;)
  Dim ShellPlate2LimitRef1 As Reference
  Set ShellPlate2LimitRef1 = ObjPart.CreateReferenceFromObject(ShellPlate2Limit1)
  Dim ShellPlate2Ornt1 As Long
  ShellPlate2Ornt1 = 8
  ShellSuperplate2.AddLimit ShellPlate2LimitRef1, ShellPlate2Ornt1
  Dim ShellPlate2Limit2 As AnyObject
  Set ShellPlate2Limit2 = ObjPart.FindObjectByName(&quot;CROSS.140&quot;)
  Dim ShellPlate2LimitRef2 As Reference
  Set ShellPlate2LimitRef2 = ObjPart.CreateReferenceFromObject(ShellPlate2Limit2)
  Dim ShellPlate2Ornt2 As Long
  ShellPlate2Ornt2 = 9
  ShellSuperplate2.AddLimit ShellPlate2LimitRef2, ShellPlate2Ornt2
  Dim ShellPlate2Limit3 As AnyObject
  Set ShellPlate2Limit3 = ObjPart.FindObjectByName(&quot;LONG.0&quot;)
  Dim ShellPlate2LimitRef3 As Reference
  Set ShellPlate2LimitRef3 = ObjPart.CreateReferenceFromObject(ShellPlate2Limit3)
  Dim ShellPlate2Ornt3 As Long
  ShellPlate2Ornt3 = 4
  ShellSuperplate2.AddLimit ShellPlate2LimitRef3, ShellPlate2Ornt3
  ShellSuperplate2.Run
  ...</pre>
				</td>
			</tr>
		</table>

		<!-- -------------------------------comment---------------------------------- -->
		<h4><a name="Step9">Creating a Deck Plate</a></h4>
		<p>Create a deck plate on the Deck.3 plane as support,
		and then limit it by the shell plates CROSS.40 and CROSS.140.</p>
		<table class="code">
			<tr>
				<td width="100%">
				<pre>  ...
  &#39;Defining Support
  Dim DeckSupport As AnyObject
  Set DeckSupport = ObjPart.FindObjectByName(&quot;DECK.3&quot;)
  Dim DeckSupportRef As Reference
  Set DeckSupportRef = ObjPart.CreateReferenceFromObject(DeckSupport)
  
  Dim DeckSuperplate As SfmSuperPlate
  Set DeckSuperplate = FactoryObj.AddSuperPlate(&quot;DeckPanel&quot;, DeckSupportRef, Nothing)
  &#39;Applying Limits
  Dim DeckPlateLimit1 As AnyObject
  Set DeckPlateLimit1 = ObjPart.FindObjectByName(&quot;CROSS.40&quot;)
  Dim DeckPlateLimitRef1 As Reference
  Set DeckPlateLimitRef1 = ObjPart.CreateReferenceFromObject(DeckPlateLimit1)
   
  Dim DeckPlateOrnt1 As Long
  DeckPlateOrnt1 = 2
  DeckSuperplate.AddLimit DeckPlateLimitRef1, DeckPlateOrnt1
  
  Dim DeckPlateLimit2 As AnyObject
  Set DeckPlateLimit2 = ObjPart.FindObjectByName(&quot;CROSS.140&quot;)
  Dim DeckPlateLimitRef2 As Reference
  Set DeckPlateLimitRef2 = ObjPart.CreateReferenceFromObject(DeckPlateLimit2)
   
  Dim DeckPlateOrnt2 As Long
  DeckPlateOrnt2 = 3
  DeckSuperplate.AddLimit DeckPlateLimitRef2, DeckPlateOrnt2
  
  &#39;Limiting DeckPlate by ShellPlate
  Dim DeckPlateOrnt3 As Long
  DeckPlateOrnt3 = 8
  DeckSuperplate.AddLimit ShellSupportRef, DeckPlateOrnt3

  &#39;SETTING MATERIAL,GRADE AND THICKNESS OF DECKPLATE
  Dim DeckPlateObj As SfmObject
  Set DeckPlateObj = DeckSuperplate
  DeckPlateObj.Material = &quot;Steel&quot;
  DeckPlateObj.Grade = &quot;A45&quot;
  DeckSuperplate.Thickness = &quot;25.0&quot;
  DeckSuperplate.Run
  ...</pre>
				</td>
			</tr>
		</table>
		<!-- -------------------------------comment---------------------------------- -->
		<h4><a name="Step10">Creating an Advanced Transverse Bulkhead</a></h4>
		<table class="code">
			<tr>
				<td width="100%">
				<pre>  ...
  &#39;Defining Support for Transverse Bulkhead Plate
  Dim TrnsPlateSupport As AnyObject
  Set TrnsPlateSupport = ObjPart.FindObjectByName(&quot;CROSS.90&quot;)
  Dim TrnsPlateSupportRef As Reference
  Set TrnsPlateSupportRef = ObjPart.CreateReferenceFromObject(TrnsPlateSupport)

  &#39;Creating SuperPlate
  Dim TrnsSuperplate As SfmSuperPlate
  Set TrnsSuperplate = FactoryObj.AddAdvSuperPlate(&quot;TransversePanel&quot;, TrnsPlateSupportRef, Nothing)

  &#39;Applying Limits
  &#39;First Limiting by ShellPlates
  Dim TrnsPlateLimitRef1 As Reference
  Set TrnsPlateLimitRef1 = ObjPart.CreateReferenceFromObject(ShellSuperplate1)
  Dim TrnsPlateOrnt1 As Long
  TrnsPlateOrnt1 = 4
  TrnsSuperplate.AddLimit TrnsPlateLimitRef1, TrnsPlateOrnt1
  Dim TrnsPlateLimitRef2 As Reference
  Set TrnsPlateLimitRef2 = ObjPart.CreateReferenceFromObject(ShellSuperplate2)
  Dim TrnsPlateOrnt2 As Long
  TrnsPlateOrnt2 = 5
  TrnsSuperplate.AddLimit TrnsPlateLimitRef2, TrnsPlateOrnt2

  &#39;Second Limiting by DeckPlate
  Dim TrnsPlateLimitRef3 As Reference
  Set TrnsPlateLimitRef3 = ObjPart.CreateReferenceFromObject(DeckSuperplate)
  Dim TrnsPlateOrnt3 As Long
  TrnsPlateOrnt3 = 7
  TrnsSuperplate.AddLimit TrnsPlateLimitRef3, TrnsPlateOrnt3
  TrnsSuperplate.Run
  ...</pre>
				</td>
			</tr>
		</table>
		<!-- -------------------------------comment---------------------------------- -->
		<h4><a name="Step11">Updating the Part Document</a></h4>
		<p>The Part has to be updated to generate the geometrical representation 
		of the created objects. Once this done, the updated objects are visible 
		in the 3D window and in the specification tree.</p>
		<table class="code">
			<tr>
				<td width="100%">
				<pre> ...
 &#39;To Update CATIA Part Document
 ObjPart.Update
End Sub</pre>
				</td>
			</tr>
		</table>
		</td>
	</tr>
	<tr>
		<td width="7%" valign="top"></td>
		<td width="93%">
		<p align="center">
		<img alt="" src="../CAAScrBase/images/aendtask.gif" width="64" height="32"></p>
		</td>
	</tr>
	<!-- -------------------------------comment---------------------------------- -->
</table>
<p align="right">[<a href="#Top">Top</a>]</p>
<hr>
<!-- -------------------------------comment---------------------------------- -->
<h4><a name="InShort"></a>In Short</h4>
<p>This use case has shown how to create plate objects.</p>
<hr>
<!-- -------------------------------comment---------------------------------- -->
<h4><a name="References"></a>References</h4>
<table border="0" width="100%">
	<tr>
		<td valign="top">[1]</td>
		<td><a href="../CAAScdInfUseCases/CAAInfLauchMacro.htm">Replaying a Macro</a></td>
	</tr>
	<tr>
		<td valign="top">[2]</td>
		<td><a href="../CAAScdInfUseCases/CAAInfOpenDocument.htm">Opening an Existing CATIA Document</a></td>
	</tr>
	<tr>
		<td colspan="2" align="right">[<a href="#Top">Top</a>]</td>
	</tr>
</table>
<hr>
<!-- -------------------------------comment---------------------------------- -->
<p><i>Copyright © 1999-2011, Dassault Systèmes. All rights reserved.</i></p>

</body>

</html>
