<html>
<head>
 <meta name="Generator" content="mihGene v1.1">
 <meta http-equiv="Expires" content="Tue, 04 Dec 1993 21:29:02 GMT">
 <title>GSMInterfaces HybridShapeLinePtPt (Object)</title>
<link rel="Stylesheet" type="text/css" href="../../../caav5.css">
</head>
<body>
<pre><a href="../main.htm">All Frameworks</a>  <a href="../tree.htm">Object Hierarchy</a>  <a href="../GSMInterfaces.htm">This Framework</a>  <a href=".htm">Previous</a>  <a href="interface_HybridShapeLineTangency_109970.htm">Next</a>  <a href="../CAAHomeIdx.htm">Indexes</a>  </pre>
<hr>
<h1>HybridShapeLinePtPt<font size=-1> (Object)</font></h1>
<pre>
<a href="../System/interface_IUnknown_14460.htm">IUnknown</a>
  |
  +---<a href="../System/interface_IDispatch_17333.htm">IDispatch</a>
    |
    +---<a href="../System/interface_CATBaseUnknown_40786.htm">CATBaseUnknown</a>
      |
      +---<a href="../System/interface_CATBaseDispatch_45333.htm">CATBaseDispatch</a>
        |
        +---<a href="../System/interface_AnyObject_17321.htm">AnyObject</a>
          |
          +---<a href="../MecModInterfaces/interface_HybridShape_25589.htm">HybridShape</a>
            |
            +---<a href="../GSMInterfaces/interface_Line_3608.htm">Line</a>
              |
              +---HybridShapeLinePtPt
 </pre>
<hr><br>
<b><i> Represents the hybrid shape line between two points feature object.</i></b><br>

 <b>Role</b>: To access the data of the line feature created between two points.
 <p>Use the  CATIAHybridShapeFactory to create a HybridShapeLinePtPt object.
 <dl>
  <dt> <b>See also:</b> 
  <dd> <a href="../InfInterfaces/interface_Reference_17481.htm">Reference</a>
  <dt> <b>See also:</b> 
  <dd> <a href="../KnowledgeInterfaces/interface_Length_8108.htm">Length</a>
  <dt> <b>See also:</b> 
  <dd> <a href="../GSMInterfaces/interface_HybridShapeFactory_68680.htm">HybridShapeFactory</a>
</dl>
<hr>
<dl>
 <h2><a name="PropertyIndex"></a>Property Index</h2>
 <dt>
    <a href="#BeginOffset"><b>BeginOffset</b></a>
<dd>  Returns the start length of the line.
 <dt>
    <a href="#EndOffset"><b>EndOffset</b></a>
<dd>  Returns the end length of the line.
 <dt>
    <a href="#PtExtremity"><b>PtExtremity</b></a>
<dd>  Returns or Sets the extremity point of the LinePtPt(Second Point).
 <dt>
    <a href="#PtOrigine"><b>PtOrigine</b></a>
<dd>  Returns or Sets the origin point of the LinePtPt(First point).
 <dt>
    <a href="#Support"><b>Support</b></a>
<dd>  Returns or Sets the supporting  surface.
</dl>
<dl>
 <h2><a name="MethodIndex"></a>Method Index</h2>
 <dt>
    <a href="#GetLengthType"><b>GetLengthType</b></a>
<dd>  Gets the length type
 Default is 0.
 <dt>
    <a href="#GetSymmetricalExtension"><b>GetSymmetricalExtension</b></a>
<dd>  Gets whether the symmetrical extension of the line is active.
 <dt>
    <a href="#RemoveSupport"><b>RemoveSupport</b></a>
<dd>  Removes the support surface.
 <dt>
    <a href="#SetLengthType"><b>SetLengthType</b></a>
<dd>  Sets the length type
 Default is 0.
 <dt>
    <a href="#SetSymmetricalExtension"><b>SetSymmetricalExtension</b></a>
<dd>  Sets the symmetrical extension of the line (start = -end).
</dl>
 <h2><a name="Properties"></a>Properties</h2> <br>
<a name="BeginOffset"><dt>

<table><tr><td>o Property <b>BeginOffset</b>(<td>) As <a href="../KnowledgeInterfaces/interface_Length_8108.htm">CATIALength</a>  (Read Only)</table></dt>
<dl>
  <dd>
 Returns the start length of the line.
 <br> Start length : extension of the line, beginning at the starting point
 <dl>
 <dt><b>Example</b>:
 <dd>
 This example retrieves in <code>oStart</code> the beginning offset length   
 for the <code>LinePtPt</code> hybrid shape feature.
 <pre>
 Dim oStart As  CATIALength 
 Set oStart = LinePtPt.<font color="red">BeginOffset</font>
 </pre>
 </dl>
</dl>
<a name="EndOffset"><dt>

<table><tr><td>o Property <b>EndOffset</b>(<td>) As <a href="../KnowledgeInterfaces/interface_Length_8108.htm">CATIALength</a>  (Read Only)</table></dt>
<dl>
  <dd>
 Returns the end length of the line.
 <br> End length : extension of the line, beginning at the ending point
 <dl>
 <dt><b>Example</b>:
 <dd>
 This example retrieves in <code>oEnd</code> the starting length   
 for the <code>LinePtPt</code> hybrid shape feature.
 <pre>
 Dim oEnd As  CATIALength 
 Set oEnd = LinePtPt.<font color="red">EndOffset</font>
 </pre>
 </dl>
</dl>
<a name="PtExtremity"><dt>

<table><tr><td>o Property <b>PtExtremity</b>(<td>) As <a href="../InfInterfaces/interface_Reference_17481.htm">CATIAReference</a> </table></dt>
<dl>
  <dd>
 Returns or Sets the extremity point of the LinePtPt(Second Point).
 <br>Sub-element(s) supported (see 
<a href="../MecModInterfaces/interface_Boundary_14542.htm">Boundary</a> object):  
<a href="../MecModInterfaces/interface_Vertex_8466.htm">Vertex</a>. <dl>
 <dt><b>Example</b>:
 <dd>
 This example retrieves in <code>oPtExtremity</code> the ending point 
 for the <code>LinePtPt</code> hybrid shape feature.
 <pre>
 Dim oPtExtremity As Reference 
 Set oPtExtremity = LinePtPt.<font color="red">PtExtremity</font>
 </pre>
 </dl>
</dl>
<a name="PtOrigine"><dt>

<table><tr><td>o Property <b>PtOrigine</b>(<td>) As <a href="../InfInterfaces/interface_Reference_17481.htm">CATIAReference</a> </table></dt>
<dl>
  <dd>
 Returns or Sets the origin point of the LinePtPt(First point).
 <br>Sub-element(s) supported (see 
<a href="../MecModInterfaces/interface_Boundary_14542.htm">Boundary</a> object):  
<a href="../MecModInterfaces/interface_Vertex_8466.htm">Vertex</a>. <dl>
 <dt><b>Example</b>:
 <dd>
 This example retrieves in <code>oPtOrigine</code> the initial point 
 for the <code>LinePtPt</code> hybrid shape feature.
 <pre>
 Dim oPtOrigine As Reference 
 Set oPtOrigine = LinePtPt.<font color="red">PtOrigine</font>
 </pre>
 </dl>
</dl>
<a name="Support"><dt>

<table><tr><td>o Property <b>Support</b>(<td>) As <a href="../InfInterfaces/interface_Reference_17481.htm">CATIAReference</a> </table></dt>
<dl>
  <dd>
 Returns or Sets the supporting  surface.
 <br> Note: the support surface is not mandatory for LinePtPt<br>
 <br>Sub-element(s) supported (see 
<a href="../MecModInterfaces/interface_Boundary_14542.htm">Boundary</a> object):  
<a href="../MecModInterfaces/interface_Face_3398.htm">Face</a>. <dl>
 <dt><b>Example</b>:
 <dd>
 This example retrieves in <code>oSurface</code> the supporting surface (if it exist)  
 for the <code>LinePtPt</code> hybrid shape feature.
 <pre>
 Dim oSurface As Reference 
 Set oSurface = LinePtPt.<font color="red">Surface</font>
 </pre>
 </dl>
</dl>
 <h2><a name="Methods"></a>Methods</h2> <br>
<a name="GetLengthType"><dt>

<table><tr><td>o Func <b>GetLengthType</b>(<td>) As long </table></dt>
<dl>
  <dd>
 Gets the length type
 Default is 0.
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> oType</tt>
   <dd>   The length type = 0 : length               - the line is limited by its extremities
                   = 1 : infinite             - the line is infinite
                   = 2 : infinite start point - the line is infinite on the side of the start point
                   = 3 : infinite end point   - the line is infinite on the side of the end point</dd>
</dl>
</dl>
</dl>
<a name="GetSymmetricalExtension"><dt>

<table><tr><td>o Func <b>GetSymmetricalExtension</b>(<td>) As boolean </table></dt>
<dl>
  <dd>
 Gets whether the symmetrical extension of the line is active.
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> oSym</tt>
   <dd>       Symetry flag</dd>
</dl>
</dl>
</dl>
<a name="RemoveSupport"><dt>

<table><tr><td>o Sub <b>RemoveSupport</b>(<td>)</table></dt>
<dl>
  <dd>
 Removes the support surface.
</dl>
<a name="SetLengthType"><dt>

<table><tr><td>o Sub <b>SetLengthType</b>(<td>long <td><tt>iType</tt>)</table></dt>
<dl>
  <dd>
 Sets the length type
 Default is 0.
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iType</tt>
   <dd>   The length type = 0 : length               - the line is limited by its extremities
                   = 1 : infinite             - the line is infinite
                   = 2 : infinite start point - the line is infinite on the side of the start point
                   = 3 : infinite end point   - the line is infinite on the side of the end point</dd>
</dl>
</dl>
</dl>
<a name="SetSymmetricalExtension"><dt>

<table><tr><td>o Sub <b>SetSymmetricalExtension</b>(<td>boolean <td><tt>iSym</tt>)</table></dt>
<dl>
  <dd>
 Sets the symmetrical extension of the line (start = -end).
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iSym</tt>
   <dd>       Symetry flag</dd>
</dl>
</dl>
</dl>

</body>
<hr><p><i>
Copyright &#169; 2003, Dassault Syst&#232;mes. All rights reserved.</i></p>
</html>
