<html>
<head>
 <meta name="Generator" content="mihGene v1.1">
 <meta http-equiv="Expires" content="Tue, 04 Dec 1993 21:29:02 GMT">
 <title>GSMInterfaces HybridShapePointOnPlane (Object)</title>
<link rel="Stylesheet" type="text/css" href="../../../caav5.css">
</head>
<body>
<pre><a href="../main.htm">All Frameworks</a>  <a href="../tree.htm">Object Hierarchy</a>  <a href="../GSMInterfaces.htm">This Framework</a>  <a href=".htm">Previous</a>  <a href="interface_HybridShapePointOnSurface_129465.htm">Next</a>  <a href="../CAAHomeIdx.htm">Indexes</a>  </pre>
<hr>
<h1>HybridShapePointOnPlane<font size=-1> (Object)</font></h1>
<pre>
<a href="../System/interface_IUnknown_14460.htm">IUnknown</a>
  |
  +---<a href="../System/interface_IDispatch_17333.htm">IDispatch</a>
    |
    +---<a href="../System/interface_CATBaseUnknown_40786.htm">CATBaseUnknown</a>
      |
      +---<a href="../System/interface_CATBaseDispatch_45333.htm">CATBaseDispatch</a>
        |
        +---<a href="../System/interface_AnyObject_17321.htm">AnyObject</a>
          |
          +---<a href="../MecModInterfaces/interface_HybridShape_25589.htm">HybridShape</a>
            |
            +---<a href="../GSMInterfaces/interface_Point_5884.htm">Point</a>
              |
              +---HybridShapePointOnPlane
 </pre>
<hr><br>
<b><i> Point on a plane.</i></b><br>

 <b>Role</b>:  Allows to access data of the point feature created on
 a plane with a reference point or not.
 <dl>
  <dt> <b>See also:</b> 
  <dd> <a href="../KnowledgeInterfaces/interface_Length_8108.htm">Length</a>, <a href="../InfInterfaces/interface_Reference_17481.htm">Reference</a>, <a href="../GSMInterfaces/interface_HybridShapeDirection_84226.htm">HybridShapeDirection</a>, <a href="../GSMInterfaces/interface_HybridShapeFactory_68680.htm">HybridShapeFactory</a>
</dl>
<hr>
<dl>
 <h2><a name="PropertyIndex"></a>Property Index</h2>
 <dt>
    <a href="#FirstDirection"><b>FirstDirection</b></a>
<dd>  Returns or sets the first direction on the plane to compute the point (for stability).
 <dt>
    <a href="#Plane"><b>Plane</b></a>
<dd>  Returns or sets the support plane.
 <dt>
    <a href="#Point"><b>Point</b></a>
<dd>  Returns or sets the reference point.
 <dt>
    <a href="#ProjectionSurface"><b>ProjectionSurface</b></a>
<dd>  Returns or sets the projection surface to compute the point.
 <dt>
    <a href="#XOffset"><b>XOffset</b></a>
<dd>  Returns the X cartesian coordinate in the plane.
 <dt>
    <a href="#YOffset"><b>YOffset</b></a>
<dd>  Returns the Y cartesian coordinate in the plane.
</dl>
<dl>
 <h2><a name="MethodIndex"></a>Method Index</h2>
 <dt>
    <a href="#GetSecondDirection"><b>GetSecondDirection</b></a>
<dd>  Gets the second direction on the plane to compute the point (for stability).
 <dt>
    <a href="#SetSecondDirection"><b>SetSecondDirection</b></a>
<dd>  Sets the second direction on the plane to compute the point (for stability).
</dl>
 <h2><a name="Properties"></a>Properties</h2> <br>
<a name="FirstDirection"><dt>

<table><tr><td>o Property <b>FirstDirection</b>(<td>) As <a href="../GSMInterfaces/interface_HybridShapeDirection_84226.htm">CATIAHybridShapeDirection</a> </table></dt>
<dl>
  <dd>
 Returns or sets the first direction on the plane to compute the point (for stability).
 <dl>
 <dt>Example</dt>:
 <dd>
 This example retrieves in <code>oDirection</code> the direction of the <code>PointOnPlane</code> feature.
 <pre>
 Dim oDirection As CATIAHybridShapeDirection
 Set oDirection = PointOnPlane.<font color="red">FirstDirection</font>
 </pre>
 </dl>
</dl>
<a name="Plane"><dt>

<table><tr><td>o Property <b>Plane</b>(<td>) As <a href="../InfInterfaces/interface_Reference_17481.htm">CATIAReference</a> </table></dt>
<dl>
  <dd>
 Returns or sets the support plane.
 <br>Sub-element(s) supported (see 
<a href="../MecModInterfaces/interface_Boundary_14542.htm">Boundary</a> object):  
<a href="../MecModInterfaces/interface_PlanarFace_20456.htm">PlanarFace</a>. <dl>
 <dt>Example</dt>:
 <dd>
 This example retrieves in <code>oPlane</code> the supporting Plane for <code>PointOnPlane</code> feature.
 <pre>
 Dim oPlane As CATIAReference
 Set oPlane  = PointOnPlane.<font color="red">Plane</font>
 </pre>
 </dl>
</dl>
<a name="Point"><dt>

<table><tr><td>o Property <b>Point</b>(<td>) As <a href="../InfInterfaces/interface_Reference_17481.htm">CATIAReference</a> </table></dt>
<dl>
  <dd>
 Returns or sets the reference point. 
 <br>  This data is not mandatory, if Point is
 <br>  null, the projection of the origin point on the plane is taken.
 <br>Sub-element(s) supported (see 
<a href="../MecModInterfaces/interface_Boundary_14542.htm">Boundary</a> object):  
<a href="../MecModInterfaces/interface_Vertex_8466.htm">Vertex</a>. <dl>
 <dt>Example</dt>:
 <dd>
 This example retrieves in <code>oPoint</code> the reference point for <code>PointOnPlane</code> feature.
 <pre>
 Dim oPoint As CATIAReference
 Set oPoint  = PointOnPlane.<font color="red">Point</font>
 </pre>
 </dl>
</dl>
<a name="ProjectionSurface"><dt>

<table><tr><td>o Property <b>ProjectionSurface</b>(<td>) As <a href="../InfInterfaces/interface_Reference_17481.htm">CATIAReference</a> </table></dt>
<dl>
  <dd>
 Returns or sets the projection surface to compute the point.
 <dl>
 <dt>Example</dt>:
 <dd>
 This example retrieves in <code>oProjSur</code> the projection surface of the <code>PointOnPlane</code> feature.
 <pre>
 Dim oProjSur As CATIAReference
 Set oProjSur = PointOnPlane.<font color="red">ProjectionSurface</font>
 </pre>
 </dl>
</dl>
<a name="XOffset"><dt>

<table><tr><td>o Property <b>XOffset</b>(<td>) As <a href="../KnowledgeInterfaces/interface_Length_8108.htm">CATIALength</a>  (Read Only)</table></dt>
<dl>
  <dd>
 Returns the X cartesian coordinate in the plane.
 <dl>
 <dt>Example</dt>:
 <dd>
 This example retrieves in <code>oX</code> the X coordinate for <code>PointOnPlane</code> feature.
 <pre>
 Dim oX As  CATIALength
 Set oX  = PointOnPlane.<font color="red">XOffset</font>
 </pre>
 </dl>
</dl>
<a name="YOffset"><dt>

<table><tr><td>o Property <b>YOffset</b>(<td>) As <a href="../KnowledgeInterfaces/interface_Length_8108.htm">CATIALength</a>  (Read Only)</table></dt>
<dl>
  <dd>
 Returns the Y cartesian coordinate in the plane.
 <dl>
 <dt>Example</dt>:
 <dd>
 This example retrieves in <code>oY</code> the Y coordinate for <code>PointOnPlane</code> feature.
 <pre>
 Dim oY As  CATIALength
 Set oY  = PointOnPlane.<font color="red">YOffset</font>
 </pre>
 </dl>
</dl>
 <h2><a name="Methods"></a>Methods</h2> <br>
<a name="GetSecondDirection"><dt>

<table><tr><td>o Sub <b>GetSecondDirection</b>(<td>double <td><tt>oDirX</tt>,<tr><td></td><td>double <td><tt>oDirY</tt>,<tr><td></td><td>double <td><tt>oDirZ</tt>)</table></dt>
<dl>
  <dd>
 Gets the second direction on the plane to compute the point (for stability).
 <br>This direction has to be kept perpendicular to the first direction
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> oDir</tt>
   <dd>      second direction
      </dd>
</dl>
  <dt> <b>See also:</b> 
  <dd> <a href="../GSMInterfaces/interface_HybridShapeDirection_84226.htm">HybridShapeDirection</a>
</dl>
</dl>
<a name="SetSecondDirection"><dt>

<table><tr><td>o Sub <b>SetSecondDirection</b>(<td>double <td><tt>iDirX</tt>,<tr><td></td><td>double <td><tt>iDirY</tt>,<tr><td></td><td>double <td><tt>iDirZ</tt>)</table></dt>
<dl>
  <dd>
 Sets the second direction on the plane to compute the point (for stability).
 <br>This direction has to be kept perpendicular to the first direction
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iDir</tt>
   <dd>      second direction
      </dd>
</dl>
  <dt> <b>See also:</b> 
  <dd> <a href="../GSMInterfaces/interface_HybridShapeDirection_84226.htm">HybridShapeDirection</a>
</dl>
</dl>

</body>
<hr><p><i>
Copyright &#169; 2003, Dassault Syst&#232;mes. All rights reserved.</i></p>
</html>
