<html>
<head>
 <meta name="Generator" content="mihGene v1.1">
 <meta http-equiv="Expires" content="Tue, 04 Dec 1993 21:29:02 GMT">
 <title>GSMInterfaces HybridShapeCircle2PointsRad (Object)</title>
<link rel="Stylesheet" type="text/css" href="../../../caav5.css">
</head>
<body>
<pre><a href="../main.htm">All Frameworks</a>  <a href="../tree.htm">Object Hierarchy</a>  <a href="../GSMInterfaces.htm">This Framework</a>  <a href=".htm">Previous</a>  <a href="interface_HybridShapeCircle3Points_117560.htm">Next</a>  <a href="../CAAHomeIdx.htm">Indexes</a>  </pre>
<hr>
<h1>HybridShapeCircle2PointsRad<font size=-1> (Object)</font></h1>
<pre>
<a href="../System/interface_IUnknown_14460.htm">IUnknown</a>
  |
  +---<a href="../System/interface_IDispatch_17333.htm">IDispatch</a>
    |
    +---<a href="../System/interface_CATBaseUnknown_40786.htm">CATBaseUnknown</a>
      |
      +---<a href="../System/interface_CATBaseDispatch_45333.htm">CATBaseDispatch</a>
        |
        +---<a href="../System/interface_AnyObject_17321.htm">AnyObject</a>
          |
          +---<a href="../MecModInterfaces/interface_HybridShape_25589.htm">HybridShape</a>
            |
            +---<a href="../GSMInterfaces/interface_HybridShapeCircle_59719.htm">HybridShapeCircle</a>
              |
              +---HybridShapeCircle2PointsRad
 </pre>
<hr><br>
<b><i> Represents the hybrid shape circle object defined using two points and a radius.</i></b><br>

 <b>Role</b>: To access the data of the hybrid shape circle object.
 <p>This data includes:
 <ul>
 <li>The circle two passing points</li>
 <li>The circle radius</li>
 <li>The surface that supports the circle</li>
 <li>The circle orientation</li>
 </ul>
 <p>Use the CATIAHybridShapeFactory to create a HybridShapeCircle2PointsRad object.
 <dl>
  <dt> <b>See also:</b> 
  <dd> <a href="../GSMInterfaces/interface_HybridShapeFactory_68680.htm">HybridShapeFactory</a>
</dl>
<hr>
<dl>
 <h2><a name="PropertyIndex"></a>Property Index</h2>
 <dt>
    <a href="#Diameter"><b>Diameter</b></a>
<dd>  Returns the circle diameter.
 <dt>
    <a href="#DiameterMode"><b>DiameterMode</b></a>
<dd>   Returns or sets the DiameterMode.
 <dt>
    <a href="#Orientation"><b>Orientation</b></a>
<dd>  Returns or sets the circle orientation.
 <dt>
    <a href="#Pt1"><b>Pt1</b></a>
<dd>  Returns or sets the circle first passing point.
 <dt>
    <a href="#Pt2"><b>Pt2</b></a>
<dd>  Returns or sets the circle second passing point.
 <dt>
    <a href="#Radius"><b>Radius</b></a>
<dd>  Returns the circle radius.
 <dt>
    <a href="#Support"><b>Support</b></a>
<dd>  Returns or sets the circle support surface.
</dl>
<dl>
 <h2><a name="MethodIndex"></a>Method Index</h2>
 <dt>
    <a href="#IsGeodesic"><b>IsGeodesic</b></a>
<dd>  Queries whether the circle is geodesic or not.
 <dt>
    <a href="#SetGeometryOnSupport"><b>SetGeometryOnSupport</b></a>
<dd>  Sets GeometryOnSupport of circle.
 <dt>
    <a href="#UnsetGeometryOnSupport"><b>UnsetGeometryOnSupport</b></a>
<dd>  Inactivates GeometryOnSupport of circle.
</dl>
 <h2><a name="Properties"></a>Properties</h2> <br>
<a name="Diameter"><dt>

<table><tr><td>o Property <b>Diameter</b>(<td>) As <a href="../KnowledgeInterfaces/interface_Length_8108.htm">CATIALength</a>  (Read Only)</table></dt>
<dl>
  <dd>
 Returns the circle diameter.
 It is expressed as a 
<a href="../KnowledgeInterfaces/interface_Length_8108.htm">Length</a> literal. Succeeds only if DiameterMode is set to True. </dl>
 <dt><b>Example</b>:
 <dd>
 This example retrieves in <code>HybShpCircleDiameter</code> the diameter
 of the <code>HybShpCircle</code> hybrid shape circle feature
 <pre>
 Dim HybShpCircleDiameter As Length
 HybShpCircleDiameter = HybShpCircle.<font color="red">Diameter</font>
 </pre>
 </dl>
</dl>
<a name="DiameterMode"><dt>

<table><tr><td>o Property <b>DiameterMode</b>(<td>) As boolean </table></dt>
<dl>
  <dd>
  Returns or sets the DiameterMode.
 <br><b>Legal values</b>: <b>True</b> implies diameter
 <b>False</b> implies radius (default).
  When DiameterMode is changed, Radius/Diameter value, which is stored will not be modified.
  
<dl>
  <dt> <b>Example:</b> 
  <dd>   This example sets that the DiameterMode of
  the <code>HybShpCircle</code> hybrid shape circle feature
  <pre>
  HybShpCircle.<font color="red">DiameterMode</font> = True
  </pre>
</dl>
</dl>
<a name="Orientation"><dt>

<table><tr><td>o Property <b>Orientation</b>(<td>) As long </table></dt>
<dl>
  <dd>
 Returns or sets the circle orientation.
 <br><b>Role</b>: The circle orientation indicates which side of the line made up
 using the two passing points is used to create the major part of the circle.
 It is determined using the cross product of the normal to the suppport
 and the vector made up using the two passing points (Pt1-Pt2).
 <br><b>Legal values</b>: 1 to state that the major part of the circle is or
 should be created on the side of the line shown by the vector resulting from this
 cross product, and -1 otherwise.
 <dl>
 <dt><b>Example</b>:
 <dd>
 This example retrieves in <code>HybShpCircleOrientation</code> the orientation
 of the <code>HybShpCircle</code> hybrid shape circle.
 <pre>
 HybShpCircleOrientation = HybShpCircle.<font color="red">Orientation</font>
 </pre>
 </dl>
</dl>
<a name="Pt1"><dt>

<table><tr><td>o Property <b>Pt1</b>(<td>) As <a href="../InfInterfaces/interface_Reference_17481.htm">CATIAReference</a> </table></dt>
<dl>
  <dd>
 Returns or sets the circle first passing point.
 <br>Sub-element(s) supported (see 
<a href="../MecModInterfaces/interface_Boundary_14542.htm">Boundary</a> object):  
<a href="../MecModInterfaces/interface_Vertex_8466.htm">Vertex</a>. <dl>
 <dt><b>Example</b>:
 <dd>
 This example retrieves the first passing point
 of the <code>HybShpCircle</code> hybrid shape circle
 in <code>HybShpCircleFirstPassingPoint</code> point.
 <pre>
 Dim HybShpCircleFirstPassingPoint As Reference
 Set HybShpCircleFirstPassingPoint = HybShpCircle.<font color="red">Pt1</font>
 </pre>
 </dl>
</dl>
<a name="Pt2"><dt>

<table><tr><td>o Property <b>Pt2</b>(<td>) As <a href="../InfInterfaces/interface_Reference_17481.htm">CATIAReference</a> </table></dt>
<dl>
  <dd>
 Returns or sets the circle second passing point.
 <br>Sub-element(s) supported (see 
<a href="../MecModInterfaces/interface_Boundary_14542.htm">Boundary</a> object):  
<a href="../MecModInterfaces/interface_Vertex_8466.htm">Vertex</a>. <dl>
 <dt><b>Example</b>:
 <dd>
 This example sets the second passing point
 of the <code>HybShpCircle</code> hybrid shape circle
 as the <code>Point12</code> point.
 <pre>
 HybShpCircle.<font color="red">Pt2</font> Point12
 </pre>
 </dl>
</dl>
<a name="Radius"><dt>

<table><tr><td>o Property <b>Radius</b>(<td>) As <a href="../KnowledgeInterfaces/interface_Length_8108.htm">CATIALength</a>  (Read Only)</table></dt>
<dl>
  <dd>
 Returns the circle radius.
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> Radius</tt>
   <dd>    The circle radius, expressed as a </dd>
</dl>
<a href="../KnowledgeInterfaces/interface_Length_8108.htm">Length</a> literal. Succeeds only if DiameterMode is set to False. </dl>
 <dt><b>Example</b>:
 <dd>
 This example retrieves in <code>HybShpCircleRadius</code> the radius
 of the <code>HybShpCircle</code> hybrid shape circle.
 <pre>
 Dim HybShpCircleRadius As Length
 HybShpCircleRadius = HybShpCircle.<font color="red">Radius</font>
 </pre>
 </dl>
</dl>
</dl>
<a name="Support"><dt>

<table><tr><td>o Property <b>Support</b>(<td>) As <a href="../InfInterfaces/interface_Reference_17481.htm">CATIAReference</a> </table></dt>
<dl>
  <dd>
 Returns or sets the circle support surface.
 <br>Sub-element(s) supported (see 
<a href="../MecModInterfaces/interface_Boundary_14542.htm">Boundary</a> object):  
<a href="../MecModInterfaces/interface_Face_3398.htm">Face</a>. <dl>
 <dt><b>Example</b>:
 <dd>
 This example retrieves in <code>HybShpCircleSupportSurf</code> the support surface
 of the <code>HybShpCircle</code> hybrid shape circle.
 <pre>
 Dim HybShpCircleSupportSurf As Reference 
 HybShpCircleSupportSurf = HybShpCircle.<font color="red">Support</font>
 </pre>
 </dl>
</dl>
 <h2><a name="Methods"></a>Methods</h2> <br>
<a name="IsGeodesic"><dt>

<table><tr><td>o Func <b>IsGeodesic</b>(<td>) As boolean </table></dt>
<dl>
  <dd>
 Queries whether the circle is geodesic or not.
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> oGeod</tt>
   <dd>       geodesic type : when TRUE, the circle is geodesic.</dd>
</dl>
</dl>
</dl>
<a name="SetGeometryOnSupport"><dt>

<table><tr><td>o Sub <b>SetGeometryOnSupport</b>(<td>)</table></dt>
<dl>
  <dd>
 Sets GeometryOnSupport of circle. 
 <br> It puts the circle on the surface.
      S_OK if OK, E_FAIL if fail
</dl>
<a name="UnsetGeometryOnSupport"><dt>

<table><tr><td>o Sub <b>UnsetGeometryOnSupport</b>(<td>)</table></dt>
<dl>
  <dd>
 Inactivates GeometryOnSupport of circle. 
 <br>Note: The circle becomes euclidean.
</dl>

</body>
<hr><p><i>
Copyright &#169; 2003, Dassault Syst&#232;mes. All rights reserved.</i></p>
</html>
