<html>
<head>
 <meta name="Generator" content="mihGene v1.1">
 <meta http-equiv="Expires" content="Tue, 04 Dec 1993 21:29:02 GMT">
 <title>GSMInterfaces HybridShapeCylinder (Object)</title>
<link rel="Stylesheet" type="text/css" href="../../../caav5.css">
</head>
<body>
<pre><a href="../main.htm">All Frameworks</a>  <a href="../tree.htm">Object Hierarchy</a>  <a href="../GSMInterfaces.htm">This Framework</a>  <a href=".htm">Previous</a>  <a href="interface_HybridShapeDevelop_68134.htm">Next</a>  <a href="../CAAHomeIdx.htm">Indexes</a>  </pre>
<hr>
<h1>HybridShapeCylinder<font size=-1> (Object)</font></h1>
<pre>
<a href="../System/interface_IUnknown_14460.htm">IUnknown</a>
  |
  +---<a href="../System/interface_IDispatch_17333.htm">IDispatch</a>
    |
    +---<a href="../System/interface_CATBaseUnknown_40786.htm">CATBaseUnknown</a>
      |
      +---<a href="../System/interface_CATBaseDispatch_45333.htm">CATBaseDispatch</a>
        |
        +---<a href="../System/interface_AnyObject_17321.htm">AnyObject</a>
          |
          +---<a href="../MecModInterfaces/interface_HybridShape_25589.htm">HybridShape</a>
            |
            +---HybridShapeCylinder
 </pre>
<hr><br>
<b><i> Represents the hybrid shape Cylinder feature object.</i></b><br>

 <b>Role</b>: To access the data of the hybrid shape Cylinder feature object.
 This data includes:
 <ul>
 <li>The center of the Cylinder </li>
 <li>The Radius of the Cylinder </li>
 <li>Length of Cylinder in the given extrusion direction </li>
 <li>Length of Cylinder opposite to extrusion direction</li>
 <li>Direction of extrusion for cylinder. </li>
 </ul>
 <p>Use the  CATIAHybridShapeFactory to create a HybridShapeCylinder object.
 <dl>
  <dt> <b>See also:</b> 
  <dd> <a href="../GSMInterfaces/interface_HybridShapeFactory_68680.htm">HybridShapeFactory</a>
</dl>
<hr>
<dl>
 <h2><a name="PropertyIndex"></a>Property Index</h2>
 <dt>
    <a href="#Center"><b>Center</b></a>
<dd>  Returns or sets the center of the cylinder object.
 <dt>
    <a href="#Direction"><b>Direction</b></a>
<dd>  Returns or sets the direction of the cylinder object.
 <dt>
    <a href="#Length1"><b>Length1</b></a>
<dd>  Returns or sets the length of the cylinder object in the given extrusion direction.
 <dt>
    <a href="#Length2"><b>Length2</b></a>
<dd>  Returns or sets the length of the cylinder object in the opposite direction of given extrusion direction.
 <dt>
    <a href="#Orientation"><b>Orientation</b></a>
<dd>  Returns or sets the the inversion of extrusion direction.
 <dt>
    <a href="#Radius"><b>Radius</b></a>
<dd>  Returns or sets the radius of the cylinder object.
</dl>
<dl>
 <h2><a name="MethodIndex"></a>Method Index</h2>
 <dt>
    <a href="#InvertOrientation"><b>InvertOrientation</b></a>
<dd>  Inverts the Orientation of Cylinder object.
</dl>
 <h2><a name="Properties"></a>Properties</h2> <br>
<a name="Center"><dt>

<table><tr><td>o Property <b>Center</b>(<td>) As <a href="../InfInterfaces/interface_Reference_17481.htm">CATIAReference</a> </table></dt>
<dl>
  <dd>
 Returns or sets the center of the cylinder object.
 <dl>
 <dt><b>Example</b>:
 <dd>
 This example retrieves in <code>CylinderCenter</code> the center of the Cylinder,
 for the <code>Cylinder</code> hybrid shape feature.
 <pre>
 Dim CylinderCenter As Reference 
 Set CylinderCenter = Cylinder.<font color="red">Center</font>
 </pre>
 </dl>
</dl>
<a name="Direction"><dt>

<table><tr><td>o Property <b>Direction</b>(<td>) As <a href="../GSMInterfaces/interface_HybridShapeDirection_84226.htm">CATIAHybridShapeDirection</a> </table></dt>
<dl>
  <dd>
 Returns or sets the direction of the cylinder object.
 <dl>
 <dt><b>Example</b>:
 <dd>
 This example retrieves in <code>CylinderDirection</code> the direction of extrusion of the Cylinder,
 for the <code>Cylinder</code> hybrid shape feature.
 <pre>
 Dim CylinderDirection As HybridShapeDirection 
 Set CylinderDirection = Cylinder.<font color="red">Direction</font>
 </pre>
 </dl>
</dl>
<a name="Length1"><dt>

<table><tr><td>o Property <b>Length1</b>(<td>) As <a href="../KnowledgeInterfaces/interface_Length_8108.htm">CATIALength</a> </table></dt>
<dl>
  <dd>
 Returns or sets the length of the cylinder object in the given extrusion direction.
 <dl>
 <dt><b>Example</b>:
 <dd>
 This example retrieves in <code>CylinderLength1</code> the length of the Cylinder in the given
 extrusion direction, for the <code>Cylinder</code> hybrid shape feature.
 <pre>
 Dim CylinderLength1 As Length
 Set CylinderLength1 = Cylinder.<font color="red">Length1</font>
 </pre>
 </dl>
</dl>
<a name="Length2"><dt>

<table><tr><td>o Property <b>Length2</b>(<td>) As <a href="../KnowledgeInterfaces/interface_Length_8108.htm">CATIALength</a> </table></dt>
<dl>
  <dd>
 Returns or sets the length of the cylinder object in the opposite direction of given extrusion direction.
 <dl>
 <dt><b>Example</b>:
 <dd>
 This example retrieves in <code>CylinderLength2</code> the length of the Cylinder in the opposite direction 
 of the given extrusion direction, for the <code>Cylinder</code> hybrid shape feature.
 <pre>
 Dim CylinderLength2 As Length
 Set CylinderLength2 = Cylinder.<font color="red">Length2</font>
 </pre>
 </dl>
</dl>
<a name="Orientation"><dt>

<table><tr><td>o Property <b>Orientation</b>(<td>boolean <td><tt>iOrientation</tt>)</table></dt>
<dl>
  <dd>
 Returns or sets the the inversion of extrusion direction.
 <dl>
 <dt><b>Example</b>:
 <dd>
 This example retrieves in <code>IsInverted</code> the inversion status of extrusion direction 
 for the <code>Cylinder</code> hybrid shape feature.
 <pre>
 Dim IsInverted As boolean
 Set IsInverted = Cylinder.<font color="red">Orientation</font>
 </pre>
 </dl>
</dl>
<a name="Radius"><dt>

<table><tr><td>o Property <b>Radius</b>(<td>) As <a href="../KnowledgeInterfaces/interface_Length_8108.htm">CATIALength</a> </table></dt>
<dl>
  <dd>
 Returns or sets the radius of the cylinder object.
 <dl>
 <dt><b>Example</b>:
 <dd>
 This example retrieves in <code>CylinderRadius</code> the radius of the Cylinder,
 for the <code>Cylinder</code> hybrid shape feature.
 <pre>
 Dim CylinderRadius As Length
 Set CylinderRadius = Cylinder.<font color="red">Radius</font>
 </pre>
 </dl>
</dl>
 <h2><a name="Methods"></a>Methods</h2> <br>
<a name="InvertOrientation"><dt>

<table><tr><td>o Sub <b>InvertOrientation</b>(<td>)</table></dt>
<dl>
  <dd>
 Inverts the Orientation of Cylinder object.
 <dl>
 <dt><b>Example</b>:
 <dd>
 This example inverts the orientation for the <code>Cylinder</code> hybrid shape feature.
 <pre>
 Cylinder.<font color="red">InvertOrientation</font>
 </pre>
 </dl>
</dl>

</body>
<hr><p><i>
Copyright &#169; 2003, Dassault Syst&#232;mes. All rights reserved.</i></p>
</html>
