<html>
<head>
 <meta name="Generator" content="mihGene v1.1">
 <meta http-equiv="Expires" content="Tue, 04 Dec 1993 21:29:02 GMT">
 <title>GSMInterfaces HybridShapePointBetween (Object)</title>
<link rel="Stylesheet" type="text/css" href="../../../caav5.css">
</head>
<body>
<pre><a href="../main.htm">All Frameworks</a>  <a href="../tree.htm">Object Hierarchy</a>  <a href="../GSMInterfaces.htm">This Framework</a>  <a href=".htm">Previous</a>  <a href="interface_HybridShapePointCenter_101398.htm">Next</a>  <a href="../CAAHomeIdx.htm">Indexes</a>  </pre>
<hr>
<h1>HybridShapePointBetween<font size=-1> (Object)</font></h1>
<pre>
<a href="../System/interface_IUnknown_14460.htm">IUnknown</a>
  |
  +---<a href="../System/interface_IDispatch_17333.htm">IDispatch</a>
    |
    +---<a href="../System/interface_CATBaseUnknown_40786.htm">CATBaseUnknown</a>
      |
      +---<a href="../System/interface_CATBaseDispatch_45333.htm">CATBaseDispatch</a>
        |
        +---<a href="../System/interface_AnyObject_17321.htm">AnyObject</a>
          |
          +---<a href="../MecModInterfaces/interface_HybridShape_25589.htm">HybridShape</a>
            |
            +---<a href="../GSMInterfaces/interface_Point_5884.htm">Point</a>
              |
              +---HybridShapePointBetween
 </pre>
<hr><br>
<b><i> Represents the hybrid shape PointBetween feature object.</i></b><br>

 <b>Role</b>: To access the data of the hybrid shape PointBetween feature object.<BR>
 This data includes:
<ul>
<li>The first reference point
<li>The second reference point
</ul>
 <dl>
  <dt> <b>See also:</b> 
  <dd> <a href="../GSMInterfaces/interface_HybridShapeFactory_68680.htm">HybridShapeFactory</a>
</dl>
<hr>
<dl>
 <h2><a name="PropertyIndex"></a>Property Index</h2>
 <dt>
    <a href="#FirstPoint"><b>FirstPoint</b></a>
<dd>  Returns or sets the first reference point.
 <dt>
    <a href="#Orientation"><b>Orientation</b></a>
<dd>  Returns or sets the orientation.
 <dt>
    <a href="#Ratio"><b>Ratio</b></a>
<dd>   Get the ratio.
 <dt>
    <a href="#SecondPoint"><b>SecondPoint</b></a>
<dd>  Returns or sets the second reference point.
 <dt>
    <a href="#Support"><b>Support</b></a>
<dd>  Returns or Sets the support.
</dl>
<dl>
</dl>
 <h2><a name="Properties"></a>Properties</h2> <br>
<a name="FirstPoint"><dt>

<table><tr><td>o Property <b>FirstPoint</b>(<td>) As <a href="../InfInterfaces/interface_Reference_17481.htm">CATIAReference</a> </table></dt>
<dl>
  <dd>
 Returns or sets the first reference point.
 <br>Sub-element(s) supported (see 
<a href="../MecModInterfaces/interface_Boundary_14542.htm">Boundary</a> object):  
<a href="../MecModInterfaces/interface_Vertex_8466.htm">Vertex</a>.<dl>
<dt><b>Example</b>:
<dd>
 This example retrieves in <code>RefPoint1</code> the first reference point for the
<code>PointBetween</code> hybrid shape feature.
<pre>
 Dim RefPoint1 As Reference
 Set RefPoint1 = PointBetween.<font color="red">FirstPoint</font>
</pre>
</dl>
</dl>
<a name="Orientation"><dt>

<table><tr><td>o Property <b>Orientation</b>(<td>) As long </table></dt>
<dl>
  <dd>
 Returns or sets the orientation.
 <b>Role</b>:<br>
  Orientation = 1 means that distance is measured from the second point
 <dl>
 <dt><b>Example</b>:
 <dd>
 This example retrieves in <code>Orient</code> the orientation for the <code>PointBetween</code> hybrid shape feature.
<pre>
 Dim Orient As long
 Set Orient = PointBetween.<font color="red">Orientation</font>
 </pre>
 </dl>
</dl>
<a name="Ratio"><dt>

<table><tr><td>o Property <b>Ratio</b>(<td>) As <a href="../KnowledgeInterfaces/interface_RealParam_17053.htm">CATIARealParam</a>  (Read Only)</table></dt>
<dl>
  <dd>
  Get the ratio.
 <b>Role</b>: <br>
   if  d1 is the distance between the first point and the created point,
   and d2 is the distance between the first point and the second point,
   then ratio = d1/d2.
 <dl>
 <dt><b>Example</b>:
 <dd>
 This example retrieves in <code>ratio</code> the orientation for the <code>PointBetween</code> hybrid shape feature.
<pre>
 Dim ratio  As CATIARealParam
 Get ratio = PointBetween.<font color="red">Ratio</font>
 </pre>
 </dl>
</dl>
<a name="SecondPoint"><dt>

<table><tr><td>o Property <b>SecondPoint</b>(<td>) As <a href="../InfInterfaces/interface_Reference_17481.htm">CATIAReference</a> </table></dt>
<dl>
  <dd>
 Returns or sets the second reference point.
 <br>Sub-element(s) supported (see 
<a href="../MecModInterfaces/interface_Boundary_14542.htm">Boundary</a> object):  
<a href="../MecModInterfaces/interface_Vertex_8466.htm">Vertex</a>.<dl>
<dt><b>Example</b>:
<dd>
 This example retrieves in <code>RefPoint2</code> the second reference point for the
<code>PointBetween</code> hybrid shape feature.
<pre>
 Dim RefPoint2 As Reference
 Set RefPoint2 = PointBetween.<font color="red">SecondPoint</font>
</pre>
</dl>
</dl>
<a name="Support"><dt>

<table><tr><td>o Property <b>Support</b>(<td>) As <a href="../InfInterfaces/interface_Reference_17481.htm">CATIAReference</a> </table></dt>
<dl>
  <dd>
 Returns or Sets the support.
 <br> Note: the support can be surface or curve. It is not mandatory.<br>
 <br>Sub-element(s) supported (see 
<a href="../MecModInterfaces/interface_Boundary_14542.htm">Boundary</a> object):  
<a href="../MecModInterfaces/interface_Face_3398.htm">Face</a> and 
<a href="../MecModInterfaces/interface_TriDimFeatEdge_39030.htm">TriDimFeatEdge</a> and 
<a href="../MecModInterfaces/interface_BiDimFeatEdge_33192.htm">BiDimFeatEdge</a>. <dl>
 <dt><b>Example</b>:
 <dd>
 This example retrieves in <code>oSupport</code> the support(if it exist)  
 for the <code>PointBetween</code> hybrid shape feature.
 <pre>
 Dim oSupport As Reference 
 Set oSupport = PointBetween.<font color="red">Support</font>
 </pre>
 </dl>
</dl>

</body>
<hr><p><i>
Copyright &#169; 2003, Dassault Syst&#232;mes. All rights reserved.</i></p>
</html>
