<html>
<head>
 <meta name="Generator" content="mihGene v1.1">
 <meta http-equiv="Expires" content="Tue, 04 Dec 1993 21:29:02 GMT">
 <title>GSMInterfaces HybridShapeWrapCurve (Object)</title>
<link rel="Stylesheet" type="text/css" href="../../../caav5.css">
</head>
<body>
<pre><a href="../main.htm">All Frameworks</a>  <a href="../tree.htm">Object Hierarchy</a>  <a href="../GSMInterfaces.htm">This Framework</a>  <a href=".htm">Previous</a>  <a href="interface_HybridShapeWrapSurface_100696.htm">Next</a>  <a href="../CAAHomeIdx.htm">Indexes</a>  </pre>
<hr>
<h1>HybridShapeWrapCurve<font size=-1> (Object)</font></h1>
<pre>
<a href="../System/interface_IUnknown_14460.htm">IUnknown</a>
  |
  +---<a href="../System/interface_IDispatch_17333.htm">IDispatch</a>
    |
    +---<a href="../System/interface_CATBaseUnknown_40786.htm">CATBaseUnknown</a>
      |
      +---<a href="../System/interface_CATBaseDispatch_45333.htm">CATBaseDispatch</a>
        |
        +---<a href="../System/interface_AnyObject_17321.htm">AnyObject</a>
          |
          +---<a href="../MecModInterfaces/interface_HybridShape_25589.htm">HybridShape</a>
            |
            +---HybridShapeWrapCurve
 </pre>
<hr><br>
<b><i> Represents the hybrid shape wrap curve surface object.</i></b><br>

 <b>Role</b>: To access the data of the hybrid shape wrap curve surface object.
 <p>This data includes:
 <ul>
 <li>Two support surfaces, one at each limit of the wrap curve surface</li>
 <li>Two curves, one for each support surface</li>
 <li>The curve closing points</li>
 </ul>
 <p>Use the CATIAHybridShapeFactory to create a HybridShapeWrapCurve object.
 <dl>
  <dt> <b>See also:</b> 
  <dd> <a href="../GSMInterfaces/interface_HybridShapeFactory_68680.htm">HybridShapeFactory</a>
</dl>
<hr>
<dl>
 <h2><a name="PropertyIndex"></a>Property Index</h2>
 <dt>
    <a href="#FirstCurvesConstraint"><b>FirstCurvesConstraint</b></a>
<dd>  Returns or sets constraint at first curves of the WrapCurve.
 <dt>
    <a href="#LastCurvesConstraint"><b>LastCurvesConstraint</b></a>
<dd>  Returns or sets constraint at last curves of the WrapCurve.
 <dt>
    <a href="#Surface"><b>Surface</b></a>
<dd>  Returns or sets the surface to deform of the WrapCurve.
</dl>
<dl>
 <h2><a name="MethodIndex"></a>Method Index</h2>
 <dt>
    <a href="#GetCurves"><b>GetCurves</b></a>
<dd>  Returns a curve from the WrapCurve.
 <dt>
    <a href="#GetNumberOfCurves"><b>GetNumberOfCurves</b></a>
<dd>  Returns the number of couples of curves of the WrapCurve.
 <dt>
    <a href="#GetReferenceDirection"><b>GetReferenceDirection</b></a>
<dd>  Gets the reference direction projection of the wrap curve feature.
 <dt>
    <a href="#GetReferenceSpine"><b>GetReferenceSpine</b></a>
<dd>  Returns the reference spine of the wrap curve feature.
 <dt>
    <a href="#InsertCurves"><b>InsertCurves</b></a>
<dd>  Inserts a couple of reference curve and target curve to the wrap curve.
 <dt>
    <a href="#InsertReferenceCurve"><b>InsertReferenceCurve</b></a>
<dd>  Inserts a of reference curve to the wrap curve.
 <dt>
    <a href="#RemoveCurves"><b>RemoveCurves</b></a>
<dd>  Removes a couple of reference curve and target curve from the WrapCurve.
 <dt>
    <a href="#SetReferenceDirection"><b>SetReferenceDirection</b></a>
<dd>  Sets the reference direction projection to the wrap curve feature.
 <dt>
    <a href="#SetReferenceSpine"><b>SetReferenceSpine</b></a>
<dd>  Sets the reference spine to the wrap curve feature.
</dl>
 <h2><a name="Properties"></a>Properties</h2> <br>
<a name="FirstCurvesConstraint"><dt>

<table><tr><td>o Property <b>FirstCurvesConstraint</b>(<td>) As long </table></dt>
<dl>
  <dd>
 Returns or sets constraint at first curves of the WrapCurve.
  <br><b>Legal values</b>: 1 = no constraint, 2 = Deformed surface will have the same tangency 
  and the same curvature as the original surface at first curves.
 </dl>
 <dl>
 <dt><b>Example</b>:
 <dd>
 This example retrieves in <code>FirstCurvesConstraint</code> the constraint at first curves
 of the <code>ShpWrapCurve</code> hybrid shape WrapCurve feature.
 <pre>
 Dim FirstCurvesConstraint As long
 Set FirstCurvesConstraint = ShpWrapCurve.<font color="red">FirstCurvesConstraint</font>
 </pre>
 </dl>
</dl>
<a name="LastCurvesConstraint"><dt>

<table><tr><td>o Property <b>LastCurvesConstraint</b>(<td>) As long </table></dt>
<dl>
  <dd>
 Returns or sets constraint at last curves of the WrapCurve.
  <br><b>Legal values</b>: 1 = no constraint, 2 = Deformed surface will have the same tangency 
  and the the same curvatureas the original surface at last curves.
 </dl>
 <dl>
 <dt><b>Example</b>:
 <dd>
 This example retrieves in <code>LastCurvesConstraint</code> the constraint at last curves
 of the <code>ShpWrapCurve</code> hybrid shape WrapCurve feature.
 <pre>
 Dim LastCurvesConstraint As long
 Set LastCurvesConstraint = ShpWrapCurve.<font color="red">LastCurvesConstraint</font>
 </pre>
 </dl>
</dl>
<a name="Surface"><dt>

<table><tr><td>o Property <b>Surface</b>(<td>) As <a href="../InfInterfaces/interface_Reference_17481.htm">CATIAReference</a> </table></dt>
<dl>
  <dd>
 Returns or sets the surface to deform of the WrapCurve.
 <br>Sub-element(s) supported (see 
<a href="../MecModInterfaces/interface_Boundary_14542.htm">Boundary</a> object):  
<a href="../MecModInterfaces/interface_Face_3398.htm">Face</a>. </dl>
 <dl>
 <dt><b>Example</b>:
 <dd>
 This example retrieves in <code>SurfaceToDeform</code> the surface to deform
 of the <code>ShpWrapCurve</code> hybrid shape WrapCurve feature.
 <pre>
 SurfaceToDeform = ShpWrapCurve.<font color="red">Surface</font>
 </pre>
 </dl>
</dl>
 <h2><a name="Methods"></a>Methods</h2> <br>
<a name="GetCurves"><dt>

<table><tr><td>o Sub <b>GetCurves</b>(<td>long <td><tt>iPosition</tt>,<tr><td></td><td><a href="../InfInterfaces/interface_Reference_17481.htm">CATIAReference</a> <td><tt>oReferenceCurve</tt>,<tr><td></td><td><a href="../InfInterfaces/interface_Reference_17481.htm">CATIAReference</a> <td><tt>oTargetCurve</tt>)</table></dt>
<dl>
  <dd>
 Returns a curve from the WrapCurve.
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iPosition</tt>
   <dd>     The position of the curves in the list of curves. 
 </dd>
    <dt><tt> oReferenceCurve</tt>
   <dd>    the reference curve. 
 </dd>
    <dt><tt> oTargetCurve</tt>
   <dd>    the target curve.
   <br><b>Legal values</b>: can be egal to Nothing. In this case, the associated ref curve will be fixed.
 <dl>
 <dt><b>Example</b>:
 <dd>
 This example retrieves in <code>WrapCurveRefCurve</code> the first reference curve 
 of the <code>ShpWrapCurve</code> hybrid shape WrapCurve feature and retrieves in <code>WrapCurveTargCurve</code>
 the first target curve of the <code>ShpWrapCurve</code> hybrid shape WrapCurve feature.
 <pre>
 Dim WrapCurveRefCurve As Reference
 Dim WrapCurveTargCurve As Reference
 ShpWrapCurve.<font color="red">GetCurve</font>(2)
 </pre>
 </dl></dd>
</dl>
</dl>
</dl>
<a name="GetNumberOfCurves"><dt>

<table><tr><td>o Func <b>GetNumberOfCurves</b>(<td>) As long </table></dt>
<dl>
  <dd>
 Returns the number of couples of curves of the WrapCurve.
   
<dl>
  <dt> <b>Returns:</b> 
  <dd>       The number of couples of curves
     <br><b>Legal values</b>: positive or null.
 </dl>
 <dt><b>Example</b>:
 <dd>
 This example retrieves in <code>NumberOfCurves</code> the number of couples of curves
 of the <code>ShpWrapCurve</code> hybrid shape WrapCurve feature.
 <pre>
 NumberOfCurves = ShpWrapCurve.<font color="red">GetNumberOfCurves</font>(2)
 </pre>
 </dl>
</dl>
</dl>
<a name="GetReferenceDirection"><dt>

<table><tr><td>o Sub <b>GetReferenceDirection</b>(<td>long <td><tt>oDirectionType</tt>,<tr><td></td><td><a href="../GSMInterfaces/interface_HybridShapeDirection_84226.htm">CATIAHybridShapeDirection</a> <td><tt>oDirection</tt>)</table></dt>
<dl>
  <dd>
 Gets the reference direction projection of the wrap curve feature.
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> oDirectionType</tt>
   <dd>     type of direction.
     <br><b>Legal values</b>: 1 = reference direction is computed,
       and 2 = user direction.
   </dd>
    <dt><tt> oDirection</tt>
   <dd>     curve to be added as a direction, if oDirectionType = 2.
 <dt><b>Example</b>:
 <dd>
 This example retrieves in <code>RefDirection</code> the reference direction
 of the <code>ShpWrapCurve</code> hybrid shape WrapCurve feature and 
 in <code>RefDirectionType</code> the reference direction
 of the <code>ShpWrapCurve</code> hybrid shape WrapCurve
 <pre>
 Dim RefDirectionType As long 
 Dim RefDirection As CATIAHybridShapeDirection 
 ShpWrapCurve.<font color="red">SetReferenceDirection</font> (RefDirectionType, RefDirection)
 </pre></dd>
</dl>
</dl>
</dl>
<a name="GetReferenceSpine"><dt>

<table><tr><td>o Sub <b>GetReferenceSpine</b>(<td>long <td><tt>oSpineType</tt>,<tr><td></td><td><a href="../InfInterfaces/interface_Reference_17481.htm">CATIAReference</a> <td><tt>oSpine</tt>)</table></dt>
<dl>
  <dd>
 Returns the reference spine of the wrap curve feature.
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> oSpineType</tt>
   <dd>     type of spine.
     <br><b>Legal values</b>: 1 = Reference Spine is equal to the first reference curve, 
       and 2 = user spine.
   </dd>
    <dt><tt> oSpine</tt>
   <dd>     curve to be added as a spine, if iSpineType = 2.
 </dl>
 <dt><b>Example</b>:
 <dd>
 This example retrieves in <code>RefSpine</code> the reference spine
 of the <code>ShpWrapCurve</code> hybrid shape WrapCurve feature and
 in <code>RefSpineType</code> the reference spine type.
 <pre>
 Dim RefSpineType As long 
 Dim RefSpine As Reference 
 ShpWrapCurve.<font color="red">GetReferenceSpine</font> (RefSpineType, RefSpine)
 </pre></dd>
</dl>
</dl>
</dl>
<a name="InsertCurves"><dt>

<table><tr><td>o Sub <b>InsertCurves</b>(<td>long <td><tt>iPosition</tt>,<tr><td></td><td><a href="../InfInterfaces/interface_Reference_17481.htm">CATIAReference</a> <td><tt>iReferenceCurve</tt>,<tr><td></td><td><a href="../InfInterfaces/interface_Reference_17481.htm">CATIAReference</a> <td><tt>iTargetCurve</tt>)</table></dt>
<dl>
  <dd>
 Inserts a couple of reference curve and target curve to the wrap curve.
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iPosition</tt>
   <dd>     The position of the curves in the list of curves. 
     <br><b>Legal values</b>: 0 for the end of the list, or positive and not null.
 </dd>
    <dt><tt> iReferenceCurve</tt>
   <dd>    the reference curve. 
 <br>Sub-element(s) supported (see </dd>
</dl>
<a href="../MecModInterfaces/interface_Boundary_14542.htm">Boundary</a> object):  
<a href="../MecModInterfaces/interface_TriDimFeatEdge_39030.htm">TriDimFeatEdge</a> and 
<a href="../MecModInterfaces/interface_BiDimFeatEdge_33192.htm">BiDimFeatEdge</a>.  
    <dt><tt> iTargetCurve</tt>
   <dd>    the target curve.
 <br>Sub-element(s) supported (see </dd>
<a href="../MecModInterfaces/interface_Boundary_14542.htm">Boundary</a> object):  
<a href="../MecModInterfaces/interface_TriDimFeatEdge_39030.htm">TriDimFeatEdge</a> and 
<a href="../MecModInterfaces/interface_BiDimFeatEdge_33192.htm">BiDimFeatEdge</a>.  </dl>
 <dt><b>Example</b>:
 <dd>
 This example sets the <code>RefCurveForWrapCurve</code> curve and the <code>TargCurveForWrapCurve</code> curve
 at the end of the list to the <code>ShpWrapCurve</code> hybrid shape WrapCurve feature.
 <pre>
 ShpWrapCurve.<font color="red">InsertCurves</font> (0, RefCurveForWrapCurve, TargCurveForWrapCurve)
 </pre>
 </dl>
</dl>
</dl>
<a name="InsertReferenceCurve"><dt>

<table><tr><td>o Sub <b>InsertReferenceCurve</b>(<td>long <td><tt>iPosition</tt>,<tr><td></td><td><a href="../InfInterfaces/interface_Reference_17481.htm">CATIAReference</a> <td><tt>iReferenceCurve</tt>)</table></dt>
<dl>
  <dd>
 Inserts a of reference curve to the wrap curve.
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iPosition</tt>
   <dd>     The position of the curves in the list of curves. 
     <br><b>Legal values</b>: 0 for the end of the list, or positive and not null.
 </dd>
    <dt><tt> iReferenceCurve</tt>
   <dd>    the reference curve. 
 <br>Sub-element(s) supported (see </dd>
</dl>
<a href="../MecModInterfaces/interface_Boundary_14542.htm">Boundary</a> object):  
<a href="../MecModInterfaces/interface_TriDimFeatEdge_39030.htm">TriDimFeatEdge</a> and 
<a href="../MecModInterfaces/interface_BiDimFeatEdge_33192.htm">BiDimFeatEdge</a>.  <dt><b>Example</b>:
 <dd>
 This example sets the <code>RefCurveForWrapCurve</code> curve 
 at the end of the list to the <code>ShpWrapCurve</code> hybrid shape WrapCurve feature.
 <pre>
 ShpWrapCurve.<font color="red">InsertCurves</font> (0, RefCurveForWrapCurve)
 </pre>
 </dl>
</dl>
</dl>
<a name="RemoveCurves"><dt>

<table><tr><td>o Sub <b>RemoveCurves</b>(<td>long <td><tt>iPosition</tt>)</table></dt>
<dl>
  <dd>
 Removes a couple of reference curve and target curve from the WrapCurve. 
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iPosition</tt>
   <dd>     The position of the curves in the list of curves. 
     <br><b>Legal values</b>: positive, not null and lower to numberOfCurves
 </dl>
 <dt><b>Example</b>:
 <dd>
 This example removes the first couple of reference curve and target curve 
 of the <code>ShpWrapCurve</code> hybrid shape WrapCurve feature.
 <pre>
 ShpWrapCurve.<font color="red">RemoveCurves</font> (1)
 </pre>
 </dl></dd>
</dl>
</dl>
</dl>
<a name="SetReferenceDirection"><dt>

<table><tr><td>o Sub <b>SetReferenceDirection</b>(<td><a href="../GSMInterfaces/interface_HybridShapeDirection_84226.htm">CATIAHybridShapeDirection</a> <td><tt>iDirection</tt>)</table></dt>
<dl>
  <dd>
 Sets the reference direction projection to the wrap curve feature.
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iDirection</tt>
   <dd>     curve to be added as a direction, if iDirectionType = 2.
 <dt><b>Example</b>:
 <dd>
 This example sets the <code>RefDirection</code> curve as the reference direction
 of the <code>ShpWrapCurve</code> hybrid shape WrapCurve feature.
 <pre>
 ShpWrapCurve.<font color="red">SetReferenceDirection</font> RefDirection
 </pre></dd>
</dl>
</dl>
</dl>
<a name="SetReferenceSpine"><dt>

<table><tr><td>o Sub <b>SetReferenceSpine</b>(<td><a href="../InfInterfaces/interface_Reference_17481.htm">CATIAReference</a> <td><tt>iSpine</tt>)</table></dt>
<dl>
  <dd>
 Sets the reference spine to the wrap curve feature.
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iSpine</tt>
   <dd>     curve to be added as a spine.
 <br>Sub-element(s) supported (see </dd>
</dl>
<a href="../MecModInterfaces/interface_Boundary_14542.htm">Boundary</a> object):  
<a href="../MecModInterfaces/interface_TriDimFeatEdge_39030.htm">TriDimFeatEdge</a>, 
<a href="../MecModInterfaces/interface_BiDimFeatEdge_33192.htm">BiDimFeatEdge</a>. </dl>
 <dt><b>Example</b>:
 <dd>
 This example sets the <code>Curve10</code> curve as the reference Spine
 of the <code>ShpWrapCurve</code> hybrid shape WrapCurve feature.
 <pre>
 ShpWrapCurve.<font color="red">SetReferenceSpine</font> Curve10
 </pre>
 </dl>
</dl>
</dl>

</body>
<hr><p><i>
Copyright &#169; 2003, Dassault Syst&#232;mes. All rights reserved.</i></p>
</html>
