<html>
<head>
 <meta name="Generator" content="mihGene v1.1">
 <meta http-equiv="Expires" content="Tue, 04 Dec 1993 21:29:02 GMT">
 <title>GSMInterfaces HybridShapeSweep (Object)</title>
<link rel="Stylesheet" type="text/css" href="../../../caav5.css">
</head>
<body>
<pre><a href="../main.htm">All Frameworks</a>  <a href="../tree.htm">Object Hierarchy</a>  <a href="../GSMInterfaces.htm">This Framework</a>  <a href=".htm">Previous</a>  <a href="interface_HybridShapeSweepCircle_100044.htm">Next</a>  <a href="../CAAHomeIdx.htm">Indexes</a>  </pre>
<hr>
<h1>HybridShapeSweep<font size=-1> (Object)</font></h1>
<pre>
<a href="../System/interface_IUnknown_14460.htm">IUnknown</a>
  |
  +---<a href="../System/interface_IDispatch_17333.htm">IDispatch</a>
    |
    +---<a href="../System/interface_CATBaseUnknown_40786.htm">CATBaseUnknown</a>
      |
      +---<a href="../System/interface_CATBaseDispatch_45333.htm">CATBaseDispatch</a>
        |
        +---<a href="../System/interface_AnyObject_17321.htm">AnyObject</a>
          |
          +---<a href="../MecModInterfaces/interface_HybridShape_25589.htm">HybridShape</a>
            |
            +---HybridShapeSweep
 </pre>
<hr><br>
<b><i> Represents the hybrid shape Sweep feature object.</i></b><br>

 <b>Role</b>: Declare  hybrid shape Sweep root feature object. 
 All interfaces for different type of sweep derivates HybridShapeSweep. 
 <p> Use the CATIAHybridShapeFactory to create a HybridShapeSweep objects.
 <dl>
  <dt> <b>See also:</b> 
  <dd> <a href="../GSMInterfaces/interface_HybridShapeFactory_68680.htm">HybridShapeFactory</a>
</dl>
<hr>
<dl>
 <h2><a name="PropertyIndex"></a>Property Index</h2>
 <dt>
    <a href="#FillTwistedAreas"><b>FillTwistedAreas</b></a>
<dd>  Returns or sets the fill twisted areas mode.
 <dt>
    <a href="#SetbackValue"><b>SetbackValue</b></a>
<dd>  Returns or sets the setback value.
</dl>
<dl>
 <h2><a name="MethodIndex"></a>Method Index</h2>
 <dt>
    <a href="#AddCutPoints"><b>AddCutPoints</b></a>
<dd>  Sets two cut points on the master guide.
 <dt>
    <a href="#AddFillPoints"><b>AddFillPoints</b></a>
<dd>  Sets two fill points on the master guide.
 <dt>
    <a href="#GetCutPoint"><b>GetCutPoint</b></a>
<dd>  <dt>
    <a href="#GetFillPoint"><b>GetFillPoint</b></a>
<dd>  <dt>
    <a href="#RemoveAllCutPoints"><b>RemoveAllCutPoints</b></a>
<dd>  Removes all cut points.
 <dt>
    <a href="#RemoveAllFillPoints"><b>RemoveAllFillPoints</b></a>
<dd>  Removes all fill points.
</dl>
 <h2><a name="Properties"></a>Properties</h2> <br>
<a name="FillTwistedAreas"><dt>

<table><tr><td>o Property <b>FillTwistedAreas</b>(<td>) As long </table></dt>
<dl>
  <dd>
 Returns or sets the fill twisted areas mode.
</dl>
<a name="SetbackValue"><dt>

<table><tr><td>o Property <b>SetbackValue</b>(<td>) As double </table></dt>
<dl>
  <dd>
 Returns or sets the setback value.
</dl>
 <h2><a name="Methods"></a>Methods</h2> <br>
<a name="AddCutPoints"><dt>

<table><tr><td>o Sub <b>AddCutPoints</b>(<td><a href="../InfInterfaces/interface_Reference_17481.htm">CATIAReference</a> <td><tt>iElement1</tt>,<tr><td></td><td><a href="../InfInterfaces/interface_Reference_17481.htm">CATIAReference</a> <td><tt>iElement2</tt>)</table></dt>
<dl>
  <dd>
 Sets two cut points on the master guide. These points define a zone to be kept
 on the final swept surface.
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iElement1</tt>
   <dd>      First / start cut point.
   </dd>
    <dt><tt> iElement2</tt>
   <dd>      Second / end cut point.</dd>
</dl>
</dl>
</dl>
<a name="AddFillPoints"><dt>

<table><tr><td>o Sub <b>AddFillPoints</b>(<td><a href="../InfInterfaces/interface_Reference_17481.htm">CATIAReference</a> <td><tt>iElement1</tt>,<tr><td></td><td><a href="../InfInterfaces/interface_Reference_17481.htm">CATIAReference</a> <td><tt>iElement2</tt>)</table></dt>
<dl>
  <dd>
 Sets two fill points on the master guide. These points define a zone to be filled
 on the final swept surface.
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iElement1</tt>
   <dd>      First / start fill point.
   </dd>
    <dt><tt> iElement2</tt>
   <dd>      Second / end fill point.</dd>
</dl>
</dl>
</dl>
<a name="GetCutPoint"><dt>

<table><tr><td>o Func <b>GetCutPoint</b>(<td>long <td><tt>iRank</tt>) As <a href="../InfInterfaces/interface_Reference_17481.htm">CATIAReference</a> </table></dt>
<dl>
  <dd>
</dl>
<a name="GetFillPoint"><dt>

<table><tr><td>o Func <b>GetFillPoint</b>(<td>long <td><tt>iRank</tt>) As <a href="../InfInterfaces/interface_Reference_17481.htm">CATIAReference</a> </table></dt>
<dl>
  <dd>
</dl>
<a name="RemoveAllCutPoints"><dt>

<table><tr><td>o Sub <b>RemoveAllCutPoints</b>(<td>)</table></dt>
<dl>
  <dd>
 Removes all cut points.
</dl>
<a name="RemoveAllFillPoints"><dt>

<table><tr><td>o Sub <b>RemoveAllFillPoints</b>(<td>)</table></dt>
<dl>
  <dd>
 Removes all fill points.
</dl>

</body>
<hr><p><i>
Copyright &#169; 2003, Dassault Syst&#232;mes. All rights reserved.</i></p>
</html>
