<html>
<head>
 <meta name="Generator" content="mihGene v1.1">
 <meta http-equiv="Expires" content="Tue, 04 Dec 1993 21:29:02 GMT">
 <title>GSMInterfaces HybridShapePolyline (Object)</title>
<link rel="Stylesheet" type="text/css" href="../../../caav5.css">
</head>
<body>
<pre><a href="../main.htm">All Frameworks</a>  <a href="../tree.htm">Object Hierarchy</a>  <a href="../GSMInterfaces.htm">This Framework</a>  <a href=".htm">Previous</a>  <a href="interface_HybridShapePositionTransfo_143932.htm">Next</a>  <a href="../CAAHomeIdx.htm">Indexes</a>  </pre>
<hr>
<h1>HybridShapePolyline<font size=-1> (Object)</font></h1>
<pre>
<a href="../System/interface_IUnknown_14460.htm">IUnknown</a>
  |
  +---<a href="../System/interface_IDispatch_17333.htm">IDispatch</a>
    |
    +---<a href="../System/interface_CATBaseUnknown_40786.htm">CATBaseUnknown</a>
      |
      +---<a href="../System/interface_CATBaseDispatch_45333.htm">CATBaseDispatch</a>
        |
        +---<a href="../System/interface_AnyObject_17321.htm">AnyObject</a>
          |
          +---<a href="../MecModInterfaces/interface_HybridShape_25589.htm">HybridShape</a>
            |
            +---HybridShapePolyline
 </pre>
<hr><br>
<b><i> Represents the hybrid shape polyline curve object.</i></b><br>

 <b>Role</b>: To access or set the data of the hybrid shape polyline object.
 This data includes:
 <ul>
 <li>Elements</li>
 <li>Radius</li>
 <li>Support</li>
 <li>Closure</li>
 </ul>
 <p>Use the <a href="../GSMInterfaces/interface_HybridShapeFactory_68680.htm">HybridShapeFactory</a> object to create a HybridShapePolyline object.
<hr>
<dl>
 <h2><a name="PropertyIndex"></a>Property Index</h2>
 <dt>
    <a href="#Closure"><b>Closure</b></a>
<dd>  Returns or sets the flag to decide closure of the polyline.
 <dt>
    <a href="#NumberOfElements"><b>NumberOfElements</b></a>
<dd>  Returns the number of elements of the polyline.
</dl>
<dl>
 <h2><a name="MethodIndex"></a>Method Index</h2>
 <dt>
    <a href="#GetElement"><b>GetElement</b></a>
<dd>  Returns the element of the polyline.
 <dt>
    <a href="#InsertElement"><b>InsertElement</b></a>
<dd>  Inserts the element at a specified position in the polyline.
 <dt>
    <a href="#RemoveElement"><b>RemoveElement</b></a>
<dd>  Removes the element at a specified position in the polyline.
 <dt>
    <a href="#ReplaceElement"><b>ReplaceElement</b></a>
<dd>  Replaces the element at a specified position in the polyline.
 <dt>
    <a href="#SetRadius"><b>SetRadius</b></a>
<dd>  Sets the radius at specified position of the polyline.
</dl>
 <h2><a name="Properties"></a>Properties</h2> <br>
<a name="Closure"><dt>

<table><tr><td>o Property <b>Closure</b>(<td>) As boolean </table></dt>
<dl>
  <dd>
 Returns or sets the flag to decide closure of the polyline.
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> Closure</tt>
   <dd> (For get_Closure)     Returns  or sets the closure property
 <dl>
 <dt><b>Example</b>:
 <dd>
 This example retrieves the closure property of the polyline
 of the <code>HybShpPolyline</code> hybrid shape polyline.
 <pre>
 Dim HybShpPolClosure As  boolean
 HybShpPolClosure = HybShpPolyline.<font color="red">Closure</font>
 </pre>
 </dl></dd>
</dl>
</dl>
</dl>
<a name="NumberOfElements"><dt>

<table><tr><td>o Property <b>NumberOfElements</b>(<td>) As long  (Read Only)</table></dt>
<dl>
  <dd>
 Returns the number of elements of the polyline.
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> NumberOfElements</tt>
   <dd>     Number of elements in the polyline.
 <dl>
 <dt><b>Example</b>:
 <dd>
 This example retrieves the number of elements in the polyline
 of the <code>HybShpPolyline</code> hybrid shape polyline.
 <pre>
 Dim HybShpPolNoOfEle As  long
 HybShpPolNoOfEle = HybShpPolyline.<font color="red">NumberOfElements</font>
 </pre>
 </dl></dd>
</dl>
</dl>
</dl>
 <h2><a name="Methods"></a>Methods</h2> <br>
<a name="GetElement"><dt>

<table><tr><td>o Sub <b>GetElement</b>(<td>long <td><tt>iPosition</tt>,<tr><td></td><td><a href="../InfInterfaces/interface_Reference_17481.htm">CATIAReference</a> <td><tt>oElement</tt>,<tr><td></td><td><a href="../KnowledgeInterfaces/interface_Length_8108.htm">CATIALength</a> <td><tt>oRadius</tt>)</table></dt>
<dl>
  <dd>
 Returns the element of the polyline.
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iPosition</tt>
   <dd>     Position at which the element is to be retrieved.
   </dd>
    <dt><tt> oElement</tt>
   <dd>     Reference to the element.
   </dd>
    <dt><tt> ioRadius</tt>
   <dd>     Length to the radius.
 <dl>
 <dt><b>Example</b>:
 <dd>
 This example retrieves the element and radius of the polyline
 at specified position of the <code>HybShpPolyline</code> hybrid shape polyline.
 <pre>
 Dim HybShpPolylineElement As Reference
 Dim HybShpPolylineRadius As Reference
 HybShpPolyline.<font color="red">GetElement 1, HybShpPolylineElement,HybShpPolylineRadius</font>
 </pre>
 </dl></dd>
</dl>
</dl>
</dl>
<a name="InsertElement"><dt>

<table><tr><td>o Sub <b>InsertElement</b>(<td><a href="../InfInterfaces/interface_Reference_17481.htm">CATIAReference</a> <td><tt>iPoint</tt>,<tr><td></td><td>long <td><tt>iPosition</tt>)</table></dt>
<dl>
  <dd>
 Inserts the element at a specified position in the polyline.
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iPoint</tt>
   <dd>      Reference of the point object to be inserted.
   </dd>
    <dt><tt> iPosition</tt>
   <dd>     Position at which the element should be inserted.
 <dl>
 <dt><b>Example</b>:
 <dd>
 This example inserts the element in the polyline
 of the <code>HybShpPolyline</code> hybrid shape polyline.
 <pre>
 HybShpPolyline.<font color="red">InsertElement PointReference,1 </font>
 </pre>
 </dl></dd>
</dl>
</dl>
</dl>
<a name="RemoveElement"><dt>

<table><tr><td>o Sub <b>RemoveElement</b>(<td>long <td><tt>iPosition</tt>)</table></dt>
<dl>
  <dd>
 Removes the element at a specified position in the polyline.
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iPosition</tt>
   <dd>      Position from which the element should be should be removed.
 <dl>
 <dt><b>Example</b>:
 <dd>
 This example removes the element in the polyline
 of the <code>HybShpPolyline</code> hybrid shape polyline.
 <pre>
 HybShpPolyline.<font color="red">RemoveElement 1 </font>
 </pre>
 </dl></dd>
</dl>
</dl>
</dl>
<a name="ReplaceElement"><dt>

<table><tr><td>o Sub <b>ReplaceElement</b>(<td><a href="../InfInterfaces/interface_Reference_17481.htm">CATIAReference</a> <td><tt>iPoint</tt>,<tr><td></td><td>long <td><tt>iPosition</tt>)</table></dt>
<dl>
  <dd>
 Replaces the element at a specified position in the polyline.
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iPoint</tt>
   <dd>      Reference of the point object that will replace the old element.
   </dd>
    <dt><tt> iPosition</tt>
   <dd>     Position at which the element should be inserted.
 <dl>
 <dt><b>Example</b>:
 <dd>
 This example replaces the element in the polyline
 of the <code>HybShpPolyline</code> hybrid shape polyline.
 <pre>
 HybShpPolyline.<font color="red">ReplaceElement PointReference, 1 </font>
 </pre>
 </dl></dd>
</dl>
</dl>
</dl>
<a name="SetRadius"><dt>

<table><tr><td>o Sub <b>SetRadius</b>(<td>long <td><tt>iPosition</tt>,<tr><td></td><td>double <td><tt>iRadius</tt>)</table></dt>
<dl>
  <dd>
 Sets the radius at specified position of the polyline.
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iPosition</tt>
   <dd>     Position at which radius should be set 
   </dd>
    <dt><tt> iRadius</tt>
   <dd>      Value of the radius to be set.
 <dl>
 <dt><b>Example</b>:
 <dd>
 This example sets the radius at the specific position of the polyline
 of the <code>HybShpPolyline</code> hybrid shape polyline.
 <pre>
 HybShpPolyline.<font color="red">SetRadius 1, 10</font>
 </pre>
 </dl></dd>
</dl>
</dl>
</dl>

</body>
<hr><p><i>
Copyright &#169; 2003, Dassault Syst&#232;mes. All rights reserved.</i></p>
</html>
