<html>
<head>
 <meta name="Generator" content="mihGene v1.1">
 <meta http-equiv="Expires" content="Tue, 04 Dec 1993 21:29:02 GMT">
 <title>GSMInterfaces HybridShapeIntersection (Object)</title>
<link rel="Stylesheet" type="text/css" href="../../../caav5.css">
</head>
<body>
<pre><a href="../main.htm">All Frameworks</a>  <a href="../tree.htm">Object Hierarchy</a>  <a href="../GSMInterfaces.htm">This Framework</a>  <a href=".htm">Previous</a>  <a href="interface_HybridShapeInverse_68654.htm">Next</a>  <a href="../CAAHomeIdx.htm">Indexes</a>  </pre>
<hr>
<h1>HybridShapeIntersection<font size=-1> (Object)</font></h1>
<pre>
<a href="../System/interface_IUnknown_14460.htm">IUnknown</a>
  |
  +---<a href="../System/interface_IDispatch_17333.htm">IDispatch</a>
    |
    +---<a href="../System/interface_CATBaseUnknown_40786.htm">CATBaseUnknown</a>
      |
      +---<a href="../System/interface_CATBaseDispatch_45333.htm">CATBaseDispatch</a>
        |
        +---<a href="../System/interface_AnyObject_17321.htm">AnyObject</a>
          |
          +---<a href="../MecModInterfaces/interface_HybridShape_25589.htm">HybridShape</a>
            |
            +---HybridShapeIntersection
 </pre>
<hr><br>
<b><i> Represents the hybrid shape intersection feature object.</i></b><br>

 <b>Role</b>: To access the data of the hybrid shape intersection object.
 This data includes:
 <ul>
 <li> The first element to intersect</li>
 <li> The second element to intersect</li>
 </ul>
 Use the CATIAHybridShapeFactory to create HybridShapeFeature object. 
 <dl>
  <dt> <b>See also:</b> 
  <dd> <a href="../GSMInterfaces/interface_HybridShapeFactory_68680.htm">HybridShapeFactory</a>
</dl>
<hr>
<dl>
 <h2><a name="PropertyIndex"></a>Property Index</h2>
 <dt>
    <a href="#Element1"><b>Element1</b></a>
<dd>  Returns or sets the first element to intersect.
 <dt>
    <a href="#Element2"><b>Element2</b></a>
<dd>  Returns or sets the second element to intersect.
 <dt>
    <a href="#ExtendMode"><b>ExtendMode</b></a>
<dd>  Returns or sets the ExtendMode flag for intersect.
 <dt>
    <a href="#ExtrapolateMode"><b>ExtrapolateMode</b></a>
<dd>  Returns or sets the ExtrapolateMode flag for intersect.
 <dt>
    <a href="#IntersectMode"><b>IntersectMode</b></a>
<dd>  Returns or sets the IntersectMode flag for intersect.
 <dt>
    <a href="#PointType"><b>PointType</b></a>
<dd>  Returns or sets the PointType flag for intersect.
 <dt>
    <a href="#SolidMode"><b>SolidMode</b></a>
<dd>  Returns or sets the SolidMode flag for intersect.
</dl>
<dl>
</dl>
 <h2><a name="Properties"></a>Properties</h2> <br>
<a name="Element1"><dt>

<table><tr><td>o Property <b>Element1</b>(<td>) As <a href="../InfInterfaces/interface_Reference_17481.htm">CATIAReference</a> </table></dt>
<dl>
  <dd>
 Returns or sets the first element to intersect. 
 <br>Sub-element(s) supported (see 
<a href="../MecModInterfaces/interface_Boundary_14542.htm">Boundary</a> object):  
<a href="../MecModInterfaces/interface_Face_3398.htm">Face</a>,  
<a href="../MecModInterfaces/interface_TriDimFeatEdge_39030.htm">TriDimFeatEdge</a> or 
<a href="../MecModInterfaces/interface_BiDimFeatEdge_33192.htm">BiDimFeatEdge</a>.  <dl>
 <dt><b>Example</b>:
 <dd>
 This example retrieves in <code>FirstElem</code> the first element to intersect for the <code>Intersection</code>
 hybrid shape feature.
 <pre>
 Dim FirstElem As Reference
 Set FirstElem = Intersection.<font color="red">Element1</font>
</pre>
</dl>
</dl>
<a name="Element2"><dt>

<table><tr><td>o Property <b>Element2</b>(<td>) As <a href="../InfInterfaces/interface_Reference_17481.htm">CATIAReference</a> </table></dt>
<dl>
  <dd>
 Returns or sets the second element to intersect. 
 <br>Sub-element(s) supported (see 
<a href="../MecModInterfaces/interface_Boundary_14542.htm">Boundary</a> object):  
<a href="../MecModInterfaces/interface_Face_3398.htm">Face</a>,  
<a href="../MecModInterfaces/interface_TriDimFeatEdge_39030.htm">TriDimFeatEdge</a> or 
<a href="../MecModInterfaces/interface_BiDimFeatEdge_33192.htm">BiDimFeatEdge</a>.  <dl>
 <dt><b>Example</b>:
 <dd>
 This example retrieves in <code>SecondElem</code> the second element to intersect for the <code>Intersection</code>
 hybrid shape feature.
 <pre>
 Dim SecondElem As Reference
 Set SecondElem = Intersection.<font color="red">Element2</font>
</pre>
</dl>
</dl>
<a name="ExtendMode"><dt>

<table><tr><td>o Property <b>ExtendMode</b>(<td>) As long </table></dt>
<dl>
  <dd>
 Returns or sets the ExtendMode flag for intersect. 
 <dl>
 <dt><b>Example</b>:
 <dd>
 This example retrieves in <code>ExtendMode</code> the ExtendMode to intersect for the <code>Intersection</code>
 hybrid shape feature.
 <pre>
 Dim ExtendMode As Reference
 Set ExtendMode = Intersection.<font color="red">ExtendMode</font>
 ExtendMode is 0 when both "Extend Linear Supposr for intersection" are unchecked
 ExtendMode is 1 when "Extend Linear Supposr for intersection" for First Element is checked and for Second Element is unchecked
 ExtendMode is 2 when "Extend Linear Supposr for intersection" for First Element is unchecked and for Second Element is checked
 ExtendMode is 3 when both "Extend Linear Supposr for intersection" are checked
</pre>
</dl>
</dl>
<a name="ExtrapolateMode"><dt>

<table><tr><td>o Property <b>ExtrapolateMode</b>(<td>) As boolean </table></dt>
<dl>
  <dd>
 Returns or sets the ExtrapolateMode flag for intersect. 
 <dl>
 <dt><b>Example</b>:
 <dd>
 This example retrieves in <code>ExtrapolateMode</code> the ExtrapolateMode to intersect for the <code>Intersection</code>
 hybrid shape feature.
 <pre>
 Dim ExtrapolateMode As Reference
 Set ExtrapolateMode = Intersection.<font color="red">ExtrapolateMode</font>
</pre>
</dl>
</dl>
<a name="IntersectMode"><dt>

<table><tr><td>o Property <b>IntersectMode</b>(<td>) As boolean </table></dt>
<dl>
  <dd>
 Returns or sets the IntersectMode flag for intersect. 
 <dl>
 <dt><b>Example</b>:
 <dd>
 This example retrieves in <code>IntersectMode</code> the IntersectMode to intersect for the <code>Intersection</code>
 hybrid shape feature.
 <pre>
 Dim IntersectMode As Reference
 Set IntersectMode = Intersection.<font color="red">IntersectMode</font>
</pre>
</dl>
</dl>
<a name="PointType"><dt>

<table><tr><td>o Property <b>PointType</b>(<td>) As long </table></dt>
<dl>
  <dd>
 Returns or sets the PointType flag for intersect. 
 <dl>
 <dt><b>Example</b>:
 <dd>
 This example retrieves in <code>PointType</code> the PointType to intersect for the <code>Intersection</code>
 hybrid shape feature.
 <pre>
 Dim PointType As Reference
 Set PointType = Intersection.<font color="red">PointType</font>
</pre>
</dl>
</dl>
<a name="SolidMode"><dt>

<table><tr><td>o Property <b>SolidMode</b>(<td>) As boolean </table></dt>
<dl>
  <dd>
 Returns or sets the SolidMode flag for intersect. 
 <dl>
 <dt><b>Example</b>:
 <dd>
 This example retrieves in <code>SolidMode</code> the SolidMode to intersect for the <code>Intersection</code>
 hybrid shape feature.
 <pre>
 Dim SolidMode As Reference
 Set SolidMode = Intersection.<font color="red">SolidMode</font>
</pre>
</dl>
</dl>

</body>
<hr><p><i>
Copyright &#169; 2003, Dassault Syst&#232;mes. All rights reserved.</i></p>
</html>
