<html>
<head>
 <meta name="Generator" content="mihGene v1.1">
 <meta http-equiv="Expires" content="Tue, 04 Dec 1993 21:29:02 GMT">
 <title>GSMInterfaces HybridShapePointOnCurve (Object)</title>
<link rel="Stylesheet" type="text/css" href="../../../caav5.css">
</head>
<body>
<pre><a href="../main.htm">All Frameworks</a>  <a href="../tree.htm">Object Hierarchy</a>  <a href="../GSMInterfaces.htm">This Framework</a>  <a href=".htm">Previous</a>  <a href="interface_HybridShapePointOnPlane_108958.htm">Next</a>  <a href="../CAAHomeIdx.htm">Indexes</a>  </pre>
<hr>
<h1>HybridShapePointOnCurve<font size=-1> (Object)</font></h1>
<pre>
<a href="../System/interface_IUnknown_14460.htm">IUnknown</a>
  |
  +---<a href="../System/interface_IDispatch_17333.htm">IDispatch</a>
    |
    +---<a href="../System/interface_CATBaseUnknown_40786.htm">CATBaseUnknown</a>
      |
      +---<a href="../System/interface_CATBaseDispatch_45333.htm">CATBaseDispatch</a>
        |
        +---<a href="../System/interface_AnyObject_17321.htm">AnyObject</a>
          |
          +---<a href="../MecModInterfaces/interface_HybridShape_25589.htm">HybridShape</a>
            |
            +---<a href="../GSMInterfaces/interface_Point_5884.htm">Point</a>
              |
              +---HybridShapePointOnCurve
 </pre>
<hr><br>
<b><i> Represents the hybrid shape point on a curve.</i></b><br>
  
 <b>Role</b>: To access the data of the point object created on a curve.
 This data includes:
 <ul>
  <li>The curve onto which the point is created</li>
  <li>The reference point from which the point is created</li>
  <li>The curvilinear distance from the reference point</li>
  <li>The ratio of distance with respect to the curve length</li>
  <li>The distance stored value type, either distance or ratio</li>
  <li>The curve orientation</li>
  <li>The distance type, either geodesic or euclidean.</li>
 </ul>
 <p>Use the <a href="../GSMInterfaces/interface_HybridShapeFactory_68680.htm">HybridShapeFactory</a> to create a HybridShapePointOnCurve object.
<hr>
<dl>
 <h2><a name="PropertyIndex"></a>Property Index</h2>
 <dt>
    <a href="#Curve"><b>Curve</b></a>
<dd>  Returns or sets the curve onto which the point is or should be created.
 <dt>
    <a href="#DistanceType"><b>DistanceType</b></a>
<dd>  Returns or sets the distance type.
 <dt>
    <a href="#Offset"><b>Offset</b></a>
<dd>  Returns the distance to the reference point.
 <dt>
    <a href="#Orientation"><b>Orientation</b></a>
<dd>  Returns or sets the curve orientation.
 <dt>
    <a href="#Point"><b>Point</b></a>
<dd>  Returns or sets the reference point.
 <dt>
    <a href="#Ratio"><b>Ratio</b></a>
<dd>  Returns the distance ratio to the reference point.
 <dt>
    <a href="#Type"><b>Type</b></a>
<dd>  Returns the distance stored value type.
</dl>
<dl>
</dl>
 <h2><a name="Properties"></a>Properties</h2> <br>
<a name="Curve"><dt>

<table><tr><td>o Property <b>Curve</b>(<td>) As <a href="../InfInterfaces/interface_Reference_17481.htm">CATIAReference</a> </table></dt>
<dl>
  <dd>
 Returns or sets the curve onto which the point is or should be created.
 <br>Sub-element(s) supported (see 
<a href="../MecModInterfaces/interface_Boundary_14542.htm">Boundary</a> object):  
<a href="../MecModInterfaces/interface_TriDimFeatEdge_39030.htm">TriDimFeatEdge</a> or 
<a href="../MecModInterfaces/interface_BiDimFeatEdge_33192.htm">BiDimFeatEdge</a>. 
<dl>
  <dt> <b>Example:</b> 
  <dd>  This example retrieves in <code>oCurve</code> the supporting curve  for
 the <code>pointOnCurve</code> hybrid shape point.
 <pre>
 Dim oCurve As CATIAReference
 Set oCurve = pointOnCurve.<font color="red">Curve</font>
 </pre>
</dl>
</dl>
<a name="DistanceType"><dt>

<table><tr><td>o Property <b>DistanceType</b>(<td>) As long </table></dt>
<dl>
  <dd>
 Returns or sets the distance type.
 <br><b>Legal values</b>: 1 for geodesic, -1 for euclidean.
 <br>Default is geodesic.
 <ul>
  <li>Geodesic means that the distance is measured with a curvilinear abscissa</li>
  <li>Euclidean means that the point is created as the intersection between
      the reference curve and a circle whose radius is the length defined above.</li>
 </ul>
 
<dl>
  <dt> <b>Example:</b> 
  <dd>  This example retrieves in <code>oDistanceType</code> the distance computation type used 
 for the <code>pointOnCurve</code> hybrid shape object.
 <pre>
 Dim oDistanceType As  long
 Set oDistanceType = pointOnCurve.<font color="red">DistanceType</font>
 </pre>
</dl>
</dl>
<a name="Offset"><dt>

<table><tr><td>o Property <b>Offset</b>(<td>) As <a href="../KnowledgeInterfaces/interface_Length_8108.htm">CATIALength</a>  (Read Only)</table></dt>
<dl>
  <dd>
 Returns the distance to the reference point.
 <br>
 This distance is a distance in a length unit,
 The distance can be null.In this case, the reference point is the curve end point
 defined using the Orientation parameter.
 
<dl>
  <dt> <b>Example:</b> 
  <dd>  This example retrieves in <code>oOffset</code> the distance from the reference point
 on the supporting curve for the <code>pointOnCurve</code> hybrid shape object.
 <pre>
 Dim oOffset As  CATIALength  
 Set oOffset = pointOnCurve.<font color="red">Offset</font>
 </pre>
</dl>
</dl>
<a name="Orientation"><dt>

<table><tr><td>o Property <b>Orientation</b>(<td>) As long </table></dt>
<dl>
  <dd>
 Returns or sets the curve orientation.
 <br><b>Legal values</b>:
 -1 means that the distance (length or ratio) is measured:
 <ul> 
  <li>in the other orientation of the curve, when a reference point has been set</li>
  <li>in the other orientation of the curve and from the other extremity,
      when no reference point has been set.</li>
 </ul>
 
<dl>
  <dt> <b>Example:</b> 
  <dd>  This example retrieves in <code>oOrientation</code> curve Orientation use 
 for the <code>pointOnCurve</code> hybrid shape feature.
 <pre>
 Dim oOrientation As  long
 Set oOrientation = pointOnCurve.<font color="red">Orientation</font>
 </pre>
</dl>
</dl>
<a name="Point"><dt>

<table><tr><td>o Property <b>Point</b>(<td>) As <a href="../InfInterfaces/interface_Reference_17481.htm">CATIAReference</a> </table></dt>
<dl>
  <dd>
 Returns or sets the reference point.
 <p>If the point does not lie on the curve, the point on the curve 
 with the smallest distance to this point is taken.</p>
 <p>The reference point may not exist. In this case, 
 the extremity of the curve is taken as reference point.</p><br>
 <br>Sub-element(s) supported (see 
<a href="../MecModInterfaces/interface_Boundary_14542.htm">Boundary</a> object):  
<a href="../MecModInterfaces/interface_Vertex_8466.htm">Vertex</a>. 
<dl>
  <dt> <b>Example:</b> 
  <dd>  This example retrieves in <code>oRefPoint</code> the reference point
 on the supporting curve for the <code>pointOnCurve</code> hybrid shape object.
 <pre>
 Dim oRefPoint As  CATIAReference
 Set oRefPoint = pointOnCurve.<font color="red">Point</font>
 </pre>
</dl>
</dl>
<a name="Ratio"><dt>

<table><tr><td>o Property <b>Ratio</b>(<td>) As <a href="../KnowledgeInterfaces/interface_RealParam_17053.htm">CATIARealParam</a>  (Read Only)</table></dt>
<dl>
  <dd>
 Returns the distance ratio to the reference point.
 <br>
 This is a real parameter which corresponds to the ratio of the distance from the
 reference point with respect to the length of the supporting curve.
 The ratio can be null. In this case, the reference point is the curve end point
 defined using the Orientation parameter.
 
<dl>
  <dt> <b>Example:</b> 
  <dd>  This example retrieves in <code>oRatio</code> the distance ratio from the reference point
 on the supporting curve for the <code>pointOnCurve</code> hybrid shape object.
 <pre>
 Dim oRatio As  CATIALength  
 Set oRatio = PointOnCurve.<font color="red">Ratio</font>
 </pre>
</dl>
</dl>
<a name="Type"><dt>

<table><tr><td>o Property <b>Type</b>(<td>) As long  (Read Only)</table></dt>
<dl>
  <dd>
 Returns the distance stored value type.
 <br><b>Legal values</b>:
 <ul> 
  <li>1 when the type of measure is the length</li>
  <li>-1 when the type of measure is the distance ratio</li>
 </ul>
 
<dl>
  <dt> <b>Example:</b> 
  <dd>  This example retrieves in <code>oType</code> the distance type computation 
 for the <code>pointOnCurve</code> hybrid shape object.
 <pre>
 Dim oType As long
 Set oType = pointOnCurve.<font color="red">Type</font>
 </pre>
</dl>
</dl>

</body>
<hr><p><i>
Copyright &#169; 2003, Dassault Syst&#232;mes. All rights reserved.</i></p>
</html>
