<html>
<head>
 <meta name="Generator" content="mihGene v1.1">
 <meta http-equiv="Expires" content="Tue, 04 Dec 1993 21:29:02 GMT">
 <title>GSMInterfaces HybridShapeLineBisecting (Object)</title>
<link rel="Stylesheet" type="text/css" href="../../../caav5.css">
</head>
<body>
<pre><a href="../main.htm">All Frameworks</a>  <a href="../tree.htm">Object Hierarchy</a>  <a href="../GSMInterfaces.htm">This Framework</a>  <a href=".htm">Previous</a>  <a href="interface_HybridShapeLineExplicit_110473.htm">Next</a>  <a href="../CAAHomeIdx.htm">Indexes</a>  </pre>
<hr>
<h1>HybridShapeLineBisecting<font size=-1> (Object)</font></h1>
<pre>
<a href="../System/interface_IUnknown_14460.htm">IUnknown</a>
  |
  +---<a href="../System/interface_IDispatch_17333.htm">IDispatch</a>
    |
    +---<a href="../System/interface_CATBaseUnknown_40786.htm">CATBaseUnknown</a>
      |
      +---<a href="../System/interface_CATBaseDispatch_45333.htm">CATBaseDispatch</a>
        |
        +---<a href="../System/interface_AnyObject_17321.htm">AnyObject</a>
          |
          +---<a href="../MecModInterfaces/interface_HybridShape_25589.htm">HybridShape</a>
            |
            +---<a href="../GSMInterfaces/interface_Line_3608.htm">Line</a>
              |
              +---HybridShapeLineBisecting
 </pre>
<hr><br>
<b><i> Represents the hybrid shape bisecting line feature object.</i></b><br>

 <b>Role</b>: To access the data of the hybrid shape bisecting line feature object.
 This data includes:
 <ul>
 <li>The two lines used to create the bisecting line</li>
 <li>The reference point</li>
 <li>The support</li>
 <li>The start and end offsets</li>
 <li>The orientation</li>
 <li>The solution type</li>
 </ul>
 <p>Use the  CATIAHybridShapeFactory to create a HybridShapeAffinity object.
 <dl>
  <dt> <b>See also:</b> 
  <dd> <a href="../GSMInterfaces/interface_HybridShapeFactory_68680.htm">HybridShapeFactory</a>
</dl>
<hr>
<dl>
 <h2><a name="PropertyIndex"></a>Property Index</h2>
 <dt>
    <a href="#BeginOffset"><b>BeginOffset</b></a>
<dd>  Returns the start offset of the line.
 <dt>
    <a href="#Elem1"><b>Elem1</b></a>
<dd>  Returns or sets the first line used to create the bisecting line.
 <dt>
    <a href="#Elem2"><b>Elem2</b></a>
<dd>  Returns or sets the second line used to create the bisecting line.
 <dt>
    <a href="#EndOffset"><b>EndOffset</b></a>
<dd>  Returns the end offset of the line.
 <dt>
    <a href="#Orientation"><b>Orientation</b></a>
<dd>  Returns or sets the orientation used to compute the bisecting line.
 <dt>
    <a href="#RefPoint"><b>RefPoint</b></a>
<dd>  Returns or sets the reference point used to create the bisecting line.
 <dt>
    <a href="#SolutionType"><b>SolutionType</b></a>
<dd>  Returns or sets the solution type.
 <dt>
    <a href="#Support"><b>Support</b></a>
<dd>  Returns or sets the support used to create the bisecting line.
</dl>
<dl>
 <h2><a name="MethodIndex"></a>Method Index</h2>
 <dt>
    <a href="#GetLengthType"><b>GetLengthType</b></a>
<dd>  Gets the length type
 Default is 0.
 <dt>
    <a href="#GetSymmetricalExtension"><b>GetSymmetricalExtension</b></a>
<dd>  Gets whether the symmetrical extension of the line is active.
 <dt>
    <a href="#SetLengthType"><b>SetLengthType</b></a>
<dd>  Sets the length type
 Default is 0.
 <dt>
    <a href="#SetSymmetricalExtension"><b>SetSymmetricalExtension</b></a>
<dd>  Sets the symmetrical extension of the line (start = -end).
</dl>
 <h2><a name="Properties"></a>Properties</h2> <br>
<a name="BeginOffset"><dt>

<table><tr><td>o Property <b>BeginOffset</b>(<td>) As <a href="../KnowledgeInterfaces/interface_Length_8108.htm">CATIALength</a>  (Read Only)</table></dt>
<dl>
  <dd>
 Returns the start offset of the line.
</dl>
<a name="Elem1"><dt>

<table><tr><td>o Property <b>Elem1</b>(<td>) As <a href="../InfInterfaces/interface_Reference_17481.htm">CATIAReference</a> </table></dt>
<dl>
  <dd>
 Returns or sets the first line used to create the bisecting line. <br>
 <br>Sub-element(s) supported (see 
<a href="../MecModInterfaces/interface_Boundary_14542.htm">Boundary</a> object):  see 
<a href="../MecModInterfaces/interface_RectilinearTriDimFeatEdge_125698.htm">RectilinearTriDimFeatEdge</a> or 
<a href="../MecModInterfaces/interface_RectilinearBiDimFeatEdge_114366.htm">RectilinearBiDimFeatEdge</a>.
</dl>
<a name="Elem2"><dt>

<table><tr><td>o Property <b>Elem2</b>(<td>) As <a href="../InfInterfaces/interface_Reference_17481.htm">CATIAReference</a> </table></dt>
<dl>
  <dd>
 Returns or sets the second line used to create the bisecting line. 
 <br>Sub-element(s) supported (see 
<a href="../MecModInterfaces/interface_Boundary_14542.htm">Boundary</a> object):  see 
<a href="../MecModInterfaces/interface_RectilinearTriDimFeatEdge_125698.htm">RectilinearTriDimFeatEdge</a> or 
<a href="../MecModInterfaces/interface_RectilinearBiDimFeatEdge_114366.htm">RectilinearBiDimFeatEdge</a>.
</dl>
<a name="EndOffset"><dt>

<table><tr><td>o Property <b>EndOffset</b>(<td>) As <a href="../KnowledgeInterfaces/interface_Length_8108.htm">CATIALength</a>  (Read Only)</table></dt>
<dl>
  <dd>
 Returns the end offset of the line.
</dl>
<a name="Orientation"><dt>

<table><tr><td>o Property <b>Orientation</b>(<td>) As long </table></dt>
<dl>
  <dd>
 Returns or sets the orientation used to compute the bisecting line.
 <br><b>Role</b>: the orientation specifies bisecting line position
 <br><b>Legal values</b>:
   The orientation can be the same(1) or the inverse(-1)
</dl>
<a name="RefPoint"><dt>

<table><tr><td>o Property <b>RefPoint</b>(<td>) As <a href="../InfInterfaces/interface_Reference_17481.htm">CATIAReference</a> </table></dt>
<dl>
  <dd>
 Returns or sets the reference point used to create the bisecting line. 
 <br>Sub-element(s) supported (see 
<a href="../MecModInterfaces/interface_Boundary_14542.htm">Boundary</a> object):  see 
<a href="../MecModInterfaces/interface_Vertex_8466.htm">Vertex</a>.
</dl>
<a name="SolutionType"><dt>

<table><tr><td>o Property <b>SolutionType</b>(<td>) As boolean </table></dt>
<dl>
  <dd>
 Returns or sets the solution type.
 <br><b>Role</b>: The solution type allows you to know where is the bisecting line.
</dl>
<a name="Support"><dt>

<table><tr><td>o Property <b>Support</b>(<td>) As <a href="../InfInterfaces/interface_Reference_17481.htm">CATIAReference</a> </table></dt>
<dl>
  <dd>
 Returns or sets the support used to create the bisecting line. 
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> oElem</tt>
   <dd>    retrieve the support of the bisecting line.
 <br>Sub-element(s) supported (see </dd>
</dl>
<a href="../MecModInterfaces/interface_Boundary_14542.htm">Boundary</a> object):  see 
<a href="../MecModInterfaces/interface_Face_3398.htm">Face</a>.
</dl>
</dl>
 <h2><a name="Methods"></a>Methods</h2> <br>
<a name="GetLengthType"><dt>

<table><tr><td>o Func <b>GetLengthType</b>(<td>) As long </table></dt>
<dl>
  <dd>
 Gets the length type
 Default is 0.
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> oType</tt>
   <dd>   The length type = 0 : length               - the line is limited by its extremities
                   = 1 : infinite             - the line is infinite
                   = 2 : infinite start point - the line is infinite on the side of the start point
                   = 3 : infinite end point   - the line is infinite on the side of the end point</dd>
</dl>
</dl>
</dl>
<a name="GetSymmetricalExtension"><dt>

<table><tr><td>o Func <b>GetSymmetricalExtension</b>(<td>) As boolean </table></dt>
<dl>
  <dd>
 Gets whether the symmetrical extension of the line is active.
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> oSym</tt>
   <dd>       Symetry flag</dd>
</dl>
</dl>
</dl>
<a name="SetLengthType"><dt>

<table><tr><td>o Sub <b>SetLengthType</b>(<td>long <td><tt>iType</tt>)</table></dt>
<dl>
  <dd>
 Sets the length type
 Default is 0.
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iType</tt>
   <dd>   The length type = 0 : length               - the line is limited by its extremities
                   = 1 : infinite             - the line is infinite
                   = 2 : infinite start point - the line is infinite on the side of the start point
                   = 3 : infinite end point   - the line is infinite on the side of the end point</dd>
</dl>
</dl>
</dl>
<a name="SetSymmetricalExtension"><dt>

<table><tr><td>o Sub <b>SetSymmetricalExtension</b>(<td>boolean <td><tt>iSym</tt>)</table></dt>
<dl>
  <dd>
 Sets the symmetrical extension of the line (start = -end).
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iSym</tt>
   <dd>       Symetry flag</dd>
</dl>
</dl>
</dl>

</body>
<hr><p><i>
Copyright &#169; 2003, Dassault Syst&#232;mes. All rights reserved.</i></p>
</html>
