<html>
<head>
 <meta name="Generator" content="mihGene v1.1">
 <meta http-equiv="Expires" content="Tue, 04 Dec 1993 21:29:02 GMT">
 <title>GSMInterfaces HybridShapePlane3Points (Object)</title>
<link rel="Stylesheet" type="text/css" href="../../../caav5.css">
</head>
<body>
<pre><a href="../main.htm">All Frameworks</a>  <a href="../tree.htm">Object Hierarchy</a>  <a href="../GSMInterfaces.htm">This Framework</a>  <a href=".htm">Previous</a>  <a href="interface_HybridShapePlaneAngle_89924.htm">Next</a>  <a href="../CAAHomeIdx.htm">Indexes</a>  </pre>
<hr>
<h1>HybridShapePlane3Points<font size=-1> (Object)</font></h1>
<pre>
<a href="../System/interface_IUnknown_14460.htm">IUnknown</a>
  |
  +---<a href="../System/interface_IDispatch_17333.htm">IDispatch</a>
    |
    +---<a href="../System/interface_CATBaseUnknown_40786.htm">CATBaseUnknown</a>
      |
      +---<a href="../System/interface_CATBaseDispatch_45333.htm">CATBaseDispatch</a>
        |
        +---<a href="../System/interface_AnyObject_17321.htm">AnyObject</a>
          |
          +---<a href="../MecModInterfaces/interface_HybridShape_25589.htm">HybridShape</a>
            |
            +---<a href="../GSMInterfaces/interface_Plane_5544.htm">Plane</a>
              |
              +---HybridShapePlane3Points
 </pre>
<hr><br>
<b><i> Represents the hybrid shape plane through three points feature object.</i></b><br>

 <b>Role</b>: Allows to access data of the plane feature passing though three points.
 This data includes:
 <ul>
 <li> The first point </li>
 <li> The second point </li>
 <li> The third point </li>
 </ul>
 Use the CATIAHybridShapeFactory to create HybridShapeFeature object.
 <dl>
  <dt> <b>See also:</b> 
  <dd> <a href="../GSMInterfaces/interface_HybridShapeFactory_68680.htm">HybridShapeFactory</a>
</dl>
<hr>
<dl>
 <h2><a name="PropertyIndex"></a>Property Index</h2>
 <dt>
    <a href="#First"><b>First</b></a>
<dd>  Returns or sets the first point.
 <dt>
    <a href="#Second"><b>Second</b></a>
<dd>  Returns or sets the second point.
 <dt>
    <a href="#Third"><b>Third</b></a>
<dd>  Returns or sets the third point.
</dl>
<dl>
</dl>
 <h2><a name="Properties"></a>Properties</h2> <br>
<a name="First"><dt>

<table><tr><td>o Property <b>First</b>(<td>) As <a href="../InfInterfaces/interface_Reference_17481.htm">CATIAReference</a> </table></dt>
<dl>
  <dd>
 Returns or sets the first point. 
 <br>Sub-element(s) supported (see 
<a href="../MecModInterfaces/interface_Boundary_14542.htm">Boundary</a> object):  
<a href="../MecModInterfaces/interface_Vertex_8466.htm">Vertex</a>.  <dl>
 <dt><b>Example</b>:
 This example retrieves in <code>FirstPoint</code> the first point for the <code>Plane</code> passing through three points hybrid shape feature.
<pre>
 Dim FirstPoint As Reference
 Set FirstPoint = Plane3Points.<font color="red">First</font>
</pre>
</dl>
</dl>
<a name="Second"><dt>

<table><tr><td>o Property <b>Second</b>(<td>) As <a href="../InfInterfaces/interface_Reference_17481.htm">CATIAReference</a> </table></dt>
<dl>
  <dd>
 Returns or sets the second point. 
 <br>Sub-element(s) supported (see 
<a href="../MecModInterfaces/interface_Boundary_14542.htm">Boundary</a> object):  
<a href="../MecModInterfaces/interface_Vertex_8466.htm">Vertex</a>.  <dl>
 <dt><b>Example</b>:
 This example retrieves in <code>SecondPoint</code> the second point for the <code>Plane</code> passing through three points hybrid shape feature.
<pre>
 Dim SecondPoint As Reference
 Set SecondPoint = Plane3Points.<font color="red">Second</font>
</pre>
</dl>
</dl>
<a name="Third"><dt>

<table><tr><td>o Property <b>Third</b>(<td>) As <a href="../InfInterfaces/interface_Reference_17481.htm">CATIAReference</a> </table></dt>
<dl>
  <dd>
 Returns or sets the third point. 
 <br>Sub-element(s) supported (see 
<a href="../MecModInterfaces/interface_Boundary_14542.htm">Boundary</a> object):  
<a href="../MecModInterfaces/interface_Vertex_8466.htm">Vertex</a>.  <dl>
 <dt><b>Example</b>:
 This example retrieves in <code>ThirdPoint</code> the third point for the <code>Plane</code> passing through three points hybrid shape feature.
<pre>
 Dim ThridPoint As Reference
 Set ThirdPoint = Plane3Points.<font color="red">Third</font>
</pre>
</dl>
</dl>

</body>
<hr><p><i>
Copyright &#169; 2003, Dassault Syst&#232;mes. All rights reserved.</i></p>
</html>
