<!DOCTYPE html
     PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
     "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
<meta http-equiv="Content-Language" content="en-us" />
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<meta name="devlang" content="idl" />
<script type="text/javascript" src="../CAADocJavaScript/DSDocHighlight.js">/* */</script>
<link rel="stylesheet" type="text/css" href="../CAADocStyleSheets/caav5.css"/>
<title>CAAScdAgtUcAccessCategoryMaterialSource.CATScript</title>
</head>

<body onload="highlightSearchTerms();">

<pre>
<span class="comment">'-------------- Sample MACRO written in Basic Script ------------------------------------------</span>
<span class="comment">'This sample demonstrates accessing the attribute of insulation object</span>
<span class="comment">'This script requires accommodation model which contains two insulations</span>
<span class="comment">'</span>
<span class="comment">''Steps</span>
<span class="comment">'   1- Searches<span lang="fr"> </span>and opens model which is named as &quot;Acc_Deck5_FZ4-535154227&quot;</span>
<span class="comment">'   2- Retrieves Part object </span>
<span class="comment">'   3- Retrieves Accommodation Root Object</span>
<span class="comment">'   4- Retrieves collection of insulation from root object</span>
<span class="comment">'   5- Retrieves the first insulation object by index</span>
<span class="comment">'   6- Retrieves the AGTMaterialMngt</span>
<span class="comment">'   7- Get the name of material by the AGTMaterialMngt</span>
<span class="comment">'   8- Set the Material</span>
<span class="comment">'   9- Retrieves the another insulation object by name</span>
<span class="comment">'  10- Retrieves the AGTCategoryMngt object</span>
<span class="comment">'  11- Get the name of category by the AGTCategoryMngt</span>
<span class="comment">'  12- Set the Category</span>
<span class="comment">'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="comment">' Language=&quot;VBSCRIPT&quot;</span> 
<span class="keyword">Dim </span>ObjPart<span class="keyword"> As </span>Part

<span class="keyword">Sub </span>CATMain()
    
<span class="comment">'   1- Searches<span lang="fr"> </span>and opens model which is named as &quot;Acc_Deck5_FZ4-535154227&quot; </span>
<span class="keyword">    Dim </span>AGTPrdEditor<span class="keyword"> As </span>Editor 
<span class="keyword">    Dim </span>prdName<span class="keyword"> As </span>String
    prdName = "Acc_Deck5_FZ4-535154227"
    OpenProduct prdName, AGTPrdEditor

<span class="comment">'   2- Retrieves Part object </span>
<span class="keyword">    Set</span> ObjPart = AGTPrdEditor.ActiveObject

<span class="comment">'   3- Retrieves Accommodation Root Object </span>
<span class="keyword">    Dim </span>oAGTRoot<span class="keyword"> As </span>AGTRoot
<span class="keyword">    Set </span>oAGTRoot = ObjPart.GetItem(&quot;CATAGTRoot&quot;)

<span class="comment">'   4- Retrieves collection of insulation from root object</span>
<span class="keyword">    Dim </span>oInsulations<span class="keyword"> As </span>AGTInsulations
<span class="keyword">    Set </span>oInsulations = oAGTRoot.Insulations

<span class="comment">'   5- Retrieves the first insulation object by index </span>
<span class="keyword">    Dim </span>oInsulationByIndex<span class="keyword"> As </span>AGTInsulation
<span class="keyword">    Set </span>oInsulationByIndex = oInsulations.Item(1)    

<span class="comment">'   6- Retrieves the AGTMaterialMngt </span>
<span class="keyword">    Dim </span>oMaterialMngt<span class="keyword"> As </span>AGTMaterialMngt
<span class="keyword">    Set </span>oMaterialMngt = oInsulationByIndex.AGTMaterialMngt

<span class="comment">'   7- Get the name of material by the AGTMaterialMngt </span>
<span class="keyword">    Dim </span>strMaterialName<span class="keyword"> As </span>String
    strMaterialName = oMaterialMngt.GetMaterial

<span class="comment">'   8- Set the Material</span>
    oMaterialMngt.SetMaterial &quot;Straw bale&quot;

<span class="comment">'   9- Retrieves the another insulation object by name</span>
<span class="keyword">    Dim </span>oInsulationByName<span class="keyword"> As </span>AGTInsulation
<span class="keyword">    Set </span>oInsulationByName = oInsulations.Item(&quot;VerticalBulkheadInsulation_10&quot;)

<span class="comment">'   10- Retrieves the AGTCategoryMngt object</span>
<span class="keyword">    Dim </span>oCategoryMngt<span class="keyword"> As </span>AGTCategoryMngt
<span class="keyword">    Set </span>oCategoryMngt = oInsulationByName.AGTCategoryMngt

<span class="comment">'   11- Get the name of category by the AGTCategoryMngt</span>
<span class="keyword">    Dim </span>strCategoryName<span class="keyword"> As </span>String
    strCategoryName = oCategoryMngt.GetCategory

<span class="comment">'   12- Set the Category</span>
    oCategoryMngt.SetCategory &quot;DeckPanelInsulation&quot;

<span class="keyword">End Sub</span>

<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="comment">'Searches a product and open it.</span>
<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="keyword">Sub </span>OpenProduct(<span class="keyword">ByVal</span> prdName <span class="keyword">As</span> String, AGTPrdEditor<span class="keyword"> As </span>Editor)
    <span class="comment">'Search product and open it</span>
    <span class="comment">'Get the SearchService</span>
<span class="keyword">    Dim </span>oSearchService <span class="keyword">As</span> SearchService
<span class="keyword">    Set </span>oSearchService = CATIA.GetSessionService(&quot;Search&quot;)
    <span class="comment">'Instantiate a DatabaseSearch through the SearchService</span>
<span class="keyword">    Dim </span>oDBSearch <span class="keyword">As</span> DatabaseSearch
<span class="keyword">    Set </span>oDBSearch = oSearchService.DatabaseSearch
    <span class="comment">'Set the type of object to query and criteria &amp; triggers the search</span>
    oDBSearch.BaseType = &quot;VPMReference&quot;
    oDBSearch.AddEasyCriteria &quot;V_Name&quot;, prdName
    oSearchService.Search
    <span class="comment">'Retrieve the listed entities</span>
<span class="keyword">    Dim </span>oEntity<span class="keyword"> As </span>PLMEntity
<span class="keyword">    Set </span>oEntity = oDBSearch.Results.Item(1)
    <span class="comment">'Get the PLMOpen service &amp; Open the first retrieved entity</span>
<span class="keyword">    Dim </span>oPLMOpenService <span class="keyword">As</span> PLMOpenService
<span class="keyword">    Set </span>oPLMOpenService = CATIA.GetSessionService(&quot;PLMOpenService&quot;)
    <span class="comment">'Get the editor</span>    
    oPLMOpenService.PLMOpen oEntity, AGTPrdEditor
<span class="keyword">End Sub</span>
</pre>
<script type="text/javascript">insertCopyright();</script>
  </body>
</html>
