<!DOCTYPE html 
     PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
     "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
<meta http-equiv="Content-Language" content="en-us" />
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<meta name="devlang" content="idl" />
<link rel="stylesheet" type="text/css" href="../CAADocStyleSheets/caav5.css"/>
<script type="text/javascript" src="../CAADocJavaScript/DSDocTocToc.js">/* */</script>
<script type="text/javascript" src="../CAADocJavaScript/DSDocHighlight.js">/* */</script>
<script type="text/javascript" src="../CAADocJavaScript/submit.js">/* */</script>
<title>CAAScdSddUcCreateOpeningSketch.CATScript</title>
</head>

<body onload="highlightSearchTerms();">
<script type="text/javascript">insertCopyright();</script>

<pre>
<span class="comment">'-------------- Sample MACRO written in Basic Script ------------------------------------------</span>
<span class="comment">'This sample creates a FEM representation and manage its associated shapes.</span>

<span class="comment">'Steps:</span>
<span class="comment">'    1- Searches and opens model which is named as &quot;CAAScdFeaProductWithoutFEM&quot;</span>
<span class="comment">'    2- Retrieves the root product</span>
<span class="comment">'    3- Retrieves the PartBody</span>
<span class="comment">'    4- Creates the FEM representation and retrieve its root object</span>
<span class="comment">'    4- Associates the PartBody with the FEM representation</span>
<span class="comment">'    6- Checks if the FEM representation have at least one associated shape</span>
<span class="comment">'    7- Removes an associated shapes</span>

<span class="keyword">Sub</span> CATMain()

<span class="comment">'--------------------------------------------------------------------------</span>
<span class="comment">' 1- Searches and opens model which is named as &quot;CAAScdFeaProductWithoutFEM&quot;</span>
<span class="comment">'--------------------------------------------------------------------------</span>
<span class="keyword">Dim</span> MyEditor <span class="keyword">As</span> Editor
OpenProduct MyEditor

<span class="comment">'--------------------------------------------------------------------------</span>
<span class="comment">' 2- Retrieves the root product</span>
<span class="comment">'--------------------------------------------------------------------------</span>
<span class="keyword">Dim</span> MyRootOcc <span class="keyword">As</span> VPMRootOccurrence
<span class="keyword">Set</span> MyRootOcc = MyEditor.ActiveObject

<span class="keyword">Dim</span> MyRootProduct <span class="keyword">As</span> VPMReference
<span class="keyword">Set</span> MyRootProduct = MyRootOcc.PLMEntity

<span class="comment">'--------------------------------------------------------------------------</span>
<span class="comment">' 3- Retrieves the PartBody</span>
<span class="comment">'--------------------------------------------------------------------------</span>
<span class="keyword">Dim</span> MyContext <span class="keyword">As</span> PLMAppContext
<span class="keyword">Set</span> MyContext = MyEditor.GetService(&quot;PLMProductContext&quot;)

<span class="keyword">Dim</span> MyPart <span class="keyword">As</span> Part
<span class="keyword">Dim</span> MyPartInstance <span class="keyword">As</span> VPMRepInstance
<span class="keyword">Dim</span> MyBody <span class="keyword">As</span> Body
<span class="keyword">For Each</span> MyEntity <span class="keyword">In</span> MyContext.EditedContent
    <span class="keyword">Dim</span> MyRef <span class="keyword">As</span> VPMReference
    <span class="keyword">Set</span> MyRef = MyEntity

    <span class="keyword">Dim</span> MyReps <span class="keyword">As</span> VPMRepInstances
    <span class="keyword">Set</span> MyReps = MyRef.RepInstances

    <span class="keyword">For Each</span> MyRep <span class="keyword">In</span> MyReps
        <span class="keyword">Dim</span> MyRepRef <span class="keyword">As</span> VPMRepReference
        <span class="keyword">Set</span> MyRepRef = MyRep.ReferenceInstanceOf
        <span class="keyword">Dim</span> attr <span class="keyword">As</span> String
        attr = MyRepRef.GetAttributeValue(&quot;V_discipline&quot;)

        <span class="keyword">If</span> (attr = &quot;Design&quot;) <span class="keyword">Then</span>
            <span class="keyword">Set</span> MyPart = MyRepRef.GetItem(&quot;Part&quot;)
            <span class="keyword">Set</span> MyPartInstance = MyRep
            <span class="keyword">Set</span> MyBody = MyPart.MainBody
        <span class="keyword">End If</span>
    <span class="keyword">Next</span>
<span class="keyword">Next</span>

<span class="comment">'--------------------------------------------------------------------------</span>
<span class="comment">' 4- Creates a FEM representation and retrieve its root object</span>
<span class="comment">'--------------------------------------------------------------------------</span>
<span class="keyword">Dim</span> MyPrdRepFactory <span class="keyword">As</span> SimPrdRepFactory
<span class="keyword">Set</span> MyPrdRepFactory = MyRootProduct.GetItem(&quot;SimPrdRepFactory&quot;)
<span class="keyword">Dim</span> MyFemRepRef <span class="keyword">As</span> VPMRepReference
<span class="keyword">Set</span> MyFemRepRef = MyPrdRepFactory.CreatePrdRep(&quot;FEM&quot;)
<span class="keyword">Dim</span> MyFemRepRoot <span class="keyword">As</span> SimFemRoot
<span class="keyword">Set</span> MyFemRepRoot = MyFemRepRef.GetItem(&quot;SimFemRoot&quot;)

<span class="comment">'--------------------------------------------------------------------------</span>
<span class="comment">' 5- Associates the PartBody with the FEM representation</span>
<span class="comment">'--------------------------------------------------------------------------</span>
<span class="keyword">Dim</span> MyProductService <span class="keyword">As</span> PLMProductService
<span class="keyword">Set</span> MyProductService = MyEditor.GetService(&quot;PLMProductService&quot;)

<span class="keyword">Dim</span> MyReference <span class="keyword">As</span> Reference
<span class="keyword">Set</span> MyReference = MyPart.CreateReferenceFromObject(MyBody)
<span class="keyword">Dim</span> MyLink <span class="keyword">As</span> AnyObject
<span class="keyword">Set</span> MyLink = MyProductService.ComposeLink(MyRootOcc, MyPartInstance, MyReference)
MyFemRepRoot.AddAssociatedRep MyLink

<span class="comment">'--------------------------------------------------------------------------</span>
<span class="comment">' 6- Checks if the FEM representation have at least one associated shape</span>
<span class="comment">'--------------------------------------------------------------------------</span>
<span class="keyword">Dim</span> bHasAnAssociatedRep <span class="keyword">As</span> Boolean
bHasAnAssociatedRep = MyFemRepRoot.HasAnAssociatedRep
<span class="keyword">If</span> (bHasAnAssociatedRep = False) <span class="keyword">Then</span>
    MsgBox &quot;Error while associating the PartBody to the FEM Rep!&quot;
    <span class="keyword">Exit Sub</span>
<span class="keyword">End If</span>

<span class="comment">'--------------------------------------------------------------------------</span>
<span class="comment">' 7- Removes an associated shapes</span>
<span class="comment">'--------------------------------------------------------------------------</span>
MyFemRepRoot.RemoveAssociatedRep MyLink
bHasAnAssociatedRep = MyFemRepRoot.HasAnAssociatedRep
<span class="keyword">If</span> (bHasAnAssociatedRep = True) <span class="keyword">Then</span>
    MsgBox &quot;Error while removing the associated shape from the FEM Rep!&quot;
    <span class="keyword">Exit Sub</span>
<span class="keyword">End If</span>

<span class="keyword">End Sub</span>

<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="comment">'Searches a product and open it.</span>
<span class="comment">''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''</span>
<span class="keyword">Sub</span> OpenProduct(oEditor As Editor)
    <span class="comment">'Search product and open it:</span>
    <span class="comment">'Get the Search Service</span>
    <span class="keyword">Dim</span> oSearchService <span class="keyword">As</span> SearchService
    <span class="keyword">Set</span> oSearchService = CATIA.GetSessionService(&quot;Search&quot;)
    <span class="keyword">Dim</span> oDBSearch <span class="keyword">As</span> DatabaseSearch
    <span class="keyword">Set</span> oDBSearch = oSearchService.DatabaseSearch
    oDBSearch.BaseType = &quot;VPMReference&quot;
    <span class="comment">' To retrieve the Product by its Title, use V_Name attribute</span>
    oDBSearch.AddEasyCriteria &quot;V_Name&quot;, &quot;CAAScdFeaProductWithoutFEM&quot;
    oSearchService.Search

    <span class="comment">'Retrieve the listed entities</span>
    <span class="keyword">Dim</span> cPLMEntities <span class="keyword">As</span> PLMEntities
    <span class="keyword">Set</span> cPLMEntities = oDBSearch.Results
    <span class="keyword">If</span> cPLMEntities.Count &lt;&gt; 0 <span class="keyword">Then</span>
       <span class="keyword">Set</span> oPLMEntity = cPLMEntities.Item(1)
       <span class="comment">'Get the PLMOpen service &amp; Open the first retrieved entity</span>
       <span class="keyword">Set</span> oPLMOpenService = CATIA.GetSessionService(&quot;PLMOpenService&quot;)
       <span class="comment">'Get the editor</span>
       oPLMOpenService.PLMOpen oPLMEntity, oEditor
    <span class="keyword">End If</span>
<span class="keyword">End Sub</span>
</pre>
<script type="text/javascript">insertCopyright();</script>
  </body>
</html>

