<!doctype html public "-//w3c//dtd html 4.0 transitional//en">
<html>
<head>
 <meta http-equiv="Content-Language" content="en-us"> 
 <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"> 
 <meta name="Generator" content="mihGene v1.1">
 <meta http-equiv="Expires" content="Tue, 04 Dec 1993 21:29:02 GMT">
 <title>CATSchPlatformInterfaces SchematicRoot (Object)</title>
<link rel="Stylesheet" type="text/css" href="../../../caav5.css">
<link href="../_index/cdg.css" rel="stylesheet" type="text/css"> 
<script type="text/javascript">var PubDirExist = false; var ProDirExist = false; var PrivDirExist = false;</script> 
<script type="text/javascript" src="../_index/cdg.js"></script> 
<script language="Javascript" id="jsLinkjs" type="text/javascript" src="../_index/jslink.js"></script> 
<script language="Javascript" id="jsFwLinkjs" type="text/javascript" src="jsFwLink.js"></script> 
<script language="Javascript" id="jsTreejs" type="text/javascript" src="../_index/jsTree.js"></script>  
</head>
<body>
<div class="menu1" id="menuViewPPP" > 
 	<a href="javascript:writeIndex('IPublic')" name="viewPPP" id="PublicView"  class="ongletPub" > Public View</a> 
 	<a href="javascript:writeIndex('IProtected')" name="viewPPP" id="ProtectedView" class="ongletPro"  > Protected View</a>  
 	<a href="javascript:writeIndex('IPrivate')" name="viewPPP" id="PrivateView" class="ongletPriv" > Private View</a> 
 </div> 
 <div id="indexView" class="menu1">	 
 <a name="multiview" class="onglet" rel="../_index/main.htm" href="../_index/main.htm">All Frameworks</a>   
 <a name="multiview" class="onglet"  rel="../_index/tree.htm" href="../_index/tree.htm">Class Hierarchy</a>   
 <a name="multiview" class="onglet"  rel="../CATSchPlatformInterfaces.htm" href="../CATSchPlatformInterfaces.htm">This Framework</a>
<a name="multiview" class="onglet"  rel="../_index/HomeIdx.htm" href="../_index/HomeIdx.htm">Indexes</a>  
 <a id="multiviewP" class="onglet" href="javascript:openLinkNP(getCurrentObjectName(),getCurrentType(),'0')"  >Previous</a>  
 	<a id="multiviewN" class="onglet" href="javascript:openLinkNP(getCurrentObjectName(),getCurrentType(),'1')"  >Next</a> 
 </div> 
<script type="text/javascript" > 
 	function getCurrentLevel() { 
 return "";	} 
	function getCurrentFw() { 
	return "CATSchPlatformInterfaces";	}
		function getCurrentObjectName() { 
 	return "SchematicRoot"; } 
	function getCurrentType() { 
 	return "interface"; }  
 function callInit() { 
 		if (PubDirExist == true || ProDirExist == true || PrivDirExist == true) {  
 			var parent = document.getElementById("indexView"); 
 			if (parent && (ProDirExist == true || PrivDirExist == true) ) { 
 			var elem = document.getElementById("multiviewP"); 
 			if(elem) parent.removeChild(elem); 
 			elem = document.getElementById("multiviewN"); 
 			if(elem) parent.removeChild(elem); }
 			initData(); 
 		} else { 
 			var elem; 
 			var parent = document.getElementById("menuViewPPP"); 
 			if (parent) { 
 				elem = document.getElementById("PublicView"); 
 				parent.removeChild(elem); 
 				elem = document.getElementById("ProtectedView"); 
 				parent.removeChild(elem); 
 				elem = document.getElementById("PrivateView"); 
 				parent.removeChild(elem); 
 			} 
 if (locateObject(getCurrentObjectName(), getCurrentType(), '0')==0) { 
 				elem = document.getElementById("multiviewP"); 
 				if (elem) { elem.removeAttribute("href"); elem.removeAttribute("onclick"); } 
 			} 
 			if (locateObject(getCurrentObjectName(), getCurrentType(), '1')==0) { 
 				elem = document.getElementById("multiviewN"); 
 				if (elem) { elem.removeAttribute("href"); elem.removeAttribute("onclick"); } 
 			} 
 }	 
 	} 
 	window.onload = callInit; 
  </script> 
 
<h1>SchematicRoot<font size=-1> (Object)</font></h1>
<script type="text/javascript" > 
 generatedFatherClass('interface_SchematicRoot_40510','SchematicRoot','0');</script>
<b><i> Represents the top node of the schematic object tree.</i></b><br>

 From this node all the queries for lists of schematic objects can be made. Furthermore, 
 all the factories handles can be obtained through this interface.<hr>
<dl>
</dl>
<dl>
 <h2><a name="MethodIndex"></a>Method Index</h2>
 <dt>
    <a href="#GetApplObjFactFromVirtualType"><b>GetApplObjFactFromVirtualType</b></a>
<dd>  Returns the object factory for specific schematic application.
 <dt>
    <a href="#GetApplicationObjectFactory"><b>GetApplicationObjectFactory</b></a>
<dd>  Returns the object factory for specific schematic application.
 <dt>
    <a href="#GetCompGroupFromCatalog"><b>GetCompGroupFromCatalog</b></a>
<dd>  Returns specific component group entry in a schematic component catalog document.
 <dt>
    <a href="#GetCompSymbolFromCatalog"><b>GetCompSymbolFromCatalog</b></a>
<dd>  Returns specific entry in a schematic component catalog document.
 <dt>
    <a href="#GetComponents"><b>GetComponents</b></a>
<dd>  Returns a list of schematic component instances under the root.
 <dt>
    <a href="#GetDrawing"><b>GetDrawing</b></a>
<dd>  Retrieves the drawing root in the schematic document.
 <dt>
    <a href="#GetDrawingStandard"><b>GetDrawingStandard</b></a>
<dd>  Get the drawing standard.
 <dt>
    <a href="#GetInterface"><b>GetInterface</b></a>
<dd>  Returns specific interface handle on a given object.
 <dt>
    <a href="#GetRefComponents"><b>GetRefComponents</b></a>
<dd>  Returns a list of schematic component references under the root.
 <dt>
    <a href="#GetRoutes"><b>GetRoutes</b></a>
<dd>  Returns a list of schematic routes under the root.
 <dt>
    <a href="#GetSchBaseFactory"><b>GetSchBaseFactory</b></a>
<dd>  Returns schematic base object factory.
 <dt>
    <a href="#GetSchematicSession"><b>GetSchematicSession</b></a>
<dd>  Returns the schematic session the document containing the root is associated with.
 <dt>
    <a href="#GetTemporaryListFactory"><b>GetTemporaryListFactory</b></a>
<dd>  Returns the factory to create lists of various types.
 <dt>
    <a href="#GetUnassociatedSymbols"><b>GetUnassociatedSymbols</b></a>
<dd>  Returns a list of unassociated symbol.
 <dt>
    <a href="#SetDrawingStandard"><b>SetDrawingStandard</b></a>
<dd>  Set the drawing standard.
</dl>
 <h2><a name="Methods"></a>Methods</h2> <br>
<a name="GetApplObjFactFromVirtualType"><dt>

<table><tr><td>o Func <b>GetApplObjFactFromVirtualType</b>(<td><script type="text/javascript"> activateLink('CATBSTR','CATBSTR')</script> <td><tt>iApplicationID</tt>) As <script type="text/javascript"> activateLink('SchAppObjectFactory','SchAppObjectFactory')</script> </table></dt>
<dl>
  <dd>
 Returns the object factory for specific schematic application.  
 
<dl>
  <dt> Example: </dt> 
  <dd> <pre class="code">  This example illustrates how to get the object factory of user defined virtual type. 
 User provides implementation to this type.
 <pre>
 Dim objSchPlatformRoot As SchematicRoot
 Dim objSchObjFact As SchAppObjectFactory
 Dim objProductRoot As Product
 Set objProductRoot = CATIA.ActiveDocument.Product
 Set objSchPlatformRoot = objProductRoot.GetTechnologicalObject ("SchematicRoot")
 Set objSchObjFact = objSchPlatformRoot.<font color="red">GetApplObjFactFromVirtualType("UserDefined")(</font>
 </pre></pre></dd>
</dl>
</dl>
<a name="GetApplicationObjectFactory"><dt>

<table><tr><td>o Func <b>GetApplicationObjectFactory</b>(<td><script type="text/javascript"> activateLink('CatSchIDLApplicationID','CatSchIDLApplicationID')</script> <td><tt>iApplicationID</tt>) As <script type="text/javascript"> activateLink('SchAppObjectFactory','SchAppObjectFactory')</script> </table></dt>
<dl>
  <dd>
 Returns the object factory for specific schematic application.  
 
<dl>
  <dt> Example: </dt> 
  <dd> <pre class="code">  This example illustrates how to get the object factory of Piping 
 and Instrumentation Diagram application.
 <pre>
 Dim objSchPlatformRoot As SchematicRoot
 Dim objSchObjFact As SchAppObjectFactory
 Dim objProductRoot As Product
 Set objProductRoot = CATIA.ActiveDocument.Product
 Set objSchPlatformRoot = objProductRoot.GetTechnologicalObject ("SchematicRoot")
 Set objSchObjFact = objSchPlatformRoot.<font color="red">GetApplicationObjectFactory("CatSchIDLCATPID")(</font>
 </pre></pre></dd>
</dl>
</dl>
<a name="GetCompGroupFromCatalog"><dt>

<table><tr><td>o Func <b>GetCompGroupFromCatalog</b>(<td><script type="text/javascript"> activateLink('CATBSTR','CATBSTR')</script> <td><tt>iCatalogEntryName</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('Document','Document')</script> <td><tt>iCtlgDoc</tt>) As <script type="text/javascript"> activateLink('SchComponent','SchComponent')</script> </table></dt>
<dl>
  <dd>
 Returns specific component group entry in a schematic component catalog document.  
 
<dl>
  <dt> Example: </dt> 
  <dd> <pre class="code">  This example illustrates how to get a specific component group entry in a schematic component catalog document.
 <pre>
 Dim objSchPlatformRoot As SchematicRoot
 Dim objSchComponent As SchComponent
 Dim objProductRoot As Product
 Set objProductRoot = CATIA.ActiveDocument.Product
 Set objSchPlatformRoot = objProductRoot.GetTechnologicalObject ("SchematicRoot")
 Dim objCtlgDoc As Document
 Set objCtlgDoc = CATIA.Documents.Open ("Electrical_ANSI_PartFunctions.catalog")
 Set objSchComponent = objSchPlatformRoot.<font color="red">GetCompGroupFromCatalog ("JuncBox-TermBoard",objCtlgDoc)
 </pre></pre></dd>
</dl>
</dl>
<a name="GetCompSymbolFromCatalog"><dt>

<table><tr><td>o Func <b>GetCompSymbolFromCatalog</b>(<td><script type="text/javascript"> activateLink('CATBSTR','CATBSTR')</script> <td><tt>iCatalogEntryName</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('Document','Document')</script> <td><tt>iCtlgDoc</tt>) As <script type="text/javascript"> activateLink('SchGRR','SchGRR')</script> </table></dt>
<dl>
  <dd>
 Returns specific entry in a schematic component catalog document.  
 
<dl>
  <dt> Example: </dt> 
  <dd> <pre class="code">  This example illustrates how to get a specific entry in a schematic component catalog document.
 <pre>
 Dim objSchPlatformRoot As SchematicRoot
 Dim objSchGRRComp As SchGRRComp
 Dim objProductRoot As Product
 Set objProductRoot = CATIA.ActiveDocument.Product
 Set objSchPlatformRoot = objProductRoot.GetTechnologicalObject ("SchematicRoot")
 Dim objCtlgDoc As Document
 Set objCtlgDoc = CATIA.Documents.Open ("PID_ANSI_Equipment.catalog")
 Set objSchGRRComp = objSchPlatformRoot.<font color="red">GetCompSymbolFromCatalog ("Blower",objCtlgDoc)
 </pre></pre></dd>
</dl>
</dl>
<a name="GetComponents"><dt>

<table><tr><td>o Func <b>GetComponents</b>(<td>) As <script type="text/javascript"> activateLink('SchListOfObjects','SchListOfObjects')</script> </table></dt>
<dl>
  <dd>
 Returns a list of schematic component instances under the root. 
 
<dl>
  <dt> Example: </dt> 
  <dd> <pre class="code">  This example illustrates how to get the list of component instances from a schematic product document.
 <pre>
 Dim objSchPlatformRoot As SchematicRoot
 Dim objSchListComps As SchListOfObjects
 Set objoSchListComps = objSchPlatformRoot.<font color="red">GetComponents</font>
 </pre></pre></dd>
</dl>
</dl>
<a name="GetDrawing"><dt>

<table><tr><td>o Func <b>GetDrawing</b>(<td>) As <script type="text/javascript"> activateLink('DrawingRoot','DrawingRoot')</script> </table></dt>
<dl>
  <dd>
 Retrieves the drawing root in the schematic document.
 
<dl>
  <dt> Example: </dt> 
  <dd> <pre class="code">  This example illustrates how to get the drawing of a schematic document.
 <pre>
 Dim objSchPlatformRoot As SchematicRoot
 Dim objProductRoot As Product
 Set objProductRoot = CATIA.ActiveDocument.Product
 Set objSchPlatformRoot = objProductRoot.GetTechnologicalObject ("SchematicRoot")
 Dim objDrawRoot As DrawingRoot
 Set objDrawRoot = objSchPlatformRoot.<font color="red">GetDrawing
 </pre></pre></dd>
</dl>
</dl>
<a name="GetDrawingStandard"><dt>

<table><tr><td>o Func <b>GetDrawingStandard</b>(<td>) As <script type="text/javascript"> activateLink('CatDrawingStandard','CatDrawingStandard')</script> </table></dt>
<dl>
  <dd>
 Get the drawing standard.
 
<dl>
  <dt> Example: </dt> 
  <dd> <pre class="code">  This example illustrates how to get the drafting standard of a schematic document.
 <pre>
 Dim objSchPlatformRoot As SchematicRoot
 Dim objSchLSymbols As SchListOfObjects
 Dim objProductRoot As Product
 Set objProductRoot = CATIA.ActiveDocument.Product
 Set objSchPlatformRoot = objProductRoot.GetTechnologicalObject ("SchematicRoot")
 oDrwStd = objSchPlatformRoot.<font color="red">GetDrawingStandard
 </pre></pre></dd>
</dl>
</dl>
<a name="GetInterface"><dt>

<table><tr><td>o Func <b>GetInterface</b>(<td><script type="text/javascript"> activateLink('CATBSTR','CATBSTR')</script> <td><tt>iInterfaceName</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('AnyObject','AnyObject')</script> <td><tt>iObject</tt>) As <script type="text/javascript"> activateLink('AnyObject','AnyObject')</script> </table></dt>
<dl>
  <dd>
 Returns specific interface handle on a given object.  
 
<dl>
  <dt> Example: </dt> 
  <dd> <pre class="code">  This example illustrates how to get a specific interface handle from a given object. 
 <pre>
 Dim objSchPlatformRoot As SchematicRoot
 Dim objSchObjFact As SchAppObjectFactory
 Dim objProductRoot As Product
 Set objProductRoot = CATIA.ActiveDocument.Product
 Set objSchPlatformRoot = objProductRoot.GetTechnologicalObject ("SchematicRoot")
 Set objSchObjFact = SchPlatformRoot.GetApplicationObjectFactory("CatSchIDLCATPID")
 Set objSchObjFact2 = objSchPlatformRoot.<font color="red">GetInterface ("CATIASchAppObjectFactory2",SchObjFact)
 </pre></pre></dd>
</dl>
</dl>
<a name="GetRefComponents"><dt>

<table><tr><td>o Func <b>GetRefComponents</b>(<td>) As <script type="text/javascript"> activateLink('SchListOfObjects','SchListOfObjects')</script> </table></dt>
<dl>
  <dd>
 Returns a list of schematic component references under the root.
 
<dl>
  <dt> Example: </dt> 
  <dd> <pre class="code">  This example illustrates how to get the list of component references from a schematic product document.
 <pre>
 Dim objSchPlatformRoot As SchematicRoot
 Dim objSchListComps As SchListOfObjects
 Set objSchListComps = objSchPlatformRoot.<font color="red">GetRefComponents</font>
 </pre></pre></dd>
</dl>
</dl>
<a name="GetRoutes"><dt>

<table><tr><td>o Func <b>GetRoutes</b>(<td>) As <script type="text/javascript"> activateLink('SchListOfObjects','SchListOfObjects')</script> </table></dt>
<dl>
  <dd>
 Returns a list of schematic routes under the root.
 
<dl>
  <dt> Example: </dt> 
  <dd> <pre class="code">  This example illustrates how to get the list of routes from a schematic product document.
 <pre>
 Dim objSchPlatformRoot As SchematicRoot
 Dim objSchListRoutes As SchListOfObjects
 Set objSchListRoutes = objSchPlatformRoot.<font color="red">GetRoutes</font>
 </pre></pre></dd>
</dl>
</dl>
<a name="GetSchBaseFactory"><dt>

<table><tr><td>o Func <b>GetSchBaseFactory</b>(<td>) As <script type="text/javascript"> activateLink('SchBaseFactory','SchBaseFactory')</script> </table></dt>
<dl>
  <dd>
 Returns schematic base object factory.  
 
<dl>
  <dt> Example: </dt> 
  <dd> <pre class="code">  This example illustrates how to get the schematic base factory.
 <pre>
 Dim objSchPlatformRoot As SchematicRoot
 Dim objSchBaseFact As SchBaseFactory
 Dim objProductRoot As Product
 Set objProductRoot = CATIA.ActiveDocument.Product
 Set objSchPlatformRoot = objProductRoot.GetTechnologicalObject ("SchematicRoot")
 Set objSchBaseFact = objSchPlatformRoot.<font color="red">GetBaseFactory
 </pre></pre></dd>
</dl>
</dl>
<a name="GetSchematicSession"><dt>

<table><tr><td>o Func <b>GetSchematicSession</b>(<td>) As <script type="text/javascript"> activateLink('SchSession','SchSession')</script> </table></dt>
<dl>
  <dd>
 Returns the schematic session the document containing the root is associated with.  
 
<dl>
  <dt> Example: </dt> 
  <dd> <pre class="code">  This example illustrates how to get the schematic session.
 <pre>
 Dim objSchPlatformRoot As SchematicRoot
 Dim objSchSession As SchSession
 Dim objProductRoot As Product
 Set objProductRoot = CATIA.ActiveDocument.Product
 Set objSchPlatformRoot = objProductRoot.GetTechnologicalObject ("SchematicRoot")
 Set objSchSession = objSchPlatformRoot.<font color="red">GetSession
 </pre></pre></dd>
</dl>
</dl>
<a name="GetTemporaryListFactory"><dt>

<table><tr><td>o Func <b>GetTemporaryListFactory</b>(<td>) As <script type="text/javascript"> activateLink('SchTempListFactory','SchTempListFactory')</script> </table></dt>
<dl>
  <dd>
 Returns the factory to create lists of various types. These lists will not 
 be saved with the model.
 
<dl>
  <dt> Example: </dt> 
  <dd> <pre class="code">  This example illustrates how to get the list factory from a schematic product document.
 <pre>
 Dim objSchPlatformRoot As SchematicRoot
 Dim objSchList As SchTempListFactory
 Dim objProductRoot As Product
 Set objProductRoot = CATIA.ActiveDocument.Product
 Set objSchPlatformRoot = objProductRoot.GetTechnologicalObject ("SchematicRoot")
 Set objSchList = objSchPlatformRoot.<font color="red">GetTemporaryListFactory</font>
 </pre></pre></dd>
</dl>
</dl>
<a name="GetUnassociatedSymbols"><dt>

<table><tr><td>o Func <b>GetUnassociatedSymbols</b>(<td>) As <script type="text/javascript"> activateLink('SchListOfObjects','SchListOfObjects')</script> </table></dt>
<dl>
  <dd>
 Returns a list of unassociated symbol.  
 
<dl>
  <dt> Example: </dt> 
  <dd> <pre class="code">  This example illustrates how to get a list of unassociated symbol.
 <pre>
 Dim objSchPlatformRoot As SchematicRoot
 Dim objSchLSymbols As SchListOfObjects
 Dim objProductRoot As Product
 Set objProductRoot = CATIA.ActiveDocument.Product
 Set objSchPlatformRoot = objProductRoot.GetTechnologicalObject ("SchematicRoot")
 Set objSchLSymbols = objSchPlatformRoot.<font color="red">GetUnassociatedSymbols
 </pre></pre></dd>
</dl>
</dl>
<a name="SetDrawingStandard"><dt>

<table><tr><td>o Sub <b>SetDrawingStandard</b>(<td><script type="text/javascript"> activateLink('CatDrawingStandard','CatDrawingStandard')</script> <td><tt>iDrwStd</tt>)</table></dt>
<dl>
  <dd>
 Set the drawing standard.  
 
<dl>
  <dt> Example: </dt> 
  <dd> <pre class="code">  This example illustrates how to set the drafting standard of a schematic document.
 <pre>
 Dim objSchPlatformRoot As SchematicRoot
 Dim objSchLSymbols As SchListOfObjects
 Dim objProductRoot As Product
 Set objProductRoot = CATIA.ActiveDocument.Product
 Set objSchPlatformRoot = objProductRoot.GetTechnologicalObject ("SchematicRoot")
 objSchPlatformRoot.<font color="red">SetDrawingStandard catISO
 </pre></pre></dd>
</dl>
</dl>
<hr/><p><i>
Copyright &#169; 1999-2011, Dassault Syst&#232;mes. All rights reserved.</i></p>
</body>

</html>

