<html><head><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><title>CAAStrWeldInfoOnMembers.CATScript</title><link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css"></head><body><pre>
<font color="#008000">'//============================================================================</font>
<font color="#008000">'// COPYRIGHT DASSAULT SYSTEMES 2013</font>
<font color="#008000">'//============================================================================</font>
<font color="#008000">'// Language="VBSCRIPT"</font>
<font color="#008000">'// Sample of macro for getting weld information on structural objects.</font>
<font color="#008000">'//============================================================================</font>
<font color="#008000">'// 03/21/2013  Creation                                                    BE9</font>
<font color="#008000">'//============================================================================</font>

<font color="#0000FF">Sub </font>CATMain()

<font color="#0000FF">Dim </font>ObjPart<font color="#0000FF"> As </font>Part
<font color="#0000FF">Set </font>ObjPart = CATIA.ActiveDocument.Part
   
<font color="#0000FF">Dim </font>FactoryObj<font color="#0000FF"> As </font>SfmFactory
<font color="#0000FF">Set </font>FactoryObj = ObjPart.GetCustomerFactory("SfmFactory")
  
<font color="#0000FF">Dim </font>ManagerObj<font color="#0000FF"> As </font>SfmManager
<font color="#0000FF">Set </font>ManagerObj = FactoryObj.GetManager

<font color="#008000">'RETRIEVING THE SUPERMembers</font>
<font color="#0000FF">Dim </font>SuperMembers<font color="#0000FF"> As </font>References
<font color="#0000FF">Set </font>SuperMembers = ManagerObj.GetSuperMembers

<font color="#0000FF">Dim </font>SuperMember1<font color="#0000FF"> As </font>SfmMember
<font color="#0000FF">Set </font>SuperMember1 = SuperMembers.Item(1)

<font color="#008000">'Retrieving The Split Members</font>
<font color="#0000FF">Dim </font>SplitMembers<font color="#0000FF"> As </font>References
<font color="#0000FF">Set </font>SplitMembers = SuperMember1.SplitProfiles

<font color="#0000FF">Dim </font>SplitMember1<font color="#0000FF"> As </font>Reference
<font color="#0000FF">Set </font>SplitMember1 = SplitMembers.Item(1)

<font color="#0000FF">Set </font>SelctionObj = CATIA.ActiveDocument.Selection
<font color="#008000">'DECK Member</font>
SelctionObj.Add SplitMember1
<font color="#0000FF">Dim </font>DeckMember1<font color="#0000FF"> As </font>SfmMember
<font color="#0000FF">Set </font>DeckMember1 = SelctionObj.FindObject("CATIASfmMember")

<font color="#008000">'Retrieving SfmMemberObject from SfmMember</font>
<font color="#0000FF">Dim </font>OperatedMemberObject<font color="#0000FF"> As </font>SfmMemberObject
<font color="#0000FF">Set </font>OperatedMemberObject = DeckMember1.GetItem("SfmMemberObject")

<font color="#008000">'Retrieving Super Plates</font>
<font color="#0000FF">Dim </font>SuperPlates<font color="#0000FF"> As </font>References
<font color="#0000FF">Set </font>SuperPlates = ManagerObj.GetSuperPlates

<font color="#008000">'Retrieving Operating Super Plate</font>
<font color="#0000FF">Dim </font>SuperPlate1<font color="#0000FF"> As </font>SfmSuperPlate
<font color="#0000FF">Set </font>SuperPlate1 = SuperPlates.Item(1)

<font color="#008000">'Retrieving the SplitPlates of SuperPlate1</font>
<font color="#0000FF">Dim </font>OperatingSplitPlateRefs<font color="#0000FF"> As </font>References
<font color="#0000FF">Set </font>OperatingSplitPlateRefs = SuperPlate1.SplitPlates

<font color="#0000FF">Dim </font>OperatingSplitPlate<font color="#0000FF"> As </font>Reference
<font color="#0000FF">Set </font>OperatingSplitPlate = OperatingSplitPlateRefs.Item(1)


<font color="#0000FF">Dim </font>WeldsUC1<font color="#0000FF"> As </font>SfmWelds
<font color="#0000FF">Set </font>WeldsUC1 = OperatedMemberObject.GetWelds(OperatingSplitPlate)

<font color="#0000FF">Dim </font>WeldUC1<font color="#0000FF"> As </font>SfmWeld
<font color="#0000FF">Set </font>WeldUC1 = WeldsUC1.Item(1)

ustrWeldTypeUC1 = WeldUC1.WeldType
ustrAddedMaterialUC1 = WeldUC1.AddedMaterial
ustrFitUpUC1 = WeldUC1.FitUp
ustrEdgePrepUC1 = WeldUC1.EdgePreparation

<font color="#0000FF">Dim </font>WeldsUC2<font color="#0000FF"> As </font>SfmWelds
<font color="#0000FF">Set </font>WeldsUC2 = OperatedMemberObject.GetWelds(Nothing)

<font color="#0000FF">Dim </font>WeldUC2<font color="#0000FF"> As </font>SfmWeld
<font color="#0000FF">Set </font>WeldUC2 = WeldsUC2.Item(1)

ustrWeldTypeUC2 = WeldUC2.WeldType
ustrAddedMaterialUC2 = WeldUC2.AddedMaterial
ustrFitUpUC2 = WeldUC2.FitUp
ustrEdgePrepUC2 = WeldUC2.EdgePreparation

<font color="#0000FF">End Sub</font>
</pre></body></html>
