<html>

<head>
<meta http-equiv="Content-Language" content="en_us">
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<meta name="GENERATOR" content="Microsoft FrontPage 12.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>Retrieving Weld Information on Stiffener Objects</title>
<link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css">
<script type="text/javascript" src="../CAAScrJavaScript/submit.js"></script>
</head>

<body>

<table border="0" width="100%">
	<tr>
		<td>
		<h2>Structure Design</h2>
		</td>
		<td align="right" valign="top">
		<h2><a name="Top"></a>Retrieving Weld Information on Stiffener Objects</h2>
		</td>
	</tr>
</table>
<hr>
<!-- -------------------------------comment--------------------------------- -->
<table border="0" width="100%">
	<tr>
		<td width="7%" valign="top">
		<img alt="Target Icon" src="../CAAScrBase/images/atarget.gif" width="32" height="32"></td>
		<td width="93%">
		<p><a name="Learn"></a>This macro shows you how to retrieve Weld information already set on SDD Stiffener Objects.</p>
		<p>
		<img alt="Starting Part" src="images/CAAScdStrWeldInfo01.png" width="621" height="268">
		</p>
		<!-- -------------------------------comment--------------------------------- -->
		</td>
	</tr>
	<tr>
		<td width="7%" valign="top">
		<img alt="Information Icon" src="../CAAScrBase/images/ainfo.gif" width="32" height="32"></td>
		<td width="93%">
		<p><a name="How"></a>CAAStrWeldInfoOnStiffeners is launched in CATIA [<a href="#References">1</a>]. 
		Some documents are needed.</p>
		<ul>
			<li><a href="CAAStrWeldInfoOnStiffenersSource.htm" target="Source">
				CAAStrWeldInfoOnStiffeners.CATScript</a> 
			is located in the CAAScdStrUseCases module.
			<a href="macros/CAAStrWeldInfoOnStiffeners.CATScript">Execute macro</a> (Windows 
			only).</li>
			<li>The document CAAStrWeldInfoOnStiffeners.CATPart is located in the CAAScdStrUseCases module in the samples directory.</li>
		</ul>
		</td>
	</tr>
	<tr>
		<td width="7%" valign="top">
		<img alt="Scenario Icon" src="../CAAScrBase/images/ascenari.gif" width="32" height="32"></td>
		<td width="93%">
		<p><a name="Step"></a>CAAStrWeldInfoOnStiffeners includes the following steps:</p>
		<ol>
			<li><a href="#Prolog">Prolog</a></li>
			<li><a href="#Step1">Retrieving Factory Object from Part Document</a></li>
			<li><a href="#Step2">Getting the Manager from Factory</a></li>
			<li><a href="#Step3">Retrieving the Super Stiffeners</a></li>
			<li><a href="#Step4">Retrieving Split Stiffeners of Super Stiffener</a></li>
			<li><a href="#Step5">Retrieving SfmStiffener object from the reference of Split Stiffener</a></li>
			<li><a href="#Step6">Retrieving SfmStiffenerObject from SfmStiffener</a></li>
			<li><a href="#Step7">Retrieving Super Plate which is used as Support for Stiffener</a></li>
			<li><a href="#Step8">Retrieving Weld Features on the Stiffener with Operating Element (Weld Use Case 1)</a></li>
			<li><a href="#Step9">Retrieving Weld Attributes of Weld Use Case 1 Features</a></li>
			<li><a href="#Step10">Retrieving Weld Features on the Stiffener with No Operating Element (Weld Use Case 2)</a></li>
			<li><a href="#Step11">Retrieving Weld Attributes of Weld Use Case 2 Features</a></li>
		</ol>
		<!-- -------------------------------comment--------------------------------- -->
		<h4><a name="Prolog"></a>Prolog</h4>
		<p>Opens the CAAStrWeldInfoOnStiffeners.CATPart in CATIA.</p>
		<pre class="code"><font color="#0000FF">Sub </font>CATMain()

<font color="#0000FF">Dim </font>ObjPart<font color="#0000FF"> As </font>Part
<font color="#0000FF">Set </font>ObjPart = CATIA.ActiveDocument.Part</pre>
		<!-- -------------------------------comment--------------------------------- -->
		<h4><a name="Step1"></a>Retrieving Factory Object from Part Document</h4>
		<p>This step describes how to get the Structure Functional Modeler Factory.
		The Factory Object will be used for creating Structure Functional Modeler Objects.</p>
		<pre class="code"><font color="#008000">'Get the Factory Object</font>
<font color="#0000FF">Dim </font>FactoryObj<font color="#0000FF"> As </font>SfmFactory
<font color="#0000FF">Set </font>FactoryObj = ObjPart.GetCustomerFactory("SfmFactory")</pre>
		<!-- -------------------------------comment--------------------------------- -->
		<h4><a name="Step2"></a>Getting the Manager from Factory</h4>
<p>The Manager Object is obtained by GetManager.</p>
		<pre class="code"><font color="#008000">'Get the Manager Object</font>
<font color="#0000FF">Dim </font>ManagerObj<font color="#0000FF"> As </font>SfmManager
<font color="#0000FF">Set </font>ManagerObj = FactoryObj.GetManager</pre>
		<!-- -------------------------------comment--------------------------------- -->
		<h4><a name="Step3"></a>Retrieving the Super Stiffeners</h4>
<p>This step describes how to get the collection of Super Stiffeners and how to get one specific element in it.</p>
		<pre class="code"><font color="#008000">'RETRIEVING THE SUPERSTIFFENERS</font>
<font color="#0000FF">Dim </font>SuperStiffeners<font color="#0000FF"> As </font>References
<font color="#0000FF">Set </font>SuperStiffeners = ManagerObj.GetSuperStiffeners

<font color="#0000FF">Dim </font>SuperStiffener1<font color="#0000FF"> As </font>SfmStiffener
<font color="#0000FF">Set </font>SuperStiffener1 = SuperStiffeners.Item(1)</pre>
		<!-- -------------------------------comment--------------------------------- -->
		<h4><a name="Step4"></a>Retrieving Split Stiffeners of Super Stiffener</h4>
<p>This step describes how to get the collection of Split Stiffeners and how to get one specific element in it.</p>
		<pre class="code"><font color="#008000">'Retrieving The Seamed Stiffeners on Deck</font>
<font color="#0000FF">Dim </font>SplitStiffeners<font color="#0000FF"> As </font>References
<font color="#0000FF">Set </font>SplitStiffeners = SuperStiffener1.SplitProfiles

<font color="#0000FF">Dim </font>SplitStiffener1<font color="#0000FF"> As </font>Reference
<font color="#0000FF">Set </font>SplitStiffener1 = SplitStiffeners.Item(1)</pre>
		<!-- -------------------------------comment--------------------------------- -->
		<h4><a name="Step5"></a>Retrieving SfmStiffener Object from the Reference of Split Stiffener</h4>
<p>This step describes how to get the SfmStiffener object from Reference of split stiffener.</p>
		<pre class="code"><font color="#0000FF">Set </font>SelctionObj = CATIA.ActiveDocument.Selection
<font color="#008000">'DECK STIFFENER</font>
SelctionObj.Add SplitStiffener1
<font color="#0000FF">Dim </font>DeckStiffener1<font color="#0000FF"> As </font>SfmStiffener
<font color="#0000FF">Set </font>DeckStiffener1 = SelctionObj.FindObject("CATIASfmStiffener")</pre>
		<!-- -------------------------------comment--------------------------------- -->
		<h4><a name="Step6"></a>Retrieving SfmStiffenerObject from SfmStiffener</h4>
<p>This step describes how to get the SfmStiffenerObject object from SfmStiffener.</p>
		<pre class="code"><font color="#008000">'Retrieving SfmStiffenerObject from SfmStiffener</font>
<font color="#0000FF">Dim </font>OperatedStiffenerObject <font color="#0000FF"> As </font>SfmStiffenerObject
<font color="#0000FF">Set </font>OperatedStiffenerObject = DeckStiffener1.GetItem("SfmStiffenerObject")</pre>

		<!-- -------------------------------comment--------------------------------- -->
		<h4><a name="Step7"></a>Retrieving Super Plate which is Used as Support for Stiffener</h4>
<p>This step describes how to get the Plate used as support for the Stiffener and accessing each element in it.</p>
		<pre class="code"><font color="#008000">'Retrieving Super Plates</font>
<font color="#0000FF">Dim </font>SuperPlates<font color="#0000FF"> As </font>References
<font color="#0000FF">Set </font>SuperPlates = ManagerObj.GetSuperPlates

<font color="#008000">'Retrieving Operating Super Plate</font>
<font color="#0000FF">Dim </font>SuperPlate1<font color="#0000FF"> As </font>SfmSuperPlate
<font color="#0000FF">Set </font>SuperPlate1 = SuperPlates.Item(1)

<font color="#008000">'Retrieving the SplitPlates of SuperPlate1</font>
<font color="#0000FF">Dim </font>OperatingSplitPlateRefs<font color="#0000FF"> As </font>References
<font color="#0000FF">Set </font>OperatingSplitPlateRefs = SuperPlate1.SplitPlates

<font color="#0000FF">Dim </font>OperatingSplitPlate<font color="#0000FF"> As </font>Reference
<font color="#0000FF">Set </font>OperatingSplitPlate = OperatingSplitPlateRefs.Item(1)</pre>

		<!-- -------------------------------comment--------------------------------- -->
		<h4><a name="Step8"></a>Retrieving Weld Features on the Stiffener with Operating Element (Weld Use Case 1)</h4>
<p>This step describes how to get the collection of Weld features with operating element and how to get one specific element in it.</p>
		<pre class="code"><font color="#0000FF">Dim </font>WeldsUC1<font color="#0000FF"> As </font>SfmWelds
<font color="#0000FF">Set </font>WeldsUC1 = OperatedStiffenerObject.GetWelds(OperatingSplitPlate)

<font color="#0000FF">Dim </font>WeldUC1<font color="#0000FF"> As </font>SfmWeld
<font color="#0000FF">Set </font>WeldUC1 = WeldsUC1.Item(1)
</pre>

		<!-- -------------------------------comment--------------------------------- -->
		<h4><a name="Step9"></a>Retrieving Weld Attributes of Weld Use Case 1 Features</h4>
<p>This step describes how to get the weld information set on the Operated split stiffener with operating element.</p>
		<pre class="code">ustrWeldTypeUC1 = WeldUC1.WeldType
ustrAddedMaterialUC1 = WeldUC1.AddedMaterial
ustrFitUpUC1 = WeldUC1.FitUp
ustrEdgePrepUC1 = WeldUC1.EdgePreparation</pre>
		<!-- -------------------------------comment--------------------------------- -->
		<h4><a name="Step10"></a>Retrieving Weld Features on the Stiffener with No Operating Element (Weld Use Case 2)</h4>
This step describes how to get the collection of Weld features with no operating element and how to get one specific element in it.
<pre class="code"><font color="#0000FF">Dim </font>WeldsUC2<font color="#0000FF"> As </font>SfmWelds
<font color="#0000FF">Set </font>WeldsUC2 = OperatedStiffenerObject.GetWelds(Nothing)

<font color="#0000FF">Dim </font>WeldUC2<font color="#0000FF"> As </font>SfmWeld
<font color="#0000FF">Set </font>WeldUC2 = WeldsUC2.Item(1)</pre>
		<!-- -------------------------------comment--------------------------------- -->
		<h4><a name="Step11"></a>Retrieving Weld Attributes of Weld Use Case 2 Features</h4>
<p>This step describes how to get the weld information set on the Operated split Stiffener with no operating element.</p>
		<pre class="code">ustrWeldTypeUC2 = WeldUC2.WeldType
ustrAddedMaterialUC2 = WeldUC2.AddedMaterial
ustrFitUpUC2 = WeldUC2.FitUp
ustrEdgePrepUC2 = WeldUC2.EdgePreparation

<font color="#0000FF">End Sub</font></pre>
		<!-- -------------------------------comment--------------------------------- -->
		</td>
	</tr>
</table>
<!-- -------------------------------comment--------------------------------- -->
<p align="center">
<img alt="End Task Icon" src="../CAAScrBase/images/aendtask.gif" width="64" height="32"></p>
<p align="right">[<a href="#Top">Top</a>]</p>
<hr>
<!-- -------------------------------comment--------------------------------- -->
<h4><a name="InShort"></a>In Short</h4>
<p>This use case has shown how to get weld information set on SDD Split Stiffener.</p>
<p align="right">[<a href="#Top">Top</a>]</p>
<hr>
<!-- -------------------------------comment--------------------------------- -->
<h4><a name="References"></a>References</h4>
<table border="0" width="100%">
	<tr>
		<td valign="top" width="40">[1]</td>
		<td><a href="../CAAScdInfUseCases/CAAInfLauchMacro.htm">Replaying 
		a macro</a></td>
	</tr>
	<tr>
		<td colspan="2" align="right">[<a href="#Top">Top</a>]</td>
	</tr>
</table>
<hr>
<!-- -------------------------------comment--------------------------------- -->
<p><i>Copyright © 1999-2013, Dassault Syst&#232;mes. All rights reserved.</i></p>

</body>

</html>
